Repository firebase/firebase-ios-sdk, pull requests merged in 2018-04, with the labels that each got.

#1012 4.11.0 Carthage update - adding Functions, Invites, and Firestore
  Carthage.md
Labels: cla: yes

#1014 update changelog for release
  Firebase/Messaging/CHANGELOG.md
Labels: cla: yes

#1015 Updating Firestore Changelog for v0.11.0
  Firestore/CHANGELOG.md
Labels: cla: yes

#1016 Updating Firebase Storage Changelog for v2.2.0
  Firebase/Storage/CHANGELOG.md
Labels: cla: yes

#1013 Drop FSTRemoteDocumentChangeBuffer
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/Local/FSTRemoteDocumentChangeBufferTests.mm
  Firestore/Source/Local/FSTLocalStore.mm
  Firestore/Source/Local/FSTRemoteDocumentChangeBuffer.h
  Firestore/Source/Local/FSTRemoteDocumentChangeBuffer.mm
Labels: cla: yes

#1017 improve logging when subscription failed
  Firebase/Messaging/FIRMMessageCode.h
  Firebase/Messaging/FIRMessagingTopicOperation.m
Labels: cla: yes

#995 store status rather than propogating it
  Firestore/core/src/firebase/firestore/remote/serializer.cc
  Firestore/core/src/firebase/firestore/util/status.h
Labels: cla: yes

#938 Updates change log
  Firebase/Auth/CHANGELOG.md
Labels: Auth, cla: yes

#1022 Updates changelog
  Firebase/Auth/CHANGELOG.md
  Firebase/Auth/Source/Public/FIRAuthTokenResult.h
Labels: cla: yes

#1023 Adds support for deep link to Email/Link sign-In
  Example/Auth/Tests/FIRAuthTests.m
  Firebase/Auth/Source/FIRAuth.m
Labels: cla: yes

#1024 Update component versions for 4.12.0
  Example/Podfile
  Firebase/Core/FIROptions.m
  FirebaseAuth.podspec
  FirebaseCore.podspec
  FirebaseFirestore.podspec
  FirebaseMessaging.podspec
  FirebaseStorage.podspec
  Firestore/Example/Podfile
Labels: cla: yes

#998 port FieldMask to C++
  Firestore/Example/Tests/Local/FSTLocalSerializerTests.mm
  Firestore/Example/Tests/Model/FSTMutationTests.mm
  Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
  Firestore/Example/Tests/Util/FSTHelpers.mm
  Firestore/Source/API/FSTUserDataConverter.h
  Firestore/Source/API/FSTUserDataConverter.mm
  Firestore/Source/Core/FSTTransaction.h
  Firestore/Source/Model/FSTMutation.h
  Firestore/Source/Model/FSTMutation.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/model/CMakeLists.txt
  Firestore/core/src/firebase/firestore/model/field_mask.h
  Firestore/core/test/firebase/firestore/model/CMakeLists.txt
  Firestore/core/test/firebase/firestore/model/field_mask_test.cc
Labels: Firestore, cla: yes

#1025 updates the changelog for pending release
  Firebase/Auth/CHANGELOG.md
Labels: cla: yes

#1027 Fix build break from trailing whitespace
  Firebase/Auth/CHANGELOG.md
Labels: cla: yes

#1026 Fix the comments for subscribe to topic
  Firebase/Messaging/Public/FIRMessaging.h
Labels: cla: yes

#1028 Cherry Pick of comments and changelog for M23
  Firebase/Auth/CHANGELOG.md
  Firebase/Messaging/Public/FIRMessaging.h
Labels: cla: yes

#1029 Fix nullability warning with new Messaging API
  Firebase/Messaging/Public/FIRMessaging.h
Labels: cla: yes

#1032 Fix nullability warning with new Messaging API (#1029)
  Firebase/Messaging/Public/FIRMessaging.h
Labels: cla: yes

#991 Add error handling for serializer (for serializing case only)
  Firestore/core/src/firebase/firestore/remote/serializer.cc
  Firestore/core/src/firebase/firestore/remote/serializer.h
  Firestore/core/test/firebase/firestore/remote/serializer_test.cc
Labels: cla: yes

#997 Fix build breakage on linux
  Firestore/core/src/firebase/firestore/immutable/sorted_map.h
  Firestore/core/src/firebase/firestore/util/firebase_assert.h
Labels: cla: yes

#1035 add NS_ASSUME_NONNULL macros to messaging
  Firebase/Messaging/FIRMessagingPubSub.h
  Firebase/Messaging/Public/FIRMessaging.h
Labels: cla: yes

#1041 Minor enhancements
  Example/Auth/Sample/MainViewController.m
  Firebase/Auth/Source/Public/FIRAuth.h
Labels: cla: yes

#1049 Unify the representation of the dotInfoConnected value to always be a…
  Firebase/Database/Core/FRepo.m
Labels: Database, cla: yes

#955 [BREAKING] Remove FIR prefix on FIRFunctionsErrorCode
  Functions/FirebaseFunctions/Public/FIRError.h
Labels: cla: yes, future major release

#1057 Fixing concurrent modification when we cancel transactions
  Firebase/Database/Core/FPersistentConnection.m
Labels: cla: yes

#1054 Remove deprecated remoteMessageDelegate
  Firebase/Messaging/FIRMessaging.m
  Firebase/Messaging/Public/FIRMessaging.h
Labels: Messaging, cla: yes

#1064 Enable Core Unit Tests to run in a Release config
  Example/Core/Tests/FIRLoggerTest.m
Labels: Core, cla: yes

#1063 Fix build on linux due to isnan not being present.
  Firestore/core/src/firebase/firestore/geo_point.cc
  Firestore/core/src/firebase/firestore/util/comparison.cc
Labels: cla: yes

#1061 Make Carthage "choosing a subset" clearer
  Carthage.md
Labels: cla: yes

#1050 Core Breaking API Changes
  Example/Core/Tests/FIRAppTest.m
  Example/Core/Tests/FIROptionsTest.m
  Example/Core/Tests/FIRTestCase.m
  Firebase/Core/CHANGELOG.md
  Firebase/Core/FIRApp.m
  Firebase/Core/FIRConfiguration.m
  Firebase/Core/FIROptions.m
  Firebase/Core/Public/FIRApp.h
  Firebase/Core/Public/FIRConfiguration.h
  Firebase/Core/Public/FIROptions.h
  Firebase/Core/third_party/FIRAppEnvironmentUtil.m
Labels: Core, cla: yes

#1062 FIREBASE_DEV_ASSERT -> FIREBASE_ASSERT within serializer.cc
  Firestore/core/src/firebase/firestore/remote/serializer.cc
Labels: cla: yes

#1033 Port FieldTransform to C++
  Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
  Firestore/Example/Tests/Util/FSTHelpers.mm
  Firestore/Source/API/FSTUserDataConverter.h
  Firestore/Source/API/FSTUserDataConverter.mm
  Firestore/Source/Core/FSTTransaction.h
  Firestore/Source/Model/FSTMutation.h
  Firestore/Source/Model/FSTMutation.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/model/CMakeLists.txt
  Firestore/core/src/firebase/firestore/model/field_transform.h
  Firestore/core/test/firebase/firestore/model/CMakeLists.txt
  Firestore/core/test/firebase/firestore/model/field_transform_test.cc
Labels: Firestore, cla: yes

#1065 Make it easier to consume sub-libraries within util
  Firestore/core/src/firebase/firestore/util/CMakeLists.txt
  Firestore/core/test/firebase/firestore/util/CMakeLists.txt
Labels: Firestore, cla: yes

#1058 Rebuild proto artifacts from existing sources and update README.md instructions.
  Firestore/Protos/FrameworkMaker.xcodeproj/project.pbxproj
  Firestore/Protos/README.md
  Firestore/Protos/nanopb/firestore/local/target.pb.c
  Firestore/Protos/nanopb/firestore/local/target.pb.h
  Firestore/Protos/objc/google/firestore/v1beta1/Firestore.pbrpc.h
  Firestore/Protos/objc/google/firestore/v1beta1/Firestore.pbrpc.m
Labels: cla: yes

#1066 Redefine Async Queue library
  Firestore/core/src/firebase/firestore/util/CMakeLists.txt
  Firestore/core/src/firebase/firestore/util/config.h.in
  Firestore/core/test/firebase/firestore/util/CMakeLists.txt
Labels: Firestore, cla: yes

#1068 remove deprecated data message callback
  Firebase/Messaging/FIRMessaging.m
  Firebase/Messaging/FIRMessagingRemoteNotificationsProxy.m
  Firebase/Messaging/Public/FIRMessaging.h
Labels: cla: yes

#1070 iOS: fix data race in FSTDispatchQueue.
  Firestore/Source/Util/FSTDispatchQueue.mm
Labels: cla: yes

#1038 Refactor deserialization methods
  Firestore/core/src/firebase/firestore/remote/serializer.cc
Labels: Firestore, cla: yes

#560 Swift naming StorageVersionString
  Firebase/Storage/Public/FIRStorage.h
Labels: cla: yes

#1073 exposing FIRAppEnvironmentUtil functionalities
  FirebaseCore.podspec
Labels: cla: yes

#1075 Update protos.
  Firestore/Protos/nanopb/google/api/http.pb.c
  Firestore/Protos/nanopb/google/api/http.pb.h
  Firestore/Protos/nanopb/google/firestore/v1beta1/query.pb.h
  Firestore/Protos/nanopb/google/firestore/v1beta1/write.pb.c
  Firestore/Protos/nanopb/google/firestore/v1beta1/write.pb.h
  Firestore/Protos/objc/google/api/HTTP.pbobjc.h
  Firestore/Protos/objc/google/api/HTTP.pbobjc.m
  Firestore/Protos/objc/google/firestore/v1beta1/Document.pbobjc.h
  Firestore/Protos/objc/google/firestore/v1beta1/Firestore.pbobjc.h
  Firestore/Protos/objc/google/firestore/v1beta1/Query.pbobjc.h
  Firestore/Protos/objc/google/firestore/v1beta1/Query.pbobjc.m
  Firestore/Protos/objc/google/firestore/v1beta1/Write.pbobjc.h
  Firestore/Protos/objc/google/firestore/v1beta1/Write.pbobjc.m
  Firestore/Protos/protos/google/api/http.proto
  Firestore/Protos/protos/google/firestore/v1beta1/common.proto
  Firestore/Protos/protos/google/firestore/v1beta1/document.proto
  Firestore/Protos/protos/google/firestore/v1beta1/firestore.proto
  Firestore/Protos/protos/google/firestore/v1beta1/query.proto
  Firestore/Protos/protos/google/firestore/v1beta1/write.proto
  Firestore/Protos/protos/google/protobuf/any.proto
  Firestore/Protos/protos/google/protobuf/timestamp.proto
Labels: Firestore, cla: yes

#1053 Add CMake options to build using sanitizers
  Firestore/CMakeLists.txt
Labels: Firestore, cla: yes

#1077 Small cleanup to UserDataConverter / FieldValue sentinel code to make adding more FieldValue sentinels easier.
  Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
  Firestore/Source/API/FIRFieldValue+Internal.h
  Firestore/Source/API/FIRFieldValue.mm
  Firestore/Source/API/FSTUserDataConverter.mm
Labels: Firestore, cla: yes

#1078 Add clang-tidy checks for Firestore
  Firestore/core/.clang-tidy
  Firestore/core/include/firebase/firestore/document_reference.h
  Firestore/core/src/firebase/firestore/auth/credentials_provider.h
  Firestore/core/src/firebase/firestore/auth/firebase_credentials_provider_apple.h
  Firestore/core/src/firebase/firestore/auth/firebase_credentials_provider_apple.mm
  Firestore/core/src/firebase/firestore/auth/token.h
  Firestore/core/src/firebase/firestore/auth/user.cc
  Firestore/core/src/firebase/firestore/auth/user.h
  Firestore/core/src/firebase/firestore/core/database_info.h
  Firestore/core/src/firebase/firestore/immutable/array_sorted_map.h
  Firestore/core/src/firebase/firestore/immutable/map_entry.h
  Firestore/core/src/firebase/firestore/local/leveldb_key.cc
  Firestore/core/src/firebase/firestore/model/database_id.h
  Firestore/core/src/firebase/firestore/model/document.cc
  Firestore/core/src/firebase/firestore/model/field_mask.h
  Firestore/core/src/firebase/firestore/model/field_value.cc
  Firestore/core/src/firebase/firestore/model/field_value.h
  Firestore/core/src/firebase/firestore/remote/serializer.cc
  Firestore/core/src/firebase/firestore/remote/serializer.h
  Firestore/core/src/firebase/firestore/timestamp.cc
  Firestore/core/src/firebase/firestore/util/bits.h
  Firestore/core/src/firebase/firestore/util/comparator_holder.h
  Firestore/core/src/firebase/firestore/util/comparison.cc
  Firestore/core/test/firebase/firestore/immutable/array_sorted_map_test.cc
  Firestore/core/test/firebase/firestore/immutable/sorted_map_test.cc
  Firestore/core/test/firebase/firestore/immutable/tree_sorted_map_test.cc
  Firestore/core/test/firebase/firestore/model/document_key_test.cc
  Firestore/core/test/firebase/firestore/model/field_path_test.cc
  Firestore/core/test/firebase/firestore/model/field_value_test.cc
  Firestore/core/test/firebase/firestore/model/resource_path_test.cc
  Firestore/core/test/firebase/firestore/remote/serializer_test.cc
  Firestore/core/test/firebase/firestore/util/bits_test.cc
Labels: Firestore, cla: yes

#1076 Fixes typo that causes token parsing to break
  Example/Auth/Tests/FIRUserTests.m
  Firebase/Auth/Source/FIRUser.m
Labels: Auth, cla: yes

#1040 Port `Precondition` to C++
  Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
  Firestore/Example/Tests/Local/FSTLocalSerializerTests.mm
  Firestore/Example/Tests/Model/FSTMutationTests.mm
  Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
  Firestore/Example/Tests/Util/FSTHelpers.mm
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRWriteBatch.mm
  Firestore/Source/API/FSTUserDataConverter.h
  Firestore/Source/API/FSTUserDataConverter.mm
  Firestore/Source/Core/FSTTransaction.mm
  Firestore/Source/Model/FSTMutation.h
  Firestore/Source/Model/FSTMutation.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/model/CMakeLists.txt
  Firestore/core/src/firebase/firestore/model/precondition.cc
  Firestore/core/src/firebase/firestore/model/precondition.h
  Firestore/core/src/firebase/firestore/model/snapshot_version.h
  Firestore/core/test/firebase/firestore/model/CMakeLists.txt
  Firestore/core/test/firebase/firestore/model/precondition_test.cc
  Firestore/core/test/firebase/firestore/testutil/testutil.h
Labels: Firestore, cla: no

#1088 FirebaseCore.podspec 5.0 updates
  FirebaseCore.podspec
Labels: cla: yes

#1090 Update changelog
  Firebase/Auth/CHANGELOG.md
Labels: cla: yes

#1087 s/FIRGetSource/FIRFirestoreSource/
  Firestore/Example/SwiftBuildTest/main.swift
  Firestore/Example/Tests/Integration/API/FIRSourceTests.mm
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.h
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/Source/Public/FIRDocumentReference.h
  Firestore/Source/Public/FIRFirestoreSource.h
  Firestore/Source/Public/FIRQuery.h
Labels: cla: yes

#1085 Options should be nullable for subscription
  Example/Messaging/Tests/FIRMessagingServiceTest.m
  Firebase/Messaging/FIRMessagingPubSub.h
Labels: cla: yes

#1092 Rename version 4.12.1 to 4.13.0
  Example/Podfile
  FirebaseCore.podspec
  Firestore/Example/Podfile
Labels: cla: yes

#1083 carbon-copy of the `optional`-relevant src from abseil
  Firestore/third_party/abseil-cpp/absl/base/inline_variable_test.cc
  Firestore/third_party/abseil-cpp/absl/base/inline_variable_test_a.cc
  Firestore/third_party/abseil-cpp/absl/base/inline_variable_test_b.cc
  Firestore/third_party/abseil-cpp/absl/base/internal/identity.h
  Firestore/third_party/abseil-cpp/absl/base/internal/inline_variable.h
  Firestore/third_party/abseil-cpp/absl/base/internal/inline_variable_testing.h
  Firestore/third_party/abseil-cpp/absl/types/bad_optional_access.cc
  Firestore/third_party/abseil-cpp/absl/types/bad_optional_access.h
  Firestore/third_party/abseil-cpp/absl/types/optional.cc
  Firestore/third_party/abseil-cpp/absl/types/optional.h
  Firestore/third_party/abseil-cpp/absl/utility/utility.h
Labels: Firestore, cla: yes

#1094 Remove didReceiveAPNSToken: triggered by IID deprecated method setAPNSToken:
  Firebase/Messaging/FIRMMessageCode.h
  Firebase/Messaging/FIRMessaging.m
  Firebase/Messaging/FIRMessaging_Private.h
Labels: Messaging, cla: yes

#1098 Replace the `SetOptions` object with a simple boolean.
  Firestore/CHANGELOG.md
  Firestore/Example/SwiftBuildTest/main.swift
  Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
  Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
  Firestore/Example/Tests/Integration/API/FIRWriteBatchTests.mm
  Firestore/Example/Tests/Integration/FSTTransactionTests.mm
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRSetOptions+Internal.h
  Firestore/Source/API/FIRSetOptions.mm
  Firestore/Source/API/FIRTransaction.mm
  Firestore/Source/API/FIRWriteBatch.mm
  Firestore/Source/API/FSTUserDataConverter.h
  Firestore/Source/API/FSTUserDataConverter.mm
  Firestore/Source/Core/FSTTransaction.h
  Firestore/Source/Core/FSTTransaction.mm
  Firestore/Source/Public/FIRDocumentReference.h
  Firestore/Source/Public/FIRSetOptions.h
  Firestore/Source/Public/FIRTransaction.h
  Firestore/Source/Public/FIRWriteBatch.h
  Firestore/Source/Public/FirebaseFirestore.h
Labels: Firestore, cla: yes

#1106 Replace `QueryListenOptions` with simple booleans
  Firestore/CHANGELOG.md
  Firestore/Example/SwiftBuildTest/main.swift
  Firestore/Example/Tests/API/FIRQuerySnapshotTests.mm
  Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
  Firestore/Example/Tests/Integration/API/FIRWriteBatchTests.mm
  Firestore/Source/API/FIRDocumentChange+Internal.h
  Firestore/Source/API/FIRDocumentChange.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/API/FIRQuerySnapshot.mm
  Firestore/Source/Public/FIRQuery.h
  Firestore/Source/Public/FIRQuerySnapshot.h
Labels: Firestore, cla: yes

#1105 Fix iteration past end in LevelDBTransaction::Iterator
  Firestore/core/src/firebase/firestore/local/leveldb_transaction.cc
Labels: Firestore, cla: yes

#1113 Update CHANGELOG with most recent changes.
  Functions/CHANGELOG.md
Labels: cla: yes

#1115 Update CHANGELOG for next release.
  Firebase/Messaging/CHANGELOG.md
Labels: Messaging, cla: yes

#1114 Rewrite some LocalStore tests
  Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
Labels: cla: yes

#1109 Replace the `SnapshotOptions` object with the behavior enum.
  Firestore/CHANGELOG.md
  Firestore/Example/SwiftBuildTest/main.swift
  Firestore/Example/Tests/Integration/API/FIRServerTimestampTests.mm
  Firestore/Source/API/FIRDocumentSnapshot.mm
  Firestore/Source/API/FIRSnapshotOptions+Internal.h
  Firestore/Source/API/FIRSnapshotOptions.mm
  Firestore/Source/Model/FSTFieldValue.h
  Firestore/Source/Model/FSTFieldValue.mm
  Firestore/Source/Public/FIRDocumentSnapshot.h
Labels: Firestore, cla: yes

#1117 Fix the build and travis change detection
  Firestore/Example/SwiftBuildTest/main.swift
  scripts/if_changed.sh
Labels: Firestore, cla: yes

#1101 Implement local and server application of arrayUnion and arrayRemove transforms.
  Firestore/Example/Tests/Model/FSTMutationTests.mm
  Firestore/Source/Model/FSTMutation.mm
  Firestore/core/src/firebase/firestore/model/transform_operations.h
Labels: Firestore, cla: yes

#1120 Match previous systemVersion functionality
  Example/Core/Tests/FIRAppEnvironmentUtilTest.m
  Example/Firebase.xcodeproj/project.pbxproj
  Firebase/Core/third_party/FIRAppEnvironmentUtil.m
Labels: cla: yes

#1121 Travis: trigger rebuild if Travis config or builds scripts have changed.
  scripts/if_changed.sh
Labels: cla: yes

#1124 Fix version number reporting for minor versions.
  Example/Core/Tests/FIRAppEnvironmentUtilTest.m
  Firebase/Core/third_party/FIRAppEnvironmentUtil.m
Labels: cla: yes

#1126 Adds documentation for parseIdToken
  Firebase/Auth/Source/FIRUser.m
Labels: cla: yes

#1111 Update abseil-cpp to a new upstream
  Firestore/third_party/abseil-cpp/CMakeLists.txt
  Firestore/third_party/abseil-cpp/absl/base/CMakeLists.txt
  Firestore/third_party/abseil-cpp/absl/base/attributes.h
  Firestore/third_party/abseil-cpp/absl/base/config.h
  Firestore/third_party/abseil-cpp/absl/base/internal/raw_logging.cc
  Firestore/third_party/abseil-cpp/absl/base/internal/raw_logging.h
  Firestore/third_party/abseil-cpp/absl/base/log_severity.h
  Firestore/third_party/abseil-cpp/absl/base/macros.h
  Firestore/third_party/abseil-cpp/absl/base/policy_checks.h
  Firestore/third_party/abseil-cpp/absl/meta/type_traits.h
  Firestore/third_party/abseil-cpp/absl/numeric/int128.cc
  Firestore/third_party/abseil-cpp/absl/numeric/int128.h
  Firestore/third_party/abseil-cpp/absl/numeric/int128_have_intrinsic.inc
  Firestore/third_party/abseil-cpp/absl/numeric/int128_no_intrinsic.inc
  Firestore/third_party/abseil-cpp/absl/numeric/int128_test.cc
  Firestore/third_party/abseil-cpp/absl/strings/escaping_test.cc
  Firestore/third_party/abseil-cpp/absl/strings/internal/stl_type_traits.h
  Firestore/third_party/abseil-cpp/absl/strings/internal/utf8.h
  Firestore/third_party/abseil-cpp/absl/strings/str_cat.cc
  Firestore/third_party/abseil-cpp/absl/strings/str_cat.h
  Firestore/third_party/abseil-cpp/absl/strings/str_cat_test.cc
  Firestore/third_party/abseil-cpp/absl/strings/str_split.h
  Firestore/third_party/abseil-cpp/absl/strings/str_split_test.cc
  Firestore/third_party/abseil-cpp/absl/strings/strip_test.cc
  Firestore/third_party/abseil-cpp/absl/strings/substitute_test.cc
  Firestore/third_party/abseil-cpp/absl/types/CMakeLists.txt
  Firestore/third_party/abseil-cpp/absl/types/optional_test.cc
  Firestore/third_party/abseil-cpp/absl/utility/CMakeLists.txt
Labels: Firestore, cla: yes

#1081 Implement TreeSortedMap::insert
  Firestore/core/src/firebase/firestore/immutable/array_sorted_map.h
  Firestore/core/src/firebase/firestore/immutable/llrb_node.h
  Firestore/core/src/firebase/firestore/immutable/map_entry.h
  Firestore/core/src/firebase/firestore/immutable/sorted_map.h
  Firestore/core/src/firebase/firestore/immutable/tree_sorted_map.h
  Firestore/core/test/firebase/firestore/immutable/array_sorted_map_test.cc
  Firestore/core/test/firebase/firestore/immutable/sorted_map_test.cc
  Firestore/core/test/firebase/firestore/immutable/tree_sorted_map_test.cc
Labels: Firestore, cla: yes

#1107 Serialize array transform mutations.
  Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
  Firestore/Source/API/FSTUserDataConverter.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/model/transform_operations.h
Labels: Firestore, cla: yes

#1108 Integration tests and FSTUserDataConverter fixes for array transforms.
  Firestore/CHANGELOG.md
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/Integration/API/FIRArrayTransformTests.mm
  Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
  Firestore/Example/Tests/Model/FSTMutationTests.mm
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.h
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
  Firestore/Source/API/FIRFieldValue.mm
  Firestore/Source/API/FSTUserDataConverter.mm
Labels: Firestore, cla: yes

#1130 Remove non-technical FirebaseAnalytics dependencies
  FirebaseAuth.podspec
  FirebaseDatabase.podspec
  FirebaseFirestore.podspec
  FirebaseMessaging.podspec
  FirebaseStorage.podspec
Labels: cla: yes

#1125 podspec updates for Firebase 5
  FirebaseAuth.podspec
  FirebaseCore.podspec
  FirebaseDatabase.podspec
  FirebaseFirestore.podspec
  FirebaseFunctions.podspec
  FirebaseMessaging.podspec
  FirebaseStorage.podspec
Labels: cla: yes

#1131 Fixes error handling when parsing tokens.
  Firebase/Auth/Source/FIRUser.m
Labels: cla: yes

#1096 merge firestore-api-changes to master
  Firestore/CHANGELOG.md
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/SwiftBuildTest/main.swift
  Firestore/Example/Tests/Integration/API/FIRFirestoreSourceTests.mm
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.h
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/Core/FSTFirestoreClient.h
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/Source/Public/FIRDocumentReference.h
  Firestore/Source/Public/FIRFirestoreSource.h
  Firestore/Source/Public/FIRQuery.h
Labels: Firestore, cla: yes

#1118 Firestore Travis: ensure CTest outputs the log on failure.
  scripts/build.sh
Labels: cla: yes

#1134 Replace the `SetOptions` object with a simple boolean (cont.)
  Firestore/Example/Tests/Integration/API/FIRFirestoreSourceTests.mm
Labels: Firestore, cla: yes

#1136 Fix bad type annotation in claims
  Firebase/Auth/Source/Public/FIRAuthTokenResult.h
Labels: Auth, cla: yes

#1132 Implement iterators for our immutable maps
  Firestore/core/src/firebase/firestore/immutable/CMakeLists.txt
  Firestore/core/src/firebase/firestore/immutable/array_sorted_map.h
  Firestore/core/src/firebase/firestore/immutable/llrb_node.h
  Firestore/core/src/firebase/firestore/immutable/llrb_node_iterator.h
  Firestore/core/src/firebase/firestore/immutable/sorted_map.h
  Firestore/core/src/firebase/firestore/immutable/sorted_map_iterator.h
  Firestore/core/src/firebase/firestore/immutable/tree_sorted_map.h
  Firestore/core/test/firebase/firestore/immutable/sorted_map_test.cc
  Firestore/core/test/firebase/firestore/immutable/testing.h
Labels: Firestore, cla: yes

#751 Add unit tests for FirebaseCore
  Example/Core/App/iOS/Core-Info.plist
  Example/Core/App/macOS/Core-Info.plist
  Example/Core/App/tvOS/Info.plist
  Example/Core/Tests/FIRMutableDictionaryTest.m
  Example/Core/Tests/FIRNetworkTest.m
  Example/Core/Tests/FIRReachabilityCheckerTest.m
  Example/Core/Tests/Tests-Info.plist
  Example/Core/Tests/third_party/GTMHTTPServer.h
  Example/Core/Tests/third_party/GTMHTTPServer.m
  Example/Firebase.xcodeproj/project.pbxproj
Labels: cla: yes

#1146 Clean up warnings in Firestore
  Firestore/Example/Tests/Util/FSTDispatchQueueTests.mm
  Firestore/Example/Tests/Util/FSTEventAccumulator.mm
  Firestore/Source/Model/FSTMutation.mm
  Firestore/core/src/firebase/firestore/util/error_apple.h
Labels: Firestore, cla: yes

#1148 Prep Firestore Podfile for multiple platforms
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Podfile
Labels: Firestore, cla: yes

#1149 replace the private OCMock method with a public one
  Example/Messaging/Tests/FIRMessagingTest.m
Labels: Messaging, cla: yes

#1153 Remove deleted framework from Link with Library phases
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
Labels: cla: yes

#1154 Fix build breakages under linux (gcc)
  Firestore/core/src/firebase/firestore/immutable/llrb_node.h
  Firestore/core/src/firebase/firestore/immutable/sorted_map_iterator.h
Labels: Firestore, cla: yes

#1156 Temporarily disable pod lib lint
  .travis.yml
Labels: cla: yes

#1152 Add missing copyright and licenses
  Functions/Backend/index.js
  scripts/check_copyright.sh
  scripts/cpplint.py
Labels: cla: yes

#1145 Implement find-related methods on C++ immutable maps
  Firestore/core/src/firebase/firestore/immutable/array_sorted_map.h
  Firestore/core/src/firebase/firestore/immutable/llrb_node.h
  Firestore/core/src/firebase/firestore/immutable/llrb_node_iterator.h
  Firestore/core/src/firebase/firestore/immutable/sorted_map.h
  Firestore/core/src/firebase/firestore/immutable/sorted_map_base.cc
  Firestore/core/src/firebase/firestore/immutable/sorted_map_base.h
  Firestore/core/src/firebase/firestore/immutable/tree_sorted_map.h
  Firestore/core/src/firebase/firestore/util/comparison.h
  Firestore/core/test/firebase/firestore/immutable/array_sorted_map_test.cc
  Firestore/core/test/firebase/firestore/immutable/sorted_map_test.cc
  Firestore/core/test/firebase/firestore/immutable/testing.h
Labels: Firestore, cla: yes

#1122 Filter out document updates from target association changes
  Firestore/Example/Tests/Remote/FSTRemoteEventTests.mm
  Firestore/Source/Core/FSTSyncEngine.mm
  Firestore/Source/Core/FSTView.h
  Firestore/Source/Remote/FSTRemoteEvent.h
  Firestore/Source/Remote/FSTRemoteEvent.mm
Labels: Firestore, cla: yes

#1160 pod lib lint status
  scripts/push-pods.sh
Labels: cla: yes

#1139 Move array transforms to internal header pending backend support.
  Firestore/CHANGELOG.md
  Firestore/Example/SwiftBuildTest/main.swift
  Firestore/Example/Tests/Integration/API/FIRArrayTransformTests.mm
  Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
  Firestore/Example/Tests/Model/FSTMutationTests.mm
  Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
  Firestore/Source/API/FIRFieldValue+Internal.h
  Firestore/Source/Public/FIRFieldValue.h
Labels: Firestore, cla: yes

#1155 Eliminate tvOS deprecation warnings in FirebaseDatabase
  Firebase/Database/Utilities/NSString+FURLUtils.h
  Firebase/Database/Utilities/NSString+FURLUtils.m
Labels: Database, cla: yes

#1161 Fixes base64URL encoding
  Example/Auth/Tests/FIRUserTests.m
  Firebase/Auth/Source/FIRUser.m
Labels: cla: yes

#1162 Merge base64url encoding fix to staging-4.13.1
  Example/Auth/Tests/FIRUserTests.m
  Firebase/Auth/Source/FIRUser.m
Labels: cla: yes

#1144 Update `FieldValue` For Porting `Mutation`s to C++
  Firestore/core/src/firebase/firestore/model/CMakeLists.txt
  Firestore/core/src/firebase/firestore/model/document.h
  Firestore/core/src/firebase/firestore/model/field_value.cc
  Firestore/core/src/firebase/firestore/model/field_value.h
  Firestore/core/src/firebase/firestore/model/maybe_document.h
  Firestore/core/test/firebase/firestore/model/field_value_test.cc
Labels: Firestore, cla: yes

#1163 Update travis to use Xcode 9.3
  .travis.yml
  Example/Database/Tests/Unit/FLevelDBStorageEngineTests.m
Labels: cla: yes

#1138 Array Contains Queries (not added to public headers yet).
  Firestore/Example/SwiftBuildTest/main.swift
  Firestore/Example/Tests/Core/FSTQueryTests.mm
  Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
  Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
  Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
  Firestore/Example/Tests/Util/FSTHelpers.h
  Firestore/Example/Tests/Util/FSTHelpers.mm
  Firestore/Source/API/FIRQuery+Internal.h
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/Core/FSTQuery.h
  Firestore/Source/Core/FSTQuery.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
Labels: Firestore, cla: yes

#1128 Firestore Travis: add test runs using sanitizers
  .travis.yml
  CMakeLists.txt
  cmake/external/firestore.cmake
  scripts/build.sh
  scripts/install_prereqs.sh
  scripts/pod_install.sh
Labels: cla: yes

#1170 Should always query the latest checkin info from InstanceID
  Firebase/Messaging/FIRMessagingClient.m
  Firebase/Messaging/FIRMessagingRegistrar.m
Labels: Messaging, cla: yes

#1039 Adjust serializer test to verify via libprotobuf.
  Firestore/CMakeLists.txt
  Firestore/Protos/CMakeLists.txt
  Firestore/Protos/build-protos.sh
  Firestore/Protos/cpp/firestore/local/maybe_document.pb.cc
  Firestore/Protos/cpp/firestore/local/maybe_document.pb.h
  Firestore/Protos/cpp/firestore/local/mutation.pb.cc
  Firestore/Protos/cpp/firestore/local/mutation.pb.h
  Firestore/Protos/cpp/firestore/local/target.pb.cc
  Firestore/Protos/cpp/firestore/local/target.pb.h
  Firestore/Protos/cpp/google/api/annotations.pb.cc
  Firestore/Protos/cpp/google/api/annotations.pb.h
  Firestore/Protos/cpp/google/api/http.pb.cc
  Firestore/Protos/cpp/google/api/http.pb.h
  Firestore/Protos/cpp/google/firestore/v1beta1/common.pb.cc
  Firestore/Protos/cpp/google/firestore/v1beta1/common.pb.h
  Firestore/Protos/cpp/google/firestore/v1beta1/document.pb.cc
  Firestore/Protos/cpp/google/firestore/v1beta1/document.pb.h
  Firestore/Protos/cpp/google/firestore/v1beta1/firestore.pb.cc
  Firestore/Protos/cpp/google/firestore/v1beta1/firestore.pb.h
  Firestore/Protos/cpp/google/firestore/v1beta1/query.pb.cc
  Firestore/Protos/cpp/google/firestore/v1beta1/query.pb.h
  Firestore/Protos/cpp/google/firestore/v1beta1/write.pb.cc
  Firestore/Protos/cpp/google/firestore/v1beta1/write.pb.h
  Firestore/Protos/cpp/google/protobuf/any.pb.cc
  Firestore/Protos/cpp/google/protobuf/any.pb.h
  Firestore/Protos/cpp/google/protobuf/empty.pb.cc
  Firestore/Protos/cpp/google/protobuf/empty.pb.h
  Firestore/Protos/cpp/google/protobuf/struct.pb.cc
  Firestore/Protos/cpp/google/protobuf/struct.pb.h
  Firestore/Protos/cpp/google/protobuf/timestamp.pb.cc
  Firestore/Protos/cpp/google/protobuf/timestamp.pb.h
  Firestore/Protos/cpp/google/protobuf/wrappers.pb.cc
  Firestore/Protos/cpp/google/protobuf/wrappers.pb.h
  Firestore/Protos/cpp/google/rpc/status.pb.cc
  Firestore/Protos/cpp/google/rpc/status.pb.h
  Firestore/Protos/cpp/google/type/latlng.pb.cc
  Firestore/Protos/cpp/google/type/latlng.pb.h
  Firestore/core/src/firebase/firestore/remote/serializer.cc
  Firestore/core/src/firebase/firestore/remote/serializer.h
  Firestore/core/test/firebase/firestore/remote/CMakeLists.txt
  Firestore/core/test/firebase/firestore/remote/serializer_test.cc
  cmake/FindProtobuf.cmake
  scripts/check_whitespace.sh
Labels: Firestore, cla: yes

#1158 Implement erase in C++ immutable maps
  Firestore/core/src/firebase/firestore/immutable/array_sorted_map.h
  Firestore/core/src/firebase/firestore/immutable/llrb_node.h
  Firestore/core/src/firebase/firestore/immutable/llrb_node_iterator.h
  Firestore/core/src/firebase/firestore/immutable/sorted_map.h
  Firestore/core/src/firebase/firestore/immutable/tree_sorted_map.h
  Firestore/core/test/firebase/firestore/immutable/array_sorted_map_test.cc
  Firestore/core/test/firebase/firestore/immutable/sorted_map_test.cc
Labels: Firestore, cla: yes

#1173 fix a bug caught by asan failure
  Firestore/core/src/firebase/firestore/model/field_value.cc
Labels: Firestore, cla: yes

#1159 Eliminate an Auth tvOS build warning
  Example/Firebase.xcodeproj/project.pbxproj
  Firebase/Auth/Source/FIRAuthNotificationManager.m
Labels: cla: yes

#1178 Remove unnecesary function that broke build
  Firebase/Auth/Source/FIRAuthWebUtils.h
  Firebase/Auth/Source/FIRAuthWebUtils.m
Labels: cla: yes

#1168 Add counter for errors and warnings logged.
  Example/Core/Tests/FIRLoggerTest.m
  Firebase/Core/FIRLogger.m
  Firebase/Core/Private/FIRLogger.h
Labels: cla: yes

#1123 First pass of Auth breaking changes
  Example/Auth/Sample/MainViewController.m
  Example/Auth/Tests/FIRAuthTests.m
  Example/Auth/Tests/FIRUserTests.m
  Firebase/Auth/Source/FIRAuth.m
  Firebase/Auth/Source/Public/FIRAuth.h
Labels: Auth, cla: yes

#1183 Fix new Xcode 9.3 warnings
  Firebase/Core/FIRNetworkURLSession.m
  Firebase/Database/FViewProcessor.m
  Firebase/Messaging/FIRMessagingRmq2PersistentStore.m
Labels: cla: yes

#1182 Port `SnapshotVersion` for `Local`
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Source/Local/FSTLevelDBQueryCache.mm
  Firestore/Source/Local/FSTLocalDocumentsView.mm
  Firestore/Source/Local/FSTLocalSerializer.h
  Firestore/Source/Local/FSTLocalSerializer.mm
  Firestore/Source/Local/FSTLocalStore.h
  Firestore/Source/Local/FSTLocalStore.mm
  Firestore/Source/Local/FSTMemoryQueryCache.mm
  Firestore/Source/Local/FSTQueryCache.h
  Firestore/Source/Local/FSTQueryData.h
  Firestore/Source/Local/FSTQueryData.mm
  Firestore/core/src/firebase/firestore/model/snapshot_version.h
Labels: Firestore, cla: yes

#1184 Updates for push-pods script
  scripts/push-pods.sh
Labels: cla: yes

#1167 Identify limbo-only document updates
  Firestore/Example/Tests/Remote/FSTRemoteEventTests.mm
  Firestore/Source/Core/FSTSyncEngine.mm
  Firestore/Source/Remote/FSTRemoteEvent.h
  Firestore/Source/Remote/FSTRemoteEvent.mm
Labels: cla: yes

#1186 Adds new callback to createUserWithEmail: API (breaking change)
  Example/Auth/Sample/MainViewController.m
  Example/Auth/SwiftSample/ViewController.swift
  Example/Auth/Tests/FIRAuthTests.m
  Firebase/Auth/Source/FIRAuth.m
  Firebase/Auth/Source/Public/FIRAuth.h
Labels: cla: yes

#1188 Removes deprecated getToken APIs
  Firebase/Auth/Source/FIRUser.m
  Firebase/Auth/Source/Public/FIRUser.h
Labels: cla: yes

#1187 Add explicit Functions umbrella
  Functions/FirebaseFunctions/Public/FirebaseFunctions.h
Labels: Functions, cla: yes

#1189 Three cherry picks for release-5.0.0
  Example/Auth/Sample/MainViewController.m
  Example/Auth/SwiftSample/ViewController.swift
  Example/Auth/Tests/FIRAuthTests.m
  Firebase/Auth/Source/FIRAuth.m
  Firebase/Auth/Source/FIRUser.m
  Firebase/Auth/Source/Public/FIRAuth.h
  Firebase/Auth/Source/Public/FIRUser.h
  Functions/FirebaseFunctions/Public/FirebaseFunctions.h
Labels: cla: yes

#1191 shouldEstablishDirectChannel cannot be replaced by isDirectChannelEst…
  Firebase/Messaging/FIRMessaging.m
  Firebase/Messaging/Public/FIRMessaging.h
Labels: cla: yes

#1192 Adds phone auth testing. (disableAppVerification)
  Example/Auth/Sample/SettingsViewController.m
  Example/Auth/Tests/FIRPhoneAuthProviderTests.m
  Firebase/Auth/Source/AuthProviders/Phone/FIRPhoneAuthProvider.m
  Firebase/Auth/Source/FIRAuth.m
  Firebase/Auth/Source/FIRAuthSettings.m
  Firebase/Auth/Source/Public/FIRAuth.h
  Firebase/Auth/Source/Public/FIRAuthSettings.h
  Firebase/Auth/Source/Public/FirebaseAuth.h
  Firebase/Auth/Source/RPCs/FIRAuthBackend.m
Labels: cla: yes

#1194 Cherry pick #1192 to release-5.0.0
  Example/Auth/Sample/SettingsViewController.m
  Example/Auth/Tests/FIRPhoneAuthProviderTests.m
  Firebase/Auth/Source/AuthProviders/Phone/FIRPhoneAuthProvider.m
  Firebase/Auth/Source/FIRAuth.m
  Firebase/Auth/Source/FIRAuthSettings.m
  Firebase/Auth/Source/Public/FIRAuth.h
  Firebase/Auth/Source/Public/FIRAuthSettings.h
  Firebase/Auth/Source/Public/FirebaseAuth.h
  Firebase/Auth/Source/RPCs/FIRAuthBackend.m
Labels: cla: yes

#1193 Try recommended stability improvements and restoring pod lib lint
  .travis.yml
Labels: cla: yes

#1196 Remove iOS 7 Simulator check from FIRLogger.
  Firebase/Core/FIRLogger.m
Labels: Core, cla: yes
