Repository firebase/firebase-ios-sdk, pull requests merged in 2018-11, with the labels that each got.

#2034 Fix static analysis warning in Core.
  Firebase/Core/FIRApp.m
Labels: Core, cla: yes

#2035 Update CHANGELOG.md for #2034
  Firebase/Core/CHANGELOG.md
Labels: cla: yes

#2030 Revert "gRPC: replace Objective-C implementation with the new C++ implementation (#1968)"
  FirebaseFirestore.podspec
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
  Firestore/Example/Tests/Integration/FSTStreamTests.mm
  Firestore/Example/Tests/Remote/FSTDatastoreTests.mm
  Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
  Firestore/Example/Tests/SpecTests/FSTMockDatastore.h
  Firestore/Example/Tests/SpecTests/FSTMockDatastore.mm
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
  Firestore/Protos/CMakeLists.txt
  Firestore/Protos/build_protos.py
  Firestore/Protos/objc/google/firestore/v1beta1/Firestore.pbrpc.h
  Firestore/Protos/objc/google/firestore/v1beta1/Firestore.pbrpc.m
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/Core/FSTSyncEngine.mm
  Firestore/Source/Core/FSTTransaction.mm
  Firestore/Source/Remote/FSTBufferedWriter.h
  Firestore/Source/Remote/FSTBufferedWriter.mm
  Firestore/Source/Remote/FSTDatastore.h
  Firestore/Source/Remote/FSTDatastore.mm
  Firestore/Source/Remote/FSTExponentialBackoff.h
  Firestore/Source/Remote/FSTExponentialBackoff.mm
  Firestore/Source/Remote/FSTRemoteStore.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/Source/Remote/FSTStream.h
  Firestore/Source/Remote/FSTStream.mm
  Firestore/Source/Util/FSTDispatchQueue.h
  Firestore/Source/Util/FSTDispatchQueue.mm
  Firestore/core/src/firebase/firestore/remote/grpc_connection.h
  Firestore/core/src/firebase/firestore/remote/grpc_connection.mm
  Firestore/core/src/firebase/firestore/remote/grpc_root_certificate_finder.h
  Firestore/core/src/firebase/firestore/remote/grpc_root_certificate_finder_apple.mm
  Firestore/core/src/firebase/firestore/remote/stream.h
  Firestore/core/src/firebase/firestore/remote/watch_stream.h
  Firestore/core/src/firebase/firestore/remote/write_stream.h
  Firestore/core/test/firebase/firestore/remote/grpc_stream_test.cc
  Firestore/etc/roots.pem
Labels: Firestore, cla: yes

#2031 Partially revert "Update CHANGELOG for Firestore v0.14.0 (#2025)"
  Firestore/CHANGELOG.md
Labels: Firestore, cla: yes

#2036 Move #2034 into 5.12.0
  Firebase/Core/CHANGELOG.md
Labels: cla: yes

#2037 Held Write Acks Changelog
  Firestore/CHANGELOG.md
Labels: Firestore, cla: yes

#2032 Fix tablet layout for in-app messaging
  Firebase/InAppMessagingDisplay/Modal/FIDModalViewController.m
  Firebase/InAppMessagingDisplay/Resources/FIRInAppMessageDisplayStoryboard.storyboard
Labels: InAppMessaging, cla: yes

#2033 Address travis timeout flakes
  InAppMessagingDisplay/Example/InAppMessagingDisplay-UITests/InAppMessagingDisplayUITestsBase.swift
Labels: cla: yes

#2038 Delete deprecated files
  Example/DynamicLinks/Tests/GINDurableDeepLinkServiceReceivingTests.m
  Example/Firebase.xcodeproj/project.pbxproj
  Firebase/DynamicLinks/CHANGELOG.md
  Firebase/DynamicLinks/GINDurableDeepLinkService.h
  Firebase/DynamicLinks/GINDurableDeepLinkServiceReceiving+Private.h
  Firebase/DynamicLinks/GINDurableDeepLinkServiceReceiving.h
  Firebase/DynamicLinks/GINDurableDeepLinkServiceReceiving.m
  Firebase/DynamicLinks/GINDurableDeepLinkService_Headers.h
Labels: cla: yes

#2042 Add missing nanopb flag
  FirebaseFirestore.podspec
Labels: cla: yes

#2043 Fix auth multi app support
  Example/Auth/Sample/AppManager.m
  Example/Auth/Sample/SettingsViewController.m
Labels: cla: yes

#2046 Isolate Firestore nanopb messages in C++ namespaces
  FirebaseFirestore.podspec
  Firestore/Protos/CMakeLists.txt
  Firestore/Protos/build_protos.py
  Firestore/Protos/nanopb/firestore/local/maybe_document.nanopb.cc
  Firestore/Protos/nanopb/firestore/local/maybe_document.nanopb.h
  Firestore/Protos/nanopb/firestore/local/mutation.nanopb.cc
  Firestore/Protos/nanopb/firestore/local/mutation.nanopb.h
  Firestore/Protos/nanopb/firestore/local/target.nanopb.cc
  Firestore/Protos/nanopb/firestore/local/target.nanopb.h
  Firestore/Protos/nanopb/google/api/annotations.nanopb.cc
  Firestore/Protos/nanopb/google/api/annotations.nanopb.h
  Firestore/Protos/nanopb/google/api/http.nanopb.cc
  Firestore/Protos/nanopb/google/api/http.nanopb.h
  Firestore/Protos/nanopb/google/firestore/v1beta1/common.nanopb.cc
  Firestore/Protos/nanopb/google/firestore/v1beta1/common.nanopb.h
  Firestore/Protos/nanopb/google/firestore/v1beta1/document.nanopb.cc
  Firestore/Protos/nanopb/google/firestore/v1beta1/document.nanopb.h
  Firestore/Protos/nanopb/google/firestore/v1beta1/firestore.nanopb.cc
  Firestore/Protos/nanopb/google/firestore/v1beta1/firestore.nanopb.h
  Firestore/Protos/nanopb/google/firestore/v1beta1/query.nanopb.cc
  Firestore/Protos/nanopb/google/firestore/v1beta1/query.nanopb.h
  Firestore/Protos/nanopb/google/firestore/v1beta1/write.nanopb.cc
  Firestore/Protos/nanopb/google/firestore/v1beta1/write.nanopb.h
  Firestore/Protos/nanopb/google/protobuf/any.nanopb.cc
  Firestore/Protos/nanopb/google/protobuf/any.nanopb.h
  Firestore/Protos/nanopb/google/protobuf/empty.nanopb.cc
  Firestore/Protos/nanopb/google/protobuf/empty.nanopb.h
  Firestore/Protos/nanopb/google/protobuf/struct.nanopb.cc
  Firestore/Protos/nanopb/google/protobuf/struct.nanopb.h
  Firestore/Protos/nanopb/google/protobuf/timestamp.nanopb.cc
  Firestore/Protos/nanopb/google/protobuf/timestamp.nanopb.h
  Firestore/Protos/nanopb/google/protobuf/wrappers.nanopb.cc
  Firestore/Protos/nanopb/google/protobuf/wrappers.nanopb.h
  Firestore/Protos/nanopb/google/rpc/status.nanopb.cc
  Firestore/Protos/nanopb/google/rpc/status.nanopb.h
  Firestore/Protos/nanopb/google/type/latlng.nanopb.cc
  Firestore/Protos/nanopb/google/type/latlng.nanopb.h
Labels: Firestore, cla: yes

#2039 gRPC: fix bugs found during testing
  Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_IntegrationTests_iOS.xcscheme
  Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_Tests_iOS.xcscheme
  Firestore/core/src/firebase/firestore/remote/grpc_connection.mm
  Firestore/core/src/firebase/firestore/remote/grpc_stream.cc
  Firestore/core/src/firebase/firestore/remote/grpc_stream.h
  Firestore/core/test/firebase/firestore/remote/grpc_stream_test.cc
  Firestore/core/test/firebase/firestore/remote/grpc_streaming_reader_test.cc
  Firestore/core/test/firebase/firestore/remote/stream_test.mm
  Firestore/core/test/firebase/firestore/util/grpc_stream_tester.cc
  Firestore/core/test/firebase/firestore/util/grpc_stream_tester.h
Labels: Firestore, cla: yes

#2047 Fix analyze errors
  Example/Database/Tests/Unit/FPruneForestTest.m
  Example/DynamicLinks/Tests/FIRDLScionLoggingTest.m
  Example/Firebase.xcodeproj/xcshareddata/xcschemes/AllUnitTests_iOS.xcscheme
  Example/Messaging/Tests/FIRMessagingAnalyticsTest.m
  Firebase/DynamicLinks/FDLURLComponents/FDLURLComponents.m
  Firebase/DynamicLinks/FIRDLDefaultRetrievalProcessV2.m
  Firebase/DynamicLinks/FIRDynamicLinks.m
Labels: cla: yes

#2050 Delete Firestore public C++ API
  CMakeLists.txt
  Firestore/core/include/firebase/firestore/CMakeLists.txt
  Firestore/core/include/firebase/firestore/collection_reference.h
  Firestore/core/include/firebase/firestore/document_change.h
  Firestore/core/include/firebase/firestore/document_reference.h
  Firestore/core/include/firebase/firestore/document_snapshot.h
  Firestore/core/include/firebase/firestore/event_listener.h
  Firestore/core/include/firebase/firestore/field_path.h
  Firestore/core/include/firebase/firestore/field_value.h
  Firestore/core/include/firebase/firestore/firestore.h
  Firestore/core/include/firebase/firestore/listener_registration.h
  Firestore/core/include/firebase/firestore/map_field_value.h
  Firestore/core/include/firebase/firestore/metadata_changes.h
  Firestore/core/include/firebase/firestore/query.h
  Firestore/core/include/firebase/firestore/query_snapshot.h
  Firestore/core/include/firebase/firestore/set_options.h
  Firestore/core/include/firebase/firestore/settings.h
  Firestore/core/include/firebase/firestore/snapshot_metadata.h
  Firestore/core/include/firebase/firestore/source.h
  Firestore/core/include/firebase/firestore/transaction.h
  Firestore/core/include/firebase/firestore/write_batch.h
Labels: Firestore, cla: yes

#2057 Add clang-format installation instructions
  README.md
Labels: cla: yes

#1962 Add support for validating FDL links from custom domains.
  Example/DynamicLinks/App/iOS/DL-Info.plist
  Example/DynamicLinks/FDLBuilderTestAppObjC/AppDelegate.m
  Example/DynamicLinks/FDLBuilderTestAppObjC/Info.plist
  Example/DynamicLinks/FDLBuilderTestAppObjCTests/Info.plist
  Example/DynamicLinks/Tests/FIRDynamicLinksTest.m
  Firebase/DynamicLinks/FIRDynamicLinks.m
  Firebase/DynamicLinks/Utilities/FDLUtilities.h
  Firebase/DynamicLinks/Utilities/FDLUtilities.m
Labels: cla: yes

#2061 Invalidate non-background url sessions
  Example/tvOSSample/tvOSSample/AuthViewController.swift
  Example/tvOSSample/tvOSSample/EmailLoginViewController.swift
  GoogleUtilities/CHANGELOG.md
  GoogleUtilities/Network/GULNetworkURLSession.m
  GoogleUtilities/Network/Private/GULNetworkURLSession.h
Labels: GoogleUtilities, cla: yes

#2064 Adding Numeric Add Proto message
  Firestore/Protos/cpp/google/firestore/v1beta1/write.pb.cc
  Firestore/Protos/cpp/google/firestore/v1beta1/write.pb.h
  Firestore/Protos/nanopb/google/firestore/v1beta1/write.nanopb.cc
  Firestore/Protos/nanopb/google/firestore/v1beta1/write.nanopb.h
  Firestore/Protos/objc/google/firestore/v1beta1/Write.pbobjc.h
  Firestore/Protos/objc/google/firestore/v1beta1/Write.pbobjc.m
  Firestore/Protos/protos/google/firestore/v1beta1/write.proto
Labels: Firestore, cla: yes

#2066 Adding base_writes proto field
  Firestore/Protos/cpp/firestore/local/mutation.pb.cc
  Firestore/Protos/cpp/firestore/local/mutation.pb.h
  Firestore/Protos/nanopb/firestore/local/mutation.nanopb.cc
  Firestore/Protos/nanopb/firestore/local/mutation.nanopb.h
  Firestore/Protos/objc/firestore/local/Mutation.pbobjc.h
  Firestore/Protos/objc/firestore/local/Mutation.pbobjc.m
  Firestore/Protos/protos/firestore/local/mutation.proto
Labels: cla: yes

#2053 Update the GULObjectSwizzler to handle NSProxy objects
  GoogleUtilities/CHANGELOG.md
  GoogleUtilities/Example/Tests/Swizzler/GULObjectSwizzlerTest.m
  GoogleUtilities/ISASwizzler/GULObjectSwizzler.m
  GoogleUtilities/ISASwizzler/GULSwizzledObject.m
  GoogleUtilities/ISASwizzler/Private/GULObjectSwizzler.h
  GoogleUtilities/SwizzlerTestHelpers/GULProxy.h
  GoogleUtilities/SwizzlerTestHelpers/GULProxy.m
Labels: cla: yes

#2067 GoogleUtilities 5.3.5
  GoogleUtilities.podspec
  GoogleUtilities/CHANGELOG.md
Labels: cla: yes

#2074 Fix `string_view` referring to an out-of-scope string
  Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_Tests_iOS.xcscheme
  Firestore/Example/Tests/API/FSTAPIHelpers.mm
Labels: Firestore, cla: yes

#2071 Allow setting the domainURIPrefix for custom domain names/paths when creating dynamic links
  Example/DynamicLinks/FDLBuilderTestAppObjC/ViewController.m
  Example/DynamicLinks/Tests/FDLURLComponentsTests.m
  Example/DynamicLinks/Tests/FIRDynamicLinkNetworkingTests.m
  Firebase/DynamicLinks/FDLURLComponents/FDLURLComponents.m
  Firebase/DynamicLinks/Logging/FDLLogging.h
  Firebase/DynamicLinks/Public/FDLURLComponents.h
Labels: DynamicLinks, cla: yes

#2076 Release manifest for 5.13.0
  Releases/Manifests/5.13.0
Labels: cla: yes

#2077 Renaming manifest
  Releases/Manifests/5.13.0.json
Labels: cla: yes

#2078 Add warning for deprecated API to indicate that the passed in domain name's scheme will deduced as https
  Firebase/DynamicLinks/CHANGELOG.md
  Firebase/DynamicLinks/FDLURLComponents/FDLURLComponents.m
  Firebase/DynamicLinks/Logging/FDLLogging.h
  Firebase/DynamicLinks/Public/FDLURLComponents.h
Labels: cla: yes

#2079 Fix GoogleUtilities nullability regressions
  GoogleUtilities.podspec
  GoogleUtilities/CHANGELOG.md
  GoogleUtilities/Network/GULNetworkURLSession.m
  GoogleUtilities/Network/Private/GULNetworkURLSession.h
Labels: cla: yes

#2083 Remove `adjustsFontForContentSizeCategory` from labels in card layout Storyboard
  Firebase/InAppMessagingDisplay/Resources/FIRInAppMessageDisplayStoryboard.storyboard
Labels: cla: yes

#2084 Add pod spec lint testing for Xcode 9
  .travis.yml
Labels: cla: yes

#2088 FirebaseAnalyticsInterop is cross-platform
  FirebaseDynamicLinks.podspec
  FirebaseMessaging.podspec
Labels: cla: yes

#1865 Database Interop
  Example/Database/Tests/Helpers/FDevice.h
  Example/Database/Tests/Helpers/FDevice.m
  Example/Database/Tests/Helpers/FIRFakeApp.h
  Example/Database/Tests/Helpers/FIRFakeApp.m
  Example/Database/Tests/Helpers/FTestHelpers.h
  Example/Database/Tests/Helpers/FTestHelpers.m
  Example/Database/Tests/Integration/FData.m
  Example/Database/Tests/Integration/FDotInfo.m
  Example/Database/Tests/Integration/FIRAuthTests.m
  Example/Database/Tests/Integration/FIRDatabaseTests.m
  Example/Database/Tests/Integration/FRealtime.m
  Example/Database/Tests/Integration/FTransactionTest.m
  Example/Database/Tests/Unit/FIRDataSnapshotTests.m
  Example/Database/Tests/Unit/FUtilitiesTest.m
  Example/Firebase.xcodeproj/project.pbxproj
  Firebase/Database/Api/FIRDatabase.m
  Firebase/Database/Api/FIRDatabaseComponent.h
  Firebase/Database/Api/FIRDatabaseComponent.m
  Firebase/Database/Api/FIRDatabaseConfig.m
  Firebase/Database/Api/Private/FIRDatabaseReference_Private.h
  Firebase/Database/Api/Private/FIRDatabase_Private.h
  Firebase/Database/FIRDatabaseConfig_Private.h
  Firebase/Database/FIRDatabaseReference.m
  Firebase/Database/Login/FAuthTokenProvider.h
  Firebase/Database/Login/FAuthTokenProvider.m
  FirebaseDatabase.podspec
Labels: cla: yes

#2093 Revert "Database Interop"
  Example/Database/Tests/Helpers/FDevice.h
  Example/Database/Tests/Helpers/FDevice.m
  Example/Database/Tests/Helpers/FIRFakeApp.h
  Example/Database/Tests/Helpers/FIRFakeApp.m
  Example/Database/Tests/Helpers/FTestHelpers.h
  Example/Database/Tests/Helpers/FTestHelpers.m
  Example/Database/Tests/Integration/FData.m
  Example/Database/Tests/Integration/FDotInfo.m
  Example/Database/Tests/Integration/FIRAuthTests.m
  Example/Database/Tests/Integration/FIRDatabaseTests.m
  Example/Database/Tests/Integration/FRealtime.m
  Example/Database/Tests/Integration/FTransactionTest.m
  Example/Database/Tests/Unit/FIRDataSnapshotTests.m
  Example/Database/Tests/Unit/FUtilitiesTest.m
  Example/Firebase.xcodeproj/project.pbxproj
  Firebase/Database/Api/FIRDatabase.m
  Firebase/Database/Api/FIRDatabaseComponent.h
  Firebase/Database/Api/FIRDatabaseComponent.m
  Firebase/Database/Api/FIRDatabaseConfig.m
  Firebase/Database/Api/Private/FIRDatabaseReference_Private.h
  Firebase/Database/Api/Private/FIRDatabase_Private.h
  Firebase/Database/FIRDatabaseConfig_Private.h
  Firebase/Database/FIRDatabaseReference.m
  Firebase/Database/Login/FAuthTokenProvider.h
  Firebase/Database/Login/FAuthTokenProvider.m
  FirebaseDatabase.podspec
Labels: cla: yes

#2097 Revert premature api changes
  Example/DynamicLinks/App/iOS/DL-Info.plist
  Example/DynamicLinks/FDLBuilderTestAppObjC/Info.plist
  Example/DynamicLinks/FDLBuilderTestAppObjC/ViewController.m
  Example/DynamicLinks/FDLBuilderTestAppObjCTests/Info.plist
  Example/DynamicLinks/Tests/FDLURLComponentsTests.m
  Example/DynamicLinks/Tests/FIRDynamicLinkNetworkingTests.m
  Example/DynamicLinks/Tests/FIRDynamicLinksTest.m
  Firebase/DynamicLinks/CHANGELOG.md
  Firebase/DynamicLinks/FDLURLComponents/FDLURLComponents.m
  Firebase/DynamicLinks/FIRDynamicLinks.m
  Firebase/DynamicLinks/Logging/FDLLogging.h
  Firebase/DynamicLinks/Public/FDLURLComponents.h
  Firebase/DynamicLinks/Utilities/FDLUtilities.h
  Firebase/DynamicLinks/Utilities/FDLUtilities.m
Labels: cla: yes

#2096 Add test for verify iOS client
  Example/Auth/EarlGreyTests/FIRVerifyIOSClientTests.m
  Example/Auth/EarlGreyTests/FirebaseAuthEarlGreyTests.m
  Example/Auth/Sample/MainViewController.m
  Example/Firebase.xcodeproj/project.pbxproj
  Example/Firebase.xcodeproj/xcshareddata/xcschemes/Auth_Sample.xcscheme
  Firebase/Auth/Source/Public/FIRPhoneAuthProvider.h
Labels: cla: yes

#2105 Pin gRPC-C++ version to exactly 0.0.5
  FirebaseFirestore.podspec
Labels: Firestore, cla: yes

#2095 Database Interop Rollforward
  Example/Database/Tests/Helpers/FDevice.h
  Example/Database/Tests/Helpers/FDevice.m
  Example/Database/Tests/Helpers/FIRFakeApp.h
  Example/Database/Tests/Helpers/FIRFakeApp.m
  Example/Database/Tests/Helpers/FTestHelpers.h
  Example/Database/Tests/Helpers/FTestHelpers.m
  Example/Database/Tests/Integration/FData.m
  Example/Database/Tests/Integration/FDotInfo.m
  Example/Database/Tests/Integration/FIRAuthTests.m
  Example/Database/Tests/Integration/FIRDatabaseTests.m
  Example/Database/Tests/Integration/FRealtime.m
  Example/Database/Tests/Integration/FTransactionTest.m
  Example/Database/Tests/Unit/FIRDataSnapshotTests.m
  Example/Database/Tests/Unit/FUtilitiesTest.m
  Example/Firebase.xcodeproj/project.pbxproj
  Example/Firebase.xcodeproj/xcshareddata/xcschemes/Database_IntegrationTests_iOS.xcscheme
  Firebase/Database/Api/FIRDatabase.m
  Firebase/Database/Api/FIRDatabaseComponent.h
  Firebase/Database/Api/FIRDatabaseComponent.m
  Firebase/Database/Api/FIRDatabaseConfig.m
  Firebase/Database/Api/Private/FIRDatabaseReference_Private.h
  Firebase/Database/Api/Private/FIRDatabase_Private.h
  Firebase/Database/FIRDatabaseConfig_Private.h
  Firebase/Database/FIRDatabaseReference.m
  Firebase/Database/Login/FAuthTokenProvider.h
  Firebase/Database/Login/FAuthTokenProvider.m
  FirebaseDatabase.podspec
Labels: cla: yes

#2106 Prefer roots.pem from gRPC-C++, but fall back to Firestore bundled ones if necessary
  FirebaseFirestore.podspec
  Firestore/core/src/firebase/firestore/remote/grpc_root_certificate_finder_apple.mm
Labels: Firestore, cla: yes

#2114 Add Firebase Source to Header Search Path
  Example/Firebase.xcodeproj/project.pbxproj
Labels: Core, cla: yes

#1973 Implement PatchMutation::ApplyToLocalView
  Firestore/core/src/firebase/firestore/model/mutation.cc
  Firestore/core/src/firebase/firestore/model/mutation.h
  Firestore/core/test/firebase/firestore/model/CMakeLists.txt
  Firestore/core/test/firebase/firestore/model/mutation_test.cc
  Firestore/core/test/firebase/firestore/testutil/testutil.cc
  Firestore/core/test/firebase/firestore/testutil/testutil.h
Labels: cla: yes

#2116 Fix build under linux/gcc
  Firestore/core/test/firebase/firestore/util/CMakeLists.txt
Labels: cla: yes

#1905 Wire together LRU GC
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.h
  Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm
  Firestore/Example/Tests/Local/FSTLevelDBLRUGarbageCollectorTests.mm
  Firestore/Example/Tests/Local/FSTMemoryLRUGarbageCollectorTests.mm
  Firestore/Example/Tests/Local/FSTPersistenceTestHelpers.h
  Firestore/Example/Tests/Local/FSTPersistenceTestHelpers.mm
  Firestore/Source/API/FIRFirestore.mm
  Firestore/Source/API/FIRFirestoreSettings.mm
  Firestore/Source/Core/FSTFirestoreClient.h
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/Source/Local/FSTLRUGarbageCollector.h
  Firestore/Source/Local/FSTLRUGarbageCollector.mm
  Firestore/Source/Local/FSTLevelDB.h
  Firestore/Source/Local/FSTLevelDB.mm
  Firestore/Source/Local/FSTLocalStore.h
  Firestore/Source/Local/FSTLocalStore.mm
  Firestore/Source/Local/FSTMemoryMutationQueue.mm
  Firestore/Source/Local/FSTMemoryPersistence.h
  Firestore/Source/Local/FSTMemoryPersistence.mm
  Firestore/Source/Local/FSTMemoryQueryCache.mm
  Firestore/Source/Local/FSTMemoryRemoteDocumentCache.mm
  Firestore/Source/Local/FSTPersistence.h
  Firestore/Source/Public/FIRFirestoreSettings.h
  Firestore/Swift/Tests/API/BasicCompileTests.swift
  Firestore/core/src/firebase/firestore/util/async_queue.h
Labels: Firestore, cla: yes

#2121 Custom fdl domain
  Example/Auth/Tests/FIRGetOOBConfirmationCodeRequestTests.m
  Firebase/Auth/Source/FIRAuthErrorUtils.h
  Firebase/Auth/Source/FIRAuthErrorUtils.m
  Firebase/Auth/Source/FIRAuthInternalErrors.h
  Firebase/Auth/Source/Public/FIRActionCodeSettings.h
  Firebase/Auth/Source/Public/FIRAuthErrors.h
  Firebase/Auth/Source/RPCs/FIRAuthBackend.m
  Firebase/Auth/Source/RPCs/FIRGetOOBConfirmationCodeRequest.h
  Firebase/Auth/Source/RPCs/FIRGetOOBConfirmationCodeRequest.m
Labels: cla: yes

#2123 Revert "Add Firebase Source to Header Search Path"
  Example/Firebase.xcodeproj/project.pbxproj
Labels: cla: yes

#2122 Changelog entry for LRU GC
  Firestore/CHANGELOG.md
Labels: cla: yes

#2124 Avoid using default FIROptions directly.
  Firebase/DynamicLinks/FDLURLComponents/FIRDynamicLinkComponentsKeyProvider.h
  Firebase/DynamicLinks/FDLURLComponents/FIRDynamicLinkComponentsKeyProvider.m
Labels: DynamicLinks, cla: yes

#2132 Carthage instructions for new gRPCCertificates.bundle location
  Carthage.md
Labels: Carthage, cla: yes

#2119 Move to `domainURIPrefix` for FIRDynamicLinkComponents
  Example/DynamicLinks/App/iOS/DL-Info.plist
  Example/DynamicLinks/FDLBuilderTestAppObjC/Info.plist
  Example/DynamicLinks/FDLBuilderTestAppObjC/ViewController.m
  Example/DynamicLinks/FDLBuilderTestAppObjCTests/Info.plist
  Example/DynamicLinks/Tests/FDLURLComponentsTests.m
  Example/DynamicLinks/Tests/FIRDynamicLinkNetworkingTests.m
  Example/DynamicLinks/Tests/FIRDynamicLinksTest.m
  Firebase/DynamicLinks/CHANGELOG.md
  Firebase/DynamicLinks/FDLURLComponents/FDLURLComponents.m
  Firebase/DynamicLinks/FIRDynamicLinks.m
  Firebase/DynamicLinks/Logging/FDLLogging.h
  Firebase/DynamicLinks/Public/FDLURLComponents.h
  Firebase/DynamicLinks/Utilities/FDLUtilities.h
  Firebase/DynamicLinks/Utilities/FDLUtilities.m
Labels: cla: yes

#2126 Make fuzzing less verbose to avoid exceeding Travis log limit
  scripts/fuzzing_ci.sh
Labels: Firestore, cla: yes

#2131 fix a typo in integration test
  Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
Labels: Firestore, cla: yes

#2133 Add test for deprecated FDLURLComponents init API.
  Example/DynamicLinks/Tests/FDLURLComponentsTests.m
Labels: cla: yes
