Repository firebase/firebase-ios-sdk, pull requests merged in 2018-08, with the labels that each got.

#1605 Simplify/normlaize CMake platform libraries
  Firestore/core/src/firebase/firestore/util/CMakeLists.txt
  Firestore/core/test/firebase/firestore/remote/CMakeLists.txt
  Firestore/core/test/firebase/firestore/util/CMakeLists.txt
  cmake/cc_rules.cmake
Labels: Firestore, cla: yes

#1618 Combine firebase_firestore_util_base and _log
  Firestore/core/src/firebase/firestore/util/CMakeLists.txt
  Firestore/core/test/firebase/firestore/util/CMakeLists.txt
Labels: Firestore, cla: yes

#1617 Add Fuzz Test to travis Firestore-iOS-xcodebuild
  scripts/build.sh
Labels: Firestore, cla: yes

#1611 OSS Fuzz CMake changes
  Firestore/core/src/firebase/firestore/fuzzing/CMakeLists.txt
  cmake/FindFuzzer.cmake
  cmake/external/libfuzzer.cmake
  cmake/external_rules.cmake
  cmake/fuzzing_options.cmake
Labels: Firestore, cla: yes

#1619 Rewrite Path to use native path character type
  Firestore/core/src/firebase/firestore/util/path.cc
  Firestore/core/src/firebase/firestore/util/path.h
  Firestore/core/test/firebase/firestore/util/path_test.cc
Labels: Firestore, cla: yes

#1622 Fixes decoding WriteResults for deletes (with no updateTime).
  Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
Labels: Firestore, bug, cla: yes

#1621 Travis to avoid fuzz tests with tsan
  scripts/build.sh
Labels: Firestore, cla: yes

#1623 Add changelog entry for delete WriteResult fix (d9f116).
  Firestore/CHANGELOG.md
Labels: Firestore, cla: yes

#1626 Cherry pick fix for #1591 for M30
  Firestore/CHANGELOG.md
  Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
Labels: Firestore, cla: yes

#1627 Make FirebaseCredentialsProvider tolerate a missing FirebaseAuth
  Firestore/core/src/firebase/firestore/auth/firebase_credentials_provider_apple.mm
  Firestore/core/test/firebase/firestore/auth/firebase_credentials_provider_test.mm
Labels: Firestore, cla: yes

#1629 Bump CoreOnly requirements to 5.5.0
  Example/Podfile
  Firestore/Example/Podfile
Labels: cla: yes

#1630 Merge Firebase 5.5.0 to master
  Example/Podfile
  Firebase/Core/FIROptions.m
  FirebaseAuth.podspec
  FirebaseAuthInterop.podspec
  FirebaseCore.podspec
  FirebaseFirestore.podspec
  FirebaseMessaging.podspec
  Firestore/CHANGELOG.md
  Firestore/Example/Podfile
  Firestore/core/src/firebase/firestore/auth/firebase_credentials_provider_apple.mm
  Firestore/core/test/firebase/firestore/auth/firebase_credentials_provider_test.mm
  Releases/Manifests/5.5.0.json
Labels: cla: yes

#1628 Rename fuzz targets and use dictionary and corpus
  Firestore/Example/FuzzTests/FuzzingResources/Serializer/Corpus/BinaryProtos/arr-strings-01
  Firestore/Example/FuzzTests/FuzzingResources/Serializer/Corpus/BinaryProtos/fv-boolean-01
  Firestore/Example/FuzzTests/FuzzingResources/Serializer/Corpus/BinaryProtos/fv-string-01
  Firestore/core/src/firebase/firestore/fuzzing/CMakeLists.txt
  Firestore/core/src/firebase/firestore/fuzzing/serializer_fuzzer.cc
Labels: Firestore, cla: yes

#1620 Prepare util::Status for Windows use
  Firestore/core/src/firebase/firestore/util/CMakeLists.txt
  Firestore/core/src/firebase/firestore/util/status.cc
  Firestore/core/src/firebase/firestore/util/status.h
  Firestore/core/src/firebase/firestore/util/status_apple.mm
  Firestore/core/src/firebase/firestore/util/status_posix.cc
  Firestore/core/src/firebase/firestore/util/status_win.cc
Labels: Firestore, cla: yes

#1631 Add multi-client support to the iOS spec runner
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/SpecTests/FSTLevelDBSpecTests.mm
  Firestore/Example/Tests/SpecTests/FSTMemorySpecTests.mm
  Firestore/Example/Tests/SpecTests/FSTSpecTests.h
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.h
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Example/Tests/SpecTests/json/collection_spec_test.json
  Firestore/Example/Tests/SpecTests/json/existence_filter_spec_test.json
  Firestore/Example/Tests/SpecTests/json/limbo_spec_test.json
  Firestore/Example/Tests/SpecTests/json/limit_spec_test.json
  Firestore/Example/Tests/SpecTests/json/listen_spec_test.json
  Firestore/Example/Tests/SpecTests/json/offline_spec_test.json
  Firestore/Example/Tests/SpecTests/json/orderby_spec_test.json
  Firestore/Example/Tests/SpecTests/json/perf_spec_test.json
  Firestore/Example/Tests/SpecTests/json/persistence_spec_test.json
  Firestore/Example/Tests/SpecTests/json/remote_store_spec_test.json
  Firestore/Example/Tests/SpecTests/json/resume_token_spec_test.json
  Firestore/Example/Tests/SpecTests/json/write_spec_test.json
Labels: cla: yes

#1637 Convert FSTLevelDBMutationQueue.userID to std::string
  Firestore/Example/Tests/Local/FSTLevelDBKeyTests.mm
  Firestore/Example/Tests/Local/FSTLevelDBMigrationsTests.mm
  Firestore/Source/Local/FSTLevelDBMutationQueue.mm
Labels: Firestore, cla: yes

#1638 Migrate [LevelDBKey descriptionForKey:] to DescribeKey()
  Firestore/Example/Tests/Local/FSTLevelDBKeyTests.mm
  Firestore/Source/Local/FSTLevelDBKey.h
  Firestore/Source/Local/FSTLevelDBKey.mm
  Firestore/Source/Local/FSTLevelDBMutationQueue.mm
  Firestore/Source/Local/FSTLevelDBQueryCache.mm
  Firestore/core/src/firebase/firestore/local/leveldb_key.cc
  Firestore/core/src/firebase/firestore/local/leveldb_key.h
  Firestore/core/src/firebase/firestore/local/leveldb_transaction.cc
  Firestore/core/src/firebase/firestore/local/leveldb_transaction.h
  Firestore/core/src/firebase/firestore/util/string_util.h
  Firestore/core/test/firebase/firestore/local/leveldb_key_test.cc
Labels: Firestore, cla: yes

#1642 Mikelehen/deleted doc source cache bug
  Firestore/CHANGELOG.md
  Firestore/Example/Tests/Integration/API/FIRFirestoreSourceTests.mm
  Firestore/Source/Core/FSTFirestoreClient.mm
Labels: Firestore, bug, cla: yes

#1641 Fix GoogleUtilities so that it compiles in app extensions.
  GoogleUtilities.podspec
  GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
  GoogleUtilities/AppDelegateSwizzler/Internal/GULAppDelegateSwizzler_Private.h
Labels: cla: yes

#1649 Don't log warning about Analytics for tvOS or macOS
  Firebase/Core/FIRApp.m
Labels: cla: yes

#1648 Bump GoogleUtilities version to push extension fix
  GoogleUtilities.podspec
Labels: cla: yes

#1645 Added FieldPath fuzzing target
  Firestore/core/CMakeLists.txt
  Firestore/core/test/firebase/firestore/fuzzing/CMakeLists.txt
  Firestore/core/test/firebase/firestore/fuzzing/fieldpath_fuzzer.cc
  Firestore/core/test/firebase/firestore/fuzzing/serializer_fuzzer.cc
Labels: Firestore, cla: yes

#1656 Update CHANGELOG for Firestore v0.13.1
  Firestore/CHANGELOG.md
Labels: cla: yes

#1657 Add 5.6 json
  Firebase/Core/FIROptions.m
  FirebaseCore.podspec
  FirebaseFirestore.podspec
  Releases/Manifests/5.6.0.json
Labels: cla: yes

#1658 Revert version bump from #1657
  Firebase/Core/FIROptions.m
  FirebaseCore.podspec
  FirebaseFirestore.podspec
Labels: cla: yes

#1655 Add cc_fuzz_test build rule
  Firestore/core/test/firebase/firestore/fuzzing/CMakeLists.txt
  cmake/cc_rules.cmake
Labels: Firestore, cla: yes

#1651 Migrate LevelDB Key classes to C++
  Firestore/Example/Benchmarks/FSTLevelDBBenchmarkTests.mm
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/Local/FSTLevelDBKeyTests.mm
  Firestore/Example/Tests/Local/FSTLevelDBMigrationsTests.mm
  Firestore/Example/Tests/Local/FSTLevelDBMutationQueueTests.mm
  Firestore/Example/Tests/Local/FSTLevelDBRemoteDocumentCacheTests.mm
  Firestore/Example/Tests/Local/StringViewTests.mm
  Firestore/Source/Local/FSTLevelDB.mm
  Firestore/Source/Local/FSTLevelDBKey.h
  Firestore/Source/Local/FSTLevelDBKey.mm
  Firestore/Source/Local/FSTLevelDBMigrations.mm
  Firestore/Source/Local/FSTLevelDBMutationQueue.mm
  Firestore/Source/Local/FSTLevelDBQueryCache.mm
  Firestore/Source/Local/FSTLevelDBRemoteDocumentCache.mm
  Firestore/Source/Local/StringView.h
  Firestore/core/src/firebase/firestore/local/leveldb_key.cc
  Firestore/core/src/firebase/firestore/local/leveldb_key.h
Labels: Firestore, cla: yes

#1625 Refactor serializers
  Firestore/Example/FuzzTests/FuzzingTargets/FSTFuzzTestSerializer.mm
  Firestore/core/src/firebase/firestore/local/local_serializer.cc
  Firestore/core/src/firebase/firestore/local/local_serializer.h
  Firestore/core/src/firebase/firestore/nanopb/reader.cc
  Firestore/core/src/firebase/firestore/nanopb/reader.h
  Firestore/core/src/firebase/firestore/nanopb/writer.cc
  Firestore/core/src/firebase/firestore/nanopb/writer.h
  Firestore/core/src/firebase/firestore/remote/serializer.cc
  Firestore/core/src/firebase/firestore/remote/serializer.h
  Firestore/core/test/firebase/firestore/fuzzing/serializer_fuzzer.cc
  Firestore/core/test/firebase/firestore/local/local_serializer_test.cc
  Firestore/core/test/firebase/firestore/remote/serializer_test.cc
Labels: Firestore, cla: yes

#1665 Remove M30 travis pod lint workaround
  .travis.yml
Labels: cla: yes

#1667 Bump travis to Xcode 9.4.1
  .travis.yml
Labels: cla: yes

#1653 Make missing analytics a warning instead of error
  Firebase/Core/FIRApp.m
Labels: cla: yes

#1659 Add fuzzing target for creating ResourcePath objects
  Firestore/core/test/firebase/firestore/fuzzing/CMakeLists.txt
  Firestore/core/test/firebase/firestore/fuzzing/resourcepath_fuzzer.cc
Labels: Firestore, cla: yes

#1668 Move fuzzers out of core/test
  Firestore/CMakeLists.txt
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/core/CMakeLists.txt
  Firestore/fuzzing/CMakeLists.txt
  Firestore/fuzzing/fieldpath_fuzzer.cc
  Firestore/fuzzing/resourcepath_fuzzer.cc
  Firestore/fuzzing/serializer_fuzzer.cc
Labels: Firestore, cla: yes

#1669 Fixed decoding issue in Serializer
  Firestore/core/src/firebase/firestore/remote/serializer.cc
  Firestore/core/test/firebase/firestore/remote/serializer_test.cc
Labels: Firestore, cla: yes

#1635 Add Status::CausedBy
  Firestore/core/src/firebase/firestore/util/status.cc
  Firestore/core/src/firebase/firestore/util/status.h
  Firestore/core/test/firebase/firestore/util/status_test.cc
Labels: Firestore, cla: yes

#1672 Fix abseil compilation error that occurs in release mode
  Firestore/third_party/abseil-cpp/absl/base/macros.h
Labels: Firestore, cla: yes

#1633 Initial filesystem implementation
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/Local/FSTPersistenceTestHelpers.mm
  Firestore/core/src/firebase/firestore/util/CMakeLists.txt
  Firestore/core/src/firebase/firestore/util/filesystem.h
  Firestore/core/src/firebase/firestore/util/filesystem_apple.mm
  Firestore/core/test/firebase/firestore/util/CMakeLists.txt
  Firestore/core/test/firebase/firestore/util/filesystem_test.cc
Labels: Firestore, cla: yes

#1676 Replace uses of absl::string_view in constructor parameters with std::string
  Firestore/Example/Benchmarks/string_apple_benchmark.mm
  Firestore/Example/Tests/API/FSTAPIHelpers.mm
  Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
  Firestore/Example/Tests/Integration/FSTStreamTests.mm
  Firestore/Example/Tests/Util/FSTHelpers.h
  Firestore/Example/Tests/Util/FSTHelpers.mm
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
  Firestore/Source/API/FIRFirestore+Internal.h
  Firestore/Source/API/FIRFirestore.mm
  Firestore/Source/API/FSTFirestoreComponent.mm
  Firestore/core/src/firebase/firestore/auth/firebase_credentials_provider_apple.mm
  Firestore/core/src/firebase/firestore/auth/token.cc
  Firestore/core/src/firebase/firestore/auth/token.h
  Firestore/core/src/firebase/firestore/auth/user.cc
  Firestore/core/src/firebase/firestore/auth/user.h
  Firestore/core/src/firebase/firestore/core/database_info.cc
  Firestore/core/src/firebase/firestore/core/database_info.h
  Firestore/core/src/firebase/firestore/model/database_id.cc
  Firestore/core/src/firebase/firestore/model/database_id.h
Labels: Firestore, cla: yes

#1675 Fuzz test internal method in FIRFieldPath
  Firestore/Example/FuzzTests/FuzzingTargets/FSTFuzzTestFieldPath.mm
Labels: cla: yes

#1646 ensure NSUserDefaults is synchronized after setting values
  Firebase/Messaging/FIRMessaging.m
Labels: cla: yes

#1677 Fix benchmark builds on non-Apple platforms
  Firestore/Example/Benchmarks/CMakeLists.txt
  cmake/cc_rules.cmake
Labels: Firestore, cla: yes

#1681 Reformat using 'clang-format version 7.0.0 (tags/google/stable/2018-04-24)'
  Example/Core/Tests/FIRComponentContainerTest.m
  Example/Core/Tests/FIROptionsTest.m
  Example/Storage/Tests/Unit/FIRStorageMetadataTests.m
  Firebase/Core/Private/FIRAppAssociationRegistration.h
  Firebase/Core/Private/FIRComponentType.h
  Firebase/Storage/FIRStorageReference.m
  Firestore/Example/Tests/API/FIRDocumentSnapshotTests.mm
  Firestore/Example/Tests/API/FIRQuerySnapshotTests.mm
  Firestore/Example/Tests/Core/FSTQueryTests.mm
  Firestore/Example/Tests/Core/FSTViewTests.mm
  Firestore/Example/Tests/Integration/API/FIRArrayTransformTests.mm
  Firestore/Example/Tests/Integration/API/FIRCursorTests.mm
  Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
  Firestore/Example/Tests/Integration/API/FIRFieldsTests.mm
  Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
  Firestore/Example/Tests/Integration/API/FIRServerTimestampTests.mm
  Firestore/Example/Tests/Integration/API/FIRTypeTests.mm
  Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
  Firestore/Example/Tests/Integration/API/FIRWriteBatchTests.mm
  Firestore/Example/Tests/Integration/FSTTransactionTests.mm
  Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm
  Firestore/Example/Tests/Local/FSTLocalSerializerTests.mm
  Firestore/Example/Tests/Local/FSTMutationQueueTests.mm
  Firestore/Example/Tests/Local/FSTRemoteDocumentCacheTests.mm
  Firestore/Example/Tests/Model/FSTDocumentSetTests.mm
  Firestore/Example/Tests/Model/FSTDocumentTests.mm
  Firestore/Example/Tests/Model/FSTFieldValueTests.mm
  Firestore/Example/Tests/Model/FSTMutationTests.mm
  Firestore/Example/Tests/Remote/FSTDatastoreTests.mm
  Firestore/Example/Tests/Remote/FSTRemoteEventTests.mm
  Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
  Firestore/Example/Tests/Util/FSTEventAccumulator.h
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/Core/FSTFirestoreClient.h
  Firestore/Source/Core/FSTTransaction.mm
  Firestore/Source/Model/FSTFieldValue.h
  Firestore/Source/Model/FSTMutation.mm
  Firestore/Source/Remote/FSTRemoteEvent.h
  Firestore/Source/Remote/FSTRemoteEvent.mm
  Firestore/Source/Remote/FSTStream.h
  Firestore/core/test/firebase/firestore/auth/firebase_credentials_provider_test.mm
  Functions/Example/IntegrationTests/FIRIntegrationTests.m
  Functions/Example/Tests/FUNSerializerTests.m
  GoogleUtilities/AppDelegateSwizzler/Private/GULAppDelegateSwizzler.h
  GoogleUtilities/Example/Tests/Swizzler/GULAppDelegateSwizzlerTest.m
Labels: Infrastructure, cla: yes

#1682 remove unused method
  Example/Messaging/Tests/FIRMessagingPubSubTest.m
  Firebase/Messaging/FIRMessagingRegistrar.h
  Firebase/Messaging/FIRMessagingRegistrar.m
Labels: cla: yes

#1683 Add retry for travis pod lib lint
  .travis.yml
  scripts/pod_lib_lint.sh
Labels: cla: yes

#1688 Fix typo in .travis.yml
  .travis.yml
Labels: cla: yes

#1634 Add POSIX and Windows Filesystems
  FirebaseFirestore.podspec
  Firestore/core/src/firebase/firestore/util/CMakeLists.txt
  Firestore/core/src/firebase/firestore/util/filesystem_apple.mm
  Firestore/core/src/firebase/firestore/util/filesystem_common.cc
  Firestore/core/src/firebase/firestore/util/filesystem_detail.h
  Firestore/core/src/firebase/firestore/util/filesystem_posix.cc
  Firestore/core/src/firebase/firestore/util/filesystem_win.cc
  Firestore/core/src/firebase/firestore/util/log_apple.mm
  Firestore/core/src/firebase/firestore/util/path.cc
  Firestore/core/src/firebase/firestore/util/status_apple.mm
  Firestore/core/src/firebase/firestore/util/status_posix.cc
  Firestore/core/test/firebase/firestore/util/CMakeLists.txt
  Firestore/core/test/firebase/firestore/util/filesystem_test.cc
Labels: Firestore, cla: yes

#1685 Adding Fuzzing Test Target LevelDb
  Firestore/Example/FuzzTests/FuzzingResources/LevelDb/leveldb.dictionary
  Firestore/fuzzing/CMakeLists.txt
  Firestore/fuzzing/leveldb_fuzzer.cc
Labels: Firestore, cla: yes

#1693 Update Firestore changelog for token change fix.
  Firestore/CHANGELOG.md
Labels: Firestore, cla: yes

#1680 Log style.sh clang-format version.
  scripts/style.sh
Labels: Infrastructure, cla: yes

#1678 Tweak array-contains test for partial object matches.
  Firestore/Example/Tests/Core/FSTQueryTests.mm
Labels: Firestore, cla: yes

#1695 Update versions for Release 5.6.0
  Example/Podfile
  Firebase/Core/FIROptions.m
  FirebaseCore.podspec
  FirebaseFirestore.podspec
  Firestore/Example/Podfile
Labels: cla: yes

#1697 Migrate FSTTargetID to C++ TargetId
  Firestore/Example/Benchmarks/FSTLevelDBBenchmarkTests.mm
  Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm
  Firestore/Example/Tests/Local/FSTLevelDBMigrationsTests.mm
  Firestore/Example/Tests/Local/FSTLevelDBQueryCacheTests.mm
  Firestore/Example/Tests/Local/FSTLocalSerializerTests.mm
  Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
  Firestore/Example/Tests/Local/FSTQueryCacheTests.mm
  Firestore/Example/Tests/SpecTests/FSTMockDatastore.mm
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.h
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Example/Tests/Util/FSTHelpers.h
  Firestore/Example/Tests/Util/FSTHelpers.mm
  Firestore/Source/Core/FSTEventManager.h
  Firestore/Source/Core/FSTEventManager.mm
  Firestore/Source/Core/FSTSyncEngine.h
  Firestore/Source/Core/FSTSyncEngine.mm
  Firestore/Source/Core/FSTTypes.h
  Firestore/Source/Local/FSTDocumentReference.h
  Firestore/Source/Local/FSTLevelDBQueryCache.mm
  Firestore/Source/Local/FSTLocalSerializer.mm
  Firestore/Source/Local/FSTLocalStore.h
  Firestore/Source/Local/FSTLocalStore.mm
  Firestore/Source/Local/FSTLocalViewChanges.h
  Firestore/Source/Local/FSTLocalViewChanges.mm
  Firestore/Source/Local/FSTMemoryQueryCache.mm
  Firestore/Source/Local/FSTQueryCache.h
  Firestore/Source/Local/FSTQueryData.h
  Firestore/Source/Local/FSTQueryData.mm
  Firestore/Source/Remote/FSTRemoteEvent.h
  Firestore/Source/Remote/FSTRemoteEvent.mm
  Firestore/Source/Remote/FSTRemoteStore.h
  Firestore/Source/Remote/FSTRemoteStore.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/Source/Remote/FSTStream.h
  Firestore/Source/Remote/FSTStream.mm
  Firestore/Source/Remote/FSTWatchChange.h
  Firestore/Source/Remote/FSTWatchChange.mm
Labels: Firestore, cla: yes

#1698 Remove stale comment from WatchChangeAggregator changes.
  Firestore/Source/Remote/FSTRemoteStore.mm
Labels: Firestore, cla: yes

#1699 Refactor pendingWrites / write pipeline.
  Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
  Firestore/Source/Remote/FSTRemoteStore.mm
Labels: Firestore, cla: yes

#1700 Migrate FSTBatchID to C++ BatchId
  Firestore/Example/Benchmarks/FSTLevelDBBenchmarkTests.mm
  Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
  Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm
  Firestore/Example/Tests/Local/FSTLevelDBMigrationsTests.mm
  Firestore/Example/Tests/Local/FSTLevelDBMutationQueueTests.mm
  Firestore/Example/Tests/Remote/FSTWatchChange+Testing.h
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.h
  Firestore/Example/Tests/Util/FSTHelpers.h
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.h
  Firestore/Source/Core/FSTEventManager.h
  Firestore/Source/Core/FSTFirestoreClient.h
  Firestore/Source/Core/FSTListenSequence.h
  Firestore/Source/Core/FSTSyncEngine.h
  Firestore/Source/Core/FSTSyncEngine.mm
  Firestore/Source/Core/FSTTypes.h
  Firestore/Source/Local/FSTDocumentReference.h
  Firestore/Source/Local/FSTLRUGarbageCollector.h
  Firestore/Source/Local/FSTLRUGarbageCollector.mm
  Firestore/Source/Local/FSTLevelDBMutationQueue.h
  Firestore/Source/Local/FSTLevelDBMutationQueue.mm
  Firestore/Source/Local/FSTLocalStore.h
  Firestore/Source/Local/FSTLocalStore.mm
  Firestore/Source/Local/FSTLocalViewChanges.h
  Firestore/Source/Local/FSTLocalWriteResult.h
  Firestore/Source/Local/FSTLocalWriteResult.mm
  Firestore/Source/Local/FSTMemoryMutationQueue.mm
  Firestore/Source/Local/FSTMutationQueue.h
  Firestore/Source/Local/FSTReferenceSet.h
  Firestore/Source/Model/FSTMutationBatch.h
  Firestore/Source/Model/FSTMutationBatch.mm
  Firestore/Source/Remote/FSTRemoteEvent.h
  Firestore/Source/Remote/FSTRemoteStore.h
  Firestore/Source/Remote/FSTRemoteStore.mm
  Firestore/Source/Remote/FSTStream.h
  Firestore/Source/Remote/FSTWatchChange.h
  Firestore/core/src/firebase/firestore/model/types.h
Labels: Firestore, cla: yes

#1703 Migrate FSTListenSequenceNumber to C++ ListenSequenceNumber
  Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm
  Firestore/Example/Tests/Local/FSTLevelDBQueryCacheTests.mm
  Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
  Firestore/Example/Tests/Local/FSTQueryCacheTests.mm
  Firestore/Source/Core/FSTListenSequence.h
  Firestore/Source/Core/FSTListenSequence.mm
  Firestore/Source/Core/FSTSyncEngine.mm
  Firestore/Source/Core/FSTTypes.h
  Firestore/Source/Local/FSTLRUGarbageCollector.h
  Firestore/Source/Local/FSTLRUGarbageCollector.mm
  Firestore/Source/Local/FSTLevelDB.mm
  Firestore/Source/Local/FSTLevelDBQueryCache.h
  Firestore/Source/Local/FSTLevelDBQueryCache.mm
  Firestore/Source/Local/FSTLocalSerializer.mm
  Firestore/Source/Local/FSTLocalStore.mm
  Firestore/Source/Local/FSTMemoryPersistence.h
  Firestore/Source/Local/FSTMemoryPersistence.mm
  Firestore/Source/Local/FSTMemoryQueryCache.mm
  Firestore/Source/Local/FSTMemoryRemoteDocumentCache.h
  Firestore/Source/Local/FSTMemoryRemoteDocumentCache.mm
  Firestore/Source/Local/FSTPersistence.h
  Firestore/Source/Local/FSTQueryCache.h
  Firestore/Source/Local/FSTQueryData.h
  Firestore/Source/Local/FSTQueryData.mm
  Firestore/core/src/firebase/firestore/model/types.h
Labels: Firestore, cla: yes

#1711 Clean up warnings in leveldb_transaction.cc
  Firestore/core/src/firebase/firestore/local/leveldb_transaction.cc
  Firestore/core/src/firebase/firestore/local/leveldb_transaction.h
Labels: Firestore, cla: yes

#1710 update changelog for next release
  Firebase/Messaging/CHANGELOG.md
Labels: cla: yes

#1707 Use new filesystem routines in FSTLevelDB
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Podfile
  Firestore/Example/Tests/Local/FSTLevelDBMigrationsTests.mm
  Firestore/Example/Tests/Local/FSTLevelDBQueryCacheTests.mm
  Firestore/Example/Tests/Local/FSTLevelDBTransactionTests.mm
  Firestore/Example/Tests/Local/FSTPersistenceTestHelpers.h
  Firestore/Example/Tests/Local/FSTPersistenceTestHelpers.mm
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/Source/Local/FSTLevelDB.h
  Firestore/Source/Local/FSTLevelDB.mm
  Firestore/Source/Local/FSTMemoryPersistence.mm
  Firestore/Source/Local/FSTPersistence.h
  Firestore/core/src/firebase/firestore/local/CMakeLists.txt
  Firestore/core/src/firebase/firestore/local/leveldb_util.cc
  Firestore/core/src/firebase/firestore/local/leveldb_util.h
  Firestore/core/test/firebase/firestore/local/CMakeLists.txt
  Firestore/core/test/firebase/firestore/local/leveldb_util_test.cc
Labels: Firestore, cla: yes

#1712 Make backoff account for already-elapsed time.
  Firestore/Source/Remote/FSTExponentialBackoff.mm
Labels: Firestore, cla: yes

#1716 Run fuzzing in the test stage
  .travis.yml
  scripts/install_prereqs.sh
Labels: Firestore, cla: yes

#1720 Delete unnecessary umbrella header import
  Example/Auth/Tests/FIRAuthTests.m
Labels: cla: yes

#1717 Fix Auth_Tests_tvOS build config
  Example/Firebase.xcodeproj/project.pbxproj
Labels: cla: yes

#1722 Revert "Fix Auth_Tests_tvOS build config (#1717)"
  Example/Firebase.xcodeproj/project.pbxproj
Labels: cla: yes

#1724 Add current version to swiftformat upgrade message
  scripts/style.sh
Labels: cla: yes

#1727 Core 5.1.2 CHANGELOG update
  Firebase/Core/CHANGELOG.md
Labels: cla: yes

#1728 Update CHANGELOG for Firestore v0.13.2
  Firestore/CHANGELOG.md
Labels: Firestore, cla: yes

#1726 Add .opensource
  .opensource/project.json
Labels: cla: yes

#1721 Fix assign default on fetcherCompletion
  Example/Storage/Tests/Unit/FIRStoragePathTests.m
  Firebase/Storage/FIRStorageDeleteTask.m
  Firebase/Storage/FIRStorageDownloadTask.m
  Firebase/Storage/FIRStorageGetDownloadURLTask.m
  Firebase/Storage/FIRStorageGetMetadataTask.m
  Firebase/Storage/FIRStorageUpdateMetadataTask.m
  Firebase/Storage/FIRStorageUploadTask.m
  Firebase/Storage/Private/FIRStorageTask_Private.h
Labels: cla: yes

#1729 Update Changelog for 3.0.1 Storage Release
  Firebase/Storage/CHANGELOG.md
Labels: cla: yes

#1734 Create 5.7.0.json
  Releases/Manifests/5.7.0.json
Labels: cla: yes

#1737 Remove bad trailing comma
  .opensource/project.json
Labels: cla: yes

#1730 Update CMake build instructions
  .gitignore
  CMAKE.md
  cmake/podspec_rules.cmake
Labels: Firestore, cla: yes

#1684 GRPC: add BufferedWriter to help issuing GRPC writes one by one
  FirebaseFirestore.podspec
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/core/src/firebase/firestore/remote/buffered_writer.cc
  Firestore/core/src/firebase/firestore/remote/buffered_writer.h
  Firestore/core/src/firebase/firestore/remote/grpc_operation.h
  Firestore/core/test/firebase/firestore/remote/buffered_writer_test.cc
Labels: Firestore, cla: yes

#1708 Fix Travis fuzz testing
  .travis.yml
Labels: Firestore, cla: yes

#1739 Fix analyze issues in Messaging
  Firebase/Messaging/FIRMessagingDataMessageManager.h
  Firebase/Messaging/FIRMessagingDataMessageManager.m
  Firebase/Messaging/FIRMessagingRmq2PersistentStore.m
Labels: cla: yes

#1740 Fix analyze issues in Auth
  Firebase/Auth/Source/FIRAuthDataResult.m
  Firebase/Auth/Source/FIRAuthDataResult_Internal.h
  Firebase/Auth/Source/FIRAuthDefaultUIDelegate.m
  Firebase/Auth/Source/FIRAuthErrorUtils.m
  Firebase/Auth/Source/FIRAuthWebUtils.h
  Firebase/Auth/Source/FIRAuthWebUtils.m
  Firebase/Auth/Source/RPCs/FIRAuthBackend.h
  Firebase/Auth/Source/RPCs/FIRAuthBackend.m
Labels: cla: yes

#1741 Fix analyze issues in Storage and Database
  Firebase/Database/Core/FPersistentConnection.m
  Firebase/Database/FIRDatabaseReference.m
  Firebase/Database/Public/FIRDatabaseReference.h
  Firebase/Database/third_party/FImmutableSortedDictionary/FImmutableSortedDictionary/FLLRBEmptyNode.m
  Firebase/Database/third_party/FImmutableSortedDictionary/FImmutableSortedDictionary/FLLRBValueNode.m
  Firebase/Database/third_party/SocketRocket/FSRWebSocket.m
  Firebase/Storage/FIRStorage.m
  Firebase/Storage/FIRStorageObservableTask.m
Labels: cla: yes

#1746 Revert "Merge pull request #1721 from morganchen12/assign"
  Example/Storage/Tests/Unit/FIRStoragePathTests.m
  Firebase/Storage/FIRStorageDeleteTask.m
  Firebase/Storage/FIRStorageDownloadTask.m
  Firebase/Storage/FIRStorageGetDownloadURLTask.m
  Firebase/Storage/FIRStorageGetMetadataTask.m
  Firebase/Storage/FIRStorageUpdateMetadataTask.m
  Firebase/Storage/FIRStorageUploadTask.m
  Firebase/Storage/Private/FIRStorageTask_Private.h
Labels: cla: yes

#1747 Minimal fix for #1565
  Firebase/Storage/Private/FIRStorageTask_Private.h
Labels: cla: yes

#1748 Update Release Note
  Firebase/Storage/CHANGELOG.md
Labels: cla: yes

#1749 Fix nullability analysis error in GULAppDelegateSwizzler
  GoogleUtilities/AppDelegateSwizzler/Internal/GULAppDelegateSwizzler_Private.h
Labels: cla: yes

#1751 Travis config for Storage and DB integration tests
  scripts/build.sh
  scripts/install_prereqs.sh
  scripts/travis-encrypted/database-storage/GoogleService-Info.plist.enc
Labels: cla: yes

#1750 Add documentation on how to use the app delegate swizzler.
  GoogleUtilities/AppDelegateSwizzler/README.md
  GoogleUtilities/README.md
Labels: cla: yes

#1742 Fix analyze of FirebaseFunctions
  Functions/FirebaseFunctions/FUNError.h
  Functions/FirebaseFunctions/FUNError.m
  Functions/FirebaseFunctions/FUNSerializer.m
Labels: cla: yes

#1713 Start restarting persistence in spec tests
  Firestore/Example/Tests/SpecTests/FSTLevelDBSpecTests.mm
  Firestore/Example/Tests/SpecTests/FSTMemorySpecTests.mm
  Firestore/Example/Tests/SpecTests/FSTSpecTests.h
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Example/Tests/SpecTests/json/listen_spec_test.json
  Firestore/Example/Tests/SpecTests/json/offline_spec_test.json
  Firestore/Example/Tests/SpecTests/json/persistence_spec_test.json
  Firestore/Example/Tests/SpecTests/json/remote_store_spec_test.json
  Firestore/Example/Tests/SpecTests/json/write_spec_test.json
Labels: cla: yes

#1762 Update Firestore's leveldb-library dependency version
  FirebaseFirestore.podspec
Labels: cla: yes

#1763 Fix analyze issues in Firestore
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/Integration/FSTTransactionTests.mm
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
  Firestore/Source/API/FIRListenerRegistration.mm
  Firestore/Source/API/FSTUserDataConverter.mm
  Firestore/Source/Core/FSTQuery.h
  Firestore/Source/Core/FSTQuery.mm
  Firestore/core/test/firebase/firestore/testutil/app_testing.h
  Firestore/third_party/Immutable/FSTTreeSortedDictionary.m
  scripts/sync_project.rb
Labels: Firestore, cla: yes

#1764 Fix rest of Auth analyze issues
  Firebase/Auth/Source/FIRAuth.m
  Firebase/Auth/Source/FIRAuthErrorUtils.h
  Firebase/Auth/Source/FIRAuthErrorUtils.m
  Firebase/Auth/Source/FIRUser.m
  Firebase/Auth/Source/FIRUser_Internal.h
  Firebase/Auth/Source/RPCs/FIRAuthRPCResponse.h
Labels: cla: yes

#1767 Fix memory leak in GULRuntimeSnapshot
  GoogleUtilities/SwizzlerTestHelpers/GULRuntimeSnapshot.m
Labels: cla: yes

#1769 Fixes incorrect declaration of the init method
  Firebase/Database/Public/FIRDatabase.h
Labels: cla: yes
