Repository firebase/firebase-ios-sdk, pull requests merged in 2019-02, with the labels that each got.

#2330 Don't build fuzz tests target on Travis
  scripts/build.sh
Labels: Firestore, cla: yes

#2325 C++ migration: port `FSTOnlineStateTracker`
  Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.h
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Source/Core/FSTEventManager.h
  Firestore/Source/Core/FSTFirestoreClient.h
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/Source/Remote/FSTOnlineStateTracker.h
  Firestore/Source/Remote/FSTOnlineStateTracker.mm
  Firestore/Source/Remote/FSTRemoteStore.h
  Firestore/Source/Remote/FSTRemoteStore.mm
  Firestore/core/src/firebase/firestore/remote/online_state_tracker.cc
  Firestore/core/src/firebase/firestore/remote/online_state_tracker.h
Labels: Firestore, cla: yes

#2334 Add more flexible swiftformat version check to scripts/style.sh.
  Example/tvOSSample/tvOSSample/StorageViewController.swift
  scripts/style.sh
Labels: Core, cla: yes

#2341 Add IAM headless to CI
  Firebase/InAppMessaging/Data/FIRIAMFetchResponseParser.h
  InAppMessaging/Example/App/InAppMessaging-Example-iOS/AppDelegate.m
  InAppMessaging/Example/Podfile
  scripts/build.sh
  scripts/install_prereqs.sh
Labels: cla: yes

#2315 Bump FirebaseAnalyticsInterop version
  Example/DynamicLinks/Tests/FIRDLScionLoggingTest.m
  Example/Messaging/Tests/FIRMessagingAnalyticsTest.m
  FirebaseAnalyticsInterop.podspec
Labels: cla: yes

#2352 Update library name to `fire-fiam`.
  Firebase/InAppMessaging/FIRInAppMessaging.m
Labels: InAppMessaging, cla: yes

#2347 Start pod lib lint CI for FIAM
  .travis.yml
  scripts/pod_lib_lint.sh
Labels: InAppMessaging, cla: yes

#2353 Update gRPC certificate bundles locations for Firebase 5.16
  Carthage.md
Labels: Firestore, cla: yes

#2355 Resolve hard dependency of GameKit
  Firebase/Auth/Source/AuthProviders/GameCenter/FIRGameCenterAuthProvider.m
  Firebase/Auth/Source/FIRAuthErrorUtils.h
  Firebase/Auth/Source/FIRAuthErrorUtils.m
  Firebase/Auth/Source/FIRAuthInternalErrors.h
  Firebase/Auth/Source/Public/FIRAuthErrors.h
Labels: cla: yes

#2335 C++ migration: port write stream-related part of `FSTRemoteStore`
  Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
  Firestore/Example/Tests/SpecTests/FSTMockDatastore.h
  Firestore/Example/Tests/SpecTests/FSTMockDatastore.mm
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.h
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Source/Model/FSTMutationBatch.h
  Firestore/Source/Model/FSTMutationBatch.mm
  Firestore/Source/Remote/FSTRemoteStore.mm
  Firestore/Source/Remote/FSTStream.h
  Firestore/core/src/firebase/firestore/remote/datastore.h
  Firestore/core/src/firebase/firestore/remote/datastore.mm
  Firestore/core/src/firebase/firestore/remote/remote_objc_bridge.h
  Firestore/core/src/firebase/firestore/remote/remote_objc_bridge.mm
  Firestore/core/src/firebase/firestore/remote/remote_store.h
  Firestore/core/src/firebase/firestore/remote/remote_store.mm
  Firestore/core/src/firebase/firestore/remote/write_stream.h
  Firestore/core/src/firebase/firestore/remote/write_stream.mm
Labels: Firestore, cla: yes

#2358 Change cocoapods version from 1.6.0.rc.2 to 1.6.0.
  Gemfile
  Gemfile.lock
  GoogleDataLogger.podspec
Labels: cla: yes

#2337 C++ migration: make all methods of `FSTRemoteStore` delegate to C++
  Firestore/Source/Remote/FSTRemoteStore.mm
  Firestore/core/src/firebase/firestore/remote/remote_store.h
  Firestore/core/src/firebase/firestore/remote/remote_store.mm
Labels: Firestore, cla: yes

#2359 Add NS_ASSUME_NONNULL_NOTATION for game center sign in
  Firebase/Auth/Source/AuthProviders/GameCenter/FIRGameCenterAuthCredential.m
  Firebase/Auth/Source/AuthProviders/GameCenter/FIRGameCenterAuthProvider.m
Labels: cla: yes

#2360 Update CI to use CocoaPods 1.6.0
  Example/Firebase.xcodeproj/project.pbxproj
  Gemfile.lock
Labels: cla: yes

#2357 Pass FSTMutations* using a vector
  Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
  Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm
  Firestore/Example/Tests/Local/FSTLocalSerializerTests.mm
  Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
  Firestore/Example/Tests/Local/FSTMutationQueueTests.mm
  Firestore/Example/Tests/SpecTests/FSTMockDatastore.h
  Firestore/Example/Tests/SpecTests/FSTMockDatastore.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Example/Tests/Util/FSTHelpers.h
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRWriteBatch.mm
  Firestore/Source/Core/FSTFirestoreClient.h
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/Source/Core/FSTSyncEngine.h
  Firestore/Source/Core/FSTSyncEngine.mm
  Firestore/Source/Core/FSTTransaction.h
  Firestore/Source/Core/FSTTransaction.mm
  Firestore/Source/Local/FSTLocalDocumentsView.mm
  Firestore/Source/Local/FSTLocalSerializer.mm
  Firestore/Source/Local/FSTLocalStore.h
  Firestore/Source/Local/FSTLocalStore.mm
  Firestore/Source/Model/FSTMutationBatch.h
  Firestore/Source/Model/FSTMutationBatch.mm
  Firestore/core/src/firebase/firestore/core/user_data.h
  Firestore/core/src/firebase/firestore/core/user_data.mm
  Firestore/core/src/firebase/firestore/local/leveldb_mutation_queue.h
  Firestore/core/src/firebase/firestore/local/leveldb_mutation_queue.mm
  Firestore/core/src/firebase/firestore/local/memory_mutation_queue.h
  Firestore/core/src/firebase/firestore/local/memory_mutation_queue.mm
  Firestore/core/src/firebase/firestore/local/mutation_queue.h
  Firestore/core/src/firebase/firestore/remote/datastore.h
  Firestore/core/src/firebase/firestore/remote/datastore.mm
  Firestore/core/src/firebase/firestore/remote/remote_objc_bridge.h
  Firestore/core/src/firebase/firestore/remote/remote_objc_bridge.mm
  Firestore/core/src/firebase/firestore/remote/write_stream.h
  Firestore/core/src/firebase/firestore/remote/write_stream.mm
  Firestore/core/test/firebase/firestore/remote/datastore_test.mm
Labels: Firestore, cla: yes

#2361 Merge master into googledatalogger
  .travis.yml
  Carthage.md
  Example/Firebase.xcodeproj/project.pbxproj
  Firebase/Auth/Source/AuthProviders/GameCenter/FIRGameCenterAuthCredential.m
  Firebase/Auth/Source/AuthProviders/GameCenter/FIRGameCenterAuthProvider.m
  Firebase/Auth/Source/FIRAuthErrorUtils.h
  Firebase/Auth/Source/FIRAuthErrorUtils.m
  Firebase/Auth/Source/FIRAuthInternalErrors.h
  Firebase/Auth/Source/Public/FIRAuthErrors.h
  Firebase/InAppMessaging/FIRInAppMessaging.m
  Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
  Firestore/Example/Tests/SpecTests/FSTMockDatastore.h
  Firestore/Example/Tests/SpecTests/FSTMockDatastore.mm
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.h
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Source/Model/FSTMutationBatch.h
  Firestore/Source/Model/FSTMutationBatch.mm
  Firestore/Source/Remote/FSTRemoteStore.mm
  Firestore/Source/Remote/FSTStream.h
  Firestore/core/src/firebase/firestore/remote/datastore.h
  Firestore/core/src/firebase/firestore/remote/datastore.mm
  Firestore/core/src/firebase/firestore/remote/remote_objc_bridge.h
  Firestore/core/src/firebase/firestore/remote/remote_objc_bridge.mm
  Firestore/core/src/firebase/firestore/remote/remote_store.h
  Firestore/core/src/firebase/firestore/remote/remote_store.mm
  Firestore/core/src/firebase/firestore/remote/write_stream.h
  Firestore/core/src/firebase/firestore/remote/write_stream.mm
  Gemfile.lock
  scripts/pod_lib_lint.sh
Labels: cla: yes

#2338 C++ migration: eliminate `FSTRemoteStore`
  Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.h
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Source/Core/FSTEventManager.h
  Firestore/Source/Core/FSTFirestoreClient.h
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/Source/Core/FSTSyncEngine.h
  Firestore/Source/Core/FSTSyncEngine.mm
  Firestore/Source/Remote/FSTRemoteStore.h
  Firestore/Source/Remote/FSTRemoteStore.mm
  Firestore/core/src/firebase/firestore/remote/online_state_tracker.h
  Firestore/core/src/firebase/firestore/remote/remote_store.h
Labels: Firestore, cla: yes

#2363 Fix a bug where sign in with email link always return isNewUser as false
  Firebase/Auth/Source/FIRAuth.m
Labels: cla: yes

#2354 Firebase In-app messaging callbacks
  Firebase/InAppMessaging/Flows/FIRIAMDisplayExecutor.h
  Firebase/InAppMessaging/Flows/FIRIAMDisplayExecutor.m
  Firebase/InAppMessaging/Public/FIRInAppMessaging.h
  Firebase/InAppMessaging/Public/FIRInAppMessagingRendering.h
  Firebase/InAppMessaging/RenderingObjects/FIRInAppMessagingRenderingDataClasses.m
  Firebase/InAppMessaging/Runtime/FIRIAMRuntimeManager.m
  Firebase/InAppMessagingDisplay/Banner/FIDBannerViewController.m
  Firebase/InAppMessagingDisplay/FIDBaseRenderingViewController.h
  Firebase/InAppMessagingDisplay/FIDBaseRenderingViewController.m
  Firebase/InAppMessagingDisplay/FIRIAMDefaultDisplayImpl.m
  Firebase/InAppMessagingDisplay/ImageOnly/FIDImageOnlyViewController.m
  Firebase/InAppMessagingDisplay/Modal/FIDModalViewController.m
  Firebase/InAppMessagingDisplay/Public/FIRIAMDefaultDisplayImpl.h
  Firestore/Swift/Source/Codable/CodableGeoPoint.swift
  InAppMessaging/Example/Tests/FIRIAMDisplayExecutorTests.m
  InAppMessagingDisplay/Example/FiamDisplaySwiftExample/BannerMessageViewController.swift
  InAppMessagingDisplay/Example/FiamDisplaySwiftExample/CommonMessageTestVC.swift
  InAppMessagingDisplay/Example/FiamDisplaySwiftExample/ImageOnlyMessageViewController.swift
  InAppMessagingDisplay/Example/FiamDisplaySwiftExample/ModalMessageViewController.swift
  InAppMessagingDisplay/Example/Podfile
Labels: cla: yes

#2368 Fix a bug where sign in with Game Center doesn’t return additional us…
  Firebase/Auth/Source/FIRAuth.m
Labels: cla: yes

#2370 Fix a bug where unlinking emailpassword doesn’t remove provider data
  Firebase/Auth/Source/FIRUser.m
Labels: cla: yes

#2362 C++ migration: port `FSTTransaction`
  Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
  Firestore/Example/Tests/Integration/FSTTransactionTests.mm
  Firestore/Source/API/FIRFirestore.mm
  Firestore/Source/API/FIRTransaction+Internal.h
  Firestore/Source/API/FIRTransaction.mm
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/Source/Core/FSTSyncEngine.mm
  Firestore/Source/Core/FSTTransaction.h
  Firestore/Source/Core/FSTTransaction.mm
  Firestore/Source/Core/FSTTypes.h
  Firestore/core/src/firebase/firestore/core/transaction.h
  Firestore/core/src/firebase/firestore/core/transaction.mm
  Firestore/core/src/firebase/firestore/remote/datastore.h
  Firestore/core/src/firebase/firestore/remote/datastore.mm
  Firestore/core/src/firebase/firestore/remote/remote_objc_bridge.h
  Firestore/core/src/firebase/firestore/remote/remote_objc_bridge.mm
  Firestore/core/src/firebase/firestore/remote/remote_store.h
  Firestore/core/src/firebase/firestore/remote/remote_store.mm
  Firestore/core/test/firebase/firestore/remote/datastore_test.mm
Labels: Firestore, cla: yes

#2371 Project structure refactor
  Example/Auth/SwiftSample/AppDelegate.swift
  Example/Auth/SwiftSample/AuthCredentialsTemplate.swift
  Example/Auth/SwiftSample/InfoTemplate.plist
  Example/Auth/SwiftSample/LaunchScreen.storyboard
  Example/Auth/SwiftSample/Main.storyboard
  Example/Auth/SwiftSample/Sample.entitlements
  Example/Auth/SwiftSample/Stubs.swift
  Example/Auth/SwiftSample/ViewController.swift
  Example/Firebase.xcodeproj/project.pbxproj
  Example/Firebase.xcodeproj/xcshareddata/xcschemes/Auth_AllTests.xcscheme
  Example/Firebase.xcodeproj/xcshareddata/xcschemes/Auth_SwiftSample.xcscheme
  Example/Podfile
Labels: cla: yes

#2380 Fix FIAM Travic CI issues
  Firebase/InAppMessagingDisplay/Banner/FIDBannerViewController.m
  Firebase/InAppMessagingDisplay/FIDBaseRenderingViewController.h
  Firebase/InAppMessagingDisplay/FIDBaseRenderingViewController.m
  Firebase/InAppMessagingDisplay/ImageOnly/FIDImageOnlyViewController.m
  Firebase/InAppMessagingDisplay/Modal/FIDModalViewController.m
Labels: cla: yes

#2383 update changelog for release
  Firebase/Messaging/CHANGELOG.md
Labels: cla: yes

#2382 Forbid queries endAt an uncommitted server timestamp.
  Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
  Firestore/Source/API/FIRQuery.mm
Labels: cla: yes

#2305 Deprecate setMinimumSessionInterval
  Firebase/Core/Public/FIRAnalyticsConfiguration.h
Labels: cla: yes

#2392 Create umbrella header for FIAM
  Firebase/InAppMessaging/Public/FirebaseInAppMessaging.h
Labels: cla: yes

#2396 Split Auth unit tests
  Example/Auth/ApiTests/FirebaseAuthApiTests.m
  Example/Auth/Tests/FIRAuthLifeCycleTests.m
  Example/Auth/Tests/FIRAuthTests.m
  Example/Firebase.xcodeproj/project.pbxproj
Labels: cla: yes

#2384 Add a ToString function to create human-readable debug descriptions
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/Model/FSTFieldValueTests.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/API/FSTUserDataConverter.mm
  Firestore/Source/Core/FSTView.mm
  Firestore/Source/Core/FSTViewSnapshot.mm
  Firestore/Source/Model/FSTDocument.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/immutable/sorted_map.h
  Firestore/core/src/firebase/firestore/local/leveldb_mutation_queue.mm
  Firestore/core/src/firebase/firestore/model/document_key.h
  Firestore/core/src/firebase/firestore/util/CMakeLists.txt
  Firestore/core/src/firebase/firestore/util/string_format.h
  Firestore/core/src/firebase/firestore/util/string_util.h
  Firestore/core/src/firebase/firestore/util/to_string.h
  Firestore/core/src/firebase/firestore/util/type_traits.h
  Firestore/core/test/firebase/firestore/util/to_string_apple_test.mm
  Firestore/core/test/firebase/firestore/util/to_string_test.cc
Labels: Firestore, cla: yes

#2399 Split auth api tests into multiple cases
  Example/Auth/ApiTests/AccountInfoTests.m
  Example/Auth/ApiTests/AnonymousAuthTests.m
  Example/Auth/ApiTests/Auth_ApiTests-Bridging-Header.h
  Example/Auth/ApiTests/CustomAuthTests.m
  Example/Auth/ApiTests/EmailPasswordAuthTests.m
  Example/Auth/ApiTests/FIRAuthApiTestsBase.h
  Example/Auth/ApiTests/FIRAuthApiTestsBase.m
  Example/Auth/ApiTests/FacebookAuthTests.m
  Example/Auth/ApiTests/FirebaseAuthApiTests.m
  Example/Auth/ApiTests/GoogleAuthTests.m
  Example/Auth/ApiTests/GoogleAuthTests.swift
  Example/Firebase.xcodeproj/project.pbxproj
  Example/Firebase.xcodeproj/xcshareddata/xcschemes/Auth_ApiTests.xcscheme
Labels: cla: yes

#2388 C++ migration: port `FSTDocumentViewChange`
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/API/FIRQuerySnapshotTests.mm
  Firestore/Example/Tests/API/FSTAPIHelpers.mm
  Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
  Firestore/Example/Tests/Core/FSTViewSnapshotTest.mm
  Firestore/Example/Tests/Core/FSTViewTests.mm
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Source/API/FIRDocumentChange.mm
  Firestore/Source/Core/FSTEventManager.mm
  Firestore/Source/Core/FSTView.mm
  Firestore/Source/Core/FSTViewSnapshot.h
  Firestore/Source/Core/FSTViewSnapshot.mm
  Firestore/Source/Local/FSTLocalViewChanges.mm
  Firestore/Source/Model/FSTMutationBatch.mm
  Firestore/core/src/firebase/firestore/core/view_snapshot.h
  Firestore/core/src/firebase/firestore/core/view_snapshot.mm
  Firestore/core/src/firebase/firestore/remote/remote_event.h
  Firestore/core/src/firebase/firestore/remote/remote_event.mm
  Firestore/core/src/firebase/firestore/remote/watch_change.mm
  Firestore/core/src/firebase/firestore/util/objc_compatibility.h
  Firestore/core/test/firebase/firestore/util/objc_compatibility_apple_test.mm
  scripts/build.sh
Labels: Firestore, cla: yes

#2409 Fix import references to other pod's headers to fix pod lib lint
  .travis.yml
  Firebase/InAppMessagingDisplay/FIRIAMDefaultDisplayImpl.m
  Firebase/InAppMessagingDisplay/Public/FIRIAMDefaultDisplayImpl.h
  InAppMessagingDisplay/Example/InAppMessagingDisplay-Sample.xcodeproj/project.pbxproj
  scripts/build.sh
  scripts/if_changed.sh
  scripts/install_prereqs.sh
Labels: cla: yes

#2411 Add style.sh details to README
  README.md
Labels: cla: yes

#2394 Be sure to validate return code when calling sysctlbyname function (C…
  Firebase/DynamicLinks/Utilities/FDLUtilities.m
Labels: DynamicLinks, cla: yes

#2413 Stop pushing extra tags
  Releases/update-versions.py
Labels: cla: yes

#2415 IID docs, versions, and pod-lib-lint
  .travis.yml
  FirebaseInstanceID.podspec
  FirebaseMessaging.podspec
  README.md
Labels: cla: yes

#2420 Move Xcode 9.4 tests to cron
  .travis.yml
Labels: cla: yes

#2417 Restore FIRInstanceIDWithFCMTest.m
  Example/Firebase.xcodeproj/project.pbxproj
  Example/Messaging/Tests/FIRInstanceIDWithFCMTest.m
Labels: cla: yes

#2374 os_log Implementation of GULLogger
  Example/Core/Tests/FIRLoggerTest.m
  Firebase/Core/FIRLogger.m
  GoogleUtilities.podspec
  GoogleUtilities/Example/GoogleUtilities.xcodeproj/project.pbxproj
  GoogleUtilities/Example/Tests/Logger/GULASLLoggerTest.m
  GoogleUtilities/Example/Tests/Logger/GULLoggerTest.m
  GoogleUtilities/Example/Tests/Logger/GULOSLoggerTest.m
  GoogleUtilities/Logger/GULLogger.m
  GoogleUtilities/Logger/Private/GULASLLogger.h
  GoogleUtilities/Logger/Private/GULASLLogger.m
  GoogleUtilities/Logger/Private/GULLogger+Internal.h
  GoogleUtilities/Logger/Private/GULLogger+Internal.m
  GoogleUtilities/Logger/Private/GULLogger.h
  GoogleUtilities/Logger/Private/GULLoggerSystem.h
  GoogleUtilities/Logger/Private/GULOSLogger.h
  GoogleUtilities/Logger/Private/GULOSLogger.m
  GoogleUtilities/Logger/Public/GULLoggerLevel.h
Labels: cla: yes

#2427 Fix race causing occasional flake
  Example/Messaging/Tests/FIRInstanceIDWithFCMTest.m
Labels: cla: yes

#2431 Fix GoogleUtilities regression for Firestore builds
  GoogleUtilities/Logger/GULLogger.m
  GoogleUtilities/Logger/Private/GULOSLogger.m
Labels: cla: yes

#2433 Fix GoogleUtilities regression for Firestore builds 2
  GoogleUtilities/Logger/GULLogger.m
  GoogleUtilities/Logger/Private/GULOSLogger.m
  scripts/if_changed.sh
Labels: cla: yes

#2429 Fix typo in header documentation.
  Firebase/Auth/Source/Public/FIRGameCenterAuthProvider.h
Labels: cla: yes

#2437 Fix GULLogger file structure
  GoogleUtilities/Example/GoogleUtilities.xcodeproj/project.pbxproj
  GoogleUtilities/Example/Tests/Logger/GULASLLoggerTest.m
  GoogleUtilities/Example/Tests/Logger/GULOSLoggerTest.m
  GoogleUtilities/Logger/GULASLLogger.h
  GoogleUtilities/Logger/GULASLLogger.m
  GoogleUtilities/Logger/GULLogger+Internal.h
  GoogleUtilities/Logger/GULLogger.m
  GoogleUtilities/Logger/GULOSLogger.h
  GoogleUtilities/Logger/GULOSLogger.m
  GoogleUtilities/Logger/Private/GULLogger+Internal.m
  GoogleUtilities/Logger/Private/GULLogger.h
Labels: cla: yes

#2436 Update to CocoaPods 1.6.1
  Gemfile
  Gemfile.lock
  InAppMessagingDisplay/Example/InAppMessagingDisplay-Sample.xcodeproj/project.pbxproj
Labels: cla: yes

#2329 Add ability to set a timeout on Functions.
  Functions/Backend/index.js
  Functions/Backend/start.sh
  Functions/Example/IntegrationTests/FIRIntegrationTests.m
  Functions/FirebaseFunctions/FIRFunctions+Internal.h
  Functions/FirebaseFunctions/FIRFunctions.m
  Functions/FirebaseFunctions/FIRHTTPSCallable.m
  Functions/FirebaseFunctions/FUNError.h
  Functions/FirebaseFunctions/FUNError.m
  Functions/FirebaseFunctions/Public/FIRHTTPSCallable.h
Labels: cla: yes

#2425 M44 release notes update
  Firebase/DynamicLinks/CHANGELOG.md
Labels: DynamicLinks, cla: yes

#2412 Added encrypted credential files and enable integration tests
  .gitignore
  scripts/build.sh
  scripts/install_prereqs.sh
  scripts/travis-encrypted/Secrets.tar.enc
  scripts/travis-encrypted/database-storage/GoogleService-Info.plist.enc
Labels: cla: yes

#2406 C++ migration: port `FSTDocumentViewChangeSet`
  Firestore/Example/Tests/Core/FSTViewSnapshotTest.mm
  Firestore/Example/Tests/Core/FSTViewTests.mm
  Firestore/Source/Core/FSTView.h
  Firestore/Source/Core/FSTView.mm
  Firestore/Source/Core/FSTViewSnapshot.h
  Firestore/Source/Core/FSTViewSnapshot.mm
  Firestore/core/src/firebase/firestore/core/view_snapshot.h
  Firestore/core/src/firebase/firestore/core/view_snapshot.mm
Labels: Firestore, cla: yes

#2446 Fix IID singleton usage.
  Example/InstanceID/Tests/FIRInstanceIDTest.m
  Example/Messaging/Tests/FIRInstanceIDWithFCMTest.m
  Firebase/InstanceID/FIRInstanceID.m
Labels: cla: yes

#2443 FirebaseMessaging: `NSUserDefaults` replaced by `GULUserDefaults`
  Example/Messaging/Tests/FIRMessagingTestUtilities.m
  Firebase/Messaging/FIRMessaging.m
  Firebase/Messaging/FIRMessagingPubSub.m
  Firebase/Messaging/FIRMessagingReceiver.h
  Firebase/Messaging/FIRMessagingReceiver.m
  FirebaseMessaging.podspec
Labels: cla: yes

#2452 Disable index-while-compiling in Travis
  scripts/build.sh
Labels: cla: yes

#2453 Fix logger warning on iOS 7.
  GoogleUtilities/Logger/GULASLLogger.m
Labels: cla: yes

#2450 Enable code coverage for AllUnitTests_iOS target
  Example/Auth/Tests/FIRAuthAppDelegateProxyTests.m
  Example/Firebase.xcodeproj/xcshareddata/xcschemes/AllUnitTests_iOS.xcscheme
Labels: cla: yes

#2454 Resolve issue with char * casting in format string invocation
  GoogleUtilities/Example/Tests/Logger/GULASLLoggerTest.m
  GoogleUtilities/Example/Tests/Logger/GULOSLoggerTest.m
  GoogleUtilities/Logger/GULASLLogger.m
  GoogleUtilities/Logger/GULOSLogger.m
Labels: GoogleUtilities, cla: yes

#2395 Add FIAM M44 release notes
  Firebase/InAppMessaging/CHANGELOG.md
  Firebase/InAppMessagingDisplay/CHANGELOG.md
Labels: cla: yes

#2460 Update CHANGELOG.md
  Firebase/Auth/CHANGELOG.md
Labels: cla: yes
