Repository firebase/firebase-ios-sdk, pull requests merged in 2019-09, with the labels that each got.

#3734 Fixes for the Codable API
  Firestore/Source/Public/FIRCollectionReference.h
  Firestore/Swift/Source/Codable/CollectionReference+WriteEncodable.swift
  Firestore/Swift/Source/Codable/Transaction+WriteEncodable.swift
  Firestore/Swift/Source/Codable/WriteBatch+WriteEncodable.swift
  Firestore/Swift/Tests/Integration/CodableIntegrationTests.swift
Labels: api: firestore, cla: yes

#3737 Fix removal of view references in FSTLocalStore
  Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
  Firestore/Source/Local/FSTLocalStore.mm
Labels: api: firestore, cla: yes

#3739 Update formatters for the Xcode 10.3 Travis image
  Example/Database/Tests/Integration/FOrderByTests.m
  FirebaseInstallations/Source/Tests/Unit/FIRInstallationsAPIServiceTests.m
  FirebaseRemoteConfig/Sources/RCNConfigDBManager.m
  Firestore/Swift/Tests/Integration/CodableIntegrationTests.swift
  README.md
Labels: cla: yes

#3738 Fix Remote Config travis flakes
  FirebaseRemoteConfig/Sources/RCNConfigDBManager.m
  FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
Labels: api: remoteconfig, cla: yes

#3764 Iterate from array copy in `latestExperimentStartTimestampBetweenTimestamp:andPayloads:`
  FirebaseABTesting/Sources/FIRExperimentController.m
Labels: cla: yes

#3767 cocoapod-generate 1.6.0 released
  Gemfile
  Gemfile.lock
Labels: cla: yes

#3766 Gate access to cached instances.
  Firebase/Core/FIRComponentContainer.m
Labels: cla: yes

#3772 Release 6.8.0: cherry pick of #3764 and #3766
  Firebase/Core/FIRComponentContainer.m
  FirebaseABTesting/Sources/FIRExperimentController.m
Labels: cla: yes

#3751 Misc Objective-C cleanups
  Firestore/Example/Tests/Util/FSTHelpers.h
  Firestore/Protos/CMakeLists.txt
  Firestore/Source/Local/FSTLocalStore.h
  Firestore/core/test/firebase/firestore/testutil/xcgmock.h
Labels: api: firestore, cla: yes

#3769 Fix erroneous move
  Firestore/core/src/firebase/firestore/core/event_manager.h
  Firestore/core/src/firebase/firestore/core/event_manager.mm
  Firestore/core/src/firebase/firestore/core/sync_engine_callback.h
Labels: api: firestore, cla: yes

#3726 Port FSTSyncEngine to C++ SyncEngine 1/2
  Firestore/Source/Core/FSTSyncEngine.mm
  Firestore/core/src/firebase/firestore/core/sync_engine.h
  Firestore/core/src/firebase/firestore/core/sync_engine.mm
Labels: api: firestore, cla: yes

#3752 Finish sizer interface
  Firestore/Source/Local/FSTLRUGarbageCollector.h
  Firestore/Source/Local/FSTLevelDB.mm
  Firestore/Source/Local/FSTMemoryPersistence.mm
  Firestore/core/src/firebase/firestore/local/lru_garbage_collector.cc
  Firestore/core/src/firebase/firestore/local/lru_garbage_collector.h
  Firestore/core/src/firebase/firestore/local/memory_mutation_queue.h
  Firestore/core/src/firebase/firestore/local/memory_mutation_queue.mm
  Firestore/core/src/firebase/firestore/local/memory_query_cache.h
  Firestore/core/src/firebase/firestore/local/memory_query_cache.mm
  Firestore/core/src/firebase/firestore/local/memory_remote_document_cache.h
  Firestore/core/src/firebase/firestore/local/memory_remote_document_cache.mm
  Firestore/core/src/firebase/firestore/local/proto_sizer.h
  Firestore/core/src/firebase/firestore/local/proto_sizer.mm
  Firestore/core/src/firebase/firestore/local/sizer.h
Labels: api: firestore, cla: yes

#3765 Fix comment for initializer for `FIRInAppMessagingAction` after deprecation
  Firebase/InAppMessaging/Public/FIRInAppMessagingRendering.h
Labels: api: inappmessaging, cla: yes

#3774 Add ComponentContainer tests for dependencies.
  Example/Core/Tests/FIRComponentContainerTest.m
  Example/Core/Tests/FIRTestComponents.h
  Example/Core/Tests/FIRTestComponents.m
Labels: cla: yes

#3781 Update FDL CHANGELOG
  Firebase/DynamicLinks/CHANGELOG.md
Labels: cla: yes

#3785 Issue number, not PR number
  Firebase/DynamicLinks/CHANGELOG.md
Labels: cla: yes

#3650 Don't persist documents that we already have
  Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
  Firestore/Example/Tests/SpecTests/json/limbo_spec_test.json
  Firestore/Example/Tests/SpecTests/json/listen_spec_test.json
  Firestore/Example/Tests/Util/FSTHelpers.h
  Firestore/Example/Tests/Util/FSTHelpers.mm
  Firestore/Source/Local/FSTLocalStore.mm
Labels: cla: yes

#3741 Port FSTSyncEngine to C++ SyncEngine 2/2
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/Core/FSTEventManagerTests.mm
  Firestore/Example/Tests/Core/FSTSyncEngine+Testing.h
  Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Source/Core/FSTSyncEngine.h
  Firestore/Source/Core/FSTSyncEngine.mm
  Firestore/core/src/firebase/firestore/core/event_manager.h
  Firestore/core/src/firebase/firestore/core/event_manager.mm
  Firestore/core/src/firebase/firestore/core/firestore_client.h
  Firestore/core/src/firebase/firestore/core/firestore_client.mm
  Firestore/core/src/firebase/firestore/core/sync_engine.h
  Firestore/core/src/firebase/firestore/core/sync_engine_callback.h
  Firestore/core/src/firebase/firestore/remote/remote_store.h
  Firestore/core/src/firebase/firestore/remote/remote_store.mm
  Firestore/core/test/firebase/firestore/core/event_manager_test.mm
Labels: api: firestore, cla: yes

#3784 Add optional value to ExplicitNull and ServerTimestamp
  Firestore/Swift/Source/Codable/ExplicitNull.swift
  Firestore/Swift/Source/Codable/FieldValue+Encodable.swift
Labels: api: firestore, cla: yes

#3762 Add @DocumentId equivalent to Swift Codable
  Firestore/Swift/Source/Codable/CodableErrors.swift
  Firestore/Swift/Source/Codable/DocumentSnapshot+ReadDecodable.swift
  Firestore/Swift/Source/Codable/SelfDocumentId.swift
  Firestore/Swift/Source/Codable/third_party/FirestoreDecoder.swift
  Firestore/Swift/Source/Codable/third_party/FirestoreEncoder.swift
  Firestore/Swift/Tests/Codable/FirestoreEncoderTests.swift
  Firestore/Swift/Tests/Integration/CodableIntegrationTests.swift
Labels: api: firestore, cla: yes

#3789 Fix symbol collision failure introduced by 6.8.0 release
  SymbolCollisionTest/Podfile
Labels: cla: yes

#3790 Release 6.8.0 cherry pick: conflicting Dynamic Links changelog changes.
  Firebase/DynamicLinks/CHANGELOG.md
Labels: cla: yes

#3786 Fix SIGSEGV in callback after block is nil'd
  Firebase/Storage/CHANGELOG.md
  Firebase/Storage/FIRStorageUploadTask.m
Labels: api: storage, cla: yes

#3795 Update comment for correct activate method.
  FirebaseRemoteConfig/Sources/Public/FIRRemoteConfig.h
Labels: cla: yes

#3799 Remove UIWebViewDelegate references
  Firebase/DynamicLinks/CHANGELOG.md
  Firebase/DynamicLinks/FIRDLJavaScriptExecutor.m
Labels: api: dynamiclinks, cla: yes

#3803 Fix header issues exposed by :generate_multiple_pod_projects
  Example/InstanceID/Tests/FIRInstanceIDCheckinServiceTest.m
  Example/InstanceID/Tests/FIRInstanceIDCheckinStoreTest.m
  Example/InstanceID/Tests/FIRInstanceIDStoreTest.m
  Example/InstanceID/Tests/FIRInstanceIDTokenOperationsTest.m
  Firebase/InstanceID/CHANGELOG.md
  Firebase/InstanceID/FIRInstanceIDCheckinPreferences+Internal.h
  Firebase/InstanceID/FIRInstanceIDCheckinPreferences_Private.h
  Firebase/InstanceID/FIRInstanceIDCheckinService.h
  Firebase/InstanceID/Private/FIRInstanceID+Private.h
Labels: api: instanceid, api: remoteconfig, cla: yes

#3805 cherry-picks and versions for 6.8.1
  Example/InstanceID/Tests/FIRInstanceIDCheckinServiceTest.m
  Example/InstanceID/Tests/FIRInstanceIDCheckinStoreTest.m
  Example/InstanceID/Tests/FIRInstanceIDStoreTest.m
  Example/InstanceID/Tests/FIRInstanceIDTokenOperationsTest.m
  Example/Podfile
  Firebase/DynamicLinks/CHANGELOG.md
  Firebase/DynamicLinks/FIRDLJavaScriptExecutor.m
  Firebase/InstanceID/CHANGELOG.md
  Firebase/InstanceID/FIRInstanceIDCheckinPreferences+Internal.h
  Firebase/InstanceID/FIRInstanceIDCheckinPreferences_Private.h
  Firebase/InstanceID/FIRInstanceIDCheckinService.h
  Firebase/InstanceID/Private/FIRInstanceID+Private.h
  Firebase/Storage/CHANGELOG.md
  Firebase/Storage/FIRStorageUploadTask.m
  FirebaseCore.podspec
  FirebaseDynamicLinks.podspec
  FirebaseInstanceID.podspec
  FirebaseStorage.podspec
  Firestore/Example/Podfile
  Releases/Manifests/6.8.1.json
  SymbolCollisionTest/Podfile
Labels: cla: yes

#3797 Remove specialization of std::hash for Timestamp
  Firestore/core/include/firebase/firestore/timestamp.h
  Firestore/core/src/firebase/firestore/model/snapshot_version.cc
  Firestore/core/src/firebase/firestore/timestamp.cc
  Firestore/core/test/firebase/firestore/timestamp_test.cc
Labels: api: firestore, cla: yes

#3810 Update CHANGELOGs
  Firebase/Core/CHANGELOG.md
  Firebase/CoreDiagnostics/CHANGELOG.md
  GoogleDataTransport/CHANGELOG.md
  GoogleDataTransportCCTSupport/CHANGELOG.md
Labels: cla: yes

#3809 Tweak code that breaks older versions of Visual Studio
  Firestore/core/src/firebase/firestore/model/field_path.cc
  Firestore/core/src/firebase/firestore/model/field_path.h
Labels: api: firestore, cla: yes

#3775 Create a GDT test app for generating events
  GoogleDataTransport.podspec
  GoogleDataTransport/GDTTestApp/app.swift
  GoogleDataTransport/GDTTestApp/gdthelpers.swift
  GoogleDataTransport/GDTTestApp/globals.swift
  GoogleDataTransport/GDTTestApp/ios/Main.storyboard
  GoogleDataTransport/GDTTestApp/macos/Main.storyboard
  GoogleDataTransport/GDTTestApp/tvos/Main.storyboard
  GoogleDataTransport/GDTTestApp/viewcontroller.swift
  GoogleDataTransport/GDTTests/Monkey/GDTMonkeyTest.swift
  GoogleDataTransportCCTSupport.podspec
Labels: cla: yes

#3811 Merge 6.8.1
  Example/Podfile
  FirebaseCore.podspec
  FirebaseDynamicLinks.podspec
  FirebaseInstanceID.podspec
  FirebaseStorage.podspec
  Firestore/Example/Podfile
  Releases/Manifests/6.8.1.json
  SymbolCollisionTest/Podfile
Labels: cla: yes

#3754 Port FSTMemoryPersistence to C++
  Firestore/core/src/firebase/firestore/local/CMakeLists.txt
  Firestore/core/src/firebase/firestore/local/lru_garbage_collector.cc
  Firestore/core/src/firebase/firestore/local/lru_garbage_collector.h
  Firestore/core/src/firebase/firestore/local/memory_eager_reference_delegate.cc
  Firestore/core/src/firebase/firestore/local/memory_eager_reference_delegate.h
  Firestore/core/src/firebase/firestore/local/memory_lru_reference_delegate.cc
  Firestore/core/src/firebase/firestore/local/memory_lru_reference_delegate.h
  Firestore/core/src/firebase/firestore/local/memory_persistence.cc
  Firestore/core/src/firebase/firestore/local/memory_persistence.h
  Firestore/core/src/firebase/firestore/local/persistence.h
  Firestore/core/src/firebase/firestore/local/reference_delegate.h
Labels: api: firestore, cla: yes

#3820 Update CHANGELOG for Firestore v1.5.1
  Firestore/CHANGELOG.md
Labels: api: firestore, cla: yes

#3821 README update for RemoteConfig open source
  README.md
Labels: cla: yes

#3819 Add RC test app.
  FirebaseRemoteConfig.podspec
  FirebaseRemoteConfig/Sources/FIRRemoteConfig.m
  FirebaseRemoteConfig/Sources/FIRRemoteConfigComponent.m
  FirebaseRemoteConfig/Sources/Private/FIRRemoteConfig_Private.h
  FirebaseRemoteConfig/Sources/Private/RCNConfigSettings.h
  FirebaseRemoteConfig/Sources/RCNConfigSettings.m
  FirebaseRemoteConfig/Sources/RCNDevice.m
  FirebaseRemoteConfig/Sources/RCNFetch.m
  FirebaseRemoteConfig/Tests/Sample/Podfile
  FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp.xcodeproj/project.pbxproj
  FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/AppDelegate.h
  FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/AppDelegate.m
  FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/Assets.xcassets/Contents.json
  FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/Base.lproj/LaunchScreen.xib
  FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/Base.lproj/Main.storyboard
  FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/FRCLog.h
  FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/FRCLog.m
  FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/Info.plist
  FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/ViewController.h
  FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/ViewController.m
  FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/main.m
  FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleAppUITests/Info.plist
  FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleAppUITests/RemoteConfigSampleAppUITests.m
  FirebaseRemoteConfig/Tests/Unit/FIRRemoteConfigComponentTest.m
  FirebaseRemoteConfig/Tests/Unit/RCNConfigContentTest.m
  FirebaseRemoteConfig/Tests/Unit/RCNConfigDBManagerTest.m
  FirebaseRemoteConfig/Tests/Unit/RCNConfigExperimentTest.m
  FirebaseRemoteConfig/Tests/Unit/RCNConfigSettingsTest.m
  FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfig+FIRAppTest.m
  FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
  FirebaseRemoteConfig/Tests/Unit/RCNTestUtilities.h
  FirebaseRemoteConfig/Tests/Unit/RCNThrottlingTests.m
Labels: api: remoteconfig, cla: yes

#3756 Migrate to C++ Persistence (1/2)
  Firestore/Source/Local/FSTLocalStore.h
  Firestore/Source/Local/FSTLocalStore.mm
  Firestore/core/src/firebase/firestore/api/firestore.mm
  Firestore/core/src/firebase/firestore/core/firestore_client.h
  Firestore/core/src/firebase/firestore/core/firestore_client.mm
  Firestore/core/src/firebase/firestore/local/leveldb_index_manager.h
  Firestore/core/src/firebase/firestore/local/leveldb_index_manager.mm
  Firestore/core/src/firebase/firestore/local/leveldb_key.h
  Firestore/core/src/firebase/firestore/local/leveldb_mutation_queue.h
  Firestore/core/src/firebase/firestore/local/leveldb_mutation_queue.mm
  Firestore/core/src/firebase/firestore/local/leveldb_query_cache.h
  Firestore/core/src/firebase/firestore/local/leveldb_query_cache.mm
  Firestore/core/src/firebase/firestore/local/leveldb_remote_document_cache.h
  Firestore/core/src/firebase/firestore/local/leveldb_remote_document_cache.mm
  Firestore/core/src/firebase/firestore/local/local_write_result.h
  Firestore/core/src/firebase/firestore/local/lru_garbage_collector.h
  Firestore/core/src/firebase/firestore/local/memory_mutation_queue.h
  Firestore/core/src/firebase/firestore/local/memory_mutation_queue.mm
  Firestore/core/src/firebase/firestore/local/memory_query_cache.h
  Firestore/core/src/firebase/firestore/local/memory_query_cache.mm
  Firestore/core/src/firebase/firestore/local/memory_remote_document_cache.h
  Firestore/core/src/firebase/firestore/local/memory_remote_document_cache.mm
  Firestore/core/src/firebase/firestore/local/mutation_queue.h
  Firestore/core/src/firebase/firestore/local/reference_delegate.h
  Firestore/core/src/firebase/firestore/local/remote_document_cache.h
Labels: api: firestore, cla: yes

#3757 Migrate to C++ Persistence (2/2)
  Firestore/Example/Benchmarks/FSTLevelDBBenchmarkTests.mm
  Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.h
  Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm
  Firestore/Example/Tests/Local/FSTLevelDBLRUGarbageCollectorTests.mm
  Firestore/Example/Tests/Local/FSTLevelDBLocalStoreTests.mm
  Firestore/Example/Tests/Local/FSTLevelDBMigrationsTests.mm
  Firestore/Example/Tests/Local/FSTLevelDBMutationQueueTests.mm
  Firestore/Example/Tests/Local/FSTLevelDBQueryCacheTests.mm
  Firestore/Example/Tests/Local/FSTLevelDBRemoteDocumentCacheTests.mm
  Firestore/Example/Tests/Local/FSTLocalStoreTests.h
  Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
  Firestore/Example/Tests/Local/FSTMemoryLRUGarbageCollectorTests.mm
  Firestore/Example/Tests/Local/FSTMemoryLocalStoreTests.mm
  Firestore/Example/Tests/Local/FSTMemoryMutationQueueTests.mm
  Firestore/Example/Tests/Local/FSTMemoryQueryCacheTests.mm
  Firestore/Example/Tests/Local/FSTMemoryRemoteDocumentCacheTests.mm
  Firestore/Example/Tests/Local/FSTMutationQueueTests.h
  Firestore/Example/Tests/Local/FSTMutationQueueTests.mm
  Firestore/Example/Tests/Local/FSTPersistenceTestHelpers.h
  Firestore/Example/Tests/Local/FSTPersistenceTestHelpers.mm
  Firestore/Example/Tests/Local/FSTQueryCacheTests.h
  Firestore/Example/Tests/Local/FSTQueryCacheTests.mm
  Firestore/Example/Tests/Local/FSTRemoteDocumentCacheTests.h
  Firestore/Example/Tests/Local/FSTRemoteDocumentCacheTests.mm
  Firestore/Example/Tests/SpecTests/FSTLevelDBSpecTests.mm
  Firestore/Example/Tests/SpecTests/FSTMemorySpecTests.mm
  Firestore/Example/Tests/SpecTests/FSTSpecTests.h
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.h
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
  Firestore/Source/Local/FSTLRUGarbageCollector.h
  Firestore/Source/Local/FSTLevelDB.h
  Firestore/Source/Local/FSTLevelDB.mm
  Firestore/Source/Local/FSTMemoryPersistence.h
  Firestore/Source/Local/FSTMemoryPersistence.mm
  Firestore/Source/Local/FSTPersistence.h
  Firestore/core/test/firebase/firestore/local/index_manager_test.h
  Firestore/core/test/firebase/firestore/local/index_manager_test.mm
  Firestore/core/test/firebase/firestore/local/leveldb_index_manager_test.mm
  Firestore/core/test/firebase/firestore/local/memory_index_manager_test.mm
  Firestore/core/test/firebase/firestore/testutil/xcgmock.h
Labels: api: firestore, cla: yes

#3761 Forward declare util::Status when possible
  Firestore/Example/Tests/SpecTests/FSTMockDatastore.h
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/Core/FSTSyncEngine.h
  Firestore/core/src/firebase/firestore/api/document_reference.h
  Firestore/core/src/firebase/firestore/api/firestore.h
  Firestore/core/src/firebase/firestore/api/write_batch.h
  Firestore/core/src/firebase/firestore/core/event_listener.h
  Firestore/core/src/firebase/firestore/core/event_manager.h
  Firestore/core/src/firebase/firestore/core/firestore_client.h
  Firestore/core/src/firebase/firestore/core/query_listener.h
  Firestore/core/src/firebase/firestore/core/sync_engine_callback.h
  Firestore/core/src/firebase/firestore/core/transaction.h
  Firestore/core/src/firebase/firestore/core/transaction_runner.h
  Firestore/core/src/firebase/firestore/local/leveldb_util.cc
  Firestore/core/src/firebase/firestore/local/leveldb_util.h
  Firestore/core/src/firebase/firestore/local/local_serializer.h
  Firestore/core/src/firebase/firestore/remote/datastore.h
  Firestore/core/src/firebase/firestore/remote/grpc_call.h
  Firestore/core/src/firebase/firestore/remote/grpc_completion.h
  Firestore/core/src/firebase/firestore/remote/grpc_connection.cc
  Firestore/core/src/firebase/firestore/remote/grpc_stream.cc
  Firestore/core/src/firebase/firestore/remote/grpc_stream.h
  Firestore/core/src/firebase/firestore/remote/grpc_stream_observer.h
  Firestore/core/src/firebase/firestore/remote/grpc_streaming_reader.cc
  Firestore/core/src/firebase/firestore/remote/grpc_streaming_reader.h
  Firestore/core/src/firebase/firestore/remote/grpc_unary_call.cc
  Firestore/core/src/firebase/firestore/remote/grpc_unary_call.h
  Firestore/core/src/firebase/firestore/remote/grpc_util.cc
  Firestore/core/src/firebase/firestore/remote/grpc_util.h
  Firestore/core/src/firebase/firestore/remote/online_state_tracker.cc
  Firestore/core/src/firebase/firestore/remote/online_state_tracker.h
  Firestore/core/src/firebase/firestore/remote/remote_objc_bridge.h
  Firestore/core/src/firebase/firestore/remote/remote_store.h
  Firestore/core/src/firebase/firestore/remote/serializer.h
  Firestore/core/src/firebase/firestore/remote/stream.h
  Firestore/core/src/firebase/firestore/remote/watch_stream.h
  Firestore/core/src/firebase/firestore/remote/write_stream.h
  Firestore/core/src/firebase/firestore/util/CMakeLists.txt
  Firestore/core/src/firebase/firestore/util/error_apple.h
  Firestore/core/src/firebase/firestore/util/error_apple.mm
  Firestore/core/src/firebase/firestore/util/filesystem.h
  Firestore/core/src/firebase/firestore/util/filesystem_common.cc
  Firestore/core/src/firebase/firestore/util/filesystem_detail.h
  Firestore/core/src/firebase/firestore/util/filesystem_posix.cc
  Firestore/core/src/firebase/firestore/util/status.h
  Firestore/core/src/firebase/firestore/util/status_fwd.h
  Firestore/core/test/firebase/firestore/local/leveldb_util_test.cc
  Firestore/core/test/firebase/firestore/nanopb/nanopb_testing.h
  Firestore/core/test/firebase/firestore/remote/grpc_connection_test.cc
  Firestore/core/test/firebase/firestore/remote/grpc_streaming_reader_test.cc
  Firestore/core/test/firebase/firestore/util/filesystem_test.cc
  Firestore/core/test/firebase/firestore/util/status_testing.h
Labels: api: firestore, cla: yes

#3828 Log stream errors
  Firestore/core/src/firebase/firestore/remote/stream.mm
Labels: api: firestore, cla: yes

#3826 Fix typos in FIRIAMFetchResponseParserTests
  InAppMessaging/Example/Tests/FIRIAMFetchResponseParserTests.m
Labels: cla: yes

#3825 Remove app_spec from GDT
  GoogleDataTransport.podspec
Labels: cla: yes

#3844 Port persistence spec test
  Firestore/Example/Tests/SpecTests/json/persistence_spec_test.json
Labels: api: firestore, cla: yes

#3836 Enable `-Werror` for Firestore XCode project
  Firestore/Example/Tests/Integration/API/FIRWriteBatchTests.mm
  Firestore/Example/Tests/Integration/FSTTransactionTests.mm
  scripts/sync_project.rb
Labels: api: firestore, cla: yes

#3845 Enable app_specs and monkey test if GDT_DEV is 1
  GoogleDataTransport.podspec
  GoogleDataTransport/GDTTestApp/app.swift
  GoogleDataTransport/GDTTestApp/gdthelpers.swift
  GoogleDataTransport/GDTTestApp/viewcontroller.swift
Labels: cla: yes

#3847 Change the order of checks in applyRemoteEvent()
  Firestore/Source/Local/FSTLocalStore.mm
Labels: api: firestore, cla: yes

#3853 fixed "expiclitlySet" typo.
  Example/Core/Tests/FIRAppTest.m
  Example/Core/Tests/FIROptionsTest.m
  Firebase/Core/FIRApp.m
  Firebase/Core/FIROptions.m
  Firebase/Core/Private/FIROptionsInternal.h
  Metrics/Tests/MetricsTests/example_report.json
Labels: cla: yes

#3848 Fix ZipBuilder README typo
  ZipBuilder/README.md
Labels: cla: yes

#3863 Allow Zip build to continue if Carthage fails.
  ZipBuilder/Sources/ZipBuilder/main.swift
Labels: cla: yes

#3861 Make mph-gdtsqlite run travis
  .travis.yml
Labels: cla: yes

#3857 Mute FCM deprecated warnings with Xcode 11 and min iOS >= 10
  Example/Messaging/Tests/FIRMessagingContextManagerServiceTest.m
  Firebase/Messaging/FIRMessaging.m
  Firebase/Messaging/FIRMessagingContextManagerService.m
  Firebase/Messaging/FIRMessagingRmq2PersistentStore.m
Labels: api: messaging, cla: yes

#3864 Add argument for build root override.
  ZipBuilder/Sources/ZipBuilder/FileManager+Utils.swift
  ZipBuilder/Sources/ZipBuilder/LaunchArgs.swift
  ZipBuilder/Sources/ZipBuilder/main.swift
Labels: cla: yes

#3846 Add a third slash to make sure generated docs include comments.…
  FirebaseRemoteConfig/Sources/Public/FIRRemoteConfig.h
Labels: cla: yes

#3868 Fix file prefix on CI.
  ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
Labels: cla: yes

#3871 Cherry picks for 6.9.0
  Example/Core/Tests/FIRAppTest.m
  Example/Core/Tests/FIROptionsTest.m
  Example/Messaging/Tests/FIRMessagingContextManagerServiceTest.m
  Firebase/Core/CHANGELOG.md
  Firebase/Core/FIRApp.m
  Firebase/Core/FIROptions.m
  Firebase/Core/Private/FIROptionsInternal.h
  Firebase/Messaging/CHANGELOG.md
  Firebase/Messaging/FIRMessaging.m
  Firebase/Messaging/FIRMessagingContextManagerService.m
  Firebase/Messaging/FIRMessagingRmq2PersistentStore.m
  FirebaseMessaging.podspec
  FirebaseRemoteConfig/CHANGELOG.md
  FirebaseRemoteConfig/Sources/Public/FIRRemoteConfig.h
  GoogleUtilities/CHANGELOG.md
  GoogleUtilities/ISASwizzler/GULObjectSwizzler.m
  Metrics/Tests/MetricsTests/example_report.json
  Releases/Manifests/6.9.0.json
Labels: cla: yes

#3872 Fix relative path for headers.
  ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
Labels: cla: yes

#3833 Port local store to C++ 1/2
  Firestore/Source/Local/FSTLocalStore.mm
  Firestore/core/src/firebase/firestore/local/local_store.h
  Firestore/core/src/firebase/firestore/local/local_store.mm
Labels: api: firestore, cla: yes

#3866 Clean up Objective-C remnants
  Firestore/Source/API/FIRFirestore.mm
  Firestore/Source/Core/FSTSyncEngine.h
  Firestore/core/src/firebase/firestore/api/document_reference.h
  Firestore/core/src/firebase/firestore/api/document_reference.mm
  Firestore/core/src/firebase/firestore/api/firestore.h
  Firestore/core/src/firebase/firestore/api/firestore.mm
  Firestore/core/src/firebase/firestore/api/query_core.mm
  Firestore/core/src/firebase/firestore/api/query_listener_registration.h
  Firestore/core/src/firebase/firestore/api/write_batch.mm
  Firestore/core/src/firebase/firestore/core/event_manager.mm
  Firestore/core/src/firebase/firestore/core/firestore_client.mm
  Firestore/core/src/firebase/firestore/core/sync_engine_callback.h
  Firestore/core/src/firebase/firestore/core/user_data.h
  Firestore/core/src/firebase/firestore/local/document_key_reference.h
  Firestore/core/src/firebase/firestore/local/leveldb_index_manager.h
  Firestore/core/src/firebase/firestore/local/leveldb_index_manager.mm
  Firestore/core/src/firebase/firestore/local/leveldb_lru_reference_delegate.h
  Firestore/core/src/firebase/firestore/local/leveldb_persistence.mm
  Firestore/core/src/firebase/firestore/local/local_documents_view.h
  Firestore/core/src/firebase/firestore/local/local_documents_view.mm
  Firestore/core/src/firebase/firestore/local/lru_garbage_collector.h
  Firestore/core/src/firebase/firestore/local/memory_eager_reference_delegate.h
  Firestore/core/src/firebase/firestore/local/memory_lru_reference_delegate.h
  Firestore/core/src/firebase/firestore/local/memory_mutation_queue.mm
  Firestore/core/src/firebase/firestore/local/memory_persistence.h
  Firestore/core/src/firebase/firestore/local/memory_query_cache.mm
  Firestore/core/src/firebase/firestore/local/memory_remote_document_cache.h
  Firestore/core/src/firebase/firestore/local/query_data.h
  Firestore/core/src/firebase/firestore/remote/datastore.h
  Firestore/core/src/firebase/firestore/remote/remote_objc_bridge.h
  Firestore/core/src/firebase/firestore/remote/remote_store.h
  Firestore/core/src/firebase/firestore/remote/remote_store.mm
  Firestore/core/src/firebase/firestore/remote/watch_stream.h
  Firestore/core/src/firebase/firestore/remote/write_stream.h
  Firestore/core/src/firebase/firestore/util/comparison.h
  Firestore/core/test/firebase/firestore/testutil/xcgmock.h
Labels: api: firestore, cla: yes

#3865 Port local store to C++ 2/2
  Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
  Firestore/Example/Tests/Local/FSTLocalStoreTests.h
  Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
  Firestore/Example/Tests/Local/FSTMemoryLocalStoreTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Source/Local/FSTLocalStore.h
  Firestore/Source/Local/FSTLocalStore.mm
  Firestore/core/src/firebase/firestore/core/firestore_client.h
  Firestore/core/src/firebase/firestore/core/firestore_client.mm
  Firestore/core/src/firebase/firestore/core/sync_engine.h
  Firestore/core/src/firebase/firestore/core/sync_engine.mm
  Firestore/core/src/firebase/firestore/local/persistence.h
  Firestore/core/src/firebase/firestore/remote/remote_store.h
  Firestore/core/src/firebase/firestore/remote/remote_store.mm
Labels: api: firestore, cla: yes

#3879 Fix release candidate parsing naming
  ZipBuilder/Sources/ZipBuilder/LaunchArgs.swift
  ZipBuilder/Sources/ZipBuilder/main.swift
Labels: cla: yes

#3880 ZipBuilder: move ManifestReader to a separate package to be reusable.
  ZipBuilder/Package.swift
  ZipBuilder/README.md
  ZipBuilder/Sources/ManifestReader/FirebaseSDKs.pb.swift
  ZipBuilder/Sources/ManifestReader/FirebaseSDKs.proto
  ZipBuilder/Sources/ManifestReader/ManifestReader.swift
  ZipBuilder/Sources/ManifestReader/Release.pb.swift
  ZipBuilder/Sources/ManifestReader/Release.proto
  ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
Labels: cla: yes

#3773 Add move operations to Status.
  Firestore/core/src/firebase/firestore/util/status.cc
  Firestore/core/src/firebase/firestore/util/status.h
  Firestore/core/src/firebase/firestore/util/status_apple.mm
  Firestore/core/test/firebase/firestore/util/status_apple_test.mm
  Firestore/core/test/firebase/firestore/util/status_test.cc
Labels: api: firestore, cla: yes

#3881 Add ERROR_DYNAMIC_LINK_NOT_ACTIVATED and ERROR_REJECTED_CREDENTIAL
  Firebase/Auth/Source/Public/FIRAuthErrors.h
  Firebase/Auth/Source/Utilities/FIRAuthErrorUtils.m
Labels: cla: yes

#3888 Firebase Installations: fix FCM tests.
  Example/Messaging/Tests/FIRMessagingHandlingTest.m
Labels: cla: yes

#3882 Fix GULMutableDictionary keyed subscript methods
  GoogleUtilities/Network/GULMutableDictionary.m
Labels: cla: yes

#3889 Add a product to the SwiftPM manifest.
  ZipBuilder/Package.swift
Labels: cla: yes

#3850 Adding onSnapshotsInSync (not public)
  Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.h
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Example/Tests/SpecTests/json/listen_spec_test.json
  Firestore/Source/API/FIRFirestore+Internal.h
  Firestore/Source/API/FIRFirestore.mm
  Firestore/core/src/firebase/firestore/api/firestore.h
  Firestore/core/src/firebase/firestore/api/firestore.mm
  Firestore/core/src/firebase/firestore/api/snapshots_in_sync_listener_registration.h
  Firestore/core/src/firebase/firestore/api/snapshots_in_sync_listener_registration.mm
  Firestore/core/src/firebase/firestore/core/event_manager.h
  Firestore/core/src/firebase/firestore/core/event_manager.mm
  Firestore/core/src/firebase/firestore/core/firestore_client.h
  Firestore/core/src/firebase/firestore/core/firestore_client.mm
  Firestore/core/src/firebase/firestore/core/query_listener.cc
  Firestore/core/src/firebase/firestore/core/query_listener.h
  Firestore/core/src/firebase/firestore/immutable/sorted_set.h
  Firestore/core/src/firebase/firestore/util/empty.h
  Firestore/core/test/firebase/firestore/core/event_manager_test.mm
Labels: api: firestore, cla: yes

#3907 Merge 6.9.0
  Example/Podfile
  Firebase/Core/CHANGELOG.md
  Firebase/Messaging/CHANGELOG.md
  FirebaseCore.podspec
  FirebaseCoreDiagnostics.podspec
  FirebaseFirestore.podspec
  FirebaseMessaging.podspec
  FirebaseRemoteConfig.podspec
  FirebaseRemoteConfig/CHANGELOG.md
  Firestore/Example/Podfile
  GoogleDataTransport.podspec
  GoogleDataTransportCCTSupport.podspec
  GoogleUtilities/CHANGELOG.md
  Releases/Manifests/6.9.0.json
  SymbolCollisionTest/Podfile
Labels: cla: yes

#3909 Increase timeout to fix travis failure
  GoogleDataTransportCCTSupport/GDTCCTTests/Integration/GDTFLLIntegrationTest.m
Labels: cla: yes

#3908 Update to CocoaPods 1.8.0
  Gemfile
  Gemfile.lock
Labels: cla: yes

#3910 Fix ubsan issues in GDT
  GoogleDataTransport/GDTCORLibrary/GDTCOREvent.m
  GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m
  GoogleDataTransport/GDTCORLibrary/GDTCORTransport.m
  GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m
  GoogleDataTransport/GDTCORLibrary/Public/GDTCOREvent.h
  GoogleDataTransport/GDTCORLibrary/Public/GDTCORTransport.h
Labels: cla: yes

#3914 Fix nanopb dependencies for CoreDiagnostics.
  FirebaseCoreDiagnostics.podspec
  GoogleDataTransportCCTSupport.podspec
Labels: cla: yes

#3916 Use at least Protobuf 3.9.2
  FirebaseABTesting.podspec
  FirebaseFirestore.podspec
  FirebaseMessaging.podspec
  FirebaseRemoteConfig.podspec
Labels: cla: yes

#3659 Make `Serializer` fully support converting `FieldValue`s
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/local/local_serializer.cc
  Firestore/core/src/firebase/firestore/model/database_id.cc
  Firestore/core/src/firebase/firestore/model/database_id.h
  Firestore/core/src/firebase/firestore/nanopb/byte_string.cc
  Firestore/core/src/firebase/firestore/nanopb/byte_string.h
  Firestore/core/src/firebase/firestore/remote/serializer.cc
  Firestore/core/src/firebase/firestore/remote/serializer.h
  Firestore/core/test/firebase/firestore/model/field_value_test.cc
  Firestore/core/test/firebase/firestore/nanopb/byte_string_test.cc
  Firestore/core/test/firebase/firestore/remote/serializer_test.cc
Labels: api: firestore, cla: yes

#3920 Fix typos in FIRDocumentSnapshot.h
  Firestore/Source/Public/FIRDocumentSnapshot.h
Labels: api: firestore, cla: yes

#3923 Better fix for typos in FIRDocumentSnapshot.h
  Firestore/Source/Public/FIRDocumentSnapshot.h
Labels: api: firestore, cla: yes

#3922 Set suppressMessageDisplay on displayExecutor
  Firebase/InAppMessaging/Runtime/FIRIAMRuntimeManager.m
Labels: cla: yes

#3897 Add cross-platform support for creating Executors
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/API/FSTUserDataConverterTests.mm
  Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
  Firestore/core/src/firebase/firestore/api/firestore.mm
  Firestore/core/src/firebase/firestore/remote/connectivity_monitor_apple.mm
  Firestore/core/src/firebase/firestore/remote/datastore.mm
  Firestore/core/src/firebase/firestore/util/executor.h
  Firestore/core/src/firebase/firestore/util/executor_libdispatch.mm
  Firestore/core/src/firebase/firestore/util/executor_std.cc
  Firestore/core/test/firebase/firestore/remote/CMakeLists.txt
  Firestore/core/test/firebase/firestore/remote/datastore_test.mm
  Firestore/core/test/firebase/firestore/remote/exponential_backoff_test.cc
  Firestore/core/test/firebase/firestore/remote/grpc_connection_test.cc
  Firestore/core/test/firebase/firestore/remote/grpc_stream_test.cc
  Firestore/core/test/firebase/firestore/remote/grpc_streaming_reader_test.cc
  Firestore/core/test/firebase/firestore/remote/grpc_unary_call_test.cc
  Firestore/core/test/firebase/firestore/remote/stream_test.mm
  Firestore/core/test/firebase/firestore/testutil/CMakeLists.txt
  Firestore/core/test/firebase/firestore/testutil/async_testing.cc
  Firestore/core/test/firebase/firestore/testutil/async_testing.h
  Firestore/core/test/firebase/firestore/testutil/time_testing.cc
  Firestore/core/test/firebase/firestore/testutil/time_testing.h
  Firestore/core/test/firebase/firestore/util/CMakeLists.txt
  Firestore/core/test/firebase/firestore/util/executor_std_test.cc
  Firestore/core/test/firebase/firestore/util/grpc_stream_tester.cc
  Firestore/core/test/firebase/firestore/util/grpc_stream_tester.h
Labels: api: firestore, cla: yes

#3794 Pristine copy of JSONEncoder.swift
  Firestore/third_party/FirestoreEncoder/JSONEncoder.swift
  Firestore/third_party/FirestoreEncoder/LICENSE
  Firestore/third_party/FirestoreEncoder/METADATA
Labels: api: firestore, cla: yes

#3898 Upgrade GoogleTest to 1.8.1
  Firestore/Example/GoogleTest.podspec
  cmake/external/googletest.cmake
Labels: api: firestore, cla: yes

#3939 CocoaPods 1.8.1
  Gemfile
  Gemfile.lock
Labels: cla: yes

#3899 Add Expectations and Async/Await for testing
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/core/test/firebase/firestore/remote/exponential_backoff_test.cc
  Firestore/core/test/firebase/firestore/testutil/CMakeLists.txt
  Firestore/core/test/firebase/firestore/testutil/async_testing.cc
  Firestore/core/test/firebase/firestore/testutil/async_testing.h
  Firestore/core/test/firebase/firestore/util/CMakeLists.txt
  Firestore/core/test/firebase/firestore/util/async_queue_libdispatch_test.mm
  Firestore/core/test/firebase/firestore/util/async_queue_test.cc
  Firestore/core/test/firebase/firestore/util/async_queue_test.h
  Firestore/core/test/firebase/firestore/util/async_tests_util.h
  Firestore/core/test/firebase/firestore/util/executor_libdispatch_test.mm
  Firestore/core/test/firebase/firestore/util/executor_std_test.cc
  Firestore/core/test/firebase/firestore/util/executor_test.cc
  Firestore/core/test/firebase/firestore/util/executor_test.h
Labels: api: firestore, cla: yes

#3940 Fix Networking to receive data for POST requests
  GoogleUtilities/Example/Tests/Network/GULNetworkTest.m
  GoogleUtilities/Network/GULNetworkURLSession.m
Labels: cla: yes

#3926 Fix an issue around deleting records from the database.
  FirebaseRemoteConfig/Sources/RCNConfigDBManager.m
  FirebaseRemoteConfig/Tests/Unit/RCNConfigDBManagerTest.m
Labels: cla: yes

#3944 Travis to Xcode 11.0
  .travis.yml
  Example/Database/Tests/Unit/FLevelDBStorageEngineTests.m
  scripts/build.sh
Labels: cla: yes

#3900 Migrate FSTViewTests to C++
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/Core/FSTViewTests.mm
  Firestore/core/test/firebase/firestore/core/CMakeLists.txt
  Firestore/core/test/firebase/firestore/core/view_test.cc
  Firestore/core/test/firebase/firestore/testutil/CMakeLists.txt
  Firestore/core/test/firebase/firestore/testutil/view_testing.cc
  Firestore/core/test/firebase/firestore/testutil/view_testing.h
Labels: api: firestore, cla: yes

#3901 Migrate FSTQueryListenerTests to C++
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
  Firestore/core/test/firebase/firestore/core/query_listener_test.cc
Labels: api: firestore, cla: yes

#3952 Make FIAM tests more robust in Travis
  .travis.yml
  scripts/build.sh
  scripts/if_changed.sh
  scripts/install_prereqs.sh
Labels: cla: yes

#3942 Make onSnapshotsInSync() public
  Firestore/CHANGELOG.md
  Firestore/Source/API/FIRFirestore+Internal.h
  Firestore/Source/Public/FIRFirestore.h
  Firestore/Swift/Tests/API/BasicCompileTests.swift
Labels: api: firestore, cla: yes

#3958 Fix Catalyst define checks
  .travis.yml
  Example/InstanceID/Tests/FIRInstanceIDKeyPairMigrationTest.m
  GoogleDataTransport/GDTCORLibrary/GDTCORStorage.m
  GoogleDataTransport/GDTCORTests/Unit/GDTCORClockTest.m
  GoogleDataTransport/GDTCORTests/Unit/GDTCOREventTest.m
  GoogleDataTransport/GDTCORTests/Unit/GDTCORStorageTest.m
  GoogleDataTransport/GDTCORTests/Unit/GDTCORUploadPackageTest.m
  scripts/build.sh
Labels: GoogleDataTransport, cla: yes
