Repository firebase/firebase-ios-sdk, pull requests merged in 2019-07, with the labels that each got.

#3277 Import GULLoggerLevel.h via public framework header
  GoogleUtilities/Logger/GULLogger.m
Labels: cla: yes

#3288 Put the need to include Firestore/Source/Public in the podspec
  FirebaseFirestore.podspec
  Firestore/Example/Podfile
Labels: api: firestore, cla: yes

#3294 Ensure Storage initializer doesn't get called
  Firebase/Storage/CHANGELOG.md
  Firebase/Storage/FIRStorage.m
  Firebase/Storage/Public/FIRStorage.h
Labels: cla: yes

#3293 FIROptions.appGroupID introduced
  Example/Core/Tests/FIROptionsTest.m
  Firebase/Core/FIROptions.m
  Firebase/Core/Public/FIROptions.h
Labels: cla: yes

#3289 Use a consistent set of dependencies on all platforms
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Podfile
Labels: api: firestore, cla: yes

#3292 Store the coerced base value in the BaseMutation
  Firestore/CHANGELOG.md
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_Tests_macOS.xcscheme
  Firestore/Example/Tests/Integration/API/FIRNumericTransformTests.mm
  Firestore/Example/Tests/Integration/API/FIRServerTimestampTests.mm
  Firestore/Example/Tests/Model/FSTMutationTests.mm
  Firestore/Example/Tests/Model/transform_operations_test.mm
  Firestore/Source/Local/FSTLocalStore.mm
  Firestore/Source/Model/FSTMutation.h
  Firestore/Source/Model/FSTMutation.mm
  Firestore/core/src/firebase/firestore/model/field_mask.cc
  Firestore/core/src/firebase/firestore/model/field_mask.h
  Firestore/core/src/firebase/firestore/model/field_transform.h
  Firestore/core/src/firebase/firestore/model/field_value.cc
  Firestore/core/src/firebase/firestore/model/field_value.h
  Firestore/core/src/firebase/firestore/model/transform_operations.h
  Firestore/core/src/firebase/firestore/model/transform_operations.mm
  Firestore/core/test/firebase/firestore/model/field_value_test.cc
Labels: api: firestore, cla: yes

#3286 In card message: set the text color on the body text view
  Firebase/InAppMessagingDisplay/Card/FIDCardViewController.m
  InAppMessagingDisplay/Example/FiamDisplaySwiftExample/CardMessageViewController.swift
Labels: cla: yes

#3301 spm functions
  Firebase/Core/Private/FIRAppInternal.h
  Firebase/Firebase/Public/Firebase.h
  Functions/FirebaseFunctions/FIRFunctions.m
  Functions/FirebaseFunctions/FUNContext.m
  Package.swift
  Sources/firebase-test/main.swift
Labels: cla: yes

#3305 [docs] add missing semicolon
  GoogleUtilities/AppDelegateSwizzler/README.md
Labels: cla: yes

#3309 Add explicit Foundation import.
  GoogleUtilities/AppDelegateSwizzler/Internal/GULAppDelegateSwizzler_Private.h
  GoogleUtilities/CHANGELOG.md
  GoogleUtilities/Common/GULLoggerCodes.h
  GoogleUtilities/Logger/Public/GULLoggerLevel.h
  GoogleUtilities/Network/Private/GULNetworkMessageCode.h
  GoogleUtilities/Reachability/Private/GULReachabilityMessageCode.h
Labels: cla: yes

#3308 Firebase Installations - eagerly request auth token
  FirebaseInstallations/Source/Library/FIRInstallations.m
  FirebaseInstallations/Source/Tests/Unit/FIRInstallationsTests.m
Labels: cla: yes

#3296 Fix and rewrite sync_project.rb
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Podfile
  scripts/build.sh
  scripts/sync_project.rb
Labels: api: firestore, cla: yes

#3313 Firebase Installations - fix flaky tests
  FirebaseInstallations/Source/Tests/Unit/FIRInstallationsTests.m
Labels: cla: yes

#3314 IID build for swiftPM
  Firebase/Core/Private/FIRLogger.h
  Firebase/InstanceID/FIRInstanceID.m
  Firebase/InstanceID/FIRInstanceIDCheckinPreferences.m
  Firebase/InstanceID/FIRInstanceIDLogger.m
  Firebase/InstanceID/FIRInstanceIDTokenFetchOperation.m
  Firebase/InstanceID/FIRInstanceIDUtilities.m
  GoogleUtilities/UserDefaults/GULUserDefaults.m
  Package.swift
  Sources/firebase-test/main.swift
Labels: cla: yes

#3318 Migrate auth api tests to a dedicated firebase project
  Example/Auth/ApiTests/AccountInfoTests.m
  Example/Auth/ApiTests/Auth_ApiTests-Bridging-Header.h
  Example/Auth/ApiTests/CustomAuthTests.m
  Example/Auth/ApiTests/EmailPasswordAuthTests.m
  Example/Auth/ApiTests/GoogleAuthTests.m
  Example/Auth/ApiTests/GoogleAuthTests.swift
  Example/Firebase.xcodeproj/project.pbxproj
  scripts/build.sh
  scripts/install_prereqs.sh
  scripts/travis-encrypted/Secrets.tar.enc
Labels: cla: yes

#3287 Throw last failed attempt's error in failed transactions
  Firestore/CHANGELOG.md
  Firestore/Example/Tests/Integration/API/FIRServerTimestampTests.mm
  Firestore/Example/Tests/Integration/FSTTransactionTests.mm
  Firestore/Source/Core/FSTSyncEngine.mm
  Firestore/core/src/firebase/firestore/core/transaction.h
  Firestore/core/src/firebase/firestore/core/transaction.mm
Labels: api: firestore, cla: yes

#3315 Add an -all_load linker flag to all example apps
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  scripts/check.sh
  scripts/sync_project.rb
Labels: api: firestore, cla: yes

#3324 Merging the 6.4.0 release into master
  Example/Podfile
  FirebaseAuth.podspec
  FirebaseCore.podspec
  FirebaseFirestore.podspec
  FirebaseInstanceID.podspec
  FirebaseMessaging.podspec
  FirebaseStorage.podspec
  Firestore/Example/Podfile
  Releases/Manifests/6.4.0.json
  SymbolCollisionTest/Podfile
Labels: cla: yes

#3325 Update to CocoaPods 1.7.4
  Gemfile
  Gemfile.lock
Labels: cla: yes

#3329 Fix constant name conflic between old and new diagnostics
  .travis.yml
  Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
Labels: cla: yes

#3322 GULMutableDictionary: use `dispatch_sync` instead of `async`.
  GoogleUtilities/Network/GULMutableDictionary.m
Labels: cla: yes

#3331 Bump GoogleUtilities version 6.2.2
  GoogleUtilities.podspec
  GoogleUtilities/CHANGELOG.md
Labels: cla: yes

#3333 Stop calling deprecated sendLogsWithServiceName
  Firebase/DynamicLinks/FIRDynamicLinks.m
  Firebase/InstanceID/FIRInstanceID.m
Labels: cla: yes

#3326 Manage search paths with sync_project.rb
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  scripts/sync_project.rb
Labels: api: firestore, cla: yes

#3334 Upgrade to Firestore Emulator 1.6.1
  scripts/run_firestore_emulator.sh
Labels: api: firestore, cla: yes

#3332 Fix the build on Windows
  Firestore/core/src/firebase/firestore/nanopb/writer.cc
  Firestore/core/src/firebase/firestore/timestamp.cc
  Firestore/core/test/firebase/firestore/model/field_value_test.cc
  Firestore/core/test/firebase/firestore/timestamp_test.cc
Labels: api: firestore, cla: yes

#3337 Revert "GULMutableDictionary: use `dispatch_sync` instead of `async`."
  GoogleUtilities.podspec
  GoogleUtilities/CHANGELOG.md
  GoogleUtilities/Network/GULMutableDictionary.m
Labels: cla: yes

#3339 Update required CocoaPods version in READMEs
  Firestore/README.md
  Functions/README.md
  README.md
Labels: cla: yes

#3335 Manage configuration for benchmarks and fuzz tests and fix them
  Firestore/Example/Benchmarks/FSTLevelDBBenchmarkTests.mm
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_Benchmarks_iOS.xcscheme
  Firestore/Example/Podfile
  scripts/sync_project.rb
Labels: api: firestore, cla: yes

#3327 Implement collection groups in C++ Query
  Firestore/Example/Tests/Core/FSTQueryTests.mm
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Source/API/FIRFirestore.mm
  Firestore/Source/Core/FSTQuery.h
  Firestore/Source/Core/FSTQuery.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/api/firestore.h
  Firestore/core/src/firebase/firestore/api/firestore.mm
  Firestore/core/src/firebase/firestore/core/query.cc
  Firestore/core/src/firebase/firestore/core/query.h
  Firestore/core/src/firebase/firestore/local/local_documents_view.mm
  Firestore/core/src/firebase/firestore/remote/serializer.cc
  Firestore/core/src/firebase/firestore/util/equality.h
  Firestore/core/src/firebase/firestore/util/string_apple.h
  Firestore/core/src/firebase/firestore/util/vector_of_ptr.h
  Firestore/core/test/firebase/firestore/core/query_test.cc
  Firestore/core/test/firebase/firestore/local/CMakeLists.txt
  Firestore/core/test/firebase/firestore/testutil/testutil.h
  Firestore/core/test/firebase/firestore/util/objc_compatibility_apple_test.mm
Labels: api: firestore, cla: yes

#3336 Add Swift integration tests to macOS and tvOS builds
  FirebaseFirestoreSwift.podspec
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Podfile
  scripts/sync_project.rb
Labels: api: firestore, cla: yes

#3340 Manage resources with sync_project.rb
  Firestore/Example/App/macOS/AppDelegate.m
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  scripts/sync_project.rb
Labels: api: firestore, cla: yes

#3338 Fix unaccessible init in FDL tests.
  Example/DynamicLinks/Tests/FIRDynamicLinksTest.m
Labels: cla: yes

#3341 Add support of error MISSING_CLIENT_IDENTIFIER
  Firebase/Auth/Source/Backend/FIRAuthBackend.m
  Firebase/Auth/Source/Public/FIRAuthErrors.h
  Firebase/Auth/Source/Utilities/FIRAuthErrorUtils.h
  Firebase/Auth/Source/Utilities/FIRAuthErrorUtils.m
  Firebase/Auth/Source/Utilities/FIRAuthInternalErrors.h
Labels: cla: yes

#3224 Docs update and directory structure proposal
  AddNewPod.md
  README.md
Labels: Infrastructure, cla: yes

#3342 Have Firestore integration tests run all tests
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/AllTests_iOS.xcscheme
  Firestore/Example/Podfile
  Firestore/Example/Tests/API/FIRQueryUnitTests.mm
  Firestore/Swift/Tests/API/BasicCompileTests.swift
  scripts/build.sh
  scripts/sync_project.rb
Labels: api: firestore, cla: yes

#3350 Handle coverage flakiness more locally
  scripts/build.sh
Labels: cla: yes

#3345 Enable incremental pod installs and fix incremental builds
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Podfile
Labels: api: firestore, cla: yes

#3346 Start reimplementing FSTQuery with C++ query
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Source/Core/FSTQuery.h
  Firestore/Source/Core/FSTQuery.mm
  Firestore/core/src/firebase/firestore/core/query.cc
  Firestore/core/src/firebase/firestore/core/query.h
Labels: api: firestore, cla: yes

#3352 Finish porting FSTFilter classes to C++ Filter classes
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/core/src/firebase/firestore/core/CMakeLists.txt
  Firestore/core/src/firebase/firestore/core/filter.cc
  Firestore/core/src/firebase/firestore/core/filter.h
  Firestore/core/src/firebase/firestore/core/nan_filter.cc
  Firestore/core/src/firebase/firestore/core/nan_filter.h
  Firestore/core/src/firebase/firestore/core/null_filter.cc
  Firestore/core/src/firebase/firestore/core/null_filter.h
  Firestore/core/src/firebase/firestore/core/relation_filter.cc
  Firestore/core/src/firebase/firestore/core/relation_filter.h
  Firestore/core/src/firebase/firestore/model/base_path.h
  Firestore/core/test/firebase/firestore/core/filter_test.cc
Labels: api: firestore, cla: yes

#3351 Restore Database integration tests
  .travis.yml
Labels: Infrastructure, api: database, cla: yes

#3348 Reimplement FSTFilter classes in terms of C++ Filter classes
  Firestore/Example/Tests/API/FIRQuerySnapshotTests.mm
  Firestore/Example/Tests/Model/FSTDocumentSetTests.mm
  Firestore/Source/Core/FSTQuery.h
  Firestore/Source/Core/FSTQuery.mm
  Firestore/Source/Model/FSTDocument.h
  Firestore/Source/Model/FSTDocument.mm
  Firestore/Source/Model/FSTMutation.mm
  Firestore/core/src/firebase/firestore/core/nan_filter.h
  Firestore/core/src/firebase/firestore/core/null_filter.h
  Firestore/core/src/firebase/firestore/core/relation_filter.h
  Firestore/core/src/firebase/firestore/model/document.h
  Firestore/core/test/firebase/firestore/remote/watch_change_test.mm
  Firestore/core/test/firebase/firestore/util/objc_compatibility_apple_test.mm
Labels: api: firestore, cla: yes

#3349 Complete migration to C++ Filters in FSTQuery
  Firestore/Example/Tests/Core/FSTQueryTests.mm
  Firestore/Example/Tests/Core/FSTViewTests.mm
  Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
  Firestore/Example/Tests/Local/FSTQueryCacheTests.mm
  Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Example/Tests/Util/FSTHelpers.h
  Firestore/Example/Tests/Util/FSTHelpers.mm
  Firestore/Source/Core/FSTQuery.h
  Firestore/Source/Core/FSTQuery.mm
  Firestore/Source/Remote/FSTSerializerBeta.h
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/api/query_core.h
  Firestore/core/src/firebase/firestore/api/query_core.mm
  Firestore/core/src/firebase/firestore/core/query.cc
  Firestore/core/src/firebase/firestore/core/query.h
  Firestore/core/src/firebase/firestore/util/vector_of_ptr.h
  Firestore/core/test/firebase/firestore/testutil/testutil.h
  Firestore/core/test/firebase/firestore/testutil/xcgmock.h
  Firestore/core/test/firebase/firestore/testutil/xcgmock_test.mm
Labels: api: firestore, cla: yes

#3356 Disable incremental installation
  Firestore/Example/Podfile
Labels: api: firestore, cla: yes

#3360 Update CHANGELOG for Firestore v1.4.2
  Firestore/CHANGELOG.md
Labels: api: firestore, cla: yes

#3361 Fix FIRDocumentChange returning incorrect values for not found
  Firestore/CHANGELOG.md
  Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
  Firestore/Source/API/FIRDocumentChange.mm
Labels: api: firestore, cla: yes

#3362 Assert version is read successfully from LevelDB
  Firestore/core/src/firebase/firestore/local/leveldb_migrations.cc
Labels: api: firestore, cla: yes

#3357 Fix warnings in CodableIntegrationTests.swift
  Firestore/Swift/Tests/Integration/CodableIntegrationTests.swift
Labels: api: firestore, cla: yes

#3366 FirebaseCore M52 changelog updates
  Firebase/Core/CHANGELOG.md
Labels: cla: yes

#3367 Storage for M52
  Firebase/Core/CHANGELOG.md
  Firebase/Storage/CHANGELOG.md
Labels: cla: yes

#3371 M52 release notes for headful SDK
  Firebase/InAppMessagingDisplay/CHANGELOG.md
Labels: cla: yes

#3370 M52 release notes for headless SDK
  Firebase/InAppMessaging/CHANGELOG.md
Labels: cla: yes

#3363 fix latency-compensated query
  Firestore/CHANGELOG.md
  Firestore/Example/Tests/SpecTests/json/query_spec_test.json
  Firestore/core/src/firebase/firestore/local/local_documents_view.h
  Firestore/core/src/firebase/firestore/local/local_documents_view.mm
Labels: api: firestore, cla: yes

#3369 Update CHANGELOG.md
  Firebase/Auth/CHANGELOG.md
Labels: cla: yes

#3214 Create Segmentation SDK structure for source and unit tests.
  .travis.yml
  FirebaseSegmentation.podspec
  FirebaseSegmentation/Public/FIRSegmentation.h
  FirebaseSegmentation/Public/FirebaseSegmentation.h
  FirebaseSegmentation/Sources/CHANGELOG.md
  FirebaseSegmentation/Sources/FIRSegmentation.m
  FirebaseSegmentation/Tests/Unit/SEGInitializationTests.m
Labels: cla: yes

#3372 Add missing GoogleUtilities version dependencies
  FirebaseDynamicLinks.podspec
Labels: api: dynamiclinks, cla: yes

#3374 Ignore unreleased SDKs from release manifests.
  ZipBuilder/Sources/ZipBuilder/ManifestReader.swift
Labels: cla: yes

#3375 Fix compilation flags for zip builder.
  ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
Labels: cla: yes

#3376 Firebase Installations as standalone SDK
  .travis.yml
  FirebaseInstallations.podspec
  FirebaseInstallations/Source/Library/Errors/FIRInstallationsErrorUtil.h
  FirebaseInstallations/Source/Library/Errors/FIRInstallationsErrorUtil.m
  FirebaseInstallations/Source/Library/Errors/FIRInstallationsHTTPError.h
  FirebaseInstallations/Source/Library/Errors/FIRInstallationsHTTPError.m
  FirebaseInstallations/Source/Library/FIRInstallations.m
  FirebaseInstallations/Source/Library/FIRInstallationsAuthTokenResult.m
  FirebaseInstallations/Source/Library/FIRInstallationsAuthTokenResultInternal.h
  FirebaseInstallations/Source/Library/FIRInstallationsItem.h
  FirebaseInstallations/Source/Library/FIRInstallationsItem.m
  FirebaseInstallations/Source/Library/FIRInstallationsVersion.m
  FirebaseInstallations/Source/Library/FIRSecureStorage.h
  FirebaseInstallations/Source/Library/FIRSecureStorage.m
  FirebaseInstallations/Source/Library/IIDMigration/FIRInstallationsIIDStore.h
  FirebaseInstallations/Source/Library/IIDMigration/FIRInstallationsIIDStore.m
  FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.h
  FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.m
  FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsItem+RegisterInstallationAPI.h
  FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsItem+RegisterInstallationAPI.m
  FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.h
  FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
  FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsSingleOperationPromiseCache.h
  FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsSingleOperationPromiseCache.m
  FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsStatus.h
  FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStore.h
  FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStore.m
  FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStoredAuthToken.h
  FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStoredAuthToken.m
  FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStoredItem.h
  FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStoredItem.m
  FirebaseInstallations/Source/Library/Public/FIRInstallations.h
  FirebaseInstallations/Source/Library/Public/FIRInstallationsAuthTokenResult.h
  FirebaseInstallations/Source/Library/Public/FIRInstallationsErrors.h
  FirebaseInstallations/Source/Library/Public/FIRInstallationsVersion.h
  FirebaseInstallations/Source/Tests/Fixture/APIGenerateTokenResponseInvalidRefreshToken.json
  FirebaseInstallations/Source/Tests/Fixture/APIGenerateTokenResponseSuccess.json
  FirebaseInstallations/Source/Tests/Fixture/APIRegisterInstallationResponseSuccess.json
  FirebaseInstallations/Source/Tests/Integration/FIRInstallationsIntegrationTests.m
  FirebaseInstallations/Source/Tests/Resources/GoogleService-Info.plist
  FirebaseInstallations/Source/Tests/Unit/FIRInstallationsAPIServiceTests.m
  FirebaseInstallations/Source/Tests/Unit/FIRInstallationsHTTPErrorTests.m
  FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m
  FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIIDStoreTests.m
  FirebaseInstallations/Source/Tests/Unit/FIRInstallationsItemTests.m
  FirebaseInstallations/Source/Tests/Unit/FIRInstallationsStoreTests.m
  FirebaseInstallations/Source/Tests/Unit/FIRInstallationsStoredAuthTokenTests.m
  FirebaseInstallations/Source/Tests/Unit/FIRInstallationsStoredItemTests.m
  FirebaseInstallations/Source/Tests/Unit/FIRInstallationsTests.m
  FirebaseInstallations/Source/Tests/Unit/FIRSecureStorageTests.m
  FirebaseInstallations/Source/Tests/Utils/FIRInstallations+Tests.h
  FirebaseInstallations/Source/Tests/Utils/FIRInstallationsErrorUtil+Tests.h
  FirebaseInstallations/Source/Tests/Utils/FIRInstallationsErrorUtil+Tests.m
  FirebaseInstallations/Source/Tests/Utils/FIRInstallationsItem+Tests.h
  FirebaseInstallations/Source/Tests/Utils/FIRInstallationsItem+Tests.m
  FirebaseInstallations/Source/Tests/Utils/FIRKeyedArchivingUtils.h
  FirebaseInstallations/Source/Tests/Utils/FIRKeyedArchivingUtils.m
  FirebaseInstallations/Source/Tests/Utils/FIRTestKeychain.h
  FirebaseInstallations/Source/Tests/Utils/FIRTestKeychain.m
  scripts/if_changed.sh
Labels: cla: yes

#3379 Headers are part of Sources
  AddNewPod.md
Labels: cla: yes

#3383 Firebase Installations - adjustments to import to google3
  FirebaseInstallations/Source/Library/FIRInstallations.m
  FirebaseInstallations/Source/Library/FIRInstallationsItem.h
  FirebaseInstallations/Source/Library/FIRSecureStorage.h
  FirebaseInstallations/Source/Library/Public/FIRInstallations.h
  FirebaseInstallations/Source/Library/Public/FirebaseInstallations.h
  FirebaseInstallations/Source/Tests/Integration/FIRInstallationsIntegrationTests.m
  FirebaseInstallations/Source/Tests/Unit/FIRInstallationsTests.m
Labels: cla: yes

#3386 Update InstanceID changelog
  Firebase/InstanceID/CHANGELOG.md
Labels: cla: yes

#3384 Delete test that fails to build internally
  GoogleUtilities/Example/Tests/Swizzler/GULRuntimeClassSnapshotTests.m
Labels: cla: yes

#3377 Upgrade to Firestore Emulator 1.6.2
  scripts/run_firestore_emulator.sh
Labels: api: firestore, cla: yes

#3394 Fix typo that caused cron failure
  CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_7_0_staticLibs/Podfile
Labels: cla: yes

#3388 Update versions for Release 6.5.0
  Example/Podfile
  FirebaseAuth.podspec
  FirebaseCore.podspec
  FirebaseDynamicLinks.podspec
  FirebaseFirestore.podspec
  FirebaseInAppMessaging.podspec
  FirebaseInAppMessagingDisplay.podspec
  FirebaseInstanceID.podspec
  FirebaseStorage.podspec
  Firestore/Example/Podfile
  Releases/Manifests/6.5.0.json
  SymbolCollisionTest/Podfile
Labels: cla: yes

#3395 Add a release notes generator
  Firestore/CHANGELOG.md
  scripts/make_release_notes.py
Labels: Infrastructure, cla: yes

#3396 Cherry pick some bug and analyzer fixes
  Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
  GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m
  GoogleDataTransport/GDTTests/Unit/GDTUploadCoordinatorTest.m
  GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
  GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m
Labels: cla: yes

#3401 Transform operations can be compiled as pure C++
  Firestore/core/src/firebase/firestore/core/query_listener.mm
  Firestore/core/src/firebase/firestore/model/CMakeLists.txt
  Firestore/core/src/firebase/firestore/model/transform_operations.cc
  Firestore/core/src/firebase/firestore/model/transform_operations.h
Labels: api: firestore, cla: yes

#3403 Make sure all move operations are marked noexcept
  Firestore/core/src/firebase/firestore/immutable/sorted_map_iterator.h
  Firestore/core/src/firebase/firestore/util/statusor_internals.h
Labels: api: firestore, cla: yes

#3404 add compile_commands.json to gitignore
  .gitignore
Labels: cla: yes

#3402 Remove extraneous imports
  Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
  Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
  Firestore/Example/Tests/Integration/API/FIRFieldsTests.mm
  Firestore/Example/Tests/Integration/API/FIRFirestoreSourceTests.mm
  Firestore/Example/Tests/Integration/API/FIRListenerRegistrationTests.mm
  Firestore/Example/Tests/Integration/API/FIRServerTimestampTests.mm
  Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/API/FIRQuerySnapshot.mm
  Firestore/Source/Core/FSTFirestoreClient.h
  Firestore/Source/Local/FSTLevelDB.mm
  Firestore/core/src/firebase/firestore/api/document_reference.mm
Labels: api: firestore, cla: yes

#3400 CocoaPods 1.7.5
  Gemfile
  Gemfile.lock
Labels: cla: yes

#3389 Port FSTLocalWriteResult to c++
  Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
  Firestore/Source/Core/FSTSyncEngine.mm
  Firestore/Source/Local/FSTLocalStore.h
  Firestore/Source/Local/FSTLocalStore.mm
  Firestore/Source/Local/FSTLocalWriteResult.h
  Firestore/Source/Local/FSTLocalWriteResult.mm
  Firestore/core/src/firebase/firestore/local/local_write_result.h
Labels: api: firestore, cla: yes

#3407 Increment the dependency of GDTCCT in FIRCD
  FirebaseCoreDiagnostics.podspec
Labels: cla: yes

#3409 FirebaseInstallations: debug logging
  FirebaseInstallations/Source/Library/FIRInstallationsLogger.h
  FirebaseInstallations/Source/Library/FIRInstallationsLogger.m
  FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.m
  FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
  FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStoredAuthToken.m
  FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStoredItem.m
Labels: cla: yes

#3408 Add check for pre-existing version tags
  Releases/update-versions.py
Labels: cla: yes

#3410 pod_lib_lint.rb - argument to ignore specified local podspecs
  .travis.yml
  scripts/pod_lib_lint.rb
Labels: cla: yes

#3419 Remove `=default`ed constructors resulting in deleted constructors.
  Firestore/core/src/firebase/firestore/core/array_contains_filter.h
  Firestore/core/src/firebase/firestore/core/key_field_filter.h
Labels: api: firestore, cla: yes

#3420 Fix fuzz build
  Firestore/fuzzing/serializer_fuzzer.cc
Labels: api: firestore, cla: yes

#3421 Avoid dirtying the workspace when linting
  scripts/pod_lib_lint.rb
Labels: api: firestore, cla: yes

#3418 pod_lib_lint.rb improvements
  .travis.yml
  scripts/pod_lib_lint.rb
Labels: Infrastructure, cla: yes

#3415 Firebase Installations: update API response handling
  FirebaseInstallations/Source/Library/Errors/FIRInstallationsErrorUtil.h
  FirebaseInstallations/Source/Library/Errors/FIRInstallationsErrorUtil.m
  FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.m
  FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsItem+RegisterInstallationAPI.m
  FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
  FirebaseInstallations/Source/Library/Public/FIRInstallations.h
  FirebaseInstallations/Source/Tests/Fixture/APIRegisterInstallationResponseSuccess.json
  FirebaseInstallations/Source/Tests/Unit/FIRInstallationsAPIServiceTests.m
  FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m
  FirebaseInstallations/Source/Tests/Unit/FIRInstallationsStoreTests.m
  FirebaseInstallations/Source/Tests/Unit/FIRInstallationsTests.m
  FirebaseInstallations/Source/Tests/Utils/FIRInstallationsItem+Tests.h
  FirebaseInstallations/Source/Tests/Utils/FIRInstallationsItem+Tests.m
Labels: cla: yes

#3422 CoreDiagnostics: set missing flag `has_sdk_name` for heartbeats.
  Example/CoreDiagnostics/Tests/FIRCoreDiagnosticsTest.m
  Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
Labels: cla: yes

#3424 Fixing version dependencies, order of pods, update-versions script
  FirebaseCore.podspec
  FirebaseCoreDiagnostics.podspec
  GoogleDataTransportCCTSupport.podspec
  Releases/Manifests/6.6.0.json
  Releases/update-versions.py
Labels: cla: yes

#3425 CoreDiagnostics: set missing flag `has_sdk_name` for heartbeats. (#3422)
  Example/CoreDiagnostics/Tests/FIRCoreDiagnosticsTest.m
  Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
Labels: cla: yes

#3427 Consolidate bug fixes without podspec version changes
  GoogleDataTransport/GDTLibrary/GDTClock.m
  GoogleDataTransport/GDTLibrary/GDTDataFuture.m
  GoogleDataTransport/GDTLibrary/Public/GDTDataFuture.h
  GoogleDataTransport/GDTTests/Unit/GDTClockTest.m
  GoogleDataTransport/GDTTests/Unit/GDTDataFutureTest.m
Labels: cla: yes

#3426 Rename Query::Filter to Query::AddingFilter
  Firestore/Source/Core/FSTQuery.mm
  Firestore/core/src/firebase/firestore/core/query.cc
  Firestore/core/src/firebase/firestore/core/query.h
  Firestore/core/test/firebase/firestore/core/query_test.cc
Labels: api: firestore, cla: yes

#3428 Firebase Installations: delete IID on default app installation delete.
  FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
  FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m
  FirebaseInstallations/Source/Tests/Utils/FIRInstallationsItem+Tests.m
Labels: cla: yes

#3423 CoreDiagnostics tests code style.
  Example/CoreDiagnostics/Tests/FIRCoreDiagnosticsTest.m
Labels: cla: yes

#3430 Add core support with interop for Segmentation SDK.
  .travis.yml
  FirebaseSegmentation.podspec
  FirebaseSegmentation/Sources/FIRSegmentation.m
  FirebaseSegmentation/Sources/FIRSegmentationComponent.m
  FirebaseSegmentation/Sources/Private/FIRSegmentationComponent.h
  FirebaseSegmentation/Sources/Private/FIRSegmentationInternal.h
  FirebaseSegmentation/Sources/Public/FIRSegmentation.h
  FirebaseSegmentation/Sources/Public/FirebaseSegmentation.h
  FirebaseSegmentation/Tests/Unit/SEGInitializationTests.m
Labels: cla: yes

#3429 Fix preconditions in transactions
  Firestore/CHANGELOG.md
  Firestore/Example/Tests/Integration/FSTTransactionTests.mm
  Firestore/core/src/firebase/firestore/core/transaction.h
  Firestore/core/src/firebase/firestore/core/transaction.mm
Labels: api: firestore, cla: yes

#3435 Port FSTLocalViewChanges to C++
  Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
  Firestore/Example/Tests/Util/FSTHelpers.h
  Firestore/Example/Tests/Util/FSTHelpers.mm
  Firestore/Source/Core/FSTSyncEngine.mm
  Firestore/Source/Local/FSTLocalStore.h
  Firestore/Source/Local/FSTLocalStore.mm
  Firestore/Source/Local/FSTLocalViewChanges.h
  Firestore/Source/Local/FSTLocalViewChanges.mm
  Firestore/core/src/firebase/firestore/local/local_view_changes.h
  Firestore/core/src/firebase/firestore/local/local_view_changes.mm
Labels: api: firestore, cla: yes

#3398 Firebase Installations: Instance ID now uses FIS under the hood.
  .travis.yml
  Example/Firebase.xcodeproj/project.pbxproj
  Example/InstanceID/Tests/FIRInstanceIDKeyPairMigrationTest.m
  Example/InstanceID/Tests/FIRInstanceIDKeyPairStoreTest.m
  Example/InstanceID/Tests/FIRInstanceIDKeyPairTest.m
  Example/InstanceID/Tests/FIRInstanceIDTest.m
  Example/InstanceID/Tests/FIRInstanceIDTokenManagerTest.m
  Example/InstanceID/Tests/FIRInstanceIDTokenOperationsTest.m
  Example/Messaging/Tests/FIRInstanceIDWithFCMTest.m
  Example/Messaging/Tests/FIRMessagingClientTest.m
  Example/Messaging/Tests/FIRMessagingLinkHandlingTest.m
  Example/Messaging/Tests/FIRMessagingServiceTest.m
  Example/Messaging/Tests/FIRMessagingTest.m
  Example/Messaging/Tests/FIRMessagingTestUtilities.h
  Example/Messaging/Tests/FIRMessagingTestUtilities.m
  Example/Podfile
  Firebase/InstanceID/FIRIMessageCode.h
  Firebase/InstanceID/FIRInstanceID+Private.h
  Firebase/InstanceID/FIRInstanceID+Private.m
  Firebase/InstanceID/FIRInstanceID.m
  Firebase/InstanceID/FIRInstanceIDKeyPair.h
  Firebase/InstanceID/FIRInstanceIDKeyPair.m
  Firebase/InstanceID/FIRInstanceIDKeyPairStore.h
  Firebase/InstanceID/FIRInstanceIDKeyPairStore.m
  Firebase/InstanceID/FIRInstanceIDKeyPairUtilities.h
  Firebase/InstanceID/FIRInstanceIDKeyPairUtilities.m
  Firebase/InstanceID/FIRInstanceIDKeychain.h
  Firebase/InstanceID/FIRInstanceIDKeychain.m
  Firebase/InstanceID/FIRInstanceIDTokenDeleteOperation.h
  Firebase/InstanceID/FIRInstanceIDTokenDeleteOperation.m
  Firebase/InstanceID/FIRInstanceIDTokenFetchOperation.h
  Firebase/InstanceID/FIRInstanceIDTokenFetchOperation.m
  Firebase/InstanceID/FIRInstanceIDTokenManager.h
  Firebase/InstanceID/FIRInstanceIDTokenManager.m
  Firebase/InstanceID/FIRInstanceIDTokenOperation+Private.h
  Firebase/InstanceID/FIRInstanceIDTokenOperation.h
  Firebase/InstanceID/FIRInstanceIDTokenOperation.m
  Firebase/InstanceID/Private/FIRInstanceID_Private.h
  FirebaseInstanceID.podspec
  InAppMessaging/Example/Podfile
  InAppMessagingDisplay/Example/Podfile
Labels: cla: yes

#3442 Fix an email unlink bug
  Example/Auth/Sample/MainViewController+Email.m
  Firebase/Auth/Source/User/FIRUser.m
Labels: cla: yes

#3443 Only retry transactions on non-permanent errors
  Firestore/Example/Tests/Integration/FSTTransactionTests.mm
  Firestore/Source/API/FIRFirestore.mm
  Firestore/Source/Core/FSTSyncEngine.mm
  Firestore/core/src/firebase/firestore/core/transaction.h
  Firestore/core/src/firebase/firestore/core/transaction.mm
Labels: api: firestore, cla: yes

#3433 Split a cron sub-job to mitigate timeout failures
  .travis.yml
Labels: cla: yes

#3437 FirebaseApp: send Core Diagnostics data on appDidBecomeActive
  Example/Core/Tests/FIRAppTest.m
  Firebase/Core/FIRApp.m
  Firebase/Core/FIRCoreDiagnosticsConnector.m
  Firebase/Core/Private/FIRCoreDiagnosticsConnector.h
Labels: cla: yes

#3444 FIRInstallations: use lazy initialization
  FirebaseInstallations/Source/Library/FIRInstallations.m
Labels: cla: yes

#3456 Adding missing pods to the M53 release
  FirebaseDynamicLinks.podspec
  FirebaseInAppMessaging.podspec
  Releases/Manifests/6.6.0.json
Labels: cla: yes

#3452 providerID should be nil in additionalUserInfo for signInAnonymouslyWithCompletion:
  Example/Auth/Tests/FIRAuthTests.m
  Firebase/Auth/Source/Auth/FIRAuth.m
Labels: cla: yes

#3446 fix for signInProvider property of FIRAuthTokenResult returning nil
  Example/Auth/Tests/FIRUserTests.m
  Firebase/Auth/Source/User/FIRUser.m
Labels: cla: yes

#3461 Changing the Zip Builder to support the new open-source FirebaseCoreD…
  ZipBuilder/README.md
  ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
  ZipBuilder/Sources/ZipBuilder/LaunchArgs.swift
  ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
  ZipBuilder/Sources/ZipBuilder/main.swift
Labels: cla: yes

#3459 Declare dependency on AppKit to fix Firestore build
  FirebaseCore.podspec
Labels: api: core, cla: yes

#3463 Update to latest version of FirebaseAnalyticsInterop
  Example/DynamicLinks/Tests/FIRDLScionLoggingTest.m
  Example/Messaging/Tests/FIRMessagingAnalyticsTest.m
  FirebaseAnalyticsInterop.podspec
  InAppMessaging/Example/Tests/FIRIAMAnalyticsEventLoggerImplTests.m
  Interop/Analytics/Public/FIRAnalyticsInterop.h
Labels: cla: yes

#3466 [docs] fix syntax errors & enable highlighting
  Interop/FirebaseComponentSystem.md
Labels: cla: yes

#3458 Remove vector_of_ptr
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/core/src/firebase/firestore/api/query_core.mm
  Firestore/core/src/firebase/firestore/core/query.cc
  Firestore/core/src/firebase/firestore/core/query.h
  Firestore/core/src/firebase/firestore/util/CMakeLists.txt
  Firestore/core/src/firebase/firestore/util/vector_of_ptr.h
  Firestore/core/test/firebase/firestore/util/CMakeLists.txt
  Firestore/core/test/firebase/firestore/util/vector_of_ptr_test.cc
Labels: api: firestore, cla: yes

#3470 Fix flaky integration test
  Firestore/Example/Tests/Integration/FSTTransactionTests.mm
Labels: api: firestore, cla: yes

#3469 Simplify the wifi vs. mobile data connection code.
  GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m
Labels: cla: yes

#3300 GULObjectSwizzler fix dealloc thread safety
  GoogleUtilities.podspec
  GoogleUtilities/Example/Tests/Swizzler/GULObjectSwizzlerTest.m
  GoogleUtilities/ISASwizzler/GULObjectSwizzler+Internal.h
  GoogleUtilities/ISASwizzler/GULObjectSwizzler.m
  GoogleUtilities/ISASwizzler/GULSwizzledObject.m
Labels: cla: yes

#3472 Update CHANGELOG for Firestore v1.4.3
  Firestore/CHANGELOG.md
Labels: api: firestore, cla: yes

#3438 Always call getToken before subscription/unsubscription
  Example/Messaging/Tests/FIRMessagingServiceTest.m
  Firebase/Messaging/FIRMessaging.m
  Firebase/Messaging/Public/FIRMessaging.h
Labels: cla: yes

#3464 update CHANGELog for Messaging
  Firebase/Messaging/CHANGELOG.md
Labels: cla: yes

#3462 Clean up changelogs
  Firebase/Auth/CHANGELOG.md
  Firebase/CoreDiagnostics/CHANGELOG.md
  Firebase/DynamicLinks/CHANGELOG.md
  Firebase/InAppMessaging/CHANGELOG.md
  Firebase/InAppMessagingDisplay/CHANGELOG.md
  Firebase/InstanceID/CHANGELOG.md
  Firebase/Messaging/CHANGELOG.md
  Functions/CHANGELOG.md
Labels: cla: yes

#3460 Rename `FirestoreErrorCode` to just `Error`
  Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
  Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.h
  Firestore/Example/Tests/Local/FSTLevelDBMigrationsTests.mm
  Firestore/Example/Tests/Local/FSTMemoryLRUGarbageCollectorTests.mm
  Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/Source/Core/FSTSyncEngine.mm
  Firestore/Source/Local/FSTLevelDB.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/include/firebase/firestore/firestore_errors.h
  Firestore/core/src/firebase/firestore/api/document_reference.mm
  Firestore/core/src/firebase/firestore/api/firestore.mm
  Firestore/core/src/firebase/firestore/api/query_core.mm
  Firestore/core/src/firebase/firestore/auth/firebase_credentials_provider_apple.mm
  Firestore/core/src/firebase/firestore/core/transaction.mm
  Firestore/core/src/firebase/firestore/local/leveldb_util.cc
  Firestore/core/src/firebase/firestore/nanopb/reader.h
  Firestore/core/src/firebase/firestore/remote/datastore.mm
  Firestore/core/src/firebase/firestore/remote/grpc_connection.cc
  Firestore/core/src/firebase/firestore/remote/grpc_util.cc
  Firestore/core/src/firebase/firestore/remote/remote_objc_bridge.mm
  Firestore/core/src/firebase/firestore/remote/stream.mm
  Firestore/core/src/firebase/firestore/util/error_apple.mm
  Firestore/core/src/firebase/firestore/util/filesystem_common.cc
  Firestore/core/src/firebase/firestore/util/filesystem_posix.cc
  Firestore/core/src/firebase/firestore/util/filesystem_win.cc
  Firestore/core/src/firebase/firestore/util/status.cc
  Firestore/core/src/firebase/firestore/util/status.h
  Firestore/core/src/firebase/firestore/util/status_apple.mm
  Firestore/core/src/firebase/firestore/util/status_posix.cc
  Firestore/core/src/firebase/firestore/util/status_win.cc
  Firestore/core/src/firebase/firestore/util/statusor.cc
  Firestore/core/src/firebase/firestore/util/statusor.h
  Firestore/core/test/firebase/firestore/local/leveldb_util_test.cc
  Firestore/core/test/firebase/firestore/remote/datastore_test.mm
  Firestore/core/test/firebase/firestore/remote/grpc_connection_test.cc
  Firestore/core/test/firebase/firestore/remote/grpc_stream_test.cc
  Firestore/core/test/firebase/firestore/remote/grpc_streaming_reader_test.cc
  Firestore/core/test/firebase/firestore/remote/grpc_unary_call_test.cc
  Firestore/core/test/firebase/firestore/remote/serializer_test.cc
  Firestore/core/test/firebase/firestore/remote/stream_test.mm
  Firestore/core/test/firebase/firestore/testutil/xcgmock_test.mm
  Firestore/core/test/firebase/firestore/util/fake_credentials_provider.cc
  Firestore/core/test/firebase/firestore/util/filesystem_test.cc
  Firestore/core/test/firebase/firestore/util/grpc_stream_tester.cc
  Firestore/core/test/firebase/firestore/util/grpc_stream_tester.h
  Firestore/core/test/firebase/firestore/util/status_apple_test.mm
  Firestore/core/test/firebase/firestore/util/status_test.cc
  Firestore/core/test/firebase/firestore/util/status_testing.h
  Firestore/core/test/firebase/firestore/util/statusor_test.cc
Labels: api: firestore, cla: yes

#3475 GoogleUtilities - M53 version bump and changelog
  GoogleUtilities.podspec
  GoogleUtilities/CHANGELOG.md
Labels: cla: yes

#3473 Unify naming of keychain services and user defaults
  Example/Auth/Tests/FIRAuthAppCredentialManagerTests.m
  Example/Auth/Tests/FIRAuthKeychainServicesTests.m
  Example/Auth/Tests/FIRAuthUserDefaultsTests.m
  Example/Firebase.xcodeproj/project.pbxproj
  Firebase/Auth/Source/Auth/FIRAuth.m
  Firebase/Auth/Source/Storage/FIRAuthKeychainServices.h
  Firebase/Auth/Source/Storage/FIRAuthKeychainServices.m
  Firebase/Auth/Source/Storage/FIRAuthUserDefaults.h
  Firebase/Auth/Source/Storage/FIRAuthUserDefaults.m
  Firebase/Auth/Source/SystemService/FIRAuthAppCredentialManager.h
  Firebase/Auth/Source/SystemService/FIRAuthAppCredentialManager.m
  Firebase/Auth/Source/SystemService/FIRAuthStoredUserManager.h
  Firebase/Auth/Source/SystemService/FIRAuthStoredUserManager.m
  Firebase/Auth/Source/SystemService/FIRSecureTokenService.m
Labels: cla: yes

#3474 Add missing doc comments to Timestamp and GeoPoint to appease linter
  Firestore/core/include/firebase/firestore/geo_point.h
  Firestore/core/include/firebase/firestore/timestamp.h
  Firestore/core/src/firebase/firestore/geo_point.cc
Labels: api: firestore, cla: yes

#3465 Fix crash in FIRInstanceID
  Firebase/InstanceID/FIRIMessageCode.h
  Firebase/InstanceID/FIRInstanceID.m
Labels: cla: yes

#3468 Port FSTSortOrder to C++ OrderBy
  Firestore/Example/Tests/Core/FSTQueryTests.mm
  Firestore/Example/Tests/Core/FSTViewTests.mm
  Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Example/Tests/Util/FSTHelpers.h
  Firestore/Example/Tests/Util/FSTHelpers.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/Core/FSTQuery.h
  Firestore/Source/Core/FSTQuery.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/api/query_core.mm
  Firestore/core/src/firebase/firestore/core/CMakeLists.txt
  Firestore/core/src/firebase/firestore/core/direction.cc
  Firestore/core/src/firebase/firestore/core/direction.h
  Firestore/core/src/firebase/firestore/core/order_by.cc
  Firestore/core/src/firebase/firestore/core/order_by.h
  Firestore/core/src/firebase/firestore/core/query.cc
  Firestore/core/src/firebase/firestore/core/query.h
  Firestore/core/test/firebase/firestore/testutil/testutil.h
  Firestore/core/test/firebase/firestore/testutil/xcgmock.h
Labels: api: firestore, cla: yes

#3480 Update InstanceID changelog
  Firebase/InstanceID/CHANGELOG.md
Labels: cla: yes
