Repository firebase/firebase-ios-sdk, pull requests merged in 2019-06, with the labels that each got.

#3121 Fix -[FIRGeoPoint compare:] analysis warning
  Firestore/Source/API/FIRGeoPoint.mm
Labels: api: firestore, cla: yes

#3101 Fix FIAM test flakes and exposed library bugs
  Firebase/InAppMessaging/Analytics/FIRIAMClearcutLogStorage.h
  Firebase/InAppMessaging/Analytics/FIRIAMClearcutLogStorage.m
  Firebase/InAppMessaging/Analytics/FIRIAMClearcutUploader.m
  InAppMessaging/Example/Tests/FIRIAMClearcutUploaderTests.m
Labels: api: inappmessaging, cla: yes

#3124 Use CocoaPods CDN
  .travis.yml
  Example/Podfile
  Firestore/Example/Podfile
  InAppMessaging/Example/Podfile
  InAppMessagingDisplay/Example/Podfile
  SymbolCollisionTest/Podfile
  scripts/build.sh
  scripts/install_prereqs.sh
  scripts/pod_lib_lint.rb
Labels: cla: yes

#3125 Update AccountInfoTests.m
  Example/Auth/ApiTests/AccountInfoTests.m
Labels: cla: yes

#3128 Disable Auth api tests
  scripts/build.sh
Labels: cla: yes

#3133 Fix Xcode 11 build warning
  GoogleUtilities/Logger/GULLogger.m
Labels: cla: yes

#3119 Use ByteString in nanopb::Reader/Writer
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/FuzzTests/FuzzingTargets/FSTFuzzTestSerializer.mm
  Firestore/core/src/firebase/firestore/local/leveldb_migrations.cc
  Firestore/core/src/firebase/firestore/nanopb/reader.cc
  Firestore/core/src/firebase/firestore/nanopb/reader.h
  Firestore/core/src/firebase/firestore/nanopb/writer.cc
  Firestore/core/src/firebase/firestore/nanopb/writer.h
  Firestore/core/src/firebase/firestore/remote/serializer.cc
  Firestore/core/test/firebase/firestore/local/local_serializer_test.cc
  Firestore/core/test/firebase/firestore/nanopb/CMakeLists.txt
  Firestore/core/test/firebase/firestore/nanopb/nanopb_testing.h
  Firestore/core/test/firebase/firestore/remote/serializer_test.cc
Labels: api: firestore, cla: yes

#3131 Make pod gen related scripts git repo dir relative
  GoogleDataTransport/generate_project.sh
  GoogleDataTransportCCTSupport/ProtoSupport/generate_cct_protos.sh
  GoogleDataTransportCCTSupport/generate_project.sh
Labels: cla: yes

#3127 Basic Keychain storage
  .travis.yml
  FirebaseInstallations.podspec
  FirebaseInstallations/Source/Library/Example.m
  FirebaseInstallations/Source/Library/FIRInstallationsErrorUtil.h
  FirebaseInstallations/Source/Library/FIRInstallationsErrorUtil.m
  FirebaseInstallations/Source/Library/FIRSecureStorage.h
  FirebaseInstallations/Source/Library/FIRSecureStorage.m
  FirebaseInstallations/Source/Library/Public/Example.h
  FirebaseInstallations/Source/Tests/FIRSecureStorageTests.m
Labels: cla: yes

#3134 Update versions for Release 6.2.0
  Example/Podfile
  FirebaseAuth.podspec
  FirebaseCore.podspec
  FirebaseFirestore.podspec
  FirebaseInstanceID.podspec
  FirebaseMessaging.podspec
  Firestore/Example/Podfile
  Releases/Manifests/6.2.0.json
  SymbolCollisionTest/Podfile
Labels: cla: yes

#3137 Add a getter for Firestore pointer to api::WriteBatch
  Firestore/core/src/firebase/firestore/api/write_batch.h
Labels: api: firestore, cla: yes

#3139 Update FIRActionCodeSettings.h
  Firebase/Auth/Source/Public/FIRActionCodeSettings.h
  Firebase/Auth/Source/Public/FIRAuth.h
  Firebase/Auth/Source/Public/FIRAuthErrors.h
  Firebase/Auth/Source/Public/FIREmailAuthProvider.h
Labels: cla: yes

#3138 Raise exception when log into Facebook using OAuth.
  Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthProvider.m
Labels: cla: yes

#3140 Add Sign in with GitHub headful lite to sample app
  Example/Auth/Sample/MainViewController+Internal.h
  Example/Auth/Sample/MainViewController+OAuth.m
  Example/Auth/Sample/MainViewController.m
Labels: cla: yes

#3142 Fix >100 character line
  Firebase/Messaging/Public/FIRMessaging.h
Labels: api: messaging, cla: yes

#3143 Exclude pod gen output from style.sh
  scripts/style.sh
Labels: cla: yes

#3126 Port FIRCollectionReference to C++
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/API/FSTAPIHelpers.mm
  Firestore/Source/API/FIRCollectionReference+Internal.h
  Firestore/Source/API/FIRCollectionReference.mm
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRFirestore.mm
  Firestore/Source/API/FIRQuery+Internal.h
  Firestore/Source/API/FIRQuery.mm
  Firestore/core/src/firebase/firestore/api/CMakeLists.txt
  Firestore/core/src/firebase/firestore/api/collection_reference.h
  Firestore/core/src/firebase/firestore/api/collection_reference.mm
  Firestore/core/src/firebase/firestore/api/document_reference.h
  Firestore/core/src/firebase/firestore/api/document_reference.mm
  Firestore/core/src/firebase/firestore/api/firestore.h
  Firestore/core/src/firebase/firestore/api/firestore.mm
  Firestore/core/src/firebase/firestore/api/query_core.h
  Firestore/core/src/firebase/firestore/api/query_core.mm
  Firestore/core/test/firebase/firestore/api/cc_compilation_test.cc
Labels: api: firestore, cla: yes

#3141 Fix builds with GCC/Linux
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/core/src/firebase/firestore/remote/grpc_connection.cc
  Firestore/core/test/firebase/firestore/util/CMakeLists.txt
  Firestore/core/test/firebase/firestore/util/ordered_code_benchmark.cc
  cmake/cc_rules.cmake
Labels: api: firestore, cla: yes

#3135 FIS Public API
  .travis.yml
  FirebaseInstallations/Source/Library/FIRInstallations.m
  FirebaseInstallations/Source/Library/FIRInstallationsAuthTokenResult.m
  FirebaseInstallations/Source/Library/FIRInstallationsAuthTokenResultInternal.h
  FirebaseInstallations/Source/Library/FIRInstallationsVersion.m
  FirebaseInstallations/Source/Library/FIRSecureStorage.m
  FirebaseInstallations/Source/Library/Public/FIRInstallations.h
  FirebaseInstallations/Source/Library/Public/FIRInstallationsAuthTokenResult.h
  FirebaseInstallations/Source/Library/Public/FIRInstallationsVersion.h
  FirebaseInstallations/Source/Tests/FIRInstallationsTests.m
Labels: cla: yes

#3026 Move clearPersistence() from internal to FIRFirestore
  Firestore/CHANGELOG.md
  Firestore/Source/API/FIRFirestore+Internal.h
  Firestore/Source/API/FIRFirestore.mm
  Firestore/Source/Public/FIRFirestore.h
  Firestore/Swift/Tests/API/BasicCompileTests.swift
Labels: api: firestore, cla: yes

#3123 Add FirebaseAuth test_spec
  .travis.yml
  Example/Auth/AuthSample/AuthSample.xcodeproj/project.pbxproj
  Example/Auth/AuthSample/AuthSample.xcodeproj/xcshareddata/xcschemes/AuthSample.xcscheme
  Example/Auth/AuthSample/AuthSample.xcodeproj/xcshareddata/xcschemes/Auth_ApiTests.xcscheme
  Example/Auth/AuthSample/AuthSample.xcodeproj/xcshareddata/xcschemes/Auth_E2eTests.xcscheme
  Example/Auth/AuthSample/Podfile
  Example/Auth/Tests/FIRAuthAPNSTokenManagerTests.m
  Example/Auth/Tests/FIRAuthTests.m
  Example/Auth/Tests/FIRAuthURLPresenterTests.m
  Example/Auth/Tests/FIRUserTests.m
  FirebaseAuth.podspec
  scripts/build.sh
  scripts/if_changed.sh
  scripts/install_prereqs.sh
Labels: api: auth, cla: yes

#3150 Clean the derived data between builds to help reduce flakiness
  scripts/build.sh
Labels: cla: yes

#3130 Migrate FSTBlobValue to FSTDelegateValue
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/API/FSTUserDataConverterTests.mm
  Firestore/Example/Tests/Model/FSTFieldValueTests.mm
  Firestore/Source/API/FSTUserDataConverter.mm
  Firestore/Source/Model/FSTFieldValue.h
  Firestore/Source/Model/FSTFieldValue.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/api/CMakeLists.txt
  Firestore/core/src/firebase/firestore/auth/CMakeLists.txt
  Firestore/core/src/firebase/firestore/local/local_serializer.cc
  Firestore/core/src/firebase/firestore/local/query_data.cc
  Firestore/core/src/firebase/firestore/local/query_data.h
  Firestore/core/src/firebase/firestore/model/CMakeLists.txt
  Firestore/core/src/firebase/firestore/model/field_value.cc
  Firestore/core/src/firebase/firestore/model/field_value.h
  Firestore/core/src/firebase/firestore/nanopb/CMakeLists.txt
  Firestore/core/src/firebase/firestore/nanopb/byte_string.cc
  Firestore/core/src/firebase/firestore/nanopb/byte_string.h
  Firestore/core/src/firebase/firestore/nanopb/nanopb_util.cc
  Firestore/core/src/firebase/firestore/nanopb/nanopb_util.h
  Firestore/core/src/firebase/firestore/nanopb/writer.cc
  Firestore/core/src/firebase/firestore/nanopb/writer.h
  Firestore/core/src/firebase/firestore/remote/serializer.cc
  Firestore/core/src/firebase/firestore/remote/serializer.h
  Firestore/core/src/firebase/firestore/util/comparison.cc
  Firestore/core/src/firebase/firestore/util/comparison.h
  Firestore/core/test/firebase/firestore/core/CMakeLists.txt
  Firestore/core/test/firebase/firestore/local/local_serializer_test.cc
  Firestore/core/test/firebase/firestore/model/field_value_test.cc
  Firestore/core/test/firebase/firestore/nanopb/CMakeLists.txt
  Firestore/core/test/firebase/firestore/nanopb/byte_string_test.cc
  Firestore/core/test/firebase/firestore/nanopb/nanopb_testing.h
  Firestore/core/test/firebase/firestore/nanopb/writer_test.cc
  Firestore/core/test/firebase/firestore/remote/serializer_test.cc
  Firestore/core/test/firebase/firestore/testutil/CMakeLists.txt
  Firestore/core/test/firebase/firestore/testutil/testutil.h
  Firestore/core/test/firebase/firestore/testutil/xcgmock.h
Labels: api: firestore, cla: yes

#3132 correct timezone proto key
  Firebase/InstanceID/FIRInstanceIDCheckinService.m
Labels: cla: yes

#3157 Local FID generating
  FirebaseInstallations.podspec
  FirebaseInstallations/Source/Library/FIRInstallations.m
  FirebaseInstallations/Source/Library/FIRInstallationsItem.h
  FirebaseInstallations/Source/Library/FIRInstallationsItem.m
  FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.h
  FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsIDController.m
  FirebaseInstallations/Source/Library/InstallationsIDController/FIRInstallationsStatus.h
  FirebaseInstallations/Source/Library/InstallationsStore/FIRInstallationsStoredItem.h
  FirebaseInstallations/Source/Tests/FIRInstallationsIDControllerTests.m
  FirebaseInstallations/Source/Tests/FIRInstallationsItemTests.m
  FirebaseInstallations/Source/Tests/FIRInstallationsStoreTests.m
  FirebaseInstallations/Source/Tests/FIRInstallationsTests.m
  FirebaseInstallations/Source/Tests/Utils/FIRInstallationsItem+Tests.h
  FirebaseInstallations/Source/Tests/Utils/FIRInstallationsItem+Tests.m
Labels: cla: yes

#3154 Add support for suppressing -Wcomma
  Firestore/core/src/firebase/firestore/util/warnings.h
Labels: api: firestore, cla: yes

#3164 Disable warnings in the Abseil build
  Firestore/third_party/abseil-cpp/absl/copts/GENERATED_AbseilCopts.cmake
  Firestore/third_party/abseil-cpp/absl/copts/GENERATED_copts.bzl
  Firestore/third_party/abseil-cpp/absl/copts/copts.py
Labels: api: firestore, cla: yes

#3166 Disable CocoaPods CDN in pod installs (#3165)
  Example/Auth/AuthSample/Podfile
  Example/Podfile
  Firestore/Example/Podfile
  InAppMessaging/Example/Podfile
  InAppMessagingDisplay/Example/Podfile
  SymbolCollisionTest/Podfile
  scripts/install_prereqs.sh
  scripts/pod_lib_lint.rb
Labels: cla: yes

#3155 Prep for FIRTimestampValue migration to C++
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/core/include/firebase/firestore/timestamp.h
  Firestore/core/src/firebase/firestore/CMakeLists.txt
  Firestore/core/src/firebase/firestore/model/field_value.cc
  Firestore/core/src/firebase/firestore/timestamp.cc
  Firestore/core/src/firebase/firestore/timestamp_internal.cc
  Firestore/core/src/firebase/firestore/timestamp_internal.h
  Firestore/core/test/firebase/firestore/CMakeLists.txt
  Firestore/core/test/firebase/firestore/model/field_value_test.cc
  Firestore/core/test/firebase/firestore/testutil/CMakeLists.txt
  Firestore/core/test/firebase/firestore/testutil/time_testing.cc
  Firestore/core/test/firebase/firestore/testutil/time_testing.h
  Firestore/core/test/firebase/firestore/timestamp_test.cc
  cmake/cc_rules.cmake
  cmake/compiler_setup.cmake
Labels: api: firestore, cla: yes

#3169 Update CHANGELOG for Firestore v1.4.0
  Firestore/CHANGELOG.md
Labels: api: firestore, cla: yes

#3156 Use C++ Timestamp internally instead of FIRTimestamp
  Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
  Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm
  Firestore/Example/Tests/Local/FSTLocalSerializerTests.mm
  Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
  Firestore/Example/Tests/Local/FSTMutationQueueTests.mm
  Firestore/Example/Tests/Model/FSTFieldValueTests.mm
  Firestore/Example/Tests/Model/FSTMutationTests.mm
  Firestore/Example/Tests/Model/transform_operations_test.mm
  Firestore/Source/API/FSTUserDataConverter.h
  Firestore/Source/API/FSTUserDataConverter.mm
  Firestore/Source/API/converters.h
  Firestore/Source/API/converters.mm
  Firestore/Source/Local/FSTLocalSerializer.mm
  Firestore/Source/Local/FSTLocalStore.mm
  Firestore/Source/Model/FSTFieldValue.h
  Firestore/Source/Model/FSTFieldValue.mm
  Firestore/Source/Model/FSTMutation.h
  Firestore/Source/Model/FSTMutation.mm
  Firestore/Source/Model/FSTMutationBatch.h
  Firestore/Source/Model/FSTMutationBatch.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/local/leveldb_mutation_queue.h
  Firestore/core/src/firebase/firestore/local/leveldb_mutation_queue.mm
  Firestore/core/src/firebase/firestore/local/memory_mutation_queue.h
  Firestore/core/src/firebase/firestore/local/memory_mutation_queue.mm
  Firestore/core/src/firebase/firestore/local/mutation_queue.h
  Firestore/core/src/firebase/firestore/model/transform_operations.h
Labels: api: firestore, cla: yes

#3171 Upgrade to Firestore Emulator 1.5.0
  Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
  Firestore/Example/Tests/Integration/API/FIRFieldsTests.mm
  Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
  Firestore/Example/Tests/Integration/API/FIRWriteBatchTests.mm
  Firestore/Example/Tests/Integration/FSTTransactionTests.mm
  scripts/run_firestore_emulator.sh
Labels: api: firestore, cla: yes

#3170 Migrate FSTTimestampValue to FSTDelegateValue
  Firestore/Example/Tests/API/FSTUserDataConverterTests.mm
  Firestore/Example/Tests/Model/FSTFieldValueTests.mm
  Firestore/Example/Tests/Model/FSTMutationTests.mm
  Firestore/Source/API/FSTUserDataConverter.mm
  Firestore/Source/Model/FSTFieldValue.h
  Firestore/Source/Model/FSTFieldValue.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/test/firebase/firestore/testutil/xcgmock.h
Labels: api: firestore, cla: yes

#3172 Update CHANGELOG.md
  Firebase/Auth/CHANGELOG.md
Labels: cla: yes

#3175 update changelog and fix a format issue in firestore
  Firebase/InstanceID/CHANGELOG.md
  Firebase/Messaging/CHANGELOG.md
  Firestore/core/src/firebase/firestore/remote/connectivity_monitor_noop.cc
  README.md
Labels: cla: yes

#3182 Remove Yahoo and Microsoft provider ID.
  Firebase/Auth/Source/AuthProvider/FIRAuthProvider.m
Labels: cla: yes

#3187 Deprecate initializers for FIAM view model objects
  Firebase/InAppMessaging/Flows/FIRIAMDisplayExecutor.m
  Firebase/InAppMessaging/Public/FIRInAppMessagingRendering.h
  Firebase/InAppMessaging/RenderingObjects/FIRInAppMessagingRenderingDataClasses.m
  Firebase/InAppMessaging/RenderingObjects/FIRInAppMessagingRenderingPrivate.h
  Firebase/InAppMessagingDisplay/Banner/FIDBannerViewController.m
  Firebase/InAppMessagingDisplay/Card/FIDCardViewController.m
  Firebase/InAppMessagingDisplay/ImageOnly/FIDImageOnlyViewController.m
  Firebase/InAppMessagingDisplay/Modal/FIDModalViewController.m
Labels: cla: yes

#3177 Migrate FSTReferenceValue to FSTDelegateValue
  Firestore/Example/Tests/API/FSTUserDataConverterTests.mm
  Firestore/Example/Tests/Model/FSTFieldValueTests.mm
  Firestore/Source/API/FIRDocumentSnapshot.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/API/FSTUserDataConverter.mm
  Firestore/Source/Core/FSTQuery.mm
  Firestore/Source/Model/FSTFieldValue.h
  Firestore/Source/Model/FSTFieldValue.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/api/query_core.mm
  Firestore/core/src/firebase/firestore/model/field_value.cc
  Firestore/core/src/firebase/firestore/model/field_value.h
  Firestore/core/test/firebase/firestore/testutil/xcgmock.h
Labels: api: firestore, cla: yes

#3161 Rewrite lint.sh as check_lint.py
  .gitignore
  .travis.yml
  Firestore/Example/Benchmarks/FSTLevelDBBenchmarkTests.mm
  scripts/binary_to_array.py
  scripts/check.sh
  scripts/check_lint.py
  scripts/check_test_inclusion.py
  scripts/lib/__init__.py
  scripts/lib/checker.py
  scripts/lib/command_trace.py
  scripts/lib/git.py
  scripts/lib/source.py
  scripts/lib/terminal.py
  scripts/lint.sh
  tox.ini
Labels: api: firestore, cla: yes

#3190 Actually change to NotImplementedError
  scripts/lib/source.py
Labels: api: firestore, cla: yes

#3188 Defend against nil bundle identifiers
  Firestore/core/src/firebase/firestore/remote/grpc_root_certificate_finder_apple.mm
Labels: api: firestore, cla: yes

#3191 Fixing Analysis issue in Storage
  Firebase/Storage/FIRStorageListTask.m
Labels: cla: yes

#3196 CocoaPods 1.7.2
  Gemfile
  Gemfile.lock
Labels: cla: yes

#3201 Require flake8 to actually be on the path.
  scripts/check_lint.py
Labels: api: firestore, cla: yes

#3202 Clean up documentation to conform to Jazzy doc style
  Firebase/InAppMessaging/Public/FIRInAppMessagingRendering.h
  Firebase/InAppMessagingDisplay/Public/FIRIAMDefaultDisplayImpl.h
Labels: cla: yes

#3208 Revert "Raise exception when log into Facebook using OAuth. (#3138)"
  Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthProvider.m
Labels: cla: yes

#3209 Cherry-pick a reverted Auth PR
  Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthProvider.m
Labels: cla: yes

#3178 Finish migration of FSTFieldValue to C++ FieldValue
  Firestore/CMakeLists.txt
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/API/FSTUserDataConverterTests.mm
  Firestore/Example/Tests/Core/FSTViewTests.mm
  Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
  Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm
  Firestore/Example/Tests/Local/FSTLocalSerializerTests.mm
  Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
  Firestore/Example/Tests/Model/FSTDocumentTests.mm
  Firestore/Example/Tests/Model/FSTFieldValueTests.mm
  Firestore/Example/Tests/Model/FSTMutationTests.mm
  Firestore/Example/Tests/Model/transform_operations_test.mm
  Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Example/Tests/Util/FSTHelpers.h
  Firestore/Example/Tests/Util/FSTHelpers.mm
  Firestore/Source/API/CMakeLists.txt
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRDocumentSnapshot.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/API/FSTUserDataConverter.h
  Firestore/Source/API/FSTUserDataConverter.mm
  Firestore/Source/CMakeLists.txt
  Firestore/Source/Core/FSTQuery.h
  Firestore/Source/Core/FSTQuery.mm
  Firestore/Source/Core/FSTView.mm
  Firestore/Source/Local/FSTLocalSerializer.mm
  Firestore/Source/Local/FSTLocalStore.mm
  Firestore/Source/Model/CMakeLists.txt
  Firestore/Source/Model/FSTDocument.h
  Firestore/Source/Model/FSTDocument.mm
  Firestore/Source/Model/FSTFieldValue.h
  Firestore/Source/Model/FSTFieldValue.mm
  Firestore/Source/Model/FSTMutation.h
  Firestore/Source/Model/FSTMutation.mm
  Firestore/Source/Remote/FSTSerializerBeta.h
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/api/document_snapshot.h
  Firestore/core/src/firebase/firestore/api/document_snapshot.mm
  Firestore/core/src/firebase/firestore/api/query_core.h
  Firestore/core/src/firebase/firestore/api/query_core.mm
  Firestore/core/src/firebase/firestore/core/user_data.h
  Firestore/core/src/firebase/firestore/core/user_data.mm
  Firestore/core/src/firebase/firestore/model/CMakeLists.txt
  Firestore/core/src/firebase/firestore/model/field_mask.cc
  Firestore/core/src/firebase/firestore/model/field_mask.h
  Firestore/core/src/firebase/firestore/model/field_value.cc
  Firestore/core/src/firebase/firestore/model/field_value.h
  Firestore/core/src/firebase/firestore/model/field_value.mm
  Firestore/core/src/firebase/firestore/model/transform_operations.h
  Firestore/core/src/firebase/firestore/model/transform_operations.mm
  Firestore/core/test/firebase/firestore/model/field_value_test.cc
  Firestore/core/test/firebase/firestore/testutil/xcgmock.h
  Firestore/third_party/Immutable/CMakeLists.txt
Labels: api: firestore, cla: yes

#3203 Delete FSTDocumentKey
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/Model/FSTDocumentKeyTests.mm
  Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.h
  Firestore/Source/Model/FSTDocumentKey.h
  Firestore/Source/Model/FSTDocumentKey.mm
  Firestore/core/test/firebase/firestore/testutil/xcgmock.h
Labels: api: firestore, cla: yes

#3198 Firestore swift Codable support
  .gitignore
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Swift/Source/Codable/CodableErrors.swift
  Firestore/Swift/Source/Codable/CodablePassThroughTypes.swift
  Firestore/Swift/Source/Codable/GeoPoint+Codable.swift
  Firestore/Swift/Source/Codable/Timestamp+Codable.swift
  Firestore/Swift/Source/Codable/third_party/FirestoreDecoder.swift
  Firestore/Swift/Source/Codable/third_party/FirestoreEncoder.swift
  Firestore/Swift/Tests/API/BasicCompileTests.swift
  Firestore/Swift/Tests/BridgingHeader.h
  Firestore/Swift/Tests/Codable/CodableTimestampTests.swift
  Firestore/Swift/Tests/Codable/FirestoreEncoderTests.swift
  scripts/style.sh
Labels: cla: yes

#3213 Remove NSLog call in FIRDocumentSnapshot
  Firestore/Source/API/FIRDocumentSnapshot.mm
Labels: api: firestore, cla: yes

#3218 Silence InAppMessaging warnings on Xcode 11
  Firebase/InAppMessaging/Runtime/FIRIAMSDKModeManager.m
Labels: cla: yes

#3222 Fix small compilation and linter issues
  Firestore/Example/Tests/API/FSTUserDataConverterTests.mm
  Firestore/Source/API/FIRDocumentSnapshot.mm
  Firestore/Source/Core/FSTQuery.mm
  Firestore/core/src/firebase/firestore/timestamp.cc
Labels: api: firestore, cla: yes

#3225 Migrate FSTDocumentState to C++ DocumentState
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/API/FIRQuerySnapshotTests.mm
  Firestore/Example/Tests/API/FSTAPIHelpers.mm
  Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
  Firestore/Example/Tests/Core/FSTQueryTests.mm
  Firestore/Example/Tests/Core/FSTViewSnapshotTest.mm
  Firestore/Example/Tests/Core/FSTViewTests.mm
  Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm
  Firestore/Example/Tests/Local/FSTLocalSerializerTests.mm
  Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
  Firestore/Example/Tests/Local/FSTRemoteDocumentCacheTests.mm
  Firestore/Example/Tests/Model/FSTDocumentSetTests.mm
  Firestore/Example/Tests/Model/FSTDocumentTests.mm
  Firestore/Example/Tests/Model/FSTMutationTests.mm
  Firestore/Example/Tests/Remote/FSTRemoteEventTests.mm
  Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Example/Tests/Util/FSTHelpers.h
  Firestore/Example/Tests/Util/FSTHelpers.mm
  Firestore/Source/Local/FSTLocalSerializer.mm
  Firestore/Source/Model/FSTDocument.h
  Firestore/Source/Model/FSTDocument.mm
  Firestore/Source/Model/FSTMutation.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/model/document.h
  Firestore/core/test/firebase/firestore/remote/watch_change_test.mm
  Firestore/core/test/firebase/firestore/util/objc_compatibility_apple_test.mm
Labels: api: firestore, cla: yes

#3216 Handle newly removed `userInfo` property on tvOS.
  Firebase/Messaging/FIRMessagingExtensionHelper.m
Labels: cla: yes

#3232 Add `firestore()` method to `api::DocumentChange`
  Firestore/core/src/firebase/firestore/api/document_change.h
Labels: api: firestore, cla: yes

#3219 Build Core with SPM
  Firebase/Core/FIRApp.m
  Firebase/Core/FIRBundleUtil.m
  Firebase/Core/FIRLogger.m
  Firebase/Core/Private/FIRAppInternal.h
  Firebase/Core/Private/FIRLogger.h
  Firebase/Core/Private/FIROptionsInternal.h
  Firebase/Core/Public/FIRConfiguration.h
  FirebaseCore.podspec
  Package.swift
  Sources/firebase-test/main.swift
Labels: cla: yes

#3235 static library and c99
  Package.swift
Labels: cla: yes

#3236 Update instructions for getting swiftformat
  README.md
Labels: Infrastructure, cla: yes

#3244 Build and run storage on mac from SPM
  Firebase/Storage/FIRStorage.m
  Firebase/Storage/FIRStorageComponent.h
  Firebase/Storage/FIRStorageComponent.m
  Firebase/Storage/FIRStorageConstants_Private.h
  Firebase/Storage/FIRStorageDeleteTask.h
  Firebase/Storage/FIRStorageDownloadTask_Private.h
  Firebase/Storage/FIRStorageErrors.h
  Firebase/Storage/FIRStorageGetDownloadURLTask.h
  Firebase/Storage/FIRStorageGetDownloadURLTask_Private.h
  Firebase/Storage/FIRStorageGetMetadataTask.h
  Firebase/Storage/FIRStorageListResult_Private.h
  Firebase/Storage/FIRStorageListTask.h
  Firebase/Storage/FIRStorageMetadata_Private.h
  Firebase/Storage/FIRStorageObservableTask_Private.h
  Firebase/Storage/FIRStoragePath.h
  Firebase/Storage/FIRStorageReference.m
  Firebase/Storage/FIRStorageReference_Private.h
  Firebase/Storage/FIRStorageTask.m
  Firebase/Storage/FIRStorageTaskSnapshot_Private.h
  Firebase/Storage/FIRStorageTask_Private.h
  Firebase/Storage/FIRStorageTokenAuthorizer.h
  Firebase/Storage/FIRStorageTokenAuthorizer.m
  Firebase/Storage/FIRStorageUpdateMetadataTask.h
  Firebase/Storage/FIRStorageUploadTask.m
  Firebase/Storage/FIRStorageUploadTask_Private.h
  Firebase/Storage/FIRStorageUtils.h
  Firebase/Storage/FIRStorageUtils.m
  Firebase/Storage/FIRStorage_Private.h
  Package.swift
  Sources/firebase-test/main.swift
Labels: cla: yes

#3239 Fix keychain issues
  Firebase/Auth/Source/Auth/FIRAuth.m
  Firebase/Auth/Source/User/FIRUser.m
Labels: cla: yes

#3089 Expose authdataresult.credential.secret in public header.
  Firebase/Auth/Source/Auth/FIRAuthDataResult_Internal.h
  Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthCredential_Internal.h
  Firebase/Auth/Source/Public/FIRAuthDataResult.h
  Firebase/Auth/Source/Public/FIROAuthCredential.h
Labels: api: auth, cla: yes

#3248 GoogleDataTransport - recover app extensions support
  GoogleDataTransport/GDTLibrary/GDTPlatform.m
Labels: cla: yes

#3246 Change telemetry uploads to upload daily
  GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTPrioritizer.m
  GoogleDataTransportCCTSupport/GDTCCTTests/Unit/GDTCCTPrioritizerTest.m
Labels: cla: yes

#3240 Update the coverage collection to point to the prod database
  Metrics/Sources/Metrics/main.swift
  Metrics/Sources/MetricsLib/UploadMetrics.swift
  Metrics/Tests/MetricsTests/UploadMetricsTests.swift
  scripts/install_prereqs.sh
  scripts/travis-encrypted/Secrets.tar.enc
Labels: cla: yes

#3251 Fix token fetch not invoking callback for unchanged token
  Example/InstanceID/Tests/FIRInstanceIDTest.m
  Firebase/InstanceID/CHANGELOG.md
  Firebase/InstanceID/FIRInstanceID.m
  Firestore/Swift/Source/Codable/third_party/FirestoreEncoder.swift
Labels: cla: yes

#3254 Fix FIAM build break
  Firebase/InAppMessaging/FIRCore+InAppMessaging.m
  Firebase/InAppMessagingDisplay/FIRCore+InAppMessagingDisplay.m
Labels: cla: yes

#3257 Fix linker issue with deprecated CoreDiagnostics
  Firebase/Core/FIRApp.m
Labels: cla: yes

#3256 Update CHANGELOG for Firestore v1.4.1
  Firestore/CHANGELOG.md
Labels: api: firestore, cla: yes

#3258 M51 GoogleUtilities, Messaging and IID Changelogs
  Firebase/InstanceID/CHANGELOG.md
  Firebase/Messaging/CHANGELOG.md
  GoogleUtilities/CHANGELOG.md
Labels: cla: yes

#3262 Update CHANGELOG.md
  Firebase/Auth/CHANGELOG.md
Labels: cla: yes

#3249 Add a vector of pointers type
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/core/src/firebase/firestore/model/CMakeLists.txt
  Firestore/core/src/firebase/firestore/util/CMakeLists.txt
  Firestore/core/src/firebase/firestore/util/vector_of_ptr.h
  Firestore/core/test/firebase/firestore/util/CMakeLists.txt
  Firestore/core/test/firebase/firestore/util/vector_of_ptr_test.cc
Labels: api: firestore, cla: yes

#3265 GoogleUtilities bump version to 6.2.1
  GoogleUtilities.podspec
Labels: cla: yes

#3263 Fix indentation of database test helper class.
  Example/Database/Tests/Helpers/SenTest+FWaiter.m
Labels: cla: yes

#3264 Fix long line in Messaging library.
  Firebase/Messaging/FIRMessagingRemoteNotificationsProxy.m
Labels: cla: yes

#3237 Fix bug where app launch messages weren't appearing on iOS
  Firebase/InAppMessaging/Data/FIRIAMFetchResponseParser.m
  Firebase/InAppMessaging/Data/FIRIAMMessageDefinition.h
  Firebase/InAppMessaging/Data/FIRIAMMessageDefinition.m
  Firebase/InAppMessaging/DisplayTrigger/FIRIAMDisplayTriggerDefinition.h
  Firebase/InAppMessaging/DisplayTrigger/FIRIAMDisplayTriggerDefinition.m
  Firebase/InAppMessaging/Flows/FIRIAMDisplayExecutor.h
  Firebase/InAppMessaging/Flows/FIRIAMDisplayExecutor.m
  Firebase/InAppMessaging/Flows/FIRIAMFetchFlow.h
  Firebase/InAppMessaging/Flows/FIRIAMFetchFlow.m
  Firebase/InAppMessaging/Flows/FIRIAMFetchOnAppForegroundFlow.m
  Firebase/InAppMessaging/Flows/FIRIAMMessageClientCache.h
  Firebase/InAppMessaging/Flows/FIRIAMMessageClientCache.m
  Firebase/InAppMessaging/Runtime/FIRIAMRuntimeManager.m
  InAppMessaging/Example/Tests/FIRIAMFetchFlowTests.m
Labels: api: inappmessaging, cla: yes

#3266 Fix linker error
  .travis.yml
  Firebase/Core/FIRApp.m
Labels: cla: yes

#3267 Add support for expanding PODS_TARGET_SRCROOT in CMake
  CMakeLists.txt
  Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
  GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTPrioritizer.m
  cmake/podspec_cmake.rb
  cmake/podspec_rules.cmake
Labels: GoogleDataTransport, api: firestore, cla: yes

#3268 CMake fixes for GoogleDataTransport
  CMakeLists.txt
  cmake/podspec_cmake.rb
  cmake/podspec_rules.cmake
Labels: api: firestore, cla: yes

#3269 Work around duplicate nanopb symbols in gRPC build
  cmake/external/grpc.cmake
Labels: api: firestore, cla: yes

#3271 Reenable CocoaPods CDN
  Example/Auth/AuthSample/Podfile
  Example/Podfile
  Firestore/Example/Podfile
  InAppMessaging/Example/Podfile
  InAppMessagingDisplay/Example/Podfile
  SymbolCollisionTest/Podfile
  scripts/install_prereqs.sh
  scripts/pod_lib_lint.rb
Labels: cla: yes

#3272 pod repo update is incompatible with travis_wait
  scripts/pod_lib_lint.rb
Labels: cla: yes

#3273 Add additional field in firebasecore.proto
  Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m
  Firebase/CoreDiagnostics/FIRCDLibrary/Protogen/nanopb/firebasecore.nanopb.c
  Firebase/CoreDiagnostics/FIRCDLibrary/Protogen/nanopb/firebasecore.nanopb.h
  Firebase/CoreDiagnostics/ProtoSupport/Protos/firebasecore.proto
Labels: cla: yes

#3274 Rename WrapNSString to MakeNSString
  Firestore/Example/Tests/Integration/API/FIRWriteBatchTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Source/API/FIRCollectionReference.mm
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRDocumentSnapshot.mm
  Firestore/Source/API/FIRFirestore.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/api/input_validation_apple.mm
  Firestore/core/src/firebase/firestore/objc/objc_compatibility.h
  Firestore/core/src/firebase/firestore/util/error_apple.mm
  Firestore/core/src/firebase/firestore/util/hard_assert_apple.mm
  Firestore/core/src/firebase/firestore/util/path.h
  Firestore/core/src/firebase/firestore/util/string_apple.h
  Firestore/core/test/firebase/firestore/remote/datastore_test.mm
  Firestore/core/test/firebase/firestore/testutil/app_testing.mm
  Firestore/core/test/firebase/firestore/util/string_apple_test.mm
Labels: api: firestore, cla: yes

#3276 Unavailable init methods should not be nullable
  Firebase/Auth/Source/Backend/FIRAuthRequestConfiguration.h
  Firebase/Storage/Public/FIRStorageListResult.h
Labels: cla: yes

#3261 Allow firestore api to work with Codable objects + ExplicitNull + Integration tests
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Podfile
  Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.h
  Firestore/Source/Core/FSTTypes.h
  Firestore/Swift/Source/Codable/DocumentReference+WriteEncodable.swift
  Firestore/Swift/Source/Codable/DocumentSnapshot+ReadDecodable.swift
  Firestore/Swift/Source/Codable/ExplicitNull.swift
  Firestore/Swift/Source/Codable/Transaction+WriteEncodable.swift
  Firestore/Swift/Source/Codable/WriteBatch+WriteEncodable.swift
  Firestore/Swift/Source/Codable/third_party/FirestoreDecoder.swift
  Firestore/Swift/Source/Codable/third_party/FirestoreEncoder.swift
  Firestore/Swift/Tests/BridgingHeader.h
  Firestore/Swift/Tests/Codable/FirestoreEncoderTests.swift
  Firestore/Swift/Tests/Integration/CodableIntegrationTests.swift
  scripts/build.sh
Labels: api: firestore, cla: yes

#3280 Update to CocoaPods 1.7.3
  Gemfile
  Gemfile.lock
Labels: cla: yes
