Repository firebase/firebase-ios-sdk, pull requests merged in 2019-05, with the labels that each got.

#2912 Bump pod generate version to 1.4.1
  Gemfile
  Gemfile.lock
Labels: cla: yes

#2915 Use portable util/log.h instead of FIRLogger
  Firestore/Source/API/FIRFirestore.mm
  Firestore/core/src/firebase/firestore/util/log.h
  Firestore/core/src/firebase/firestore/util/log_apple.mm
Labels: api: firestore, cla: yes

#2916 Put secret and oauth credentials into the private headers for now.
  Firebase/Auth/Source/Auth/FIRAuthDataResult_Internal.h
  Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthCredential_Internal.h
  Firebase/Auth/Source/Public/FIRAuthDataResult.h
  Firebase/Auth/Source/Public/FIROAuthCredential.h
Labels: cla: yes

#2919 Cherrypick of PR/2916
  Firebase/Auth/Source/Auth/FIRAuthDataResult_Internal.h
  Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthCredential_Internal.h
  Firebase/Auth/Source/Public/FIRAuthDataResult.h
  Firebase/Auth/Source/Public/FIROAuthCredential.h
Labels: cla: yes

#2923 Revert "Add metrics secret to tar and install_prereqs script (#2904)"
  scripts/install_prereqs.sh
  scripts/travis-encrypted/Secrets.tar.enc
Labels: cla: yes

#2921 Add missing Messaging weak_framework dep
  FirebaseMessaging.podspec
Labels: api: messaging, cla: yes

#2917 Adding documentation for WriteBatch size limit
  Firestore/Source/Public/FIRFirestore.h
Labels: api: firestore, cla: yes

#2930 Add missing Messaging weak_framework dep (#2921)
  FirebaseMessaging.podspec
Labels: cla: yes

#2911 GULAppDelegateSwizzler macOS support
  GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
  GoogleUtilities/AppDelegateSwizzler/Internal/GULAppDelegateSwizzler_Private.h
  GoogleUtilities/AppDelegateSwizzler/Private/GULAppDelegateSwizzler.h
  GoogleUtilities/AppDelegateSwizzler/Private/GULApplication.h
  GoogleUtilities/Example/GoogleUtilities.xcodeproj/project.pbxproj
  GoogleUtilities/Example/Tests/Swizzler/GULAppDelegateSwizzlerTest.m
Labels: cla: yes

#2927 Fix Resources issues with builder.
  ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
  ZipBuilder/Sources/ZipBuilder/ResourcesManager.swift
  ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
  ZipBuilder/Sources/ZipBuilder/main.swift
Labels: cla: yes, zip-builder

#2931 Fix clang analyzer warning.
  Example/Auth/Sample/MainViewController+Internal.h
  Example/Auth/Sample/MainViewController.m
Labels: cla: yes

#2932 Fix a bug where request string for VerifyBeforeUpdateEmail is set inc…
  Firebase/Auth/Source/Backend/RPC/FIRGetOOBConfirmationCodeRequest.m
Labels: cla: yes

#2922 Add support for running Firestore integration tests against the emulator
  Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
  Firestore/Example/Tests/Integration/API/FIRFieldsTests.mm
  Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
  Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
  Firestore/Example/Tests/Integration/API/FIRWriteBatchTests.mm
  Firestore/Example/Tests/Integration/FSTTransactionTests.mm
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.h
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
  Firestore/README.md
Labels: api: firestore, cla: yes

#2928 Extract secrets on PRs coming from the same repo.
  scripts/install_prereqs.sh
Labels: cla: yes

#2936 Run Firestore integration tests against the emulator
  .gitignore
  Firestore/Example/Tests/Integration/API/FIRArrayTransformTests.mm
  Firestore/Example/Tests/Integration/API/FIRNumericTransformTests.mm
  scripts/build.sh
  scripts/run_firestore_emulator.sh
Labels: api: firestore, cla: yes

#2935 Run CocoaPods tests in travis test stage
  .gitignore
  .travis.yml
  CocoapodsIntegrationTest/Gemfile.lock
Labels: cla: yes

#2941 Fix cron tests by disallowing CocoaPods 1.7.0.rc.1
  CocoapodsIntegrationTest/Gemfile
Labels: cla: yes

#2939 Fix data collection switch unit tests
  Example/Core/Tests/FIRAppTest.m
Labels: cla: yes

#2937 Remove unused FIRFirestore instances dictionary
  Firestore/Source/API/FIRFirestore.mm
Labels: api: firestore, cla: yes

#2943 Add FirebaseCore test_spec
  .travis.yml
  Example/Core/Tests/FIROptionsTest.m
  FirebaseCore.podspec
  scripts/if_changed.sh
Labels: cla: yes

#2944 CocoaPods Tests cleanups and temporary fix
  .gitignore
  CocoapodsIntegrationTest/Gemfile
  CocoapodsIntegrationTest/Podfile
  CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_7_0_multiprojects_staticLibs/Gemfile
  CocoapodsIntegrationTest/TestEnvironments/Cocoapods1_7_0_staticLibs/Gemfile
Labels: cla: yes

#2945 Fixed small spelling errors.
  Firebase/Storage/CHANGELOG.md
Labels: api: storage, cla: yes

#2949 When expanding all subspecs, exclude test specs
  cmake/podspec_cmake.rb
Labels: api: firestore, cla: yes

#2940 Fix sanitizer builds
  Firestore/Example/Tests/Integration/API/FIRWriteBatchTests.mm
  Firestore/core/src/firebase/firestore/remote/grpc_connection.cc
  Firestore/core/src/firebase/firestore/util/sanitizers.h
Labels: api: firestore, cla: yes

#2948 Restore cmake build inadvertently deleted in #2482
  .travis.yml
Labels: cla: yes

#2958 Resolve merge conflicts from release-6.0.0 branch
  Example/Podfile
  FirebaseAuth.podspec
  FirebaseCore.podspec
  FirebaseDatabase.podspec
  FirebaseDynamicLinks.podspec
  FirebaseFirestore.podspec
  FirebaseFunctions.podspec
  FirebaseInAppMessagingDisplay.podspec
  FirebaseMessaging.podspec
  FirebaseStorage.podspec
  Firestore/Example/Podfile
  Releases/Manifests/6.0.0.json
  SymbolCollisionTest/Podfile
Labels: cla: yes

#2955 Removing test specs since it cause the pod push failure on 1.6.1
  FirebaseFunctions.podspec
Labels: cla: yes

#2954 Ensure Firestore emulator is shut down on build failure
  scripts/build.sh
Labels: api: firestore, cla: yes

#2964 Update Podfiles after 6.0.0 release
  Example/Podfile
  Firestore/Example/Podfile
Labels: cla: yes

#2967 Fix SymbolCollision Test
  SymbolCollisionTest/Podfile
Labels: cla: yes

#2969 Use correct framework names in README.
  ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
Labels: cla: yes

#2966 CMake fixes
  CMakeLists.txt
  Firestore/core/test/firebase/firestore/objc/CMakeLists.txt
  cmake/cc_rules.cmake
Labels: api: firestore, cla: yes

#2970 Update FIAM Podfile now that 6.0.0 is public
  InAppMessaging/Example/Podfile
Labels: cla: yes

#2960 Add new SDKs to zip builder.
  ZipBuilder/Sources/ZipBuilder/CocoaPod.swift
Labels: cla: yes

#2959 Add support of web.app as an auth domain
  Firebase/Auth/Source/AuthProvider/Phone/FIRPhoneAuthProvider.m
  Firebase/Auth/Source/Utilities/FIRAuthWebUtils.m
Labels: cla: yes

#2913 Collect code coverage stats on Travis
  scripts/build.sh
  scripts/collect_metrics.sh
Labels: cla: yes

#2971 Updating Carthage.md to reflect the SDKs added in v6.0.0
  Carthage.md
Labels: cla: yes

#2975 Add LogEvent.event_code property b/132272883.
  GoogleDataTransportCCTSupport/ProtoSupport/Protos/cct.proto
Labels: cla: yes

#2977 Fix check.sh when running a push build with a single commit
  .travis.yml
  scripts/check.sh
Labels: cla: yes

#2979 Remove wilhuff/fix-check from .travis.yml
  .travis.yml
Labels: cla: yes

#2978 Throw error in subsequent function calls after the client is shutdown
  Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/core/src/firebase/firestore/api/firestore.mm
Labels: api: firestore, cla: yes

#2972 Fix the metric collection on postsubmit.
  scripts/collect_metrics.sh
Labels: cla: yes

#2968 Ordered code fixes
  Firestore/Example/Benchmarks/CMakeLists.txt
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Podfile
  Firestore/core/src/firebase/firestore/util/ordered_code.cc
  Firestore/core/test/firebase/firestore/util/CMakeLists.txt
  Firestore/core/test/firebase/firestore/util/ordered_code_benchmark.mm
  Firestore/core/test/firebase/firestore/util/string_apple_benchmark.mm
  scripts/cpplint.py
Labels: api: firestore, cla: yes

#2976 Expand the upload package capabilities
  GoogleDataTransport/GDTLibrary/GDTEvent.m
  GoogleDataTransport/GDTLibrary/GDTUploadPackage.m
  GoogleDataTransport/GDTLibrary/Private/GDTUploadPackage_Private.h
  GoogleDataTransport/GDTLibrary/Public/GDTUploadPackage.h
  GoogleDataTransport/GDTLibrary/Public/GDTUploader.h
  GoogleDataTransport/GDTTests/Integration/Helpers/GDTIntegrationTestPrioritizer.m
  GoogleDataTransport/GDTTests/Lifecycle/Helpers/GDTLifecycleTestPrioritizer.m
  GoogleDataTransport/GDTTests/Unit/GDTUploadCoordinatorTest.m
  GoogleDataTransport/GDTTests/Unit/GDTUploadPackageTest.m
  GoogleDataTransport/GDTTests/Unit/Helpers/GDTTestPrioritizer.m
  GoogleDataTransport/GDTTests/Unit/Helpers/GDTTestUploader.m
Labels: cla: yes

#2983 Prevent `xcodebuild` from outputting to console.
  ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
Labels: cla: yes

#2985 CMake: Upgrade nanopb to 0.3.9.2
  CMakeLists.txt
  Firestore/Protos/CMakeLists.txt
  Firestore/Protos/nanopb/firestore/local/maybe_document.nanopb.cc
  Firestore/Protos/nanopb/firestore/local/maybe_document.nanopb.h
  Firestore/Protos/nanopb/firestore/local/mutation.nanopb.cc
  Firestore/Protos/nanopb/firestore/local/mutation.nanopb.h
  Firestore/Protos/nanopb/firestore/local/target.nanopb.cc
  Firestore/Protos/nanopb/firestore/local/target.nanopb.h
  Firestore/Protos/nanopb/google/api/annotations.nanopb.cc
  Firestore/Protos/nanopb/google/api/annotations.nanopb.h
  Firestore/Protos/nanopb/google/api/http.nanopb.cc
  Firestore/Protos/nanopb/google/api/http.nanopb.h
  Firestore/Protos/nanopb/google/firestore/v1/common.nanopb.cc
  Firestore/Protos/nanopb/google/firestore/v1/common.nanopb.h
  Firestore/Protos/nanopb/google/firestore/v1/document.nanopb.cc
  Firestore/Protos/nanopb/google/firestore/v1/document.nanopb.h
  Firestore/Protos/nanopb/google/firestore/v1/firestore.nanopb.cc
  Firestore/Protos/nanopb/google/firestore/v1/firestore.nanopb.h
  Firestore/Protos/nanopb/google/firestore/v1/query.nanopb.cc
  Firestore/Protos/nanopb/google/firestore/v1/query.nanopb.h
  Firestore/Protos/nanopb/google/firestore/v1/write.nanopb.cc
  Firestore/Protos/nanopb/google/firestore/v1/write.nanopb.h
  Firestore/Protos/nanopb/google/protobuf/any.nanopb.cc
  Firestore/Protos/nanopb/google/protobuf/any.nanopb.h
  Firestore/Protos/nanopb/google/protobuf/empty.nanopb.cc
  Firestore/Protos/nanopb/google/protobuf/empty.nanopb.h
  Firestore/Protos/nanopb/google/protobuf/struct.nanopb.cc
  Firestore/Protos/nanopb/google/protobuf/struct.nanopb.h
  Firestore/Protos/nanopb/google/protobuf/timestamp.nanopb.cc
  Firestore/Protos/nanopb/google/protobuf/timestamp.nanopb.h
  Firestore/Protos/nanopb/google/protobuf/wrappers.nanopb.cc
  Firestore/Protos/nanopb/google/protobuf/wrappers.nanopb.h
  Firestore/Protos/nanopb/google/rpc/status.nanopb.cc
  Firestore/Protos/nanopb/google/rpc/status.nanopb.h
  Firestore/Protos/nanopb/google/type/latlng.nanopb.cc
  Firestore/Protos/nanopb/google/type/latlng.nanopb.h
  Firestore/core/src/firebase/firestore/local/CMakeLists.txt
  Firestore/core/src/firebase/firestore/nanopb/CMakeLists.txt
  Firestore/core/src/firebase/firestore/remote/CMakeLists.txt
  cmake/external/nanopb.cmake
Labels: api: firestore, cla: yes

#2991 Fix objc_test on Windows
  Firestore/core/test/firebase/firestore/objc/CMakeLists.txt
Labels: api: firestore, cla: yes

#2994 Update CHANGELOG for Firestore v1.3.1
  Firestore/CHANGELOG.md
Labels: api: firestore, cla: yes

#2953 FIRInstanceIDKeyPairStore crash fix
  Example/InstanceID/Tests/FIRInstanceIDKeyPairMigrationTest.m
  Firebase/InstanceID/CHANGELOG.md
  Firebase/InstanceID/FIRInstanceIDKeyPairStore.m
Labels: cla: yes

#2990 Flesh out C++ FieldValue
  Firestore/Source/API/FIRTimestamp.m
  Firestore/core/include/firebase/firestore/geo_point.h
  Firestore/core/src/firebase/firestore/geo_point.cc
  Firestore/core/src/firebase/firestore/model/field_value.cc
  Firestore/core/src/firebase/firestore/model/field_value.h
  Firestore/core/test/firebase/firestore/model/field_value_test.cc
Labels: api: firestore, cla: yes

#2989 Port FSTFieldValueOptions to C++
  Firestore/Source/API/FIRDocumentSnapshot.mm
  Firestore/Source/Model/FSTFieldValue.h
  Firestore/Source/Model/FSTFieldValue.mm
  Firestore/core/src/firebase/firestore/model/CMakeLists.txt
  Firestore/core/src/firebase/firestore/model/field_value_options.h
  Firestore/core/test/firebase/firestore/testutil/xcgmock.h
Labels: api: firestore, cla: yes

#2992 Use outputDir for build logs.
  ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
  ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
  ZipBuilder/Sources/ZipBuilder/main.swift
Labels: cla: yes

#2998 FirebaseStorage 3.2.1 changelog
  Firebase/Storage/CHANGELOG.md
Labels: cla: yes

#2997 FirebaseCore 6.0.1 changelog
  Firebase/Core/CHANGELOG.md
Labels: cla: yes

#2999 GoogleUtilities 6.1.0
  GoogleUtilities.podspec
  GoogleUtilities/CHANGELOG.md
Labels: cla: yes

#2986 Port FIRQuery to C++
  Firestore/Example/Tests/API/FIRQueryTests.mm
  Firestore/Source/API/FIRCollectionReference.mm
  Firestore/Source/API/FIRQuery+Internal.h
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/API/FIRQuerySnapshot.mm
  Firestore/Source/API/FIRQuery_Init.h
  Firestore/Source/Core/FSTFirestoreClient.h
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/Source/Core/FSTQuery.mm
  Firestore/core/src/firebase/firestore/api/CMakeLists.txt
  Firestore/core/src/firebase/firestore/api/document_snapshot.h
  Firestore/core/src/firebase/firestore/api/firestore.mm
  Firestore/core/src/firebase/firestore/api/query_core.h
  Firestore/core/src/firebase/firestore/api/query_core.mm
  Firestore/core/src/firebase/firestore/api/query_snapshot.h
  Firestore/core/src/firebase/firestore/api/query_snapshot.mm
  Firestore/core/src/firebase/firestore/core/CMakeLists.txt
  Firestore/core/src/firebase/firestore/core/direction.cc
  Firestore/core/src/firebase/firestore/core/direction.h
Labels: api: firestore, cla: yes

#2995 prepare release log for Messaging and InstanceID
  Firebase/InstanceID/CHANGELOG.md
  Firebase/Messaging/CHANGELOG.md
Labels: cla: yes

#3000 Attempt to move GDT's integration test to the allowed_failures section
  .travis.yml
  scripts/build.sh
Labels: cla: yes

#2996 Use shared_ptr for AsyncQueue and Executor
  Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
  Firestore/Example/Tests/Util/FIRFirestore+Testing.h
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.h
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
  Firestore/Source/API/FIRFirestore+Internal.h
  Firestore/Source/API/FIRFirestore.mm
  Firestore/Source/Core/FSTFirestoreClient.h
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/core/src/firebase/firestore/api/firestore.h
  Firestore/core/src/firebase/firestore/api/firestore.mm
  Firestore/core/src/firebase/firestore/core/event_listener.h
Labels: api: firestore, cla: yes

#3007 Early return from sending analytics events if instance ID is nil
  Firebase/InAppMessaging/Analytics/FIRIAMClearcutLogger.m
Labels: cla: yes

#3003 Remove state management from the upload coordinator
  GoogleDataTransport/GDTLibrary/GDTStorage.m
  GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m
  GoogleDataTransport/GDTLibrary/GDTUploadPackage.m
  GoogleDataTransport/GDTLibrary/Private/GDTUploadCoordinator_Private.h
  GoogleDataTransport/GDTLibrary/Public/GDTPrioritizer.h
  GoogleDataTransport/GDTLibrary/Public/GDTUploader.h
  GoogleDataTransport/GDTTests/Common/Categories/GDTUploadCoordinator+Testing.m
  GoogleDataTransport/GDTTests/Integration/Helpers/GDTIntegrationTestPrioritizer.m
  GoogleDataTransport/GDTTests/Integration/Helpers/GDTIntegrationTestUploader.m
  GoogleDataTransport/GDTTests/Lifecycle/GDTLifecycleTest.m
  GoogleDataTransport/GDTTests/Lifecycle/Helpers/GDTLifecycleTestPrioritizer.m
  GoogleDataTransport/GDTTests/Lifecycle/Helpers/GDTLifecycleTestUploader.m
  GoogleDataTransport/GDTTests/Unit/GDTUploadCoordinatorTest.m
  GoogleDataTransport/GDTTests/Unit/Helpers/GDTTestPrioritizer.m
  GoogleDataTransport/GDTTests/Unit/Helpers/GDTTestUploader.h
  GoogleDataTransport/GDTTests/Unit/Helpers/GDTTestUploader.m
Labels: cla: yes

#3008 Update to CocoaPods 1.6.2 and CocoaPods generate to 1.5.0
  Gemfile
  Gemfile.lock
Labels: cla: yes

#3002 Fix typo in log message.
  Firebase/InAppMessaging/Runtime/FIRIAMActionURLFollower.m
Labels: cla: yes

#3011 Release 6.1.0 - cherry pick of #3007
  Firebase/InAppMessaging/Analytics/FIRIAMClearcutLogger.m
  FirebaseInAppMessaging.podspec
  Releases/Manifests/6.1.0.json
Labels: cla: yes

#3012 Update GDT to v0.1.1
  GoogleDataTransport.podspec
Labels: cla: yes

#3010 Use the new protocol APIs and upload package callbacks in GDT CCT
  GoogleDataTransportCCTSupport.podspec
  GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
  GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTPrioritizer.m
  GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m
  GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCCTUploader.h
  GoogleDataTransportCCTSupport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.c
  GoogleDataTransportCCTSupport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.h
  GoogleDataTransportCCTSupport/GDTCCTTests/Integration/GDTCCTIntegrationTest.m
  GoogleDataTransportCCTSupport/GDTCCTTests/Unit/GDTCCTPrioritizerTest.m
  GoogleDataTransportCCTSupport/GDTCCTTests/Unit/GDTCCTUploaderTest.m
  GoogleDataTransportCCTSupport/GDTCCTTests/Unit/Helpers/GDTCCTEventGenerator.m
  GoogleDataTransportCCTSupport/generate_project.sh
Labels: cla: yes

#3016 Release notes for FIAM in M48
  Firebase/InAppMessaging/CHANGELOG.md
Labels: cla: yes

#3019 GDT code cleanup and package tracking
  GoogleDataTransport.podspec
  GoogleDataTransport/GDTLibrary/GDTLifecycle.m
  GoogleDataTransport/GDTLibrary/GDTRegistrar.m
  GoogleDataTransport/GDTLibrary/GDTStorage.m
  GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m
  GoogleDataTransport/GDTLibrary/GDTUploadPackage.m
  GoogleDataTransport/GDTLibrary/Private/GDTStorage_Private.h
  GoogleDataTransport/GDTLibrary/Private/GDTUploadCoordinator.h
  GoogleDataTransport/GDTLibrary/Private/GDTUploadCoordinator_Private.h
  GoogleDataTransport/GDTLibrary/Public/GDTLifecycle.h
  GoogleDataTransport/GDTTests/Common/Categories/GDTUploadCoordinator+Testing.h
  GoogleDataTransport/GDTTests/Common/Categories/GDTUploadCoordinator+Testing.m
  GoogleDataTransport/GDTTests/Integration/Helpers/GDTIntegrationTestPrioritizer.m
  GoogleDataTransport/GDTTests/Integration/Helpers/GDTIntegrationTestUploader.m
  GoogleDataTransport/GDTTests/Lifecycle/GDTLifecycleTest.m
  GoogleDataTransport/GDTTests/Lifecycle/Helpers/GDTLifecycleTestPrioritizer.m
  GoogleDataTransport/GDTTests/Lifecycle/Helpers/GDTLifecycleTestUploader.m
  GoogleDataTransport/GDTTests/Unit/GDTStorageTest.m
  GoogleDataTransport/GDTTests/Unit/GDTUploadCoordinatorTest.m
  GoogleDataTransport/GDTTests/Unit/Helpers/GDTTestPrioritizer.m
  GoogleDataTransport/GDTTests/Unit/Helpers/GDTTestUploader.m
Labels: cla: yes

#3017 Make GDT CCT responsive to lifecycle and package events
  GoogleDataTransportCCTSupport.podspec
  GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTPrioritizer.m
  GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m
  GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCCTUploader.h
Labels: cla: yes

#3021 Ensure that only one package per target should ever be in flight
  GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m
  GoogleDataTransport/GDTLibrary/GDTUploadPackage.m
  GoogleDataTransport/GDTLibrary/Private/GDTUploadCoordinator.h
  GoogleDataTransport/GDTTests/Common/Categories/GDTUploadCoordinator+Testing.m
  GoogleDataTransport/GDTTests/Unit/GDTTestCase.m
  GoogleDataTransport/GDTTests/Unit/GDTUploadCoordinatorTest.m
  GoogleDataTransport/GDTTests/Unit/GDTUploadPackageTest.m
  GoogleDataTransport/GDTTests/Unit/Helpers/GDTTestPrioritizer.h
  GoogleDataTransport/GDTTests/Unit/Helpers/GDTTestPrioritizer.m
Labels: cla: yes

#3014 Fix XCode Analysis Issues for XCode 10.1
  Firebase/DynamicLinks/Utilities/FDLUtilities.m
  Firebase/InAppMessaging/Analytics/FIRIAMClearcutLogger.m
  Firebase/InAppMessaging/Flows/FIRIAMBookKeeper.m
  Firebase/InAppMessaging/Public/FIRInAppMessagingRendering.h
  Firebase/InAppMessaging/RenderingObjects/FIRInAppMessagingRenderingDataClasses.m
  Firestore/Source/Local/FSTLocalStore.mm
  Firestore/Source/Model/FSTDocument.h
  Firestore/Source/Model/FSTMutation.h
  Firestore/Source/Model/FSTMutation.mm
  Functions/FirebaseFunctions/FUNError.m
  Functions/FirebaseFunctions/FUNSerializer.h
  Functions/FirebaseFunctions/FUNSerializer.m
Labels: cla: yes

#3020 Fix check script for 1st travis run on non-master branch
  scripts/check.sh
Labels: cla: yes

#3024 Add reachability build
  Package.swift
Labels: cla: yes

#2993 Add clearPersistence()
  Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.h
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
  Firestore/Source/API/FIRFirestore+Internal.h
  Firestore/Source/API/FIRFirestore.mm
  Firestore/Source/Core/FSTFirestoreClient.h
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/Source/Local/FSTLevelDB.h
  Firestore/Source/Local/FSTLevelDB.mm
  Firestore/core/src/firebase/firestore/api/firestore.h
  Firestore/core/src/firebase/firestore/api/firestore.mm
Labels: api: firestore, cla: yes

#3004 Change AsyncQueue to used shared_ptr instead of raw pointers
  Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
  Firestore/Example/Tests/SpecTests/FSTMockDatastore.h
  Firestore/Example/Tests/SpecTests/FSTMockDatastore.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/Source/Core/FSTSyncEngine.h
  Firestore/Source/Core/FSTSyncEngine.mm
  Firestore/core/src/firebase/firestore/core/event_listener.h
  Firestore/core/src/firebase/firestore/remote/connectivity_monitor.h
  Firestore/core/src/firebase/firestore/remote/connectivity_monitor_apple.mm
  Firestore/core/src/firebase/firestore/remote/datastore.h
  Firestore/core/src/firebase/firestore/remote/datastore.mm
  Firestore/core/src/firebase/firestore/remote/exponential_backoff.cc
  Firestore/core/src/firebase/firestore/remote/exponential_backoff.h
  Firestore/core/src/firebase/firestore/remote/grpc_completion.cc
  Firestore/core/src/firebase/firestore/remote/grpc_completion.h
  Firestore/core/src/firebase/firestore/remote/grpc_connection.cc
  Firestore/core/src/firebase/firestore/remote/grpc_connection.h
  Firestore/core/src/firebase/firestore/remote/grpc_stream.cc
  Firestore/core/src/firebase/firestore/remote/grpc_stream.h
  Firestore/core/src/firebase/firestore/remote/grpc_streaming_reader.cc
  Firestore/core/src/firebase/firestore/remote/grpc_streaming_reader.h
  Firestore/core/src/firebase/firestore/remote/grpc_unary_call.cc
  Firestore/core/src/firebase/firestore/remote/grpc_unary_call.h
  Firestore/core/src/firebase/firestore/remote/online_state_tracker.h
  Firestore/core/src/firebase/firestore/remote/remote_store.h
  Firestore/core/src/firebase/firestore/remote/remote_store.mm
  Firestore/core/src/firebase/firestore/remote/stream.h
  Firestore/core/src/firebase/firestore/remote/stream.mm
  Firestore/core/src/firebase/firestore/remote/watch_stream.h
  Firestore/core/src/firebase/firestore/remote/watch_stream.mm
  Firestore/core/src/firebase/firestore/remote/write_stream.h
  Firestore/core/src/firebase/firestore/remote/write_stream.mm
  Firestore/core/test/firebase/firestore/remote/datastore_test.mm
  Firestore/core/test/firebase/firestore/remote/exponential_backoff_test.cc
  Firestore/core/test/firebase/firestore/remote/grpc_connection_test.cc
  Firestore/core/test/firebase/firestore/remote/grpc_stream_test.cc
  Firestore/core/test/firebase/firestore/remote/grpc_streaming_reader_test.cc
  Firestore/core/test/firebase/firestore/remote/grpc_unary_call_test.cc
  Firestore/core/test/firebase/firestore/remote/stream_test.mm
  Firestore/core/test/firebase/firestore/util/grpc_stream_tester.cc
  Firestore/core/test/firebase/firestore/util/grpc_stream_tester.h
Labels: api: firestore, cla: yes

#3029 Enable gRPC Keepalives at 30s of inactivity.
  Firestore/core/src/firebase/firestore/remote/grpc_connection.cc
Labels: api: firestore, cla: yes

#3030 Fix link with email link bug
  Example/Auth/Sample/MainViewController+Email.h
  Example/Auth/Sample/MainViewController+Email.m
  Example/Auth/Tests/FIRUserTests.m
  Firebase/Auth/Source/Auth/FIRAuth.m
  Firebase/Auth/Source/User/FIRUser.m
  Firebase/Auth/Source/Utilities/FIRAuthWebUtils.h
  Firebase/Auth/Source/Utilities/FIRAuthWebUtils.m
Labels: cla: yes

#3028 kill assertion code
  Example/Firebase.xcodeproj/project.pbxproj
  Firebase/InstanceID/FIRIMessageCode.h
  Firebase/InstanceID/FIRInstanceID.m
  Firebase/InstanceID/FIRInstanceIDBackupExcludedPlist.m
  Firebase/InstanceID/FIRInstanceIDCheckinPreferences.m
  Firebase/InstanceID/FIRInstanceIDCheckinService.m
  Firebase/InstanceID/FIRInstanceIDDefines.h
  Firebase/InstanceID/FIRInstanceIDKeyPairStore.m
  Firebase/InstanceID/FIRInstanceIDKeyPairUtilities.m
  Firebase/InstanceID/FIRInstanceIDStringEncoding.m
  Firebase/InstanceID/FIRInstanceIDTokenFetchOperation.m
  Firebase/InstanceID/FIRInstanceIDTokenOperation.m
  Firebase/InstanceID/FIRInstanceIDUtilities.m
  Firebase/InstanceID/FIRInstanceIDVersionUtilities.m
Labels: cla: yes

#3035 Make FIAM tests required for Travis CI build to pass
  .travis.yml
  InAppMessaging/Example/Tests/FIRIAMClearcutUploaderTests.m
Labels: cla: yes

#2963 Disable data protection when opening the Rmq2PersistentStore
  Firebase/Messaging/FIRMessagingRmq2PersistentStore.m
Labels: api: messaging, cla: yes

#3001 Update CHANGELOG.md
  Firebase/Auth/CHANGELOG.md
Labels: cla: yes

#3027 Support macOS and tvOS in GDT and GDTCCT
  GoogleDataTransport.podspec
  GoogleDataTransport/GDTLibrary/GDTLifecycle.m
  GoogleDataTransport/GDTLibrary/GDTPlatform.m
  GoogleDataTransport/GDTLibrary/GDTRegistrar.m
  GoogleDataTransport/GDTLibrary/GDTStorage.m
  GoogleDataTransport/GDTLibrary/GDTTransformer.m
  GoogleDataTransport/GDTLibrary/GDTUploadCoordinator.m
  GoogleDataTransport/GDTLibrary/Public/GDTLifecycle.h
  GoogleDataTransport/GDTLibrary/Public/GDTPlatform.h
  GoogleDataTransport/GDTTests/Lifecycle/GDTLifecycleTest.m
  GoogleDataTransportCCTSupport.podspec
  GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
  GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m
  scripts/build.sh
  scripts/if_changed.sh
  scripts/install_prereqs.sh
Labels: cla: yes

#3038 Upgrade the emulator we use for integration testing to 1.4.6
  Firestore/Example/Tests/Integration/API/FIRArrayTransformTests.mm
  Firestore/Example/Tests/Integration/API/FIRNumericTransformTests.mm
  Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
  Firestore/Example/Tests/Integration/FSTTransactionTests.mm
  scripts/run_firestore_emulator.sh
Labels: api: firestore, cla: yes

#3039 Remove checks for boolean migration
  Firestore/core/src/firebase/firestore/local/leveldb_mutation_queue.mm
  scripts/cpplint.py
Labels: api: firestore, cla: yes

#3023 Add test_spec for FirebaseStorage
  .travis.yml
  Example/Storage/Tests/Integration/FIRStorageIntegrationTests.m
  FirebaseStorage.podspec
  scripts/build.sh
  scripts/check.sh
  scripts/if_changed.sh
  scripts/install_prereqs.sh
Labels: api: storage, cla: yes

#3034 Add test_specs and fix test build warnings for Database
  .travis.yml
  Example/Database/Tests/Helpers/FDevice.m
  Example/Database/Tests/Helpers/FEventTester.m
  Example/Database/Tests/Helpers/FTestHelpers.m
  Example/Database/Tests/Helpers/SenTest+FWaiter.h
  Example/Database/Tests/Helpers/SenTest+FWaiter.m
  Example/Database/Tests/Integration/FData.m
  Example/Database/Tests/Integration/FIRDatabaseQueryTests.m
  Example/Database/Tests/Integration/FIRDatabaseTests.m
  Example/Database/Tests/Integration/FTransactionTest.m
  Example/Database/Tests/Unit/FTrackedQueryManagerTest.m
  Example/Database/Tests/third_party/Base64.m
  Example/Storage/Tests/Integration/FIRStorageIntegrationTests.m
  FirebaseDatabase.podspec
  scripts/build.sh
  scripts/if_changed.sh
  scripts/install_prereqs.sh
Labels: api: database, cla: yes

#3036 Add InstanceID test_spec
  .travis.yml
  Example/InstanceID/Tests/FIRInstanceIDAPNSInfoTest.m
  Example/InstanceID/Tests/FIRInstanceIDAuthKeyChainTest.m
  Example/InstanceID/Tests/FIRInstanceIDAuthServiceTest.m
  Example/InstanceID/Tests/FIRInstanceIDCheckinServiceTest.m
  Example/InstanceID/Tests/FIRInstanceIDCheckinStoreTest.m
  Example/InstanceID/Tests/FIRInstanceIDKeyPairStoreTest.m
  Example/InstanceID/Tests/FIRInstanceIDStoreTest.m
  Example/InstanceID/Tests/FIRInstanceIDTest.m
  Example/InstanceID/Tests/FIRInstanceIDTokenInfoTest.m
  FirebaseInstanceID.podspec
  scripts/if_changed.sh
Labels: api: instanceid, cla: yes

#3040 Make DatabaseId a cheap value type
  Firestore/core/src/firebase/firestore/model/database_id.cc
  Firestore/core/src/firebase/firestore/model/database_id.h
  Firestore/core/test/firebase/firestore/model/database_id_test.cc
Labels: api: firestore, cla: yes

#3013 fix the typo error that cause bundle identifier checking failed for app extension
  Example/Core/Tests/FIRBundleUtilTest.m
  Firebase/Core/FIRBundleUtil.m
Labels: cla: yes

#2918 In case user is nil, we don't generate FIRAuthResult.
  Firebase/Auth/Source/Auth/FIRAuth.m
  Firebase/Auth/Source/Auth/FIRAuthDataResult.m
  Firebase/Auth/Source/Auth/FIRAuthDataResult_Internal.h
Labels: cla: yes

#3047 FieldValue::Map -> ObjectValue
  Firestore/core/src/firebase/firestore/model/field_value.h
  Firestore/core/test/firebase/firestore/model/field_value_test.cc
  Firestore/core/test/firebase/firestore/testutil/testutil.h
Labels: api: firestore, cla: yes

#3025 Rewrite FieldValue tests to match the Android port
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/API/FSTUserDataConverterTests.mm
  Firestore/Example/Tests/Model/FSTFieldValueTests.mm
  Firestore/core/src/firebase/firestore/model/field_value.h
  Firestore/core/test/firebase/firestore/model/field_value_test.cc
  Firestore/core/test/firebase/firestore/testutil/testutil.h
Labels: api: firestore, cla: yes

#3041 Refactor usages of DatabaseId to avoid raw pointers
  Firestore/Example/Benchmarks/FSTLevelDBBenchmarkTests.mm
  Firestore/Example/FuzzTests/FuzzingTargets/FSTFuzzTestSerializer.mm
  Firestore/Example/Tests/API/FSTAPIHelpers.mm
  Firestore/Example/Tests/API/FSTUserDataConverterTests.mm
  Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
  Firestore/Example/Tests/Local/FSTLevelDBQueryCacheTests.mm
  Firestore/Example/Tests/Local/FSTLocalSerializerTests.mm
  Firestore/Example/Tests/Local/FSTPersistenceTestHelpers.mm
  Firestore/Example/Tests/Model/FSTFieldValueTests.mm
  Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
  Firestore/Example/Tests/SpecTests/FSTMockDatastore.mm
  Firestore/Example/Tests/Util/FSTHelpers.mm
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
  Firestore/Source/API/FIRDocumentSnapshot.mm
  Firestore/Source/API/FIRFirestore+Internal.h
  Firestore/Source/API/FIRFirestore.mm
  Firestore/Source/API/FSTFirestoreComponent.mm
  Firestore/Source/API/FSTUserDataConverter.h
  Firestore/Source/API/FSTUserDataConverter.mm
  Firestore/Source/Core/FSTFirestoreClient.h
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/Source/Local/FSTLevelDB.mm
  Firestore/Source/Model/FSTFieldValue.h
  Firestore/Source/Model/FSTFieldValue.mm
  Firestore/Source/Remote/FSTSerializerBeta.h
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/api/firestore.h
  Firestore/core/src/firebase/firestore/api/firestore.mm
  Firestore/core/src/firebase/firestore/api/query_core.mm
  Firestore/core/src/firebase/firestore/core/database_info.cc
  Firestore/core/src/firebase/firestore/core/database_info.h
  Firestore/core/src/firebase/firestore/model/database_id.h
  Firestore/core/src/firebase/firestore/model/field_value.cc
  Firestore/core/src/firebase/firestore/model/field_value.h
  Firestore/core/src/firebase/firestore/remote/remote_objc_bridge.mm
  Firestore/core/src/firebase/firestore/remote/serializer.cc
  Firestore/core/src/firebase/firestore/remote/serializer.h
  Firestore/core/test/firebase/firestore/core/database_info_test.cc
  Firestore/core/test/firebase/firestore/local/local_serializer_test.cc
  Firestore/core/test/firebase/firestore/model/field_value_test.cc
  Firestore/core/test/firebase/firestore/remote/grpc_connection_test.cc
  Firestore/core/test/firebase/firestore/remote/serializer_test.cc
Labels: api: firestore, cla: yes

#3050 Restore necessary pod repo update's
  scripts/install_prereqs.sh
Labels: cla: yes

#3055 CocoaPods 1.7.0 has released
  Gemfile
  Gemfile.lock
Labels: cla: yes

#3056 Update Firestore.xcodeproj for CocoaPods 1.7
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
Labels: api: firestore, cla: yes

#3042 Rewrite C++ FieldValue using traditional polymorphism
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/core/src/firebase/firestore/model/field_value.cc
  Firestore/core/src/firebase/firestore/model/field_value.h
  Firestore/core/src/firebase/firestore/util/comparison.h
  Firestore/core/test/firebase/firestore/model/CMakeLists.txt
  Firestore/core/test/firebase/firestore/model/field_value_benchmark.cc
  Firestore/core/test/firebase/firestore/model/field_value_test.cc
  Firestore/core/test/firebase/firestore/util/CMakeLists.txt
Labels: api: firestore, cla: yes

#3059 Deflake and speedup iid tests
  .travis.yml
Labels: cla: yes

#3058 Stop conditional compilation for GoogleUtilities testing
  Example/DynamicLinks/Tests/FIRDynamicLinkNetworkingTests.m
  Example/DynamicLinks/Tests/FIRDynamicLinksTest.m
  Example/Firebase.xcodeproj/project.pbxproj
  Example/Podfile
  GoogleUtilities.podspec
  GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
  GoogleUtilities/AppDelegateSwizzler/Internal/GULAppDelegateSwizzler_Private.h
  GoogleUtilities/Example/GoogleUtilities.xcodeproj/project.pbxproj
  GoogleUtilities/Example/Podfile
  GoogleUtilities/Example/Tests/Swizzler/GULSwizzlerInheritedMethodsSwizzlingTest.m
  GoogleUtilities/Example/Tests/Swizzler/GULSwizzlerTest.m
  GoogleUtilities/Example/Tests/Swizzler/GULSwizzlingCacheTest.m
  GoogleUtilities/MethodSwizzler/GULSwizzler.m
  GoogleUtilities/MethodSwizzler/Private/GULSwizzler.h
  GoogleUtilities/SwizzlerTestHelpers/GULSwizzler+Unswizzle.h
  GoogleUtilities/SwizzlerTestHelpers/GULSwizzler+Unswizzle.m
  GoogleUtilities/SwizzlerTestHelpers/GULSwizzlingCache.h
  GoogleUtilities/SwizzlerTestHelpers/GULSwizzlingCache.m
  GoogleUtilities/SwizzlerTestHelpers/GULSwizzlingCache_Private.h
Labels: cla: yes

#3060 Fix common typos.
  Firebase/Auth/Source/Public/FIRAuth.h
  Firebase/Auth/Source/Public/FIRUserMetadata.h
  Firebase/InstanceID/Public/FIRInstanceID.h
Labels: cla: yes

#3037 Handle new cert bundle name in gRPC-C++
  FirebaseFirestore.podspec
  Firestore/core/src/firebase/firestore/remote/grpc_root_certificate_finder_apple.mm
Labels: api: firestore, cla: yes

#3061 Fix Auth post-submit CI build break
  Example/Auth/Sample/FacebookAuthProvider.m
  scripts/build.sh
Labels: api: auth, cla: yes

#3057 call callback handler only when it's not null.
  Firebase/Auth/Source/Auth/FIRAuth.m
Labels: cla: yes

#3063 Reformat the repo
  Firestore/core/src/firebase/firestore/model/field_value.cc
  GoogleDataTransport/GDTLibrary/GDTPlatform.m
  GoogleDataTransport/GDTLibrary/Public/GDTPlatform.h
  GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
  GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTUploader.m
Labels: cla: yes

#3064 Remove --warn-uninitialized from CMake builds
  scripts/build.sh
Labels: api: firestore, cla: yes

#3065 Remove flaky retain count checking
  Example/InstanceID/Tests/FIRInstanceIDKeyPairMigrationTest.m
Labels: api: instanceid, cla: yes

#3072 Add a script to print the local dependencies of a given podspec file.
  scripts/pod_local_deps.rb
Labels: cla: yes

#3073 Fiam make nonrequired
  .travis.yml
Labels: cla: yes

#3071 Fix compilation error in non-Apple builds.
  Firestore/core/src/firebase/firestore/remote/connectivity_monitor_noop.cc
Labels: api: firestore, cla: yes

#3075 Rewrite pod_lib_lint as a ruby script
  .travis.yml
  scripts/if_changed.sh
  scripts/pod_lib_lint.rb
  scripts/pod_lib_lint.sh
Labels: cla: yes

#3043 Fix C++ FieldValue equality
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/core/src/firebase/firestore/model/field_value.cc
  Firestore/core/src/firebase/firestore/model/field_value.h
  Firestore/core/test/firebase/firestore/model/CMakeLists.txt
  Firestore/core/test/firebase/firestore/model/field_value_test.cc
  Firestore/core/test/firebase/firestore/testutil/CMakeLists.txt
  Firestore/core/test/firebase/firestore/testutil/equals_tester.h
  Firestore/core/test/firebase/firestore/testutil/testutil.h
Labels: api: firestore, cla: yes

#3078 Update sample app deployment target to iOS 8.0
  Example/Firebase.xcodeproj/project.pbxproj
Labels: cla: yes

#3077 Update FIRAuthDataResult_Internal.h
  Firebase/Auth/Source/Auth/FIRAuthDataResult_Internal.h
Labels: cla: yes

#3079 Update CHANGELOG.md
  Firebase/Auth/CHANGELOG.md
Labels: cla: yes

#3083 Use standard import syntax
  GoogleUtilities/SwizzlerTestHelpers/GULSwizzler+Unswizzle.m
Labels: GoogleUtilities, cla: yes

#3085 Fix debug mode crash found internally
  GoogleUtilities/MethodSwizzler/GULSwizzler.m
Labels: GoogleUtilities, cla: yes

#3086 fix typo
  GoogleUtilities/MethodSwizzler/GULSwizzler.m
Labels: cla: yes

#3044 Migrate null, numbers, and GeoPoints to FSTDelegateValue
  Firestore/Example/Tests/API/FSTUserDataConverterTests.mm
  Firestore/Example/Tests/Core/FSTViewTests.mm
  Firestore/Example/Tests/Model/FSTFieldValueTests.mm
  Firestore/Example/Tests/Model/FSTMutationTests.mm
  Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
  Firestore/Source/API/FIRGeoPoint+Internal.h
  Firestore/Source/API/FIRGeoPoint.mm
  Firestore/Source/API/FSTUserDataConverter.mm
  Firestore/Source/Core/FSTQuery.h
  Firestore/Source/Core/FSTQuery.mm
  Firestore/Source/Model/FSTFieldValue.h
  Firestore/Source/Model/FSTFieldValue.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/model/field_value.h
  Firestore/core/src/firebase/firestore/model/transform_operations.h
  Firestore/core/test/firebase/firestore/testutil/xcgmock.h
Labels: api: firestore, cla: yes

#3080 Restore style checking on travis
  .travis.yml
  scripts/check.sh
Labels: cla: yes

#3094 FIRMessagingRemoteNotificationsProxyTest fixes for iOS 8
  Example/Messaging/Tests/FIRMessagingRemoteNotificationsProxyTest.m
Labels: cla: yes

#3093 GoogleUtilities unit tests on iOS 8
  GoogleUtilities/Example/Tests/Swizzler/GULAppDelegateSwizzlerTest.m
  GoogleUtilities/SwizzlerTestHelpers/GULRuntimeClassSnapshot.m
Labels: cla: yes

#3067 IID tests improvements
  Example/InstanceID/Tests/FIRInstanceIDKeyPairMigrationTest.m
  Example/InstanceID/Tests/FIRInstanceIDKeyPairStoreTest.m
  Example/InstanceID/Tests/FIRInstanceIDKeyPairTest.m
  Example/InstanceID/Tests/FIRInstanceIDResultTest.m
  Example/InstanceID/Tests/FIRInstanceIDTokenManagerTest.m
Labels: cla: yes

#3081 FIAM Programmatic triggers
  Firebase/InAppMessaging/FIRInAppMessaging.m
  Firebase/InAppMessaging/Public/FIRInAppMessaging.h
  Firebase/InAppMessaging/RenderingObjects/FIRInAppMessagingRenderingDataClasses.m
  Firebase/InAppMessaging/RenderingObjects/FIRInAppMessagingRenderingPrivate.h
  InAppMessaging/Example/App/InAppMessaging-Example-iOS/AutoDisplayFlowViewController.m
  InAppMessaging/Example/App/InAppMessaging-Example-iOS/Base.lproj/Main.storyboard
Labels: cla: yes

#2908 GoogleUtilities to testspec and pod gen
  .travis.yml
  GoogleUtilities.podspec
  GoogleUtilities/Example/Tests/Network/third_party/GTMHTTPServer.m
  GoogleUtilities/Example/Tests/Swizzler/GULAppDelegateSwizzlerTest.m
  GoogleUtilities/README.md
  scripts/if_changed.sh
Labels: cla: yes

#3088 Add test_spec for FCM
  .travis.yml
  Example/Messaging/Tests/FIRMessagingAnalyticsTest.m
  Example/Messaging/Tests/FIRMessagingClientTest.m
  Example/Messaging/Tests/FIRMessagingDataMessageManagerTest.m
  Example/Messaging/Tests/FIRMessagingExtensionHelperTest.m
  Example/Messaging/Tests/FIRMessagingPendingTopicsListTest.m
  Example/Messaging/Tests/FIRMessagingRemoteNotificationsProxyTest.m
  Example/Messaging/Tests/FIRMessagingRmqManagerTest.m
  FirebaseMessaging.podspec
  scripts/build.sh
  scripts/if_changed.sh
  scripts/install_prereqs.sh
Labels: api: messaging, cla: yes

#3096 Update release CHANGELOG
  Firebase/InstanceID/CHANGELOG.md
  Firebase/Messaging/CHANGELOG.md
Labels: cla: yes

#3097 GoogleUtilities 6.2.0
  FirebaseAuth.podspec
  FirebaseMessaging.podspec
  GoogleUtilities.podspec
  GoogleUtilities/CHANGELOG.md
Labels: GoogleUtilities, cla: yes

#3098 Speed up regular testing
  .travis.yml
Labels: GoogleUtilities, cla: yes

#3099 Add release notes for FIAM M49
  Firebase/InAppMessaging/CHANGELOG.md
  Firebase/InAppMessagingDisplay/CHANGELOG.md
Labels: cla: yes

#3103 Update CHANGELOG for Firestore v1.3.2
  Firestore/CHANGELOG.md
Labels: api: firestore, cla: yes

#3102 Fix FIAM pod lib lint issue
  Firebase/InAppMessaging/Flows/FIRIAMDisplayExecutor.m
Labels: cla: yes

#3100 Very small fixes
  Firestore/core/src/firebase/firestore/api/document_reference.mm
  Firestore/core/src/firebase/firestore/model/database_id.cc
  Firestore/core/src/firebase/firestore/model/database_id.h
Labels: api: firestore, cla: yes

#3116 CocoaPods 1.7.1
  Gemfile
  Gemfile.lock
Labels: cla: yes

#3117 Add Twitter, LinkedIn, Yahoo OAuth provider to sample app.
  Example/Auth/Sample/MainViewController+Internal.h
  Example/Auth/Sample/MainViewController+OAuth.m
  Example/Auth/Sample/MainViewController.m
Labels: cla: yes

#2880 Adding macOS support for Messaging and InstanceID
  .travis.yml
  Example/InstanceID/Tests/FIRInstanceIDAuthKeyChainTest.m
  Example/InstanceID/Tests/FIRInstanceIDKeyPairMigrationTest.m
  Example/InstanceID/Tests/FIRInstanceIDKeyPairStoreTest.m
  Example/InstanceID/Tests/FIRInstanceIDTest.m
  Example/Messaging/Tests/FIRMessagingAnalyticsTest.m
  Example/Messaging/Tests/FIRMessagingExtensionHelperTest.m
  Example/Messaging/Tests/FIRMessagingRemoteNotificationsProxyTest.m
  Example/Messaging/Tests/FIRMessagingServiceTest.m
  Example/Messaging/Tests/FIRMessagingTest.m
  Firebase/InstanceID/FIRInstanceID.m
  Firebase/InstanceID/FIRInstanceIDAuthKeyChain.m
  Firebase/InstanceID/FIRInstanceIDTokenInfo.m
  Firebase/InstanceID/FIRInstanceIDTokenStore.m
  Firebase/InstanceID/FIRInstanceIDUtilities.m
  Firebase/Messaging/FIRMessaging.m
  Firebase/Messaging/FIRMessagingAnalytics.m
  Firebase/Messaging/FIRMessagingContextManagerService.m
  Firebase/Messaging/FIRMessagingExtensionHelper.m
  Firebase/Messaging/FIRMessagingPubSub.m
  Firebase/Messaging/FIRMessagingReceiver.m
  Firebase/Messaging/FIRMessagingRemoteNotificationsProxy.m
  Firebase/Messaging/FIRMessagingUtilities.h
  Firebase/Messaging/FIRMessagingUtilities.m
  Firebase/Messaging/Public/FIRMessaging.h
  Firebase/Messaging/Public/FIRMessagingExtensionHelper.h
  FirebaseInstanceID.podspec
  FirebaseMessaging.podspec
  GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
Labels: cla: yes

#3118 Add script to generate a module map from a podspec
  scripts/module_map.rb
Labels: cla: yes, zip-builder

#3122 FirebaseInstallations initial podspec
  .travis.yml
  FirebaseInstallations.podspec
  FirebaseInstallations/Source/Example.m
  FirebaseInstallations/Source/Public/Example.h
  FirebaseInstallations/Source/Tests/ExampleTest.m
Labels: cla: yes

#3120 Change limit to an int32 to match the backend
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/Core/FSTQuery.h
  Firestore/Source/Core/FSTQuery.mm
  Firestore/Source/Core/FSTView.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/api/query_core.h
  Firestore/core/src/firebase/firestore/api/query_core.mm
  Firestore/core/src/firebase/firestore/core/query.h
Labels: api: firestore, cla: yes

#3115 DynamicLinks test_spec
  .travis.yml
  Example/DynamicLinks/App/DL-Info.plist
  Example/DynamicLinks/Tests/FIRDynamicLinksTest.m
  Example/Firebase.xcodeproj/project.pbxproj
  FirebaseDynamicLinks.podspec
  scripts/if_changed.sh
  scripts/install_prereqs.sh
Labels: cla: yes
