Repository firebase/firebase-ios-sdk, pull requests merged in 2019-03, with the labels that each got.

#2391 Fix build for non-clang compilers
  Firestore/Example/Tests/Integration/API/FIRFieldsTests.mm
  Firestore/Source/API/FIRDocumentSnapshot.mm
  Firestore/Source/API/FIRFirestoreSettings.mm
  Firestore/core/src/firebase/firestore/remote/grpc_connection.h
  Firestore/core/src/firebase/firestore/remote/grpc_stream.h
  Firestore/core/src/firebase/firestore/remote/grpc_streaming_reader.h
  Firestore/core/src/firebase/firestore/remote/grpc_unary_call.h
  Firestore/core/src/firebase/firestore/util/CMakeLists.txt
  Firestore/core/src/firebase/firestore/util/warnings.h
Labels: cla: yes

#2441 C++ migration: port `FSTViewSnapshot`
  Firestore/Example/Tests/API/FIRQuerySnapshotTests.mm
  Firestore/Example/Tests/API/FSTAPIHelpers.mm
  Firestore/Example/Tests/Core/FSTEventManagerTests.mm
  Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
  Firestore/Example/Tests/Core/FSTViewSnapshotTest.mm
  Firestore/Example/Tests/Core/FSTViewTests.mm
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.h
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Example/Tests/Util/FSTHelpers.h
  Firestore/Example/Tests/Util/FSTHelpers.mm
  Firestore/Source/API/FIRDocumentChange+Internal.h
  Firestore/Source/API/FIRDocumentChange.mm
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/API/FIRQuerySnapshot+Internal.h
  Firestore/Source/API/FIRQuerySnapshot.mm
  Firestore/Source/Core/FSTEventManager.h
  Firestore/Source/Core/FSTEventManager.mm
  Firestore/Source/Core/FSTFirestoreClient.h
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/Source/Core/FSTSyncEngine.h
  Firestore/Source/Core/FSTSyncEngine.mm
  Firestore/Source/Core/FSTView.h
  Firestore/Source/Core/FSTView.mm
  Firestore/Source/Core/FSTViewSnapshot.h
  Firestore/Source/Core/FSTViewSnapshot.mm
  Firestore/Source/Local/FSTLocalViewChanges.h
  Firestore/Source/Local/FSTLocalViewChanges.mm
  Firestore/Source/Util/FSTAsyncQueryListener.h
  Firestore/Source/Util/FSTAsyncQueryListener.mm
  Firestore/core/src/firebase/firestore/core/view_snapshot.h
  Firestore/core/src/firebase/firestore/core/view_snapshot.mm
  Firestore/core/src/firebase/firestore/util/error_apple.h
  Firestore/core/src/firebase/firestore/util/to_string.h
  Firestore/core/test/firebase/firestore/util/to_string_test.cc
Labels: Firestore, cla: yes

#2463 Fix build with gcc
  Firestore/core/src/firebase/firestore/util/warnings.h
Labels: cla: yes

#2458 FIRStorageUploadTask: fail on invalid file URL
  Example/Storage/Tests/Unit/FIRStorageReferenceTests.m
  Firebase/Storage/FIRStorageUploadTask.m
Labels: cla: yes

#2393 Ensure ArraySortedMap is actually sorted
  Firestore/core/src/firebase/firestore/immutable/array_sorted_map.h
  Firestore/core/test/firebase/firestore/immutable/array_sorted_map_test.cc
  Firestore/core/test/firebase/firestore/immutable/tree_sorted_map_test.cc
Labels: cla: yes

#2467 Update CHANGELOG for Firestore v1.0.2
  Firestore/CHANGELOG.md
Labels: Firestore, cla: yes

#2456 C++: make internal Objective-C API wrap `DocumentSnapshot` from core API
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Source/API/FIRDocumentSnapshot.mm
  Firestore/Source/Model/FSTFieldValue.h
  Firestore/Source/Model/FSTFieldValue.mm
  Firestore/core/src/firebase/firestore/api/document_snapshot.h
  Firestore/core/src/firebase/firestore/api/document_snapshot.mm
  Firestore/core/src/firebase/firestore/util/hashing.h
  Firestore/core/test/firebase/firestore/util/hashing_test_apple.mm
Labels: Firestore, cla: yes

#2468 Fix Functions unit tests for 32bit targets
  Functions/Example/Tests/FUNSerializerTests.m
Labels: Functions, cla: yes

#2472 Fix for CocoaPods 1.6
  InAppMessagingDisplay/Example/InAppMessagingDisplay-Sample.xcodeproj/project.pbxproj
Labels: cla: yes

#2464 Update Changelog for Firebase Storage
  Firebase/Storage/CHANGELOG.md
Labels: cla: yes

#2428 Make FCM and InstanceID compatible with tvOS
  Example/Firebase.xcodeproj/project.pbxproj
  Example/Firebase.xcodeproj/xcshareddata/xcschemes/AllUnitTests_tvOS.xcscheme
  Example/Firebase.xcodeproj/xcshareddata/xcschemes/Messaging_Example_tvOS.xcscheme
  Example/Firebase.xcodeproj/xcshareddata/xcschemes/Messaging_Tests_tvOS.xcscheme
  Example/Messaging/App/tvOS/AppDelegate.h
  Example/Messaging/App/tvOS/AppDelegate.m
  Example/Messaging/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  Example/Messaging/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Contents.json
  Example/Messaging/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Contents.json
  Example/Messaging/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  Example/Messaging/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Contents.json
  Example/Messaging/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  Example/Messaging/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Contents.json
  Example/Messaging/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  Example/Messaging/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Contents.json
  Example/Messaging/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Contents.json
  Example/Messaging/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  Example/Messaging/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Contents.json
  Example/Messaging/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  Example/Messaging/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Contents.json
  Example/Messaging/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json
  Example/Messaging/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image Wide.imageset/Contents.json
  Example/Messaging/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json
  Example/Messaging/App/tvOS/Assets.xcassets/Contents.json
  Example/Messaging/App/tvOS/Assets.xcassets/Launch Image.launchimage/Contents.json
  Example/Messaging/App/tvOS/Base.lproj/Main.storyboard
  Example/Messaging/App/tvOS/Info.plist
  Example/Messaging/App/tvOS/ViewController.h
  Example/Messaging/App/tvOS/ViewController.m
  Example/Messaging/App/tvOS/main.m
  Example/Messaging/Tests/FIRMessagingContextManagerServiceTest.m
  Example/Messaging/Tests/FIRMessagingRemoteNotificationsProxyTest.m
  Example/Podfile
  Firebase/InstanceID/FIRInstanceIDUtilities.m
  Firebase/Messaging/FIRMessaging.m
  Firebase/Messaging/FIRMessagingContextManagerService.m
  FirebaseInstanceID.podspec
  FirebaseMessaging.podspec
Labels: cla: yes

#2471 Improved query performance in the face of subcollections.
  Firestore/CHANGELOG.md
  Firestore/Example/Tests/Local/FSTRemoteDocumentCacheTests.mm
  Firestore/core/src/firebase/firestore/local/leveldb_remote_document_cache.mm
Labels: api: firestore, cla: yes

#2476 Revert GoogleUtilities version bump.
  GoogleUtilities.podspec
  Releases/Manifests/5.18.0.json
Labels: cla: yes

#2477 Release 5.18.0
  Example/Podfile
  Firebase/Core/FIROptions.m
  FirebaseAuth.podspec
  FirebaseCore.podspec
  FirebaseDynamicLinks.podspec
  FirebaseFirestore.podspec
  FirebaseFunctions.podspec
  FirebaseInAppMessaging.podspec
  FirebaseInAppMessagingDisplay.podspec
  FirebaseMessaging.podspec
  Firestore/Example/Podfile
  Releases/Manifests/5.18.0.json
  SymbolCollisionTest/Podfile
Labels: cla: yes

#2480 Fix Functions IntegrationTests for 32bit architectures
  Functions/Backend/index.js
  Functions/Example/IntegrationTests/FIRIntegrationTests.m
Labels: api: functions, cla: yes

#2469 C++ migration: make `FIRDocumentReference` implementation delegate to core API
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/Core/FSTFirestoreClient.h
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/core/src/firebase/firestore/api/document_reference.h
  Firestore/core/src/firebase/firestore/api/document_reference.mm
Labels: api: firestore, cla: yes

#2482 Stop Xcode 9 testing
  .travis.yml
Labels: cla: yes

#2075 Adding FieldValue.increment()
  Firestore/CHANGELOG.md
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/Integration/API/FIRNumericTransformTests.mm
  Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
  Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm
  Firestore/Example/Tests/Local/FSTLocalSerializerTests.mm
  Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
  Firestore/Example/Tests/Local/FSTMutationQueueTests.mm
  Firestore/Example/Tests/Model/FSTMutationTests.mm
  Firestore/Example/Tests/Model/transform_operations_test.mm
  Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
  Firestore/Example/Tests/Util/FSTHelpers.mm
  Firestore/Source/API/FIRFieldValue+Internal.h
  Firestore/Source/API/FIRFieldValue.mm
  Firestore/Source/API/FSTUserDataConverter.mm
  Firestore/Source/Local/FSTLocalSerializer.mm
  Firestore/Source/Local/FSTLocalStore.mm
  Firestore/Source/Model/FSTFieldValue.h
  Firestore/Source/Model/FSTFieldValue.mm
  Firestore/Source/Model/FSTMutation.h
  Firestore/Source/Model/FSTMutation.mm
  Firestore/Source/Model/FSTMutationBatch.h
  Firestore/Source/Model/FSTMutationBatch.mm
  Firestore/Source/Public/FIRFieldValue.h
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/local/leveldb_mutation_queue.h
  Firestore/core/src/firebase/firestore/local/leveldb_mutation_queue.mm
  Firestore/core/src/firebase/firestore/local/memory_mutation_queue.h
  Firestore/core/src/firebase/firestore/local/memory_mutation_queue.mm
  Firestore/core/src/firebase/firestore/local/mutation_queue.h
  Firestore/core/src/firebase/firestore/model/field_mask.h
  Firestore/core/src/firebase/firestore/model/field_transform.h
  Firestore/core/src/firebase/firestore/model/transform_operations.h
Labels: api: firestore, cla: yes

#2475 Update release notes for Functions.
  Functions/CHANGELOG.md
Labels: cla: yes

#2407 Introduce Zip File Builder (in Swift)
  .gitignore
  ZipBuilder/.gitignore
  ZipBuilder/FirebaseSDKs.proto
  ZipBuilder/Package.swift
  ZipBuilder/README.md
  ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
  ZipBuilder/Sources/ZipBuilder/FileManager+Utils.swift
  ZipBuilder/Sources/ZipBuilder/FirebaseSDKs.pb.swift
  ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
  ZipBuilder/Sources/ZipBuilder/LaunchArgs.swift
  ZipBuilder/Sources/ZipBuilder/ManifestReader.swift
  ZipBuilder/Sources/ZipBuilder/Release.pb.swift
  ZipBuilder/Sources/ZipBuilder/Release.proto
  ZipBuilder/Sources/ZipBuilder/ResourcesManager.swift
  ZipBuilder/Sources/ZipBuilder/ShellUtils.swift
  ZipBuilder/Sources/ZipBuilder/Subspec.swift
  ZipBuilder/Sources/ZipBuilder/URL+Utils.swift
  ZipBuilder/Sources/ZipBuilder/Zip.swift
  ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
  ZipBuilder/Sources/ZipBuilder/main.swift
  ZipBuilder/Template/Crash/batch-upload
  ZipBuilder/Template/Crash/dump_syms
  ZipBuilder/Template/Crash/extract-keys
  ZipBuilder/Template/Crash/upload-sym
  ZipBuilder/Template/Crash/upload-sym-util.bash
  ZipBuilder/Template/Crash/upload-sym.sh
  ZipBuilder/Template/Firebase.h
  ZipBuilder/Template/FrameworkMaker.xcodeproj/project.pbxproj
  ZipBuilder/Template/Info.plist
  ZipBuilder/Template/NOTICES
  ZipBuilder/Template/README.md
  ZipBuilder/Template/module.modulemap
Labels: cla: yes

#2473 Switch FieldValue to use immutable::sorted_map (instead of std::map)
  Firestore/core/src/firebase/firestore/model/field_value.cc
  Firestore/core/src/firebase/firestore/model/field_value.h
  Firestore/core/src/firebase/firestore/model/mutation.cc
  Firestore/core/src/firebase/firestore/remote/serializer.cc
  Firestore/core/test/firebase/firestore/model/document_test.cc
  Firestore/core/test/firebase/firestore/model/field_value_test.cc
  Firestore/core/test/firebase/firestore/model/mutation_test.cc
  Firestore/core/test/firebase/firestore/remote/serializer_test.cc
  Firestore/core/test/firebase/firestore/testutil/testutil.cc
  Firestore/core/test/firebase/firestore/testutil/testutil.h
Labels: api: firestore, cla: yes

#2486 Bump the patch version of FirebaseInstanceID.
  FirebaseInstanceID.podspec
Labels: cla: yes

#2484 Use `CaseIterable` from Xcode 10+.
  ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
  ZipBuilder/Sources/ZipBuilder/LaunchArgs.swift
  ZipBuilder/Sources/ZipBuilder/Subspec.swift
  ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
Labels: cla: yes

#2487 Bump the minor version.
  FirebaseInstanceID.podspec
Labels: cla: yes

#2483 Adding unit tests for InstanceID tvOS support
  Example/Firebase.xcodeproj/project.pbxproj
  Example/Firebase.xcodeproj/xcshareddata/xcschemes/AllUnitTests_tvOS.xcscheme
  Example/Firebase.xcodeproj/xcshareddata/xcschemes/InstanceID_Example_tvOS.xcscheme
  Example/Firebase.xcodeproj/xcshareddata/xcschemes/InstanceID_Tests_tvOS.xcscheme
  Example/InstanceID/App/tvOS/AppDelegate.h
  Example/InstanceID/App/tvOS/AppDelegate.m
  Example/InstanceID/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  Example/InstanceID/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Contents.json
  Example/InstanceID/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Contents.json
  Example/InstanceID/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  Example/InstanceID/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Contents.json
  Example/InstanceID/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  Example/InstanceID/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Contents.json
  Example/InstanceID/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  Example/InstanceID/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Contents.json
  Example/InstanceID/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Contents.json
  Example/InstanceID/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  Example/InstanceID/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Contents.json
  Example/InstanceID/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  Example/InstanceID/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Contents.json
  Example/InstanceID/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json
  Example/InstanceID/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image Wide.imageset/Contents.json
  Example/InstanceID/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json
  Example/InstanceID/App/tvOS/Assets.xcassets/Contents.json
  Example/InstanceID/App/tvOS/Assets.xcassets/Launch Image.launchimage/Contents.json
  Example/InstanceID/App/tvOS/Base.lproj/Main.storyboard
  Example/InstanceID/App/tvOS/Info.plist
  Example/InstanceID/App/tvOS/ViewController.h
  Example/InstanceID/App/tvOS/ViewController.m
  Example/InstanceID/App/tvOS/main.m
  Example/InstanceID/Tests/FIRInstanceIDAPNSInfoTest.m
  Example/InstanceID/Tests/FIRInstanceIDAuthKeyChainTest.m
  Example/InstanceID/Tests/FIRInstanceIDTest.m
  Example/InstanceID/Tests/FIRInstanceIDTokenInfoTest.m
  Example/InstanceID/Tests/FIRInstanceIDTokenManager+Test.h
  Example/InstanceID/Tests/FIRInstanceIDTokenManagerTest.m
  Example/Podfile
Labels: cla: yes

#1864 Use test specs for Functions unit tests
  .gitignore
  .travis.yml
  FirebaseFunctions.podspec
  Functions/Backend/start.sh
  Functions/Example/Podfile
  Functions/README.md
  Gemfile
  Gemfile.lock
  scripts/build.sh
  scripts/if_changed.sh
  scripts/install_prereqs.sh
Labels: Infrastructure, api: functions, cla: yes

#2494 Add xcov instructions in README
  README.md
Labels: cla: yes

#2378 Collection Group Queries port to iOS
  Firestore/CHANGELOG.md
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
  Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
  Firestore/Example/Tests/Local/FSTLevelDBMigrationsTests.mm
  Firestore/Example/Tests/Local/FSTMemoryRemoteDocumentCacheTests.mm
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Example/Tests/SpecTests/json/query_spec_test.json
  Firestore/Source/API/FIRFirestore+Internal.h
  Firestore/Source/API/FIRFirestore.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/Core/FSTQuery.h
  Firestore/Source/Core/FSTQuery.mm
  Firestore/Source/Local/FSTLevelDB.mm
  Firestore/Source/Local/FSTLocalDocumentsView.h
  Firestore/Source/Local/FSTLocalDocumentsView.mm
  Firestore/Source/Local/FSTLocalStore.mm
  Firestore/Source/Local/FSTMemoryPersistence.mm
  Firestore/Source/Local/FSTPersistence.h
  Firestore/Source/Public/FIRFirestore.h
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/Swift/Tests/API/BasicCompileTests.swift
  Firestore/core/src/firebase/firestore/core/query.h
  Firestore/core/src/firebase/firestore/local/CMakeLists.txt
  Firestore/core/src/firebase/firestore/local/index_manager.h
  Firestore/core/src/firebase/firestore/local/leveldb_index_manager.h
  Firestore/core/src/firebase/firestore/local/leveldb_index_manager.mm
  Firestore/core/src/firebase/firestore/local/leveldb_key.cc
  Firestore/core/src/firebase/firestore/local/leveldb_key.h
  Firestore/core/src/firebase/firestore/local/leveldb_migrations.cc
  Firestore/core/src/firebase/firestore/local/leveldb_mutation_queue.mm
  Firestore/core/src/firebase/firestore/local/leveldb_remote_document_cache.mm
  Firestore/core/src/firebase/firestore/local/memory_index_manager.cc
  Firestore/core/src/firebase/firestore/local/memory_index_manager.h
  Firestore/core/src/firebase/firestore/local/memory_mutation_queue.mm
  Firestore/core/src/firebase/firestore/local/memory_remote_document_cache.h
  Firestore/core/src/firebase/firestore/local/memory_remote_document_cache.mm
  Firestore/core/src/firebase/firestore/model/document_key.h
  Firestore/core/src/firebase/firestore/remote/serializer.cc
  Firestore/core/test/firebase/firestore/local/CMakeLists.txt
  Firestore/core/test/firebase/firestore/local/index_manager_test.h
  Firestore/core/test/firebase/firestore/local/index_manager_test.mm
  Firestore/core/test/firebase/firestore/local/leveldb_index_manager_test.mm
  Firestore/core/test/firebase/firestore/local/leveldb_key_test.cc
  Firestore/core/test/firebase/firestore/local/memory_index_manager_test.mm
Labels: api: firestore, cla: yes

#2474 Update CHANGELOG for 5.18.0
  Firebase/Messaging/CHANGELOG.md
Labels: cla: yes

#2488 Add missing nil check
  Firebase/Database/CHANGELOG.md
  Firebase/Database/third_party/SocketRocket/FSRWebSocket.m
Labels: cla: yes

#2504 Restore GULLogger APIs, unit tests, and contents
  Firebase/Core/FIRLogger.m
  GoogleUtilities/Example/Tests/Logger/GULOSLoggerTest.m
  GoogleUtilities/Logger/GULASLLogger.m
  GoogleUtilities/Logger/GULLogger.m
  GoogleUtilities/Logger/GULOSLogger.m
  GoogleUtilities/Logger/Private/GULLogger.h
  GoogleUtilities/Logger/Private/GULLoggerSystem.h
Labels: cla: yes

#2514 Delete test with new
  GoogleUtilities/Example/Tests/Swizzler/GULRuntimeClassSnapshotTests.m
Labels: GoogleUtilities, cla: yes

#2501 Change sample code to use "microsoft.com" instead of string constant,…
  Example/Auth/Sample/MainViewController.m
Labels: cla: yes

#2509 Add Firebase info to checkin requests (directly from FIRInstanceIDCheckinService) - b/124533860
  Example/InstanceID/Tests/FIRInstanceIDCheckinServiceTest.m
  Firebase/InstanceID/FIRInstanceIDCheckinService.h
  Firebase/InstanceID/FIRInstanceIDCheckinService.m
Labels: cla: yes

#2513 Use free() for memory allocated with malloc.
  Firestore/core/src/firebase/firestore/nanopb/nanopb_string.cc
  Firestore/core/src/firebase/firestore/nanopb/nanopb_string.h
Labels: api: firestore, cla: yes

#2478 FIRDynamicLink: preserve all parameters passed to initializer
  Example/DynamicLinks/Tests/FIRDynamicLinksTest.m
  Firebase/DynamicLinks/FIRDynamicLink+Private.h
  Firebase/DynamicLinks/FIRDynamicLink.m
Labels: api: dynamiclinks, cla: yes

#2506 Add community supported tvOS and macOS for FirebaseFunctions
  FirebaseFunctions.podspec
  Functions/CHANGELOG.md
  README.md
Labels: api: functions, cla: yes, tvOS

#2507 Feedback for #2492 in the form of a PR
  Firestore/Example/Tests/API/FIRQuerySnapshotTests.mm
  Firestore/Example/Tests/API/FSTAPIHelpers.mm
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
  Firestore/Source/API/FIRCollectionReference.mm
  Firestore/Source/API/FIRDocumentChange+Internal.h
  Firestore/Source/API/FIRDocumentChange.mm
  Firestore/Source/API/FIRDocumentReference+Internal.h
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRDocumentSnapshot+Internal.h
  Firestore/Source/API/FIRDocumentSnapshot.mm
  Firestore/Source/API/FIRFirestore+Internal.h
  Firestore/Source/API/FIRFirestore.mm
  Firestore/Source/API/FIRQuerySnapshot.mm
  Firestore/Source/API/FIRTransaction.mm
  Firestore/Source/API/FSTFirestoreComponent.mm
  Firestore/core/src/firebase/firestore/api/firestore.h
  Firestore/core/src/firebase/firestore/api/firestore.mm
Labels: api: firestore, cla: yes

#2491 Add image on notification support
  Example/Firebase.xcodeproj/project.pbxproj
  Example/Messaging/Tests/FIRMessagingExtensionHelperTest.m
  Firebase/Messaging/FIRMMessageCode.h
  Firebase/Messaging/FIRMessaging.m
  Firebase/Messaging/FIRMessagingExtensionHelper.m
  Firebase/Messaging/Public/FIRMessaging.h
  Firebase/Messaging/Public/FIRMessagingExtensionHelper.h
  Firebase/Messaging/Public/FirebaseMessaging.h
Labels: cla: yes

#2518 Instead of using UIApplicationDelegate's window property (optional) to size the UIWindow for in-app messages, use UIScreen bounds
  Firebase/InAppMessagingDisplay/FIDRenderingWindowHelper.m
Labels: cla: yes

#2521 make VerifyAssertion is valid with pendingToken
  Firebase/Auth/Source/RPCs/FIRVerifyAssertionRequest.m
Labels: cla: yes

#2520 Update CHANGELOG for Firestore v1.1.0
  Firestore/CHANGELOG.md
Labels: api: firestore, cla: yes

#2515 Allow Bundle IDs that have a valid prefix - strict validation
  Example/Core/Tests/FIRBundleUtilTest.m
  Firebase/Core/FIRApp.m
  Firebase/Core/FIRBundleUtil.m
  Firebase/Core/Private/FIRBundleUtil.h
  FirebaseCore.podspec
Labels: cla: yes

#2523 Only assign message validation regex once
  GoogleUtilities/Logger/GULASLLogger.m
  GoogleUtilities/Logger/GULLogger.m
  GoogleUtilities/Logger/GULOSLogger.m
Labels: GoogleUtilities, cla: yes

#2524 Remove unused loggerWithLevel parameter
  GoogleUtilities/Example/Tests/Logger/GULOSLoggerTest.m
  GoogleUtilities/Logger/GULASLLogger.m
  GoogleUtilities/Logger/GULLogger.m
  GoogleUtilities/Logger/GULOSLogger.m
  GoogleUtilities/Logger/Private/GULLoggerSystem.h
Labels: cla: yes

#2526 Fix build (unused parameter) under mac/cmake/clang
  Firestore/core/src/firebase/firestore/model/transform_operations.h
Labels: api: firestore, cla: yes

#2517 deprecate Microsoft and Yahoo Auth Provider ID
  Firebase/Auth/Source/Public/FIROAuthProvider.h
Labels: cla: yes

#2532 FIAM release notes for M45
  Firebase/InAppMessagingDisplay/CHANGELOG.md
Labels: cla: yes

#2531 Update project and fix warnings
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/AllTests_iOS.xcscheme
  Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_Example_iOS.xcscheme
  Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_FuzzTests_iOS.xcscheme
  Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_IntegrationTests_iOS.xcscheme
  Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_SwiftTests_iOS.xcscheme
  Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_Tests_iOS.xcscheme
  Firestore/Example/Tests/API/FIRQuerySnapshotTests.mm
  Firestore/Example/Tests/API/FSTAPIHelpers.h
  Firestore/Example/Tests/API/FSTAPIHelpers.mm
  Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
  Firestore/Example/Tests/Core/FSTViewSnapshotTest.mm
  Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
  Firestore/Example/Tests/Integration/API/FIRFieldsTests.mm
  Firestore/Example/Tests/Integration/API/FIRNumericTransformTests.mm
  Firestore/Example/Tests/Integration/API/FIRServerTimestampTests.mm
  Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
  Firestore/Example/Tests/Model/FSTFieldValueTests.mm
  Firestore/Example/Tests/Util/FSTHelpers.h
  Firestore/Source/Local/FSTLevelDB.mm
  Firestore/core/test/firebase/firestore/model/field_value_test.cc
Labels: api: firestore, cla: yes

#2536 Update CHANGELOG.md
  Firebase/DynamicLinks/CHANGELOG.md
Labels: cla: yes

#2530 Don't create credential when VerifyAssertionResponse is empty
  Firebase/Auth/Source/RPCs/FIRAuthBackend.m
Labels: cla: yes

#2535 Adding deprecation warning and update CHANGELOG
  Firebase/InstanceID/CHANGELOG.md
  Firebase/Messaging/CHANGELOG.md
  Firebase/Messaging/Public/FIRMessaging.h
Labels: api: messaging, cla: yes

#2538 Update Changelog for Auth v5.4.1
  Firebase/Auth/CHANGELOG.md
Labels: cla: yes

#2537 M45 Core release notes
  Firebase/Core/CHANGELOG.md
Labels: cla: yes

#2516 Moving FIRAnalyticsConfiguration calls to Analytics.
  Firebase/Core/CHANGELOG.md
  Firebase/Core/FIRAnalyticsConfiguration.m
  Firebase/Core/FIRApp.m
  Firebase/Core/FIRConfiguration.m
  Firebase/Core/Public/FIRAnalyticsConfiguration.h
  Firebase/Core/Public/FIRConfiguration.h
Labels: api: core, cla: yes

#2542 extract errorMessage directly from response when server returns 200
  Firebase/Auth/CHANGELOG.md
  Firebase/Auth/Source/RPCs/FIRAuthBackend.m
Labels: api: auth, cla: yes

#2528 Implement PatchingDeletedDocumentsDoesNothing test
  Firestore/core/test/firebase/firestore/model/mutation_test.cc
Labels: api: firestore, cla: yes

#2519 GoogleUtilities 5.4.0
  GoogleUtilities.podspec
  GoogleUtilities/CHANGELOG.md
Labels: cla: yes

#2496 File directory for tvOS should change from NSApplicationSupportDirector to NSCachesDirectory
  Example/Firebase.xcodeproj/project.pbxproj
  Example/InstanceID/Tests/FIRInstanceIDBackupExcludedPlistTest.m
  Example/InstanceID/Tests/FIRInstanceIDCheckinStoreTest.m
  Example/InstanceID/Tests/FIRInstanceIDKeyPairStoreTest.m
  Example/InstanceID/Tests/FIRInstanceIDStoreTest.m
  Example/InstanceID/Tests/FIRInstanceIDTokenManagerTest.m
  Example/Messaging/Tests/FIRMessagingExtensionHelperTest.m
  Firebase/InstanceID/FIRInstanceID.m
  Firebase/InstanceID/FIRInstanceIDBackupExcludedPlist.h
  Firebase/InstanceID/FIRInstanceIDBackupExcludedPlist.m
  Firebase/InstanceID/FIRInstanceIDCheckinStore.h
  Firebase/InstanceID/FIRInstanceIDCheckinStore.m
  Firebase/InstanceID/FIRInstanceIDConstants.h
  Firebase/InstanceID/FIRInstanceIDConstants.m
  Firebase/InstanceID/FIRInstanceIDKeyPairStore.m
  Firebase/InstanceID/FIRInstanceIDStore.h
  Firebase/InstanceID/FIRInstanceIDStore.m
  Firebase/Messaging/FIRMessaging.m
  Firebase/Messaging/FIRMessagingConstants.h
  Firebase/Messaging/FIRMessagingConstants.m
  Firebase/Messaging/FIRMessagingRmq2PersistentStore.m
  Firebase/Messaging/FIRMessagingUtilities.h
  Firebase/Messaging/FIRMessagingUtilities.m
Labels: api: messaging, cla: yes

#2549 Update CHANGELOG.md
  Firebase/Auth/CHANGELOG.md
Labels: cla: yes

#2547 Disable Facebook API tests
  Example/Auth/ApiTests/FacebookAuthTests.m
Labels: cla: yes

#2548 FIRInstanceIDCheckinService: make sure tasks are not submitted to an invalidated NSURLSession
  Example/InstanceID/Tests/FIRInstanceIDCheckinServiceTest.m
  Firebase/InstanceID/FIRIMessageCode.h
  Firebase/InstanceID/FIRInstanceIDCheckinService.m
Labels: cla: yes

#2552 Fix GULResetLogger API breakage
  GoogleUtilities.podspec
  GoogleUtilities/CHANGELOG.md
  GoogleUtilities/Logger/GULLogger.m
Labels: cla: yes

#2553 Rename ApplicationSupportDirectory in IID tests
  Example/InstanceID/Tests/FIRInstanceIDAuthKeyChainTest.m
  Example/InstanceID/Tests/FIRInstanceIDBackupExcludedPlistTest.m
  Example/InstanceID/Tests/FIRInstanceIDCheckinStoreTest.m
  Example/InstanceID/Tests/FIRInstanceIDStoreTest.m
  Example/InstanceID/Tests/FIRInstanceIDTokenManagerTest.m
  Firebase/InstanceID/FIRInstanceID.m
  Firebase/InstanceID/FIRInstanceIDBackupExcludedPlist.m
  Firebase/Messaging/FIRMessaging.m
Labels: cla: yes

#2554 Clean the pod cache before starting.
  ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
  ZipBuilder/Sources/ZipBuilder/ShellUtils.swift
  ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
Labels: cla: yes

#2557 InstanceID changelog update
  Firebase/InstanceID/CHANGELOG.md
Labels: cla: yes

#2556 Restore GoogleUtilities 5.3.7 - revert os_log changes
  Example/Core/Tests/FIRLoggerTest.m
  Firebase/Core/FIRLogger.m
  GoogleUtilities.podspec
  GoogleUtilities/CHANGELOG.md
  GoogleUtilities/Example/GoogleUtilities.xcodeproj/project.pbxproj
  GoogleUtilities/Example/Tests/Logger/GULASLLoggerTest.m
  GoogleUtilities/Example/Tests/Logger/GULLoggerTest.m
  GoogleUtilities/Example/Tests/Logger/GULOSLoggerTest.m
  GoogleUtilities/Example/Tests/Swizzler/GULRuntimeClassSnapshotTests.m
  GoogleUtilities/Logger/GULASLLogger.h
  GoogleUtilities/Logger/GULASLLogger.m
  GoogleUtilities/Logger/GULLogger+Internal.h
  GoogleUtilities/Logger/GULLogger.m
  GoogleUtilities/Logger/GULOSLogger.h
  GoogleUtilities/Logger/GULOSLogger.m
  GoogleUtilities/Logger/Private/GULLogger.h
  GoogleUtilities/Logger/Private/GULLoggerSystem.h
  GoogleUtilities/Logger/Public/GULLoggerLevel.h
Labels: cla: yes

#2560 Overwrite CoreDiagnostics framework with framework passed in.
  ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
Labels: cla: yes

#2529 Avoid using NSRegularExpression in FIRApp (b/65122393)
  Example/Core/Tests/FIRAppTest.m
  Firebase/Core/FIRApp.m
Labels: cla: yes

#2561 Changes to build m45 zip
  ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
  ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
  ZipBuilder/Sources/ZipBuilder/Subspec.swift
Labels: cla: yes

#2533 Add a run-all-checks script
  .travis.yml
  scripts/check.sh
Labels: api: firestore, cla: yes

#2567 Fix resources packaging.
  ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
Labels: cla: yes

#2568 Disable flaky tests in FIAM
  InAppMessaging/Example/Tests/FIRIAMClearcutUploaderTests.m
Labels: api: inappmessaging, cla: yes

#2570 Fix method names in CHANGELOG
  Firebase/Core/CHANGELOG.md
Labels: cla: yes

#2492 C++ migration: make `FIRFirestore` implementation delegate to core API
  Firestore/Example/Tests/API/FIRQuerySnapshotTests.mm
  Firestore/Example/Tests/API/FSTAPIHelpers.mm
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
  Firestore/Source/API/FIRCollectionReference.mm
  Firestore/Source/API/FIRDocumentChange+Internal.h
  Firestore/Source/API/FIRDocumentChange.mm
  Firestore/Source/API/FIRDocumentReference+Internal.h
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRDocumentSnapshot+Internal.h
  Firestore/Source/API/FIRDocumentSnapshot.mm
  Firestore/Source/API/FIRFirestore+Internal.h
  Firestore/Source/API/FIRFirestore.mm
  Firestore/Source/API/FIRQuerySnapshot.mm
  Firestore/Source/API/FIRTransaction.mm
  Firestore/Source/API/FSTFirestoreComponent.mm
  Firestore/Source/Core/FSTFirestoreClient.h
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/core/src/firebase/firestore/api/document_reference.h
  Firestore/core/src/firebase/firestore/api/document_reference.mm
  Firestore/core/src/firebase/firestore/api/document_snapshot.h
  Firestore/core/src/firebase/firestore/api/document_snapshot.mm
  Firestore/core/src/firebase/firestore/api/firestore.h
  Firestore/core/src/firebase/firestore/api/firestore.mm
  Firestore/core/src/firebase/firestore/util/statusor_callback.h
Labels: api: firestore, cla: yes

#2566 Revert "Disable Facebook API tests"
  Example/Auth/ApiTests/FacebookAuthTests.m
Labels: cla: yes

#2569 Travis: when linting Firestore, only lint iOS
  .travis.yml
  scripts/pod_lib_lint.sh
Labels: api: firestore, cla: yes

#2573 Revert "Revert "Disable Facebook API tests (#2547)" (#2566)"
  Example/Auth/ApiTests/FacebookAuthTests.m
Labels: cla: yes

#2576 Fix typos
  Example/Auth/Tests/FIROAuthProviderTests.m
  Firebase/Auth/Source/AuthProviders/OAuth/FIROAuthProvider.m
  Firebase/Auth/Source/FIRAuthInternalErrors.h
  Firebase/Auth/Source/FIRUser.m
  Firebase/Auth/Source/Public/FIRAuth.h
Labels: api: auth, cla: yes

#2577 Retain OAuthProvider instance in sample app
  Example/Auth/Sample/MainViewController.m
Labels: cla: yes

#2578 Upgrade project to CocoaPods 1.6.1
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
Labels: api: firestore, cla: yes

#2583 update the changelog
  Firebase/Messaging/CHANGELOG.md
Labels: cla: yes

#2582 Revert #2491
  Example/Firebase.xcodeproj/project.pbxproj
  Example/Messaging/Tests/FIRMessagingExtensionHelperTest.m
  Firebase/Messaging/FIRMMessageCode.h
  Firebase/Messaging/FIRMessaging.m
  Firebase/Messaging/FIRMessagingExtensionHelper.m
  Firebase/Messaging/Public/FIRMessaging.h
  Firebase/Messaging/Public/FIRMessagingExtensionHelper.h
  Firebase/Messaging/Public/FirebaseMessaging.h
Labels: cla: yes

#2574 Eliminate Objective-C BOOL in Firestore/core
  Firestore/Example/Tests/Local/FSTLRUGarbageCollectorTests.mm
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/Source/Local/FSTLRUGarbageCollector.h
  Firestore/Source/Local/FSTLRUGarbageCollector.mm
  Firestore/Source/Local/FSTLevelDB.mm
  Firestore/Source/Local/FSTMemoryPersistence.mm
  Firestore/Source/Model/FSTDocument.h
  Firestore/Source/Model/FSTDocument.mm
  Firestore/core/src/firebase/firestore/local/CMakeLists.txt
  Firestore/core/src/firebase/firestore/local/leveldb_query_cache.h
  Firestore/core/src/firebase/firestore/local/leveldb_query_cache.mm
  Firestore/core/src/firebase/firestore/local/memory_query_cache.h
  Firestore/core/src/firebase/firestore/local/memory_query_cache.mm
  Firestore/core/src/firebase/firestore/local/query_cache.h
  Firestore/core/src/firebase/firestore/util/CMakeLists.txt
  Firestore/core/src/firebase/firestore/util/objc_compatibility.h
  Firestore/core/test/firebase/firestore/util/objc_compatibility_apple_test.mm
  cmake/cc_rules.cmake
Labels: api: firestore, cla: yes

#2527 Create ObjectValue as a wrapper around a FieldValue which contains a map
  Firestore/core/src/firebase/firestore/local/local_serializer.cc
  Firestore/core/src/firebase/firestore/model/document.cc
  Firestore/core/src/firebase/firestore/model/document.h
  Firestore/core/src/firebase/firestore/model/field_value.cc
  Firestore/core/src/firebase/firestore/model/field_value.h
  Firestore/core/src/firebase/firestore/model/mutation.cc
  Firestore/core/src/firebase/firestore/model/mutation.h
  Firestore/core/src/firebase/firestore/remote/serializer.cc
  Firestore/core/src/firebase/firestore/remote/serializer.h
  Firestore/core/test/firebase/firestore/local/local_serializer_test.cc
  Firestore/core/test/firebase/firestore/model/document_test.cc
  Firestore/core/test/firebase/firestore/model/field_value_test.cc
  Firestore/core/test/firebase/firestore/model/mutation_test.cc
  Firestore/core/test/firebase/firestore/remote/serializer_test.cc
  Firestore/core/test/firebase/firestore/testutil/testutil.cc
  Firestore/core/test/firebase/firestore/testutil/testutil.h
Labels: cla: yes

#2563 Fix for issue where matchesshortlinkformat was returning true for all links.
  Example/DynamicLinks/Tests/FIRDynamicLinksTest.m
  Firebase/DynamicLinks/Utilities/FDLUtilities.m
Labels: cla: yes

#2581 Port FIRQuerySnapshot to C++
  Firestore/Example/Tests/API/FIRQuerySnapshotTests.mm
  Firestore/Example/Tests/API/FSTAPIHelpers.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/API/FIRQuerySnapshot+Internal.h
  Firestore/Source/API/FIRQuerySnapshot.mm
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/core/src/firebase/firestore/api/query_snapshot.h
  Firestore/core/src/firebase/firestore/api/query_snapshot.mm
Labels: api: firestore, cla: yes

#2594 Show qualified usage of Timestamp
  Firestore/Swift/Tests/API/BasicCompileTests.swift
Labels: api: firestore, cla: yes

#2579 Add DelayedConstructor<T>
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
  Firestore/Source/API/FIRFirestore.mm
  Firestore/core/src/firebase/firestore/util/CMakeLists.txt
  Firestore/core/src/firebase/firestore/util/delayed_constructor.h
  Firestore/core/test/firebase/firestore/util/CMakeLists.txt
  Firestore/core/test/firebase/firestore/util/delayed_constructor_test.cc
  scripts/check.sh
Labels: api: firestore, cla: yes

#2597 Exclude sub-packages of abseil that are problematic
  FirebaseFirestore.podspec
Labels: api: firestore, cla: yes, tvOS

#2596 Temporarily make FIAM tests non-required
  .travis.yml
Labels: cla: yes

#2598 Update tvOS and macOS README
  README.md
Labels: cla: yes

#2599 Update Carthage instructions for FirebaseMLNLSmartReplyBinary
  Carthage.md
Labels: cla: yes

#2600 b/62961699: Use :nodoc: to prevent methods from showing up in reference docs.
  Firestore/Source/Public/FIRCollectionReference.h
  Firestore/Source/Public/FIRDocumentChange.h
  Firestore/Source/Public/FIRDocumentReference.h
  Firestore/Source/Public/FIRDocumentSnapshot.h
  Firestore/Source/Public/FIRFieldValue.h
  Firestore/Source/Public/FIRFirestore.h
  Firestore/Source/Public/FIRGeoPoint.h
  Firestore/Source/Public/FIRQuery.h
  Firestore/Source/Public/FIRQuerySnapshot.h
  Firestore/Source/Public/FIRSnapshotMetadata.h
  Firestore/Source/Public/FIRTimestamp.h
  Firestore/Source/Public/FIRTransaction.h
Labels: cla: yes

#2605 Remove stale roadmap items
  ROADMAP.md
Labels: cla: yes

#2601 GULLogger - count errors and warnigns
  GoogleUtilities/Example/Tests/Logger/GULLoggerTest.m
  GoogleUtilities/Logger/GULLogger.m
  GoogleUtilities/Logger/Private/GULLogger.h
Labels: cla: yes

#2595 Add xcgmock
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
  Firestore/Example/Tests/Core/FSTViewTests.mm
  Firestore/core/include/firebase/firestore/timestamp.h
  Firestore/core/src/firebase/firestore/core/view_snapshot.h
  Firestore/core/src/firebase/firestore/core/view_snapshot.mm
  Firestore/core/src/firebase/firestore/timestamp.cc
  Firestore/core/src/firebase/firestore/util/status.cc
  Firestore/core/src/firebase/firestore/util/status.h
  Firestore/core/test/firebase/firestore/testutil/CMakeLists.txt
  Firestore/core/test/firebase/firestore/testutil/xcgmock.h
  Firestore/core/test/firebase/firestore/testutil/xcgmock_test.mm
Labels: api: firestore, cla: yes

#2606 Rework gRPC certificate loading one last time
  Firestore/CHANGELOG.md
  Firestore/Example/App/iOS/Images.xcassets/AppIcon.appiconset/Contents.json
  Firestore/Example/App/macOS_example/AppDelegate.m
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/core/src/firebase/firestore/remote/grpc_root_certificate_finder_apple.mm
Labels: api: firestore, cla: yes

#2602 Lay the groundwork for CCT support, and include the prioritizer imple…
  .travis.yml
  GoogleDataTransport/Tests/Unit/GDTUploadCoordinatorTest.m
  GoogleDataTransportCCTSupport.podspec
  GoogleDataTransportCCTSupport/CHANGELOG.md
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/Classes/GDTCCTPrioritizer.m
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/Classes/GDTCCTUploader.m
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/Classes/Private/GDTCCTPrioritizer.h
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/Classes/Private/GDTCCTUploader.h
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/ProtoSupport/README.md
  GoogleDataTransportCCTSupport/README.md
  GoogleDataTransportCCTSupport/Tests/Unit/GDTCCTPrioritizerTest.m
  GoogleDataTransportCCTSupport/Tests/Unit/GDTCCTUploaderTest.m
  GoogleDataTransportCCTSupport/Tests/Unit/Helpers/GDTCCTEventGenerator.h
  GoogleDataTransportCCTSupport/Tests/Unit/Helpers/GDTCCTEventGenerator.m
  GoogleDataTransportCCTSupport/generate_project.sh
  scripts/build.sh
  scripts/if_changed.sh
  scripts/install_prereqs.sh
Labels: cla: yes

#2588 Add support to [de]serialize missing FV types to the remote serializer
  Firestore/core/src/firebase/firestore/model/field_value.h
  Firestore/core/src/firebase/firestore/remote/serializer.cc
  Firestore/core/src/firebase/firestore/remote/serializer.h
  Firestore/core/test/firebase/firestore/remote/serializer_test.cc
Labels: cla: yes

#2610 GULLogger - issue count synchronous getters
  GoogleUtilities/Example/Tests/Logger/GULLoggerTest.m
  GoogleUtilities/Logger/GULLogger.m
  GoogleUtilities/Logger/Private/GULLogger.h
Labels: cla: yes

#2562 Ensure token refresh notification is triggered any time a new token is refreshed. b/77662386
  Example/InstanceID/Tests/FIRInstanceIDTest.m
  Firebase/InstanceID/FIRInstanceID+Testing.h
  Firebase/InstanceID/FIRInstanceID.m
Labels: cla: yes

#2489 Port FSTLocalDocumentsView to C++
  Firestore/Source/Local/FSTLocalDocumentsView.h
  Firestore/Source/Local/FSTLocalDocumentsView.mm
  Firestore/Source/Local/FSTLocalStore.mm
  Firestore/core/src/firebase/firestore/local/CMakeLists.txt
  Firestore/core/src/firebase/firestore/local/local_documents_view.h
  Firestore/core/src/firebase/firestore/local/local_documents_view.mm
Labels: api: firestore, cla: yes

#2614 Improve error message
  Firebase/Core/FIRApp.m
Labels: cla: yes

#2613 Fix all IID analyzer warnings
  Firebase/InstanceID/FIRInstanceIDAuthKeyChain.m
  Firebase/InstanceID/FIRInstanceIDKeyPairStore.m
  Firebase/InstanceID/FIRInstanceIDStore.h
  Firebase/InstanceID/FIRInstanceIDTokenDeleteOperation.h
  Firebase/InstanceID/FIRInstanceIDTokenOperation.h
Labels: cla: yes

#2621 Avoid retain cycles in parent pointers
  Firestore/core/src/firebase/firestore/local/leveldb_remote_document_cache.h
  Firestore/core/src/firebase/firestore/local/memory_mutation_queue.h
  Firestore/core/src/firebase/firestore/local/memory_query_cache.h
  Firestore/core/src/firebase/firestore/local/memory_remote_document_cache.h
Labels: api: firestore, cla: yes

#2559 Fix handler for multiple calls of -[FIRInstanceID instanceIDWithHandler:] (#2445)
  Example/InstanceID/Tests/FIRInstanceIDTest.m
  Example/default.profraw
  Firebase/InstanceID/FIRInstanceID.m
  Firebase/InstanceID/FIRInstanceIDCombinedHandler.h
  Firebase/InstanceID/FIRInstanceIDCombinedHandler.m
  default.profraw
Labels: cla: yes

#2622 Clean up warnings in the Firestore project
  Firestore/core/src/firebase/firestore/local/CMakeLists.txt
  Firestore/core/src/firebase/firestore/local/document_key_reference.cc
  Firestore/core/src/firebase/firestore/local/document_key_reference.h
  Firestore/core/src/firebase/firestore/local/local_serializer.cc
  Firestore/core/src/firebase/firestore/local/memory_mutation_queue.h
  Firestore/core/src/firebase/firestore/local/memory_mutation_queue.mm
  Firestore/core/src/firebase/firestore/local/reference_set.cc
  Firestore/core/src/firebase/firestore/local/reference_set.h
  Firestore/core/src/firebase/firestore/nanopb/nanopb_string.cc
  Firestore/core/src/firebase/firestore/nanopb/nanopb_util.h
  Firestore/core/src/firebase/firestore/remote/serializer.cc
  Firestore/core/src/firebase/firestore/remote/serializer.h
Labels: api: firestore, cla: yes

#2608 Port FSTDocumentSet to C++
  Firestore/Example/Tests/API/FIRQuerySnapshotTests.mm
  Firestore/Example/Tests/API/FSTAPIHelpers.mm
  Firestore/Example/Tests/Core/FSTEventManagerTests.mm
  Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
  Firestore/Example/Tests/Core/FSTViewSnapshotTest.mm
  Firestore/Example/Tests/Core/FSTViewTests.mm
  Firestore/Example/Tests/Local/FSTLocalStoreTests.mm
  Firestore/Example/Tests/Model/FSTDocumentSetTests.mm
  Firestore/Example/Tests/Util/FSTHelpers.h
  Firestore/Example/Tests/Util/FSTHelpers.mm
  Firestore/Source/API/FIRDocumentChange.mm
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRQuerySnapshot+Internal.h
  Firestore/Source/API/FIRQuerySnapshot.mm
  Firestore/Source/Core/FSTEventManager.mm
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/Source/Core/FSTSyncEngine.mm
  Firestore/Source/Core/FSTView.h
  Firestore/Source/Core/FSTView.mm
  Firestore/Source/Local/FSTLocalViewChanges.h
  Firestore/Source/Model/FSTDocumentSet.h
  Firestore/Source/Model/FSTDocumentSet.mm
  Firestore/core/src/firebase/firestore/api/document_reference.mm
  Firestore/core/src/firebase/firestore/api/query_snapshot.h
  Firestore/core/src/firebase/firestore/api/query_snapshot.mm
  Firestore/core/src/firebase/firestore/core/view_snapshot.h
  Firestore/core/src/firebase/firestore/core/view_snapshot.mm
  Firestore/core/src/firebase/firestore/immutable/array_sorted_map.h
  Firestore/core/src/firebase/firestore/immutable/llrb_node.h
  Firestore/core/src/firebase/firestore/immutable/sorted_container.cc
  Firestore/core/src/firebase/firestore/immutable/sorted_container.h
  Firestore/core/src/firebase/firestore/immutable/sorted_map.h
  Firestore/core/src/firebase/firestore/immutable/sorted_set.h
  Firestore/core/src/firebase/firestore/immutable/tree_sorted_map.h
  Firestore/core/src/firebase/firestore/model/document_set.h
  Firestore/core/src/firebase/firestore/model/document_set.mm
  Firestore/core/test/firebase/firestore/immutable/sorted_map_test.cc
  Firestore/core/test/firebase/firestore/immutable/sorted_set_test.cc
Labels: api: firestore, cla: yes

#2616 Add missing #include <ostream>
  Firestore/core/src/firebase/firestore/timestamp.cc
  Firestore/core/src/firebase/firestore/util/status.cc
  scripts/cpplint.py
Labels: api: firestore, cla: yes

#2546 Alter testutuil::*Doc to return shared_ptrs.
  Firestore/core/test/firebase/firestore/core/query_test.cc
  Firestore/core/test/firebase/firestore/local/local_serializer_test.cc
  Firestore/core/test/firebase/firestore/model/mutation_test.cc
  Firestore/core/test/firebase/firestore/model/precondition_test.cc
  Firestore/core/test/firebase/firestore/testutil/testutil.h
Labels: cla: yes

#2629 Support ERROR_INVALID_PROVIDER_ID in Firebase Auth.
  Firebase/Auth/Source/FIRAuthErrorUtils.h
  Firebase/Auth/Source/FIRAuthErrorUtils.m
  Firebase/Auth/Source/FIRAuthInternalErrors.h
  Firebase/Auth/Source/Public/FIRAuthErrors.h
  Firebase/Auth/Source/RPCs/FIRAuthBackend.m
Labels: cla: yes

#2633 Rework the IWYU test to handle types with multiple valid sources
  scripts/cpplint.py
Labels: api: firestore, cla: yes

#2617 Port FSTListenOptions to C++
  Firestore/Example/Tests/Core/FSTEventManagerTests.mm
  Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/Core/FSTEventManager.h
  Firestore/Source/Core/FSTEventManager.mm
  Firestore/Source/Core/FSTFirestoreClient.h
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/core/src/firebase/firestore/api/document_reference.h
  Firestore/core/src/firebase/firestore/api/document_reference.mm
  Firestore/core/src/firebase/firestore/core/CMakeLists.txt
  Firestore/core/src/firebase/firestore/core/listen_options.h
  Firestore/core/test/firebase/firestore/testutil/xcgmock.h
Labels: api: firestore, cla: yes

#2618 Port FSTQueryListener to C++
  Firestore/Example/Tests/Core/FSTEventManagerTests.mm
  Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRListenerRegistration+Internal.h
  Firestore/Source/API/FIRListenerRegistration.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/Core/FSTEventManager.h
  Firestore/Source/Core/FSTEventManager.mm
  Firestore/Source/Core/FSTFirestoreClient.h
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/Source/Util/FSTAsyncQueryListener.h
  Firestore/core/src/firebase/firestore/api/document_reference.mm
  Firestore/core/src/firebase/firestore/core/query_listener.h
  Firestore/core/src/firebase/firestore/core/query_listener.mm
  Firestore/core/src/firebase/firestore/immutable/CMakeLists.txt
  Firestore/core/src/firebase/firestore/local/memory_query_cache.h
  Firestore/core/src/firebase/firestore/util/objc_compatibility.h
  Firestore/core/test/firebase/firestore/testutil/xcgmock.h
  scripts/cpplint.py
Labels: api: firestore, cla: yes

#2638 Remove default.profraw files
  .gitignore
  Example/default.profraw
  default.profraw
Labels: cla: yes

#2631 fix race condition that checkin can be deleted right after fetched (#2438)
  Example/InstanceID/Tests/FIRInstanceIDCheckinStoreTest.m
  Firebase/InstanceID/FIRIMessageCode.h
  Firebase/InstanceID/FIRInstanceIDCheckinService.m
  Firebase/InstanceID/FIRInstanceIDCheckinStore.m
  Firebase/InstanceID/FIRInstanceIDKeyPairStore.m
  Firebase/InstanceID/FIRInstanceIDKeychain.m
  Firebase/InstanceID/FIRInstanceIDStore.m
  ZipBuilder/Sources/ZipBuilder/FrameworkBuilder.swift
Labels: cla: yes

#2612 Create a swift utility for uploading project health metrics from Travis
  Metrics/.gitignore
  Metrics/Package.resolved
  Metrics/Package.swift
  Metrics/README.md
  Metrics/Sources/Metrics/main.swift
  Metrics/Sources/MetricsLib/CoverageReport.swift
  Metrics/Sources/MetricsLib/UploadMetrics.swift
  Metrics/Tests/MetricsTests/CoverageReportTests.swift
  Metrics/Tests/MetricsTests/UploadMetricsTests.swift
  Metrics/Tests/MetricsTests/example_report.json
Labels: cla: yes

#2628 Revert "Disable Facebook API tests"
  Example/Auth/ApiTests/FacebookAuthTests.m
Labels: cla: yes

#2639 FIRApp: thread safety fixes
  Firebase/Core/FIRApp.m
Labels: cla: yes

#2623 Prepare for macOS test support
  Firestore/Example/GoogleBenchmark.podspec
  Firestore/Example/GoogleTest.podspec
  Firestore/Example/LibFuzzer.podspec
  Firestore/Example/ProtobufCpp.podspec
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/core/test/firebase/firestore/FSTGoogleTestTests.mm
Labels: api: firestore, cla: yes

#2620 Port FSTAsyncQueryListener to C++
  Firestore/Example/Tests/Core/FSTEventManagerTests.mm
  Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
  Firestore/Example/Tests/Integration/API/FIRFirestoreSourceTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/Core/FSTEventManager.mm
  Firestore/Source/Core/FSTFirestoreClient.h
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/Source/Util/FSTAsyncQueryListener.mm
  Firestore/core/src/firebase/firestore/api/document_reference.h
  Firestore/core/src/firebase/firestore/api/document_reference.mm
  Firestore/core/src/firebase/firestore/api/document_snapshot.h
  Firestore/core/src/firebase/firestore/api/listener_registration.h
  Firestore/core/src/firebase/firestore/api/listener_registration.mm
  Firestore/core/src/firebase/firestore/core/event_listener.h
  Firestore/core/src/firebase/firestore/core/query_listener.h
  Firestore/core/src/firebase/firestore/core/query_listener.mm
  Firestore/core/src/firebase/firestore/core/view_snapshot.h
  Firestore/core/test/firebase/firestore/testutil/xcgmock.h
Labels: api: firestore, cla: yes

#2627 GULLogger: logged issue counting concurrency issue fix
  GoogleUtilities/Example/Tests/Logger/GULLoggerTest.m
  GoogleUtilities/Logger/GULLogger.m
Labels: cla: yes

#2634 Update changelog for instanceID release
  Firebase/InstanceID/CHANGELOG.md
Labels: cla: yes

#2632 Expose all properties of a GDTClock, better -hash and -isEqual impls
  GoogleDataTransport.podspec
  GoogleDataTransport/GoogleDataTransport/Classes/GDTClock.m
  GoogleDataTransport/GoogleDataTransport/Classes/GDTStoredEvent.m
  GoogleDataTransport/GoogleDataTransport/Classes/Public/GDTClock.h
  GoogleDataTransport/Tests/Unit/GDTStoredEventTest.m
Labels: cla: yes

#2646 Update FDL CHANGELOG for M46.
  Firebase/DynamicLinks/CHANGELOG.md
Labels: cla: yes

#2649 Update CHANGELOG.md
  Firebase/Auth/CHANGELOG.md
Labels: cla: yes

#2641 Add support for Firestore unit tests on macOS
  Firestore/Example/App/macOS/AppDelegate.h
  Firestore/Example/App/macOS/AppDelegate.m
  Firestore/Example/App/macOS/Assets.xcassets/AppIcon.appiconset/Contents.json
  Firestore/Example/App/macOS/Assets.xcassets/Contents.json
  Firestore/Example/App/macOS/Base.lproj/MainMenu.xib
  Firestore/Example/App/macOS/Info.plist
  Firestore/Example/App/macOS/macOS.entitlements
  Firestore/Example/App/macOS/main.m
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_Example_macOS.xcscheme
  Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_Tests_macOS.xcscheme
  Firestore/Example/Podfile
  scripts/sync_project.rb
Labels: api: firestore, cla: yes

#2650 fix analyze warning in fcm
  Example/Messaging/Tests/FIRMessagingReceiverTest.m
Labels: cla: yes

#2643 Disable gRPC death tests
  Firestore/Example/App/macOS/AppDelegate.m
  Firestore/core/test/firebase/firestore/remote/grpc_stream_test.cc
  Firestore/core/test/firebase/firestore/remote/grpc_streaming_reader_test.cc
  Firestore/core/test/firebase/firestore/remote/grpc_unary_call_test.cc
Labels: api: firestore, cla: yes

#2644 add image on notification support
  Example/Firebase.xcodeproj/project.pbxproj
  Example/Messaging/Tests/FIRMessagingExtensionHelperTest.m
  Firebase/Messaging/CHANGELOG.md
  Firebase/Messaging/FIRMMessageCode.h
  Firebase/Messaging/FIRMessaging.m
  Firebase/Messaging/FIRMessagingExtensionHelper.m
  Firebase/Messaging/Public/FIRMessaging.h
  Firebase/Messaging/Public/FIRMessagingExtensionHelper.h
  Firebase/Messaging/Public/FirebaseMessaging.h
Labels: cla: yes

#2655 M46 Core Changelog
  Firebase/Core/CHANGELOG.md
Labels: cla: yes

#2645 Build Firestore macOS on Travis
  .travis.yml
  scripts/build.sh
Labels: cla: yes

#2656 Update CHANGELOG for Firestore v1.2.0
  Firestore/CHANGELOG.md
Labels: api: firestore, cla: yes

#2651 Eliminate 'instanceof' checks for FSTFieldValue
  Firestore/Example/Tests/Model/FSTFieldValueTests.mm
  Firestore/Example/Tests/Util/FSTHelpers.mm
  Firestore/Source/API/FIRDocumentSnapshot.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/Core/FSTQuery.mm
  Firestore/Source/Model/FSTFieldValue.h
  Firestore/Source/Model/FSTFieldValue.mm
  Firestore/core/src/firebase/firestore/model/field_value.h
  Firestore/core/src/firebase/firestore/model/transform_operations.h
Labels: api: firestore, cla: yes

#2657 GULAppDelegateSwizzlerTests fix
  GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
  GoogleUtilities/Example/GoogleUtilities.xcodeproj/project.pbxproj
  GoogleUtilities/Example/GoogleUtilities.xcodeproj/xcshareddata/xcschemes/Example_iOS.xcscheme
  GoogleUtilities/Example/Tests/Swizzler/GULAppDelegateSwizzlerTest.m
Labels: cla: yes

#2648 Upgrade gRPC-C++ to 0.0.8, enabling experimental tvOS support
  FirebaseFirestore.podspec
Labels: api: firestore, cla: yes

#2661 Fix build warning
  Example/DynamicLinks/Tests/FIRDynamicLinksTest.m
Labels: api: dynamiclinks, cla: yes

#2667 Temporarily enable testing the branch for #2664
  .travis.yml
Labels: api: firestore, cla: yes

#2662 Add tvOS support to Firestore
  .travis.yml
  Firestore/CHANGELOG.md
  Firestore/Example/App/tvOS/AppDelegate.h
  Firestore/Example/App/tvOS/AppDelegate.m
  Firestore/Example/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  Firestore/Example/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Contents.json
  Firestore/Example/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Contents.json
  Firestore/Example/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  Firestore/Example/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Contents.json
  Firestore/Example/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  Firestore/Example/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Contents.json
  Firestore/Example/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
  Firestore/Example/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Contents.json
  Firestore/Example/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Contents.json
  Firestore/Example/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
  Firestore/Example/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Contents.json
  Firestore/Example/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
  Firestore/Example/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Contents.json
  Firestore/Example/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json
  Firestore/Example/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image Wide.imageset/Contents.json
  Firestore/Example/App/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json
  Firestore/Example/App/tvOS/Assets.xcassets/Contents.json
  Firestore/Example/App/tvOS/Assets.xcassets/Launch Image.launchimage/Contents.json
  Firestore/Example/App/tvOS/Base.lproj/Main.storyboard
  Firestore/Example/App/tvOS/Info.plist
  Firestore/Example/App/tvOS/ViewController.h
  Firestore/Example/App/tvOS/ViewController.m
  Firestore/Example/App/tvOS/main.m
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_Example_tvOS.xcscheme
  Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_IntegrationTests_tvOS.xcscheme
  Firestore/Example/Firestore.xcodeproj/xcshareddata/xcschemes/Firestore_Tests_tvOS.xcscheme
  Firestore/Example/GoogleBenchmark.podspec
  Firestore/Example/GoogleTest.podspec
  Firestore/Example/LibFuzzer.podspec
  Firestore/Example/Podfile
  Firestore/Example/ProtobufCpp.podspec
  README.md
  scripts/build.sh
  scripts/sync_project.rb
Labels: api: firestore, cla: yes

#2670 Port FSTUsageValidation to C++
  FirebaseFirestore.podspec
  Firestore/Source/API/FIRCollectionReference.mm
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRDocumentSnapshot.mm
  Firestore/Source/API/FIRFieldPath.mm
  Firestore/Source/API/FIRFirestore.mm
  Firestore/Source/API/FIRFirestoreSettings.mm
  Firestore/Source/API/FIRGeoPoint.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/API/FIRQuerySnapshot.mm
  Firestore/Source/API/FIRTransaction.mm
  Firestore/Source/API/FIRWriteBatch.mm
  Firestore/Source/API/FSTFirestoreComponent.mm
  Firestore/Source/API/FSTUserDataConverter.mm
  Firestore/Source/Core/FSTQuery.mm
  Firestore/Source/Util/FSTUsageValidation.h
  Firestore/Source/Util/FSTUsageValidation.mm
  Firestore/core/src/firebase/firestore/api/CMakeLists.txt
  Firestore/core/src/firebase/firestore/api/document_reference.mm
  Firestore/core/src/firebase/firestore/api/input_validation.h
  Firestore/core/src/firebase/firestore/api/input_validation_apple.mm
  Firestore/core/src/firebase/firestore/api/input_validation_std.cc
  Firestore/core/src/firebase/firestore/api/query_snapshot.mm
  Firestore/core/src/firebase/firestore/core/user_data.mm
  Firestore/core/src/firebase/firestore/util/log.h
  Firestore/core/src/firebase/firestore/util/log_apple.mm
  Firestore/core/src/firebase/firestore/util/log_stdio.cc
Labels: api: firestore, cla: yes

#2672 FIRMessagingRemoteNotificationsProxy - test only public API with no assumptions on implementation
  Example/Messaging/Tests/FIRMessagingRemoteNotificationsProxyTest.m
  Firebase/Messaging/FIRMessaging.m
  Firebase/Messaging/FIRMessagingRemoteNotificationsProxy.h
  Firebase/Messaging/FIRMessagingRemoteNotificationsProxy.m
Labels: cla: yes

#2673 fix typo in iOS target
  Example/Messaging/Tests/FIRMessagingDataMessageManagerTest.m
  Firebase/Messaging/FIRMessagingCheckinService.h
  Firebase/Messaging/FIRMessagingRmq2PersistentStore.m
Labels: cla: yes

#2675 fix typo in iOS target (#2673)
  Example/Messaging/Tests/FIRMessagingDataMessageManagerTest.m
  Firebase/Messaging/FIRMessagingCheckinService.h
  Firebase/Messaging/FIRMessagingRmq2PersistentStore.m
Labels: cla: yes

#2652 Implement the CCT proto using nanopb
  GoogleDataTransport/GoogleDataTransport/Classes/Private/GDTAssert.h
  GoogleDataTransport/GoogleDataTransport/DependencyWrappers/GDTConsoleLogger.h
  GoogleDataTransportCCTSupport.podspec
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/Classes/GDTCCTNanopbHelpers.m
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/Classes/Private/GDTCCTNanopbHelpers.h
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/Classes/Protogen/nanopb/cct.nanopb.c
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/Classes/Protogen/nanopb/cct.nanopb.h
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/Classes/Protos/cct.options
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/Classes/Protos/cct.proto
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/ProtoSupport/generate_cct_protos.sh
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/ProtoSupport/nanopb_objc_generator.py
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/ProtoSupport/proto_generator.py
  GoogleDataTransportCCTSupport/Tests/Data/message-32347456.dat
  GoogleDataTransportCCTSupport/Tests/Data/message-35458880.dat
  GoogleDataTransportCCTSupport/Tests/Data/message-39882816.dat
  GoogleDataTransportCCTSupport/Tests/Data/message-40043840.dat
  GoogleDataTransportCCTSupport/Tests/Data/message-40657984.dat
  GoogleDataTransportCCTSupport/Tests/Unit/GDTCCTNanopbHelpersTest.m
  GoogleDataTransportCCTSupport/Tests/Unit/Helpers/GDTCCTEventGenerator.h
  GoogleDataTransportCCTSupport/Tests/Unit/Helpers/GDTCCTEventGenerator.m
  scripts/check_whitespace.sh
Labels: cla: yes

#2678 fix a few place that copybara not properly handle the change
  Example/Messaging/Tests/FIRInstanceIDWithFCMTest.m
  Example/Messaging/Tests/FIRMessagingExtensionHelperTest.m
Labels: cla: yes

#2676 Remove pendingToken from public API.
  Firebase/Auth/Source/AuthProviders/OAuth/FIROAuthCredential_Internal.h
  Firebase/Auth/Source/AuthProviders/OAuth/FIROAuthProvider.m
  Firebase/Auth/Source/Public/FIROAuthCredential.h
  Firebase/Auth/Source/Public/FIROAuthProvider.h
Labels: cla: yes

#2680 Minimum osx from 10.10 to 10.11
  Example/Firebase.xcodeproj/project.pbxproj
  Example/Podfile
  FirebaseAnalyticsInterop.podspec
  FirebaseAuth.podspec
  FirebaseAuthInterop.podspec
  FirebaseCore.podspec
  FirebaseDatabase.podspec
  FirebaseFirestore.podspec
  FirebaseStorage.podspec
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/GoogleBenchmark.podspec
  Firestore/Example/GoogleTest.podspec
  Firestore/Example/LibFuzzer.podspec
  Firestore/Example/Podfile
  Firestore/Example/ProtobufCpp.podspec
  Firestore/Protos/FrameworkMaker.xcodeproj/project.pbxproj
  GoogleUtilities.podspec
  GoogleUtilities/Example/Podfile
Labels: cla: yes

#2685 Fix a couple expected error messages in tests to match recent code changes.
  Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
Labels: api: firestore, cla: yes

#2686 Fix use-after-free in DocumentReference::AddSnapshotListener
  Firestore/CHANGELOG.md
  Firestore/Example/Tests/Integration/API/FIRListenerRegistrationTests.mm
  Firestore/core/src/firebase/firestore/api/document_reference.mm
Labels: api: firestore, cla: yes
