Repository firebase/firebase-ios-sdk, pull requests merged in 2019-04, with the labels that each got.

#2691 Merge 5.20.1 back to master
  Example/Podfile
  FirebaseFirestore.podspec
  Firestore/CHANGELOG.md
  Firestore/Example/Podfile
  SymbolCollisionTest/Podfile
Labels: cla: yes

#2694 Fix CMake build
  Firestore/core/src/firebase/firestore/api/input_validation_std.cc
Labels: api: firestore, cla: yes

#2684 Add support of sso
  Example/Auth/Sample/SettingsViewController.m
  Example/Auth/Tests/FIRAuthUserDefaultsStorageTests.m
  Firebase/Auth/Source/FIRAuth.m
  Firebase/Auth/Source/FIRAuthKeychain.h
  Firebase/Auth/Source/FIRAuthKeychain.m
  Firebase/Auth/Source/FIRAuthStoredUserManager.h
  Firebase/Auth/Source/FIRAuthStoredUserManager.m
  Firebase/Auth/Source/FIRAuthUserDefaultsStorage.h
  Firebase/Auth/Source/FIRAuthUserDefaultsStorage.m
  Firebase/Auth/Source/Public/FIRActionCodeSettings.h
  Firebase/Auth/Source/Public/FIRAuth.h
  Firebase/Auth/Source/Public/FIRAuthSettings.h
  Firebase/Auth/Source/Public/FIRAuthTokenResult.h
  Firebase/Auth/Source/Public/FIRUserMetadata.h
  Firebase/Auth/Source/RPCs/FIRGetOOBConfirmationCodeRequest.h
Labels: cla: yes

#2699 Make high priority events force an upload via upload conditions
  GoogleDataTransport/GoogleDataTransport/Classes/GDTClock.m
  GoogleDataTransport/GoogleDataTransport/Classes/GDTStorage.m
  GoogleDataTransport/GoogleDataTransport/Classes/GDTUploadCoordinator.h
  GoogleDataTransport/GoogleDataTransport/Classes/GDTUploadCoordinator.m
  GoogleDataTransport/GoogleDataTransport/Classes/Public/GDTPrioritizer.h
  GoogleDataTransport/Tests/Common/Fakes/GDTUploadCoordinatorFake.m
  GoogleDataTransport/Tests/Integration/GDTIntegrationTest.m
  GoogleDataTransport/Tests/Unit/GDTUploadCoordinatorTest.m
Labels: cla: yes

#2668 Delete references to deprecated Crash and Invites
  Carthage.md
  Example/Core/Tests/FIRLoggerTest.m
  Firebase/Core/FIRErrors.m
  Firebase/Core/FIRLogger.m
  Firebase/Core/Private/FIRAppInternal.h
  Firebase/Core/Private/FIRErrors.h
  Firebase/Core/Private/FIRLogger.h
  Firebase/DynamicLinks/FIRDynamicLinkNetworking.h
  Rome.md
  SymbolCollisionTest/Podfile
  ZipBuilder/Sources/ZipBuilder/Subspec.swift
  ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
  ZipBuilder/Template/Crash/batch-upload
  ZipBuilder/Template/Crash/dump_syms
  ZipBuilder/Template/Crash/extract-keys
  ZipBuilder/Template/Crash/upload-sym
  ZipBuilder/Template/Crash/upload-sym-util.bash
  ZipBuilder/Template/Crash/upload-sym.sh
  ZipBuilder/Template/Firebase.h
Labels: api: invites, cla: yes

#2701 Implement the CCT prioritizer and an integration test
  GoogleDataTransportCCTSupport.podspec
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/Classes/GDTCCTPrioritizer.m
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/Classes/GDTCCTUploader.m
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/Classes/Private/GDTCCTPrioritizer.h
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/Classes/Private/GDTCCTUploader.h
  GoogleDataTransportCCTSupport/Tests/Integration/GDTCCTIntegrationTest.m
  GoogleDataTransportCCTSupport/Tests/Unit/GDTCCTUploaderTest.m
  GoogleDataTransportCCTSupport/Tests/Unit/TestServer/GDTCCTTestServer.h
  GoogleDataTransportCCTSupport/Tests/Unit/TestServer/GDTCCTTestServer.m
Labels: cla: yes

#2702 Change library podspecs to require 1.5.3, and change old tag string
  GoogleDataTransport.podspec
  GoogleDataTransportCCTSupport.podspec
Labels: cla: yes

#2693 Make fuzzing compile
  Firestore/fuzzing/leveldb_fuzzer.cc
  Firestore/fuzzing/serializer_fuzzer.cc
Labels: api: firestore, cla: yes

#2703 Remove the GULLogger dependency
  GoogleDataTransport.podspec
  GoogleDataTransport/GoogleDataTransport/Classes/GDTConsoleLogger.m
  GoogleDataTransport/GoogleDataTransport/Classes/Private/GDTConsoleLogger.h
Labels: cla: yes

#2708 Remove the .proto and .options files from the cocoapod
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/ProtoSupport/generate_cct_protos.sh
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/Protos/cct.options
  GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/Protos/cct.proto
  scripts/check_whitespace.sh
Labels: cla: yes

#2545 Add quick instructions for building the Zip.
  ZipBuilder/README.md
Labels: cla: yes

#2698 GULAppDelegateSwizzler - remote notifications methods and tvOS support
  GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
  GoogleUtilities/Common/GULLoggerCodes.h
  GoogleUtilities/Example/GoogleUtilities.xcodeproj/project.pbxproj
  GoogleUtilities/Example/Podfile
  GoogleUtilities/Example/Tests/Swizzler/GULAppDelegateSwizzlerTest.m
Labels: cla: yes

#2714 Revert "GULLogger - count errors and warnigns"
  GoogleUtilities/Example/Tests/Logger/GULLoggerTest.m
  GoogleUtilities/Logger/GULLogger.m
  GoogleUtilities/Logger/Private/GULLogger.h
Labels: cla: yes

#2715 Bump GoogleUtilities version to 5.6.0
  GoogleUtilities.podspec
Labels: cla: yes

#2683 FIRMessagingRemoteNotificationsProxy updated to use GULAppDelegateSwizzler
  Example/Firebase.xcodeproj/project.pbxproj
  Example/Messaging/Tests/FIRMessagingRemoteNotificationsProxyTest.m
  Example/Podfile
  Firebase/Messaging/FIRMessaging.m
  Firebase/Messaging/FIRMessagingRemoteNotificationsProxy.m
  FirebaseMessaging.podspec
  GoogleUtilities/AppDelegateSwizzler/Internal/GULAppDelegateSwizzler_Private.h
  GoogleUtilities/AppDelegateSwizzler/Private/GULAppDelegateSwizzler.h
Labels: cla: yes

#2716 Minor bugfix wrt converting strings with embedded 0s
  Firestore/core/src/firebase/firestore/util/string_apple.h
  Firestore/core/test/firebase/firestore/util/string_apple_test.mm
Labels: api: firestore, cla: yes

#2663 Implement oauth secret token in headful-lite.
  Example/Auth/Tests/FIRUserTests.m
  Example/Firebase.xcodeproj/project.pbxproj
  Firebase/Auth/Source/Auth Provider/OAuth/FIROAuthCredential.m
  Firebase/Auth/Source/Auth Provider/OAuth/FIROAuthCredential_Internal.h
  Firebase/Auth/Source/Auth Provider/OAuth/FIROAuthProvider.m
  Firebase/Auth/Source/Auth Provider/Twitter/FIRTwitterAuthCredential.h
  Firebase/Auth/Source/Auth Provider/Twitter/FIRTwitterAuthCredential.m
  Firebase/Auth/Source/Auth Provider/Twitter/FIRTwitterAuthProvider.m
  Firebase/Auth/Source/Auth/FIRAuth.m
  Firebase/Auth/Source/Auth/FIRAuthDataResult.m
  Firebase/Auth/Source/Auth/FIRAuthDataResult_Internal.h
  Firebase/Auth/Source/Backend/FIRAuthBackend.m
  Firebase/Auth/Source/Backend/RPC/FIRVerifyAssertionResponse.h
  Firebase/Auth/Source/Backend/RPC/FIRVerifyAssertionResponse.m
  Firebase/Auth/Source/Public/FIRAuthDataResult.h
  Firebase/Auth/Source/Public/FIROAuthCredential.h
  Firebase/Auth/Source/Public/FIRTwitterAuthProvider.h
  Firebase/Auth/Source/User/FIRUser.m
  Firebase/Auth/Source/Utilities/FIRAuthErrorUtils.h
  Firebase/Auth/Source/Utilities/FIRAuthErrorUtils.m
Labels: cla: yes

#2681 Add FSTDelegateValue which delegates to model::FieldValue
  Firestore/Example/Tests/Model/FSTFieldValueTests.mm
  Firestore/Source/API/FSTUserDataConverter.mm
  Firestore/Source/Model/FSTFieldValue.h
  Firestore/Source/Model/FSTFieldValue.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/model/field_value.cc
  Firestore/core/src/firebase/firestore/model/field_value.h
  Firestore/core/src/firebase/firestore/model/field_value.mm
  Firestore/core/test/firebase/firestore/testutil/xcgmock.h
Labels: api: firestore, cla: yes

#2721 Don't init FIRAuthStoredUserManager with a nil keychainServiceName.
  Firebase/Auth/Source/Auth/FIRAuth.m
Labels: api: auth, cla: yes

#2722 Update FIRAuthSettings.h
  Firebase/Auth/Source/Public/FIRAuthSettings.h
Labels: cla: yes

#2726 Fix changes conflict to fix build
  GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
  GoogleUtilities/Common/GULLoggerCodes.h
  GoogleUtilities/Example/GoogleUtilities.xcodeproj/project.pbxproj
  GoogleUtilities/Example/Podfile
  GoogleUtilities/Example/Tests/Swizzler/GULAppDelegateSwizzlerTest.m
Labels: cla: yes

#2717 Remove deprecated API to connect direct channel
  Firebase/Messaging/FIRMMessageCode.h
  Firebase/Messaging/FIRMessaging.m
  Firebase/Messaging/Public/FIRMessaging.h
Labels: cla: yes

#2730 Remove unused import
  Firebase/Auth/Source/Auth/FIRAuth.m
Labels: cla: yes

#2710 Auth - use GULAppDelegateSwizzler
  Example/Auth/Tests/FIRAuthAppDelegateProxyTests.m
  Example/Auth/Tests/FIRAuthTests.m
  Example/Firebase.xcodeproj/project.pbxproj
  Firebase/Auth/Source/Auth/FIRAuth.m
  Firebase/Auth/Source/Utilities/FIRAuthAppDelegateProxy.h
  Firebase/Auth/Source/Utilities/FIRAuthAppDelegateProxy.m
  FirebaseAuth.podspec
Labels: cla: yes

#2734 Remove missing analytics runtime warning
  Firebase/Core/FIRApp.m
Labels: cla: yes

#2723 Remove deprecated APIs
  Example/Auth/ApiTests/FacebookAuthTests.m
  Example/Auth/ApiTests/GoogleAuthTests.m
  Example/Auth/ApiTests/GoogleAuthTests.swift
  Example/Auth/Sample/MainViewController.m
  Example/Auth/Tests/FIRAuthTests.m
  Example/Auth/Tests/FIRUserTests.m
  Example/Firebase.xcodeproj/project.pbxproj
  Firebase/Auth/Source/Auth/FIRAuth.m
  Firebase/Auth/Source/Public/FIRAuth.h
  Firebase/Auth/Source/Public/FIRAuthErrors.h
  Firebase/Auth/Source/Public/FIREmailAuthProvider.h
  Firebase/Auth/Source/Public/FIROAuthProvider.h
  Firebase/Auth/Source/Public/FIRUser.h
  Firebase/Auth/Source/User/FIRUser.m
Labels: cla: yes

#2742 Set Swift back to version 4.2
  Example/Firebase.xcodeproj/project.pbxproj
Labels: cla: yes

#2739 Remove implicit Analytics dependency from FIAM
  FirebaseInAppMessaging.podspec
  InAppMessaging/Example/Podfile
Labels: cla: yes

#2744 Auth and Messaging require GoogleUtilities 5.6
  FirebaseAuth.podspec
  FirebaseMessaging.podspec
Labels: cla: yes

#2745 Stop requiring multiple Core version updates
  Example/Core/Tests/FIROptionsTest.m
  Firebase/Core/FIROptions.m
  Releases/update-versions.py
Labels: cla: yes

#2720 Begin migrating FIRLoggerService declarations to clients
  Example/Core/Tests/FIRLoggerTest.m
  Example/Podfile
  Firebase/Core/FIRLogger.m
  Firebase/Core/Private/FIRLogger.h
  Firebase/Database/Utilities/FUtilities.h
  Firebase/Database/Utilities/FUtilities.m
  Firebase/DynamicLinks/Logging/FDLLogging.m
  Firebase/Messaging/FIRMessagingLogger.m
  FirebaseCore.podspec
  Firestore/Example/Podfile
  Firestore/core/src/firebase/firestore/util/log_apple.mm
Labels: cla: yes

#2752 Fix Xcode's interactive error highlighting
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Podfile
Labels: api: firestore, cla: yes

#2756 Deprecate fetchProvidersForEmail
  Firebase/Auth/Source/Public/FIRAuth.h
  Firebase/Auth/Source/Public/FIRUser.h
Labels: cla: yes

#2719 Migrate FSTStringValue to FSTDelegateValue
  Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
  Firestore/Example/Tests/Model/FSTDocumentTests.mm
  Firestore/Example/Tests/Model/FSTFieldValueTests.mm
  Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
  Firestore/Source/API/FSTUserDataConverter.mm
  Firestore/Source/Model/FSTFieldValue.h
  Firestore/Source/Model/FSTFieldValue.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/model/field_value.cc
Labels: api: firestore, cla: yes

#2738 Remove implicit Analytics dependency from DynamicLinks
  FirebaseDynamicLinks.podspec
Labels: cla: yes

#2759 Remove support for deprecated API for Firebase 6
  Example/Auth/Tests/FIRAuthTests.m
  Firebase/Auth/Source/Auth Provider/Email/FIREmailAuthProvider.m
  Firebase/Auth/Source/Auth Provider/FIRAuthProvider.m
  Firebase/Auth/Source/Utilities/FIRAuthErrorUtils.m
Labels: cla: yes

#2758 Changelog updates for Messaging, Auth and InstanceID
  Firebase/Auth/CHANGELOG.md
  Firebase/InstanceID/CHANGELOG.md
  Firebase/Messaging/CHANGELOG.md
Labels: cla: yes

#2754 `pod lib lint GoogleUtilities.podspec` warnings fixes
  GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
  GoogleUtilities/Environment/third_party/GULAppEnvironmentUtil.h
  GoogleUtilities/Environment/third_party/GULAppEnvironmentUtil.m
Labels: cla: yes

#2765 Revert Twitter Auth deprecation because devepler may want to build their own sign in flow
  Firebase/Auth/Source/Auth Provider/Twitter/FIRTwitterAuthCredential.h
  Firebase/Auth/Source/Auth Provider/Twitter/FIRTwitterAuthCredential.m
  Firebase/Auth/Source/Auth Provider/Twitter/FIRTwitterAuthProvider.m
  Firebase/Auth/Source/Public/FIRTwitterAuthProvider.h
Labels: cla: yes

#2767 Add license files for Google Utilities 3rd party code
  GoogleUtilities/Environment/third_party/LICENSE
  GoogleUtilities/Example/Tests/Network/third_party/LICENSE
Labels: cla: yes

#2764 Use `if: type = cron` instead of `if_cron.sh`
  .travis.yml
  scripts/if_cron.sh
Labels: cla: yes

#2741 remove deprecated token API
  Example/InstanceID/Tests/FIRInstanceIDTest.m
  Firebase/InstanceID/FIRInstanceID+Private.h
  Firebase/InstanceID/FIRInstanceID.m
  Firebase/InstanceID/Private/FIRInstanceID_Private.h
  Firebase/InstanceID/Public/FIRInstanceID.h
  Firebase/Messaging/FIRMessaging.m
  FirebaseInstanceID.podspec
Labels: cla: yes

#2755 Bump FirebaseCore to 6.0.0
  Example/Podfile
  FirebaseAuth.podspec
  FirebaseCore.podspec
  FirebaseDatabase.podspec
  FirebaseDynamicLinks.podspec
  FirebaseFirestore.podspec
  FirebaseFunctions.podspec
  FirebaseInAppMessaging.podspec
  FirebaseInAppMessagingDisplay.podspec
  FirebaseInstanceID.podspec
  FirebaseMessaging.podspec
  FirebaseStorage.podspec
  Firestore/Example/Podfile
Labels: cla: yes

#2769 Fix minor typo
  Example/Core/Tests/FIROptionsTest.m
Labels: cla: yes

#2771 Private headers need to also be part of public
  FirebaseInstanceID.podspec
Labels: cla: yes

#2770 Remove deprecated RTDB API
  Firebase/Database/CHANGELOG.md
  Firebase/Database/FIRDatabaseReference.m
  Firebase/Database/Public/FIRDatabaseReference.h
Labels: cla: yes

#2772 Use development version of IID for FIAM testing
  InAppMessaging/Example/Podfile
  InAppMessagingDisplay/Example/Podfile
Labels: cla: yes

#2768 Remove deprecated API in FDLURLComponents.
  Example/DynamicLinks/Tests/FDLURLComponentsTests.m
  Firebase/DynamicLinks/Public/FDLURLComponents.h
Labels: api: dynamiclinks, cla: yes

#2749 Port FIRFirestoreSource to C++ Source
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRFirestoreSource+Internal.h
  Firestore/Source/API/FIRFirestoreSource.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/core/src/firebase/firestore/api/document_reference.h
  Firestore/core/src/firebase/firestore/api/document_reference.mm
  Firestore/core/src/firebase/firestore/api/source.h
Labels: api: firestore, cla: yes

#2777 Use NSCachesDirectory for database storage on tvOS
  Firestore/Source/Local/FSTLevelDB.mm
Labels: api: firestore, cla: yes

#2773 Undeprecate +[FIRFirestore enableLogging:]
  Firestore/Source/Public/FIRFirestore.h
Labels: api: firestore, cla: yes

#2779 M47 FirebaseCore release notes
  Firebase/Core/CHANGELOG.md
Labels: cla: yes

#2727 Move input validation logic from FIRFieldPath to model::FieldPath.
  Firestore/Source/API/FIRFieldPath.mm
  Firestore/core/src/firebase/firestore/model/CMakeLists.txt
  Firestore/core/src/firebase/firestore/model/field_path.cc
  Firestore/core/src/firebase/firestore/model/field_path.h
Labels: api: firestore, cla: yes

#2785 Update CHANGELOG for Firestore v1.3.0
  Firestore/CHANGELOG.md
Labels: api: firestore, cla: yes

#2783 remove test header from source code
  Example/InstanceID/Tests/FIRInstanceIDResultTest.m
  Example/InstanceID/Tests/FIRInstanceIDTest.m
  Firebase/InstanceID/FIRInstanceID+Testing.h
Labels: cla: yes

#2789 Revert "Move input validation logic from FIRFieldPath to model::FieldPath. (#2727)"
  Firestore/Source/API/FIRFieldPath.mm
  Firestore/core/src/firebase/firestore/model/CMakeLists.txt
  Firestore/core/src/firebase/firestore/model/field_path.cc
  Firestore/core/src/firebase/firestore/model/field_path.h
Labels: api: firestore, cla: yes

#2787 update CHANGELOG for Messaging and InstanceID
  Firebase/InstanceID/CHANGELOG.md
  Firebase/Messaging/CHANGELOG.md
Labels: cla: yes

#2781 Update CHANGELOG.md
  Firebase/Auth/CHANGELOG.md
Labels: cla: yes

#2791 Adding missing LICENSE files
  Firebase/Database/third_party/SocketRocket/LICENSE
  Firebase/Database/third_party/Wrap-leveldb/LICENSE
Labels: cla: yes

#2778 Fix FSTDelegateValue: property -> ivar
  Firestore/Source/Model/FSTFieldValue.h
  Firestore/Source/Model/FSTFieldValue.mm
Labels: cla: yes

#2786 Expose Collection Group queries.
  Firestore/CHANGELOG.md
  Firestore/Example/Tests/Integration/API/FIRQueryTests.mm
  Firestore/Example/Tests/Integration/API/FIRValidationTests.mm
  Firestore/Source/API/FIRFirestore+Internal.h
  Firestore/Source/Public/FIRFirestore.h
  Firestore/Swift/Tests/API/BasicCompileTests.swift
Labels: api: firestore, cla: yes

#2792 FDL release notes for M47
  Firebase/DynamicLinks/CHANGELOG.md
Labels: cla: yes

#2793 Fix 1P build issue
  Firebase/DynamicLinks/FDLURLComponents/FDLURLComponents+Private.h
  Firebase/DynamicLinks/FDLURLComponents/FDLURLComponents.m
  Firebase/DynamicLinks/FIRDynamicLinks+Private.h
Labels: api: dynamiclinks, cla: yes

#2784 Fix headers imports moved private
  Firebase/Core/FIRAnalyticsConfiguration.m
  Firebase/Core/FIRConfiguration.m
Labels: cla: yes

#2794 InstanceID - Add private initializer used by Swift 1p tests
  Firebase/InstanceID/FIRInstanceID+Private.h
Labels: cla: yes

#2795 Fix internal build target
  Firebase/DynamicLinks/FDLURLComponents/FDLURLComponents.m
  Firebase/DynamicLinks/FIRDynamicLinks.m
Labels: api: dynamiclinks, cla: yes

#2798 Remove spaces in file paths
  Firebase/Auth/Source/AuthProvider/Email/FIREmailAuthProvider.m
  Firebase/Auth/Source/AuthProvider/Email/FIREmailPasswordAuthCredential.h
  Firebase/Auth/Source/AuthProvider/Email/FIREmailPasswordAuthCredential.m
  Firebase/Auth/Source/AuthProvider/FIRAuthCredential.m
  Firebase/Auth/Source/AuthProvider/FIRAuthCredential_Internal.h
  Firebase/Auth/Source/AuthProvider/FIRAuthProvider.m
  Firebase/Auth/Source/AuthProvider/Facebook/FIRFacebookAuthCredential.h
  Firebase/Auth/Source/AuthProvider/Facebook/FIRFacebookAuthCredential.m
  Firebase/Auth/Source/AuthProvider/Facebook/FIRFacebookAuthProvider.m
  Firebase/Auth/Source/AuthProvider/GameCenter/FIRGameCenterAuthCredential.h
  Firebase/Auth/Source/AuthProvider/GameCenter/FIRGameCenterAuthCredential.m
  Firebase/Auth/Source/AuthProvider/GameCenter/FIRGameCenterAuthProvider.m
  Firebase/Auth/Source/AuthProvider/GitHub/FIRGitHubAuthCredential.h
  Firebase/Auth/Source/AuthProvider/GitHub/FIRGitHubAuthCredential.m
  Firebase/Auth/Source/AuthProvider/GitHub/FIRGitHubAuthProvider.m
  Firebase/Auth/Source/AuthProvider/Google/FIRGoogleAuthCredential.h
  Firebase/Auth/Source/AuthProvider/Google/FIRGoogleAuthCredential.m
  Firebase/Auth/Source/AuthProvider/Google/FIRGoogleAuthProvider.m
  Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthCredential.m
  Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthCredential_Internal.h
  Firebase/Auth/Source/AuthProvider/OAuth/FIROAuthProvider.m
  Firebase/Auth/Source/AuthProvider/Phone/FIRPhoneAuthCredential.m
  Firebase/Auth/Source/AuthProvider/Phone/FIRPhoneAuthCredential_Internal.h
  Firebase/Auth/Source/AuthProvider/Phone/FIRPhoneAuthProvider.m
  Firebase/Auth/Source/AuthProvider/Twitter/FIRTwitterAuthCredential.h
  Firebase/Auth/Source/AuthProvider/Twitter/FIRTwitterAuthCredential.m
  Firebase/Auth/Source/AuthProvider/Twitter/FIRTwitterAuthProvider.m
  Firebase/Auth/Source/SystemService/FIRAuthAPNSToken.h
  Firebase/Auth/Source/SystemService/FIRAuthAPNSToken.m
  Firebase/Auth/Source/SystemService/FIRAuthAPNSTokenManager.h
  Firebase/Auth/Source/SystemService/FIRAuthAPNSTokenManager.m
  Firebase/Auth/Source/SystemService/FIRAuthAppCredential.h
  Firebase/Auth/Source/SystemService/FIRAuthAppCredential.m
  Firebase/Auth/Source/SystemService/FIRAuthAppCredentialManager.h
  Firebase/Auth/Source/SystemService/FIRAuthAppCredentialManager.m
  Firebase/Auth/Source/SystemService/FIRAuthNotificationManager.h
  Firebase/Auth/Source/SystemService/FIRAuthNotificationManager.m
  Firebase/Auth/Source/SystemService/FIRAuthStoredUserManager.h
  Firebase/Auth/Source/SystemService/FIRAuthStoredUserManager.m
  Firebase/Auth/Source/SystemService/FIRSecureTokenService.h
  Firebase/Auth/Source/SystemService/FIRSecureTokenService.m
Labels: cla: yes

#2796 InstanceID - podspec lint fix
  Firebase/InstanceID/FIRInstanceID+Private.h
  Firebase/InstanceID/Private/FIRInstanceID_Private.h
  scripts/if_changed.sh
Labels: cla: yes

#2797 FIRErrorCodeDurableDeepLinkFailed is for 3P only
  Firebase/DynamicLinks/FIRDynamicLinks.m
Labels: cla: yes

#2800 Implement app-lifecycle groundwork
  GoogleDataTransport/GoogleDataTransport/Classes/GDTLifecycle.m
  GoogleDataTransport/GoogleDataTransport/Classes/GDTStorage.m
  GoogleDataTransport/GoogleDataTransport/Classes/GDTUploadCoordinator.m
  GoogleDataTransport/GoogleDataTransport/Classes/Private/GDTStorage_Private.h
  GoogleDataTransport/GoogleDataTransport/Classes/Private/GDTTransformer_Private.h
  GoogleDataTransport/GoogleDataTransport/Classes/Private/GDTUploadCoordinator_Private.h
  GoogleDataTransport/GoogleDataTransport/Classes/Public/GDTLifecycle.h
  GoogleDataTransport/GoogleDataTransport/Classes/Public/GDTTargets.h
  GoogleDataTransport/Tests/Common/Categories/GDTUploadCoordinator+Testing.h
  GoogleDataTransport/Tests/Common/Categories/GDTUploadCoordinator+Testing.m
  GoogleDataTransport/Tests/Unit/GDTStorageTest.m
Labels: cla: yes

#2802 Move collectionGroup method out of the Internal category
  Firestore/Source/API/FIRFirestore.mm
Labels: api: firestore, cla: yes

#2803 Temporarily restore setAnalyticsCollectionEnabled
  Firebase/Core/FIRAnalyticsConfiguration.m
  Firebase/Core/Private/FIRAnalyticsConfiguration.h
Labels: cla: yes

#2806 Fix a couple small issues I tripped over today.
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
  Firestore/Source/API/FIRFirestore+Internal.h
  Firestore/Source/API/FIRFirestore.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/API/FIRWriteBatch.mm
  Firestore/core/src/firebase/firestore/api/firestore.h
Labels: api: firestore, cla: yes

#2809 Restore kFIRLoggerCrash for internal clients
  Firebase/Core/FIRLogger.m
  Firebase/Core/Private/FIRLogger.h
Labels: cla: yes

#2811 Testing travis
  scripts/check.sh
Labels: api: firestore, cla: yes

#2805 Use enum for DelayedConstructor<> so XCode can decode it in the debugger window...
  Firestore/core/src/firebase/firestore/util/delayed_constructor.h
Labels: api: firestore, cla: yes

#2812 Port FSTRelationFilterOperator to C++ Filter::Operator
  Firestore/Example/Tests/Core/FSTViewTests.mm
  Firestore/Example/Tests/Util/FSTHelpers.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/Core/FSTQuery.h
  Firestore/Source/Core/FSTQuery.mm
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/core/src/firebase/firestore/core/filter.h
  Firestore/core/src/firebase/firestore/core/relation_filter.cc
Labels: api: firestore, cla: yes

#2814 Adding a missing LorOrRun
  Releases/update-versions.py
Labels: cla: yes

#2813 GoogleUtilities to 5.8.0
  FirebaseAuth.podspec
  FirebaseMessaging.podspec
  GoogleUtilities.podspec
Labels: cla: yes

#2790 Take 2: Move input validation logic from FIRFieldPath to model::FieldPath. (#2727)
  Firestore/Source/API/FIRFieldPath.mm
  Firestore/core/src/firebase/firestore/model/CMakeLists.txt
  Firestore/core/src/firebase/firestore/model/field_path.cc
  Firestore/core/src/firebase/firestore/model/field_path.h
Labels: api: firestore, cla: yes

#2815 Skip tests on pod repo push
  Releases/update-versions.py
Labels: cla: yes

#2817 Update GoogleUtilities CHANGELOG
  GoogleUtilities/CHANGELOG.md
Labels: GoogleUtilities, cla: yes

#2819 Add detailed instructions for building the Zip.
  ZipBuilder/README.md
Labels: cla: yes

#2820 Push `firebase_version` tag after creating it.
  Releases/update-versions.py
Labels: cla: yes

#2818 Update FirebaseSDKs.textproto with new fields.
  ZipBuilder/FirebaseSDKs.proto
  ZipBuilder/Sources/ZipBuilder/FirebaseSDKs.pb.swift
Labels: cla: yes

#2824 Proposed improvements to space checking
  scripts/check_filename_spaces.sh
Labels: cla: yes

#2808 Tunnel underlying NSErrors through C++ Status
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Source/API/FIRFirestore.mm
  Firestore/core/src/firebase/firestore/auth/firebase_credentials_provider_apple.mm
  Firestore/core/src/firebase/firestore/util/CMakeLists.txt
  Firestore/core/src/firebase/firestore/util/error_apple.h
  Firestore/core/src/firebase/firestore/util/error_apple.mm
  Firestore/core/src/firebase/firestore/util/status.cc
  Firestore/core/src/firebase/firestore/util/status.h
  Firestore/core/src/firebase/firestore/util/status_apple.mm
  Firestore/core/src/firebase/firestore/util/status_posix.cc
  Firestore/core/test/firebase/firestore/util/CMakeLists.txt
  Firestore/core/test/firebase/firestore/util/status_apple_test.mm
  Firestore/core/test/firebase/firestore/util/status_test.cc
Labels: api: firestore, cla: yes

#2821 Add travis check for filename spaces
  Interop/FirebaseComponentSystem.md
  scripts/check.sh
  scripts/check_filename_spaces.sh
Labels: cla: yes

#2827 Don't use using statements in Objective-C headers ...
  Firestore/Example/Tests/API/FIRQuerySnapshotTests.mm
  Firestore/Example/Tests/API/FSTAPIHelpers.mm
  Firestore/Example/Tests/Core/FSTEventManagerTests.mm
  Firestore/Example/Tests/Core/FSTQueryListenerTests.mm
  Firestore/Example/Tests/Integration/FSTDatastoreTests.mm
  Firestore/Example/Tests/Model/FSTDocumentTests.mm
  Firestore/Example/Tests/Remote/FSTSerializerBetaTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Source/API/FIRCollectionReference+Internal.h
  Firestore/Source/API/FIRDocumentChange+Internal.h
  Firestore/Source/API/FIRDocumentReference+Internal.h
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRDocumentSnapshot+Internal.h
  Firestore/Source/API/FIRDocumentSnapshot.mm
  Firestore/Source/API/FIRFieldPath+Internal.h
  Firestore/Source/API/FIRFirestore+Internal.h
  Firestore/Source/API/FIRListenerRegistration+Internal.h
  Firestore/Source/API/FIRListenerRegistration.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/API/FIRQuerySnapshot+Internal.h
  Firestore/Source/API/FIRQuerySnapshot.mm
  Firestore/Source/API/FIRSnapshotMetadata+Internal.h
  Firestore/Source/API/FIRSnapshotMetadata.mm
  Firestore/Source/API/FIRTransaction+Internal.h
  Firestore/Source/API/FSTUserDataConverter.h
  Firestore/Source/API/FSTUserDataConverter.mm
  Firestore/Source/Core/FSTEventManager.h
  Firestore/Source/Core/FSTEventManager.mm
  Firestore/Source/Core/FSTFirestoreClient.h
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/Source/Core/FSTQuery.h
  Firestore/Source/Core/FSTSyncEngine.h
  Firestore/Source/Core/FSTTypes.h
  Firestore/Source/Core/FSTView.h
  Firestore/Source/Local/FSTLRUGarbageCollector.h
  Firestore/Source/Local/FSTLevelDB.h
  Firestore/Source/Local/FSTLocalSerializer.h
  Firestore/Source/Local/FSTLocalStore.h
  Firestore/Source/Local/FSTLocalViewChanges.h
  Firestore/Source/Local/FSTLocalWriteResult.h
  Firestore/Source/Local/FSTMemoryPersistence.h
  Firestore/Source/Local/FSTPersistence.h
  Firestore/Source/Local/FSTQueryData.h
  Firestore/Source/Model/FSTDocument.h
  Firestore/Source/Model/FSTDocumentKey.h
  Firestore/Source/Model/FSTFieldValue.h
  Firestore/Source/Model/FSTMutation.h
  Firestore/Source/Model/FSTMutationBatch.h
  Firestore/Source/Remote/FSTSerializerBeta.h
  Firestore/Source/Remote/FSTSerializerBeta.mm
  Firestore/Source/Util/FSTAsyncQueryListener.h
  Firestore/core/src/firebase/firestore/api/document_reference.mm
  Firestore/core/src/firebase/firestore/model/field_value.mm
Labels: api: firestore, cla: yes

#2804 Port FirestoreSettings to C++.
  Firestore/Source/API/FIRDocumentSnapshot.mm
  Firestore/Source/API/FIRFirestore.mm
  Firestore/Source/API/FIRFirestoreSettings+Internal.h
  Firestore/Source/API/FIRFirestoreSettings.mm
  Firestore/Source/Core/FSTFirestoreClient.h
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/core/src/firebase/firestore/api/CMakeLists.txt
  Firestore/core/src/firebase/firestore/api/firestore.h
  Firestore/core/src/firebase/firestore/api/firestore.mm
  Firestore/core/src/firebase/firestore/api/settings.cc
  Firestore/core/src/firebase/firestore/api/settings.h
Labels: api: firestore, cla: yes

#2832 Copy Firebase.h and modulemap from the Firebase pod.
  ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
  ZipBuilder/Template/Firebase.h
  ZipBuilder/Template/module.modulemap
Labels: cla: yes, zip-builder

#2834 Update FirebaseSDKs.textproto with new fields. (#2818)
  ZipBuilder/FirebaseSDKs.proto
  ZipBuilder/Sources/ZipBuilder/FirebaseSDKs.pb.swift
Labels: cla: yes

#2830 Use shared_ptr<Firestore> instead of Firestore* for api:: classes.
  Firestore/Example/Tests/API/FIRQuerySnapshotTests.mm
  Firestore/Source/API/FIRDocumentReference+Internal.h
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRDocumentSnapshot+Internal.h
  Firestore/Source/API/FIRDocumentSnapshot.mm
  Firestore/Source/API/FIRFirestore+Internal.h
  Firestore/Source/API/FIRFirestore.mm
  Firestore/Source/API/FIRQuery.mm
  Firestore/Source/API/FIRQuerySnapshot+Internal.h
  Firestore/Source/API/FIRQuerySnapshot.mm
  Firestore/core/src/firebase/firestore/api/document_reference.h
  Firestore/core/src/firebase/firestore/api/document_reference.mm
  Firestore/core/src/firebase/firestore/api/document_snapshot.h
  Firestore/core/src/firebase/firestore/api/document_snapshot.mm
  Firestore/core/src/firebase/firestore/api/firestore.h
  Firestore/core/src/firebase/firestore/api/firestore.mm
  Firestore/core/src/firebase/firestore/api/query_snapshot.h
  Firestore/core/src/firebase/firestore/api/query_snapshot.mm
Labels: api: firestore, cla: yes

#2825 Remove reflection call to get checkin info from InstanceID
  Example/Messaging/Tests/FIRMessagingClientTest.m
  Example/Messaging/Tests/FIRMessagingRegistrarTest.m
  Firebase/InstanceID/FIRInstanceID+Private.h
  Firebase/InstanceID/FIRInstanceID+Private.m
  Firebase/InstanceID/FIRInstanceID.m
  Firebase/InstanceID/FIRInstanceIDCheckinPreferences.h
  Firebase/InstanceID/Private/FIRInstanceID_Private.h
  Firebase/Messaging/FIRMessagingCheckinService.h
  Firebase/Messaging/FIRMessagingCheckinService.m
  Firebase/Messaging/FIRMessagingClient.m
  Firebase/Messaging/FIRMessagingPubSubRegistrar.h
  Firebase/Messaging/FIRMessagingPubSubRegistrar.m
  Firebase/Messaging/FIRMessagingReceiver.h
  Firebase/Messaging/FIRMessagingReceiver.m
  Firebase/Messaging/FIRMessagingRegistrar.h
  Firebase/Messaging/FIRMessagingRegistrar.m
  Firebase/Messaging/FIRMessagingTopicOperation.h
  Firebase/Messaging/FIRMessagingTopicOperation.m
  FirebaseInstanceID.podspec
  FirebaseMessaging.podspec
Labels: cla: yes

#2839 Refactor headers for GDT CCT support library
  GoogleDataTransportCCTSupport/Library/GDTCCTNanopbHelpers.m
  GoogleDataTransportCCTSupport/Library/GDTCCTPrioritizer.m
  GoogleDataTransportCCTSupport/Library/GDTCCTUploader.m
  GoogleDataTransportCCTSupport/Library/Private/GDTCCTNanopbHelpers.h
  GoogleDataTransportCCTSupport/Tests/Integration/GDTCCTIntegrationTest.m
  GoogleDataTransportCCTSupport/Tests/Unit/GDTCCTNanopbHelpersTest.m
  GoogleDataTransportCCTSupport/Tests/Unit/GDTCCTPrioritizerTest.m
  GoogleDataTransportCCTSupport/Tests/Unit/GDTCCTUploaderTest.m
  GoogleDataTransportCCTSupport/Tests/Unit/Helpers/GDTCCTEventGenerator.m
  GoogleDataTransportCCTSupport/Tests/Unit/TestServer/GDTCCTTestServer.h
  GoogleDataTransportCCTSupport/Tests/Unit/TestServer/GDTCCTTestServer.m
Labels: cla: yes

#2831 Migrate api::Firestore completions to C++
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRFirestore.mm
  Firestore/Source/API/FIRWriteBatch.mm
  Firestore/Source/Core/FSTEventManager.mm
  Firestore/Source/Core/FSTFirestoreClient.h
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/Source/Core/FSTSyncEngine.h
  Firestore/Source/Core/FSTSyncEngine.mm
  Firestore/Source/Core/FSTTypes.h
  Firestore/core/src/firebase/firestore/api/document_reference.h
  Firestore/core/src/firebase/firestore/api/document_reference.mm
  Firestore/core/src/firebase/firestore/api/firestore.h
  Firestore/core/src/firebase/firestore/api/firestore.mm
  Firestore/core/src/firebase/firestore/core/transaction.h
  Firestore/core/src/firebase/firestore/core/transaction.mm
  Firestore/core/src/firebase/firestore/util/error_apple.h
  Firestore/core/src/firebase/firestore/util/error_apple.mm
  Firestore/core/src/firebase/firestore/util/status.h
  Firestore/core/src/firebase/firestore/util/status_apple.mm
Labels: api: firestore, cla: yes

#2855 Fix a single missing header change
  GoogleDataTransport/Library/Private/GDTUploadCoordinator_Private.h
Labels: cla: yes

#2845 Decouple verify client logic from phone auth
  Firebase/Auth/Source/AuthProvider/Phone/FIRPhoneAuthProvider.m
Labels: cla: yes

#2857 Implement verifyBeforeUpdateEmail.
  Firebase/Auth/Source/Backend/RPC/FIRGetOOBConfirmationCodeRequest.h
  Firebase/Auth/Source/Backend/RPC/FIRGetOOBConfirmationCodeRequest.m
  Firebase/Auth/Source/User/FIRUser.m
  Firebase/Auth/Source/User/FIRUser_Internal.h
Labels: cla: yes

#2835 GULAppDelegateSwizzler - proxy APNS methods separately
  Example/Firebase.xcodeproj/project.pbxproj
  Example/Messaging/App/iOS/NotificationService/Info.plist
  Example/Messaging/App/iOS/NotificationService/NotificationService.h
  Example/Messaging/App/iOS/NotificationService/NotificationService.m
  Example/Podfile
  Firebase/Auth/Source/Auth/FIRAuth.m
  Firebase/Messaging/FIRMessagingRemoteNotificationsProxy.m
  GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
  GoogleUtilities/AppDelegateSwizzler/Private/GULAppDelegateSwizzler.h
  GoogleUtilities/AppDelegateSwizzler/README.md
  GoogleUtilities/Example/GoogleUtilities.xcodeproj/xcshareddata/xcschemes/Example_iOS.xcscheme
  GoogleUtilities/Example/Tests/Swizzler/GULAppDelegateSwizzlerTest.m
Labels: cla: yes

#2854 Make api::DocumentReference accept ParsedSetData / ParsedUserData.
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/core/src/firebase/firestore/api/document_reference.h
  Firestore/core/src/firebase/firestore/api/document_reference.mm
Labels: api: firestore, cla: yes

#2858 GULAppDelegateSwizzler - proxy APNS methods separately (#2835)
  Example/Firebase.xcodeproj/project.pbxproj
  Example/Messaging/App/iOS/NotificationService/Info.plist
  Example/Messaging/App/iOS/NotificationService/NotificationService.h
  Example/Messaging/App/iOS/NotificationService/NotificationService.m
  Example/Podfile
  Firebase/Auth/Source/Auth/FIRAuth.m
  Firebase/Messaging/FIRMessagingRemoteNotificationsProxy.m
  GoogleUtilities/AppDelegateSwizzler/GULAppDelegateSwizzler.m
  GoogleUtilities/AppDelegateSwizzler/Private/GULAppDelegateSwizzler.h
  GoogleUtilities/AppDelegateSwizzler/README.md
  GoogleUtilities/Example/GoogleUtilities.xcodeproj/xcshareddata/xcschemes/Example_iOS.xcscheme
  GoogleUtilities/Example/Tests/Swizzler/GULAppDelegateSwizzlerTest.m
Labels: cla: yes

#2853 remove FIRMessagingRegistrar class
  Example/Firebase.xcodeproj/project.pbxproj
  Example/Messaging/Tests/FIRMessagingClientTest.m
  Example/Messaging/Tests/FIRMessagingRegistrarTest.m
  Firebase/Messaging/FIRMessagingClient.m
  Firebase/Messaging/FIRMessagingRegistrar.h
  Firebase/Messaging/FIRMessagingRegistrar.m
Labels: cla: yes

#2841 Tweak Functions error messages to be consistent with Android and C++.
  Functions/Example/IntegrationTests/FIRIntegrationTests.m
  Functions/FirebaseFunctions/FIRFunctions.m
  Functions/FirebaseFunctions/FUNError.m
Labels: cla: yes

#2859 Set DerivePointerAlignment=false for Firestore cpp files.
  Firestore/core/.clang-format
  Firestore/core/src/firebase/firestore/local/memory_remote_document_cache.h
  Firestore/core/test/firebase/firestore/FSTGoogleTestTests.mm
  Firestore/core/test/firebase/firestore/local/index_manager_test.h
  Firestore/core/test/firebase/firestore/local/index_manager_test.mm
  Firestore/core/test/firebase/firestore/remote/watch_change_test.mm
Labels: api: firestore, cla: yes

#2844 Port FIRWriteBatch.
  Firestore/Source/API/FIRDocumentReference+Internal.h
  Firestore/Source/API/FIRDocumentReference.mm
  Firestore/Source/API/FIRFirestore.mm
  Firestore/Source/API/FIRWriteBatch+Internal.h
  Firestore/Source/API/FIRWriteBatch.mm
  Firestore/core/src/firebase/firestore/api/document_reference.h
  Firestore/core/src/firebase/firestore/api/document_reference.mm
  Firestore/core/src/firebase/firestore/api/document_snapshot.h
  Firestore/core/src/firebase/firestore/api/firestore.h
  Firestore/core/src/firebase/firestore/api/firestore.mm
  Firestore/core/src/firebase/firestore/api/write_batch.h
  Firestore/core/src/firebase/firestore/api/write_batch.mm
Labels: api: firestore, cla: yes

#2864 [storage] small typo in code comments
  Firebase/Storage/Public/FIRStorageMetadata.h
Labels: cla: yes

#2860 fix race condition checkin is deleted before writing during app start
  Firebase/InstanceID/FIRIMessageCode.h
  Firebase/InstanceID/FIRInstanceIDCheckinStore.m
Labels: cla: yes

#2862 Make disabling GC prevent even scheduling it
  Firestore/Source/API/FIRFirestoreSettings.mm
  Firestore/Source/Core/FSTFirestoreClient.mm
  Firestore/Source/Local/FSTLRUGarbageCollector.h
  Firestore/Source/Local/FSTLRUGarbageCollector.mm
  Firestore/Source/Public/FIRFirestoreSettings.h
  Firestore/core/src/firebase/firestore/api/settings.cc
  Firestore/core/src/firebase/firestore/api/settings.h
Labels: api: firestore, cla: yes

#2867 Fix headers for copybara import for GDT
  GoogleDataTransport/Library/Private/GDTConsoleLogger.h
  GoogleDataTransport/Library/Private/GDTReachability_Private.h
  GoogleDataTransport/Library/Private/GDTStorage_Private.h
  GoogleDataTransport/Library/Private/GDTTransformer_Private.h
  GoogleDataTransport/Library/Public/GDTUploader.h
  GoogleDataTransport/Tests/Integration/GDTIntegrationTest.m
  GoogleDataTransport/Tests/Integration/Helpers/GDTIntegrationTestPrioritizer.h
  GoogleDataTransport/Tests/Integration/Helpers/GDTIntegrationTestPrioritizer.m
  GoogleDataTransport/Tests/Integration/Helpers/GDTIntegrationTestUploader.h
  GoogleDataTransport/Tests/Integration/Helpers/GDTIntegrationTestUploader.m
  GoogleDataTransport/Tests/Lifecycle/GDTLifecycleTest.m
  GoogleDataTransport/Tests/Lifecycle/Helpers/GDTLifecycleTestPrioritizer.h
  GoogleDataTransport/Tests/Lifecycle/Helpers/GDTLifecycleTestPrioritizer.m
  GoogleDataTransport/Tests/Lifecycle/Helpers/GDTLifecycleTestUploader.h
  GoogleDataTransportCCTSupport/Library/Protogen/nanopb/cct.nanopb.h
  GoogleDataTransportCCTSupport/ProtoSupport/Protos/cct.proto
Labels: cla: yes

#2865 Move the util::objc namespace to just objc
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/Example/Tests/SpecTests/FSTSpecTests.mm
  Firestore/Example/Tests/SpecTests/FSTSyncEngineTestDriver.mm
  Firestore/Source/Core/FSTEventManager.mm
  Firestore/Source/Model/FSTMutationBatch.mm
  Firestore/core/CMakeLists.txt
  Firestore/core/src/firebase/firestore/api/document_reference.mm
  Firestore/core/src/firebase/firestore/api/document_snapshot.mm
  Firestore/core/src/firebase/firestore/api/query_snapshot.mm
  Firestore/core/src/firebase/firestore/core/view_snapshot.mm
  Firestore/core/src/firebase/firestore/local/memory_query_cache.h
  Firestore/core/src/firebase/firestore/model/document_set.mm
  Firestore/core/src/firebase/firestore/objc/CMakeLists.txt
  Firestore/core/src/firebase/firestore/objc/objc_compatibility.h
  Firestore/core/src/firebase/firestore/objc/objc_type_traits.h
  Firestore/core/src/firebase/firestore/remote/watch_change.mm
  Firestore/core/src/firebase/firestore/util/CMakeLists.txt
  Firestore/core/src/firebase/firestore/util/hashing.h
  Firestore/core/src/firebase/firestore/util/string_format.h
  Firestore/core/src/firebase/firestore/util/to_string.h
  Firestore/core/src/firebase/firestore/util/type_traits.h
  Firestore/core/test/firebase/firestore/objc/CMakeLists.txt
  Firestore/core/test/firebase/firestore/objc/objc_type_traits_apple_test.mm
  Firestore/core/test/firebase/firestore/util/CMakeLists.txt
  Firestore/core/test/firebase/firestore/util/objc_compatibility_apple_test.mm
  cmake/cc_rules.cmake
  scripts/cpplint.py
Labels: api: firestore, cla: yes

#2869 Change Functions test app to allow testing against prod, using a GoogleService-Info.plist
  FirebaseFunctions.podspec
  Functions/Example/GoogleService-Info.plist
  Functions/Example/IntegrationTests/FIRIntegrationTests.m
Labels: cla: yes

#2871 Make sure all the test targets for GDT and GDTCCT are run
  scripts/build.sh
Labels: cla: yes

#2876 GoogleUtilities min ios version from 6 to 8
  FirebaseAuth.podspec
  FirebaseCore.podspec
  FirebaseInstanceID.podspec
  FirebaseMessaging.podspec
  GoogleUtilities.podspec
  GoogleUtilities/CHANGELOG.md
Labels: cla: yes

#2878 Remove GoogleDataTransport umbrella header imports
  GoogleDataTransportCCTSupport/GDTCCTLibrary/GDTCCTPrioritizer.m
  GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCCTNanopbHelpers.h
  GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCCTPrioritizer.h
  GoogleDataTransportCCTSupport/GDTCCTLibrary/Private/GDTCCTUploader.h
  GoogleDataTransportCCTSupport/GDTCCTTests/Integration/GDTCCTIntegrationTest.m
  GoogleDataTransportCCTSupport/GDTCCTTests/Unit/GDTCCTUploaderTest.m
Labels: cla: yes

#2879 Fix clang analyzer warnings for Firebase Auth.
  Firebase/Auth/Source/Auth/FIRAuth.m
  Firebase/Auth/Source/AuthProvider/Phone/FIRPhoneAuthProvider.m
  Firebase/Auth/Source/Public/FIRAuth.h
  Firebase/Auth/Source/Storage/FIRAuthKeychain.h
  Firebase/Auth/Source/Storage/FIRAuthKeychain.m
  Firebase/Auth/Source/Utilities/FIRAuthErrorUtils.m
Labels: cla: yes

#2882 Cherry-picks for M47 RC5
  Firebase/InstanceID/FIRIMessageCode.h
  Firebase/InstanceID/FIRInstanceIDCheckinStore.m
  FirebaseAuth.podspec
  FirebaseCore.podspec
  FirebaseInstanceID.podspec
  FirebaseMessaging.podspec
  GoogleUtilities.podspec
  GoogleUtilities/CHANGELOG.md
Labels: cla: yes

#2891 Update CHANGELOG.md
  Firebase/Auth/CHANGELOG.md
Labels: cla: yes

#2892 Implement a type of future for GDT stored NSData
  GoogleDataTransport/GDTLibrary/GDTDataFuture.m
  GoogleDataTransport/GDTLibrary/GDTEvent.m
  GoogleDataTransport/GDTLibrary/GDTStorage.m
  GoogleDataTransport/GDTLibrary/GDTStoredEvent.m
  GoogleDataTransport/GDTLibrary/Public/GDTDataFuture.h
  GoogleDataTransport/GDTLibrary/Public/GDTEvent.h
  GoogleDataTransport/GDTLibrary/Public/GDTStoredEvent.h
  GoogleDataTransport/GDTLibrary/Public/GoogleDataTransport.h
  GoogleDataTransport/GDTTests/Integration/Helpers/GDTIntegrationTestUploader.m
  GoogleDataTransport/GDTTests/Unit/GDTStorageTest.m
  GoogleDataTransport/GDTTests/Unit/GDTStoredEventTest.m
  GoogleDataTransport/GDTTests/Unit/Helpers/GDTEventGenerator.m
Labels: cla: yes

#2893 Add GoogleSignIn to Zip file.
  ZipBuilder/Sources/ZipBuilder/CocoaPod.swift
  ZipBuilder/Sources/ZipBuilder/CocoaPodUtils.swift
  ZipBuilder/Sources/ZipBuilder/URL+Utils.swift
  ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
Labels: cla: yes, zip-builder

#2883 Add objc::Handle and OBJC_CLASS
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/core/src/firebase/firestore/objc/CMakeLists.txt
  Firestore/core/src/firebase/firestore/objc/objc_class.h
  Firestore/core/src/firebase/firestore/objc/objc_class.mm
  Firestore/core/src/firebase/firestore/objc/objc_compatibility.h
  Firestore/core/test/firebase/firestore/objc/CMakeLists.txt
  Firestore/core/test/firebase/firestore/objc/objc_class_test.cc
  Firestore/core/test/firebase/firestore/objc/objc_class_test_helper.h
  Firestore/core/test/firebase/firestore/objc/objc_class_test_helper.mm
Labels: api: firestore, cla: yes

#2884 Use three-way comparisons in C++
  Firestore/Source/Core/FSTQuery.mm
  Firestore/Source/Model/FSTDocument.mm
  Firestore/Source/Model/FSTDocumentKey.h
  Firestore/Source/Model/FSTDocumentKey.mm
  Firestore/Source/Model/FSTFieldValue.h
  Firestore/Source/Model/FSTFieldValue.mm
  Firestore/core/src/firebase/firestore/immutable/CMakeLists.txt
  Firestore/core/src/firebase/firestore/immutable/array_sorted_map.h
  Firestore/core/src/firebase/firestore/immutable/keys_view.h
  Firestore/core/src/firebase/firestore/immutable/llrb_node.h
  Firestore/core/src/firebase/firestore/immutable/llrb_node_iterator.h
  Firestore/core/src/firebase/firestore/immutable/map_entry.h
  Firestore/core/src/firebase/firestore/immutable/tree_sorted_map.h
  Firestore/core/src/firebase/firestore/local/document_key_reference.cc
  Firestore/core/src/firebase/firestore/local/document_key_reference.h
  Firestore/core/src/firebase/firestore/model/base_path.h
  Firestore/core/src/firebase/firestore/model/database_id.cc
  Firestore/core/src/firebase/firestore/model/database_id.h
  Firestore/core/src/firebase/firestore/model/document_key.cc
  Firestore/core/src/firebase/firestore/model/document_key.h
  Firestore/core/src/firebase/firestore/model/document_set.h
  Firestore/core/src/firebase/firestore/model/field_path.h
  Firestore/core/src/firebase/firestore/model/field_value.cc
  Firestore/core/src/firebase/firestore/model/field_value.h
  Firestore/core/src/firebase/firestore/model/resource_path.h
  Firestore/core/src/firebase/firestore/model/snapshot_version.cc
  Firestore/core/src/firebase/firestore/model/snapshot_version.h
  Firestore/core/src/firebase/firestore/nanopb/nanopb_string.cc
  Firestore/core/src/firebase/firestore/nanopb/nanopb_string.h
  Firestore/core/src/firebase/firestore/util/CMakeLists.txt
  Firestore/core/src/firebase/firestore/util/comparator_holder.h
  Firestore/core/src/firebase/firestore/util/comparison.cc
  Firestore/core/src/firebase/firestore/util/comparison.h
  Firestore/core/src/firebase/firestore/util/compressed_member.h
  Firestore/core/test/firebase/firestore/model/document_key_test.cc
Labels: api: firestore, cla: yes

#2885 Use C++ three-way comparison in FSTQuery
  Firestore/Example/Tests/API/FIRQuerySnapshotTests.mm
  Firestore/Example/Tests/API/FSTAPIHelpers.mm
  Firestore/Example/Tests/Core/FSTQueryTests.mm
  Firestore/Example/Tests/Core/FSTViewSnapshotTest.mm
  Firestore/Example/Tests/Model/FSTDocumentSetTests.mm
  Firestore/Example/Tests/Util/FSTHelpers.h
  Firestore/Example/Tests/Util/FSTHelpers.mm
  Firestore/Source/Core/FSTQuery.h
  Firestore/Source/Core/FSTQuery.mm
  Firestore/Source/Core/FSTView.mm
  Firestore/Source/Model/FSTDocument.h
  Firestore/Source/Model/FSTDocument.mm
  Firestore/core/src/firebase/firestore/api/query_snapshot.mm
  Firestore/core/src/firebase/firestore/model/document_set.h
  Firestore/core/src/firebase/firestore/model/document_set.mm
  Firestore/core/src/firebase/firestore/util/comparison.h
Labels: api: firestore, cla: yes

#2886 Make all core C++ APIs usable in plain C++
  Firestore/Example/Firestore.xcodeproj/project.pbxproj
  Firestore/core/src/firebase/firestore/api/document_reference.h
  Firestore/core/src/firebase/firestore/api/document_reference.mm
  Firestore/core/src/firebase/firestore/api/document_snapshot.h
  Firestore/core/src/firebase/firestore/api/document_snapshot.mm
  Firestore/core/src/firebase/firestore/api/firestore.h
  Firestore/core/src/firebase/firestore/api/firestore.mm
  Firestore/core/src/firebase/firestore/api/listener_registration.h
  Firestore/core/src/firebase/firestore/api/listener_registration.mm
  Firestore/core/src/firebase/firestore/api/query_snapshot.h
  Firestore/core/src/firebase/firestore/api/query_snapshot.mm
  Firestore/core/src/firebase/firestore/api/write_batch.h
  Firestore/core/src/firebase/firestore/api/write_batch.mm
  Firestore/core/src/firebase/firestore/core/query_listener.h
  Firestore/core/src/firebase/firestore/core/query_listener.mm
  Firestore/core/src/firebase/firestore/core/transaction.h
  Firestore/core/src/firebase/firestore/core/transaction.mm
  Firestore/core/src/firebase/firestore/core/view_snapshot.h
  Firestore/core/src/firebase/firestore/core/view_snapshot.mm
  Firestore/core/src/firebase/firestore/local/leveldb_remote_document_cache.mm
  Firestore/core/src/firebase/firestore/local/memory_remote_document_cache.mm
  Firestore/core/src/firebase/firestore/model/document_map.h
  Firestore/core/src/firebase/firestore/model/document_map.mm
  Firestore/core/src/firebase/firestore/model/document_set.h
  Firestore/core/src/firebase/firestore/objc/objc_class.h
  Firestore/core/test/firebase/firestore/api/cc_compilation_test.cc
Labels: api: firestore, cla: yes

#2897 Address flakiness in the GDT integration test.
  GoogleDataTransport/GDTTests/Integration/GDTIntegrationTest.m
Labels: cla: yes

#2905 Make `api::DocumentSnapshot::document_id()` return a const reference.
  Firestore/core/src/firebase/firestore/api/document_snapshot.h
  Firestore/core/src/firebase/firestore/api/document_snapshot.mm
Labels: api: firestore, cla: yes

#2861 GULAppDelegateSwizzlerTest
  GoogleUtilities/Example/Tests/Swizzler/GULAppDelegateSwizzlerTest.m
Labels: cla: yes

#2906 FIRApp - validate app name using NSCharacterSet
  Example/Core/Tests/FIRAppTest.m
  Firebase/Core/FIRApp.m
Labels: cla: yes

#2904 Add metrics database config to tar and install_prereqs script
  scripts/install_prereqs.sh
  scripts/travis-encrypted/Secrets.tar.enc
Labels: cla: yes

#2902 FIRStorageUploadTask - fix crash in `isContentToUploadValid`
  Example/Storage/Tests/Unit/FIRStorageReferenceTests.m
  Firebase/Storage/CHANGELOG.md
  Firebase/Storage/FIRStorageUploadTask.m
Labels: cla: yes

#2900 Add support for uploading metrics to the database
  Metrics/README.md
  Metrics/Sources/Metrics/main.swift
  Metrics/Sources/MetricsLib/Uploader.swift
Labels: cla: yes
