Repository firebase/firebase-ios-sdk, pull requests merged in 2020-07, with the labels that each got.

#5946 Adding plist property 'FirebaseDeepLinkPasteboardRetrievalEnabled'
  FirebaseDynamicLinks/CHANGELOG.md
  FirebaseDynamicLinks/Sources/FIRDLDefaultRetrievalProcessV2.m
Labels: api: dynamiclinks, cla: yes

#5954 Update auth pod test
  .github/workflows/auth.yml
Labels: cla: yes

#5957 Update RemoteConfig workflow.
  .github/workflows/remoteconfig.yml
Labels: cla: yes

#5952 FDL Sample App: Fixing imports and Pod file
  FirebaseDynamicLinks/Tests/Sample/FDLBuilderTestAppObjC/AppDelegate.m
  FirebaseDynamicLinks/Tests/Sample/Podfile
Labels: api: dynamiclinks, cla: yes

#5960 Fix checks running in clones with nonstandard names
  scripts/check_imports.swift
Labels: api: firestore

#5962 Update scripts due to the change of add_framework tool.
  scripts/setup_quickstart_framework.sh
Labels: cla: yes

#5941 Update FIRDynamicLinkNetworking.m
  FirebaseDynamicLinks/Sources/FIRDynamicLinkNetworking.m
Labels: api: dynamiclinks, cla: yes

#5965 Update DL Changelog for 5941
  FirebaseDynamicLinks/CHANGELOG.md
Labels: api: dynamiclinks, cla: yes

#5963 Add Auth Swift Framework Test.
  .github/workflows/auth.yml
  scripts/setup_quickstart_framework.sh
Labels: cla: yes

#5968 Disable zip testing in private repo.
  .github/workflows/database.yml
  .github/workflows/dynamiclinks.yml
  .github/workflows/storage.yml
Labels: cla: yes

#5974 Stop last scheduled job still on Private
  .github/workflows/crashlytics.yml
Labels: cla: yes

#5959 SPM: Core ObjC unit tests
  .github/workflows/spm.yml
  FirebaseCore.podspec
  FirebaseCore/Tests/SwiftUnit/FirebaseAppTests.swift
  FirebaseCore/Tests/SwiftUnit/FirebaseConfigurationTests.swift
  FirebaseCore/Tests/SwiftUnit/FirebaseCore-unit-Bridging-Header.h
  FirebaseCore/Tests/SwiftUnit/FirebaseOptionsTests.swift
  FirebaseCore/Tests/SwiftUnit/SwiftTestingUtilities/Constants.swift
  FirebaseCore/Tests/SwiftUnit/SwiftTestingUtilities/ExceptionCatcher.h
  FirebaseCore/Tests/SwiftUnit/SwiftTestingUtilities/ExceptionCatcher.m
  FirebaseCore/Tests/Unit/FIRAppTest.m
  FirebaseCore/Tests/Unit/FIROptionsTest.m
  FirebaseCore/Tests/Unit/FIRTestCase.h
  FirebaseCore/Tests/Unit/FIRTestCase.m
  FirebaseCore/Tests/Unit/Tests-Info.plist
  Package.swift
  Tests/firebase-test/main.swift
  scripts/check_imports.swift
Labels: api: core, cla: yes

#5890 Remove Protobuf from the ABT SDK
  Firebase.podspec
  FirebaseABTesting.podspec
  FirebaseABTesting/CHANGELOG.md
  FirebaseABTesting/Sources/ABTConditionalUserPropertyController.h
  FirebaseABTesting/Sources/ABTConditionalUserPropertyController.m
  FirebaseABTesting/Sources/ABTExperimentPayload.m
  FirebaseABTesting/Sources/FIRExperimentController.m
  FirebaseABTesting/Sources/Private/ABTExperimentPayload.h
  FirebaseABTesting/Sources/Protos/PortableProtoFilterTemplate.asciipb
  FirebaseABTesting/Sources/Protos/developers/mobile/abt/proto/ExperimentPayload.pbobjc.h
  FirebaseABTesting/Sources/Protos/developers/mobile/abt/proto/ExperimentPayload.pbobjc.m
  FirebaseABTesting/Sources/Public/FIRExperimentController.h
  FirebaseABTesting/Tests/Unit/ABTConditionalUserPropertyControllerTest.m
  FirebaseABTesting/Tests/Unit/ABTExperimentPayloadTest.m
  FirebaseABTesting/Tests/Unit/FIRExperimentControllerTest.m
  FirebaseABTesting/Tests/Unit/Resources/TestABTPayload1.txt
  FirebaseABTesting/Tests/Unit/Resources/TestABTPayload2.txt
  FirebaseABTesting/Tests/Unit/Resources/TestABTPayload3.txt
  FirebaseABTesting/Tests/Unit/Resources/TestABTPayload4.txt
  FirebaseABTesting/Tests/Unit/Resources/TestABTPayload5.txt
  FirebaseABTesting/Tests/Unit/Resources/TestABTPayload6.txt
  FirebaseABTesting/Tests/Unit/Utilities/ABTTestUtilities.h
  FirebaseABTesting/Tests/Unit/Utilities/ABTTestUtilities.m
  FirebaseInAppMessaging.podspec
  FirebaseInAppMessaging/CHANGELOG.md
  FirebaseInAppMessaging/Sources/Data/FIRIAMFetchResponseParser.m
  FirebaseInAppMessaging/Sources/Private/Data/FIRIAMMessageDefinition.h
  FirebaseInAppMessaging/Tests/Unit/FIRIAMDisplayExecutorTests.m
  FirebaseRemoteConfig.podspec
  FirebaseRemoteConfig/CHANGELOG.md
  FirebaseRemoteConfig/Sources/RCNConfigExperiment.m
  FirebaseRemoteConfig/Tests/Unit/RCNConfigExperimentTest.m
  FirebaseRemoteConfig/Tests/Unit/TestABTPayload.txt
Labels: api: abtesting, api: inappmessaging, api: remoteconfig, cla: yes, public-api-change

#5976 Storage SPM Unit Tests
  Example/Shared/Shared.xcassets/AppIcon.appiconset/Contents.json
  Example/Shared/Shared.xcassets/AppIcon.appiconset/Icon-Mac-128.png
  Example/Shared/Shared.xcassets/AppIcon.appiconset/Icon-Pad-76.png
  Example/Shared/Shared.xcassets/AppIcon.appiconset/Icon-Pad-76@2x.png
  Example/Shared/Shared.xcassets/AppIcon.appiconset/Icon-Pad-83.5@2x.png
  Example/Shared/Shared.xcassets/AppIcon.appiconset/Icon-Pad-Notification.png
  Example/Shared/Shared.xcassets/AppIcon.appiconset/Icon-Pad-Notification@2x.png
  Example/Shared/Shared.xcassets/AppIcon.appiconset/Icon-Pad-Settings.png
  Example/Shared/Shared.xcassets/AppIcon.appiconset/Icon-Pad-Settings@2x.png
  Example/Shared/Shared.xcassets/AppIcon.appiconset/Icon-Pad-Spotlight.png
  Example/Shared/Shared.xcassets/AppIcon.appiconset/Icon-Pad-Spotlight@2x.png
  Example/Shared/Shared.xcassets/AppIcon.appiconset/Icon-Phone-60@2x.png
  Example/Shared/Shared.xcassets/AppIcon.appiconset/Icon-Phone-60@3x.png
  Example/Shared/Shared.xcassets/AppIcon.appiconset/Icon-Phone-Notification@2x.png
  Example/Shared/Shared.xcassets/AppIcon.appiconset/Icon-Phone-Notification@3x.png
  Example/Shared/Shared.xcassets/AppIcon.appiconset/Icon-Phone-Settings@2x.png
  Example/Shared/Shared.xcassets/AppIcon.appiconset/Icon-Phone-Settings@3x.png
  Example/Shared/Shared.xcassets/AppIcon.appiconset/Icon-Phone-Spotlight@2x.png
  Example/Shared/Shared.xcassets/AppIcon.appiconset/Icon-Phone-Spotlight@3x.png
  Example/Shared/Shared.xcassets/AppIcon.appiconset/iTunesArtwork@2x.png
  Example/Shared/Shared.xcassets/Contents.json
  FirebaseDatabase.podspec
  FirebaseDatabase/Tests/Helpers/FIRFakeApp.m
  FirebaseDatabase/Tests/Helpers/FTestHelpers.m
  FirebaseDatabase/Tests/Integration/FIRAuthTests.m
  FirebaseFunctions.podspec
  FirebaseStorage.podspec
  FirebaseStorage/Tests/Unit/FIRStorageComponentTests.m
  FirebaseStorage/Tests/Unit/FIRStorageReferenceTests.m
  FirebaseStorage/Tests/Unit/FIRStorageTestHelpers.h
  FirebaseStorage/Tests/Unit/FIRStorageTestHelpers.m
  FirebaseStorage/Tests/Unit/FIRStorageTests.m
  FirebaseStorage/Tests/Unit/FIRStorageTokenAuthorizerTests.m
  Package.swift
  SharedTestUtilities/FIRAuthInteropFake.h
  SharedTestUtilities/FIRAuthInteropFake.m
  SharedTestUtilities/FIRComponentTestUtilities.h
  SharedTestUtilities/FIRComponentTestUtilities.m
  SharedTestUtilities/FIRSampleAppUtilities.h
  SharedTestUtilities/FIRSampleAppUtilities.m
  scripts/check_no_module_imports.sh
Labels: api: database, api: storage, cla: yes

#5961 Have ListenerRegistration::Remove block until callbacks are complete
  Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
  Firestore/Example/Tests/Integration/API/FIRListenerRegistrationTests.mm
  Firestore/Example/Tests/Util/FSTIntegrationTestCase.mm
  Firestore/Example/Tests/Util/XCTestCase+Await.h
  Firestore/Example/Tests/Util/XCTestCase+Await.mm
  Firestore/core/src/api/query_core.cc
  Firestore/core/src/core/event_listener.h
Labels: api: firestore, cla: yes

#5980 ABT Path fixes and RC Maltese bug fix
  FirebaseABTesting/Sources/ABTConditionalUserPropertyController.h
  FirebaseABTesting/Sources/ABTExperimentPayload.m
  FirebaseABTesting/Sources/FIRExperimentController.m
  FirebaseABTesting/Tests/Unit/ABTConditionalUserPropertyControllerTest.m
  FirebaseABTesting/Tests/Unit/ABTExperimentPayloadTest.m
  FirebaseABTesting/Tests/Unit/FIRExperimentControllerTest.m
  FirebaseABTesting/Tests/Unit/Utilities/ABTTestUtilities.m
  FirebaseRemoteConfig/Sources/RCNDevice.m
Labels: api: abtesting, api: remoteconfig

#5942 GDT: Retry uploading batches failed to upload before the app termination
  GoogleDataTransport.podspec
  GoogleDataTransport/GDTCCTLibrary/GDTCCTUploader.m
  GoogleDataTransport/GDTCCTTests/Common/TestStorage/GDTCCTTestStorage.h
  GoogleDataTransport/GDTCCTTests/Common/TestStorage/GDTCCTTestStorage.m
  GoogleDataTransport/GDTCCTTests/Unit/GDTCCTUploaderTest.m
  GoogleDataTransport/GDTCCTTests/Unit/TestServer/GDTCCTTestServer.h
  GoogleDataTransport/GDTCCTTests/Unit/TestServer/GDTCCTTestServer.m
  GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage.m
  GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m
  GoogleDataTransport/GDTCORLibrary/Public/GDTCORStorageProtocol.h
  GoogleDataTransport/GDTCORTests/Unit/GDTCORFlatFileStorageTest.m
Labels: GoogleDataTransport, cla: yes, public-api-change

#5988 Unreleased M74 changelog items updated with M75
  FirebaseCore/CHANGELOG.md
  FirebaseInstallations/CHANGELOG.md
  GoogleUtilities/CHANGELOG.md
Labels: cla: yes

#5977 Access filesystem outside of GULHeartbeatDateStorage initializer
  GoogleUtilities/CHANGELOG.md
  GoogleUtilities/Environment/GULHeartbeatDateStorage.m
  GoogleUtilities/Example/Tests/Environment/GULHeartbeatDateStorageTest.m
Labels: GoogleUtilities, api: core, cla: yes

#5985 Failure to load zip will fail workflows.
  scripts/get_latest_zip_from_gcs.sh
Labels: cla: yes

#5981 Update the sample app to use a random nonce in the Sign in with Apple flow
  FirebaseAuth/Tests/Sample/Sample/MainViewController+Internal.h
  FirebaseAuth/Tests/Sample/Sample/MainViewController+OAuth.m
Labels: api: auth, cla: yes

#5982 Swift Firestore Framework Testing
  .github/workflows/firestore.yml
  scripts/setup_quickstart_framework.sh
Labels: cla: yes

#5995 Don't allow script to erase repo
  scripts/build_zip.sh
Labels: cla: yes, zip-builder

#5996 Migrate remoteconfig zip test to zip workflow.
  .github/workflows/zip.yml
Labels: cla: yes

#5997 Merging the 6.27.1 release into master
  Firebase.podspec
  FirebaseCore.podspec
Labels: cla: yes

#5999 Structural setup for SPM GoogleUtilities tests
  GoogleUtilities.podspec
  GoogleUtilities/Example/Tests/Tests-Info.plist
  GoogleUtilities/Tests/Unit/Environment/GULAppEnvironmentUtilTest.m
  GoogleUtilities/Tests/Unit/Environment/GULHeartbeatDateStorageTest.m
  GoogleUtilities/Tests/Unit/Environment/GULKeychainStorageTests.m
  GoogleUtilities/Tests/Unit/Logger/GULLoggerTest.m
  GoogleUtilities/Tests/Unit/Network/GULMutableDictionaryTest.m
  GoogleUtilities/Tests/Unit/Network/GULNetworkTest.m
  GoogleUtilities/Tests/Unit/Network/third_party/GTMHTTPServer.h
  GoogleUtilities/Tests/Unit/Network/third_party/GTMHTTPServer.m
  GoogleUtilities/Tests/Unit/Network/third_party/LICENSE
  GoogleUtilities/Tests/Unit/Reachability/GULReachabilityCheckerTest.m
  GoogleUtilities/Tests/Unit/SecureCoding/GULSecureCodingTests.m
  GoogleUtilities/Tests/Unit/Swizzler/GULAppDelegateSwizzlerTest.m
  GoogleUtilities/Tests/Unit/Swizzler/GULObjectSwizzlerTest.m
  GoogleUtilities/Tests/Unit/Swizzler/GULRuntimeClassDiffTests.m
  GoogleUtilities/Tests/Unit/Swizzler/GULRuntimeClassSnapshotTests.m
  GoogleUtilities/Tests/Unit/Swizzler/GULRuntimeDiffTests.m
  GoogleUtilities/Tests/Unit/Swizzler/GULRuntimeSnapshotTests.m
  GoogleUtilities/Tests/Unit/Swizzler/GULRuntimeStateHelperTests.m
  GoogleUtilities/Tests/Unit/Swizzler/GULSceneDelegateSwizzlerTest.m
  GoogleUtilities/Tests/Unit/Swizzler/GULSwizzlerInheritedMethodsSwizzlingTest.m
  GoogleUtilities/Tests/Unit/Swizzler/GULSwizzlerTest.m
  GoogleUtilities/Tests/Unit/Swizzler/GULSwizzlingCacheTest.m
  GoogleUtilities/Tests/Unit/UserDefaults/GULUserDefaultsTests.m
  GoogleUtilities/Tests/Unit/Utils/GULTestKeychain.h
  GoogleUtilities/Tests/Unit/Utils/GULTestKeychain.m
  Package.swift
Labels: GoogleUtilities, cla: yes

#6000 Storage: specify only supported platforms for test specs
  FirebaseStorage.podspec
Labels: cla: yes

#5978 Fix inaccurate doc comment
  FirebaseInAppMessaging/CHANGELOG.md
  FirebaseInAppMessaging/Sources/Public/FIRInAppMessagingRendering.h
Labels: api: inappmessaging, cla: yes, public-api-change

#6003 Ease diagnosis of origin of check failures
  scripts/check.sh
Labels: cla: yes

#6004 Update path of zip file
  .github/workflows/zip.yml
Labels: cla: yes

#6002 Move doc domment fix to M76
  FirebaseInAppMessaging/CHANGELOG.md
Labels: api: inappmessaging, cla: yes

#6008 Edit Feature Request link to link to the template
  ROADMAP.md
Labels: cla: yes

#6012 Fix path.
  .github/workflows/zip.yml
Labels: cla: yes

#6010 GDTCORFlatFileStorage: keep not expired events when expired batch removed
  GoogleDataTransport/CHANGELOG.md
  GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage.m
  GoogleDataTransport/GDTCORTests/Unit/GDTCORFlatFileStorageTest.m
Labels: GoogleDataTransport, cla: yes

#6013 ABTesting - Repo-relative imports and SwiftPM
  FirebaseABTesting.podspec
  FirebaseABTesting/Sources/ABTConditionalUserPropertyController.m
  FirebaseABTesting/Sources/FIRExperimentController.m
  FirebaseABTesting/Sources/FIRLifecycleEvents.m
  FirebaseABTesting/Tests/Unit/ABTConditionalUserPropertyControllerTest.m
  FirebaseABTesting/Tests/Unit/FIRExperimentControllerTest.m
  FirebaseABTesting/Tests/Unit/Utilities/ABTTestUtilities.m
  FirebaseInAppMessaging.podspec
  FirebaseInAppMessaging/Sources/Data/FIRIAMFetchResponseParser.m
  FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m
  FirebaseInAppMessaging/Tests/Unit/FIRIAMDisplayExecutorTests.m
  FirebaseRemoteConfig.podspec
  FirebaseRemoteConfig/Sources/FIRRemoteConfig.m
  FirebaseRemoteConfig/Sources/RCNConfigExperiment.m
  FirebaseRemoteConfig/Tests/Unit/RCNConfigExperimentTest.m
  Package.swift
  Tests/firebase-test/main.swift
  scripts/change_headers.swift
  scripts/check_imports.swift
Labels: api: abtesting, api: inappmessaging, api: remoteconfig, cla: yes

#6020 Move checkout first which will reset the workspace.
  .github/workflows/zip.yml
Labels: cla: yes

#6016 Turn on ABT unit tests with SPM
  FirebaseABTesting/Tests/Unit/Utilities/ABTTestUtilities.m
  Package.swift
Labels: api: abtesting, cla: yes

#6021 remove test that is dependent on other tests
  FirebaseMessaging/Tests/UnitTests/FIRMessagingRemoteNotificationsProxyTest.m
Labels: api: messaging

#6015 RC: Repo-relative imports and SwiftPM
  FirebaseRemoteConfig/Sources/FIRConfigValue.m
  FirebaseRemoteConfig/Sources/FIRRemoteConfig.m
  FirebaseRemoteConfig/Sources/Private/FIRRemoteConfig_Private.h
  FirebaseRemoteConfig/Sources/Private/RCNConfigFetch.h
  FirebaseRemoteConfig/Sources/Private/RCNConfigSettings.h
  FirebaseRemoteConfig/Sources/RCNConfigContent.m
  FirebaseRemoteConfig/Sources/RCNConfigValue_Internal.h
  FirebaseRemoteConfig/Sources/RCNConstants3P.m
  FirebaseRemoteConfig/Sources/RCNUserDefaultsManager.m
  FirebaseRemoteConfig/Tests/FakeUtils/Bridging-Header.h
  FirebaseRemoteConfig/Tests/FakeUtils/FetchMocks.m
  FirebaseRemoteConfig/Tests/Unit/RCNConfigAnalyticsTest.m
  FirebaseRemoteConfig/Tests/Unit/RCNConfigContentTest.m
  FirebaseRemoteConfig/Tests/Unit/RCNConfigDBManagerTest.m
  FirebaseRemoteConfig/Tests/Unit/RCNConfigExperimentTest.m
  FirebaseRemoteConfig/Tests/Unit/RCNConfigSettingsTest.m
  FirebaseRemoteConfig/Tests/Unit/RCNConfigTest.m
  FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m
  FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfig+FIRAppTest.m
  FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
  FirebaseRemoteConfig/Tests/Unit/RCNThrottlingTests.m
  Package.swift
  Tests/firebase-test/main.swift
  scripts/change_headers.swift
  scripts/check_imports.swift
Labels: api: remoteconfig, cla: yes

#6024 Qualify the error code in grpc_util.cc with StatusCode
  Firestore/core/src/remote/grpc_util.cc
Labels: api: firestore, cla: yes

#6022 SPM: Build and unit test RTDB
  FirebaseDatabase/Sources/Firebase-Prefix.pch
  FirebaseDatabase/Sources/Info.plist
  FirebaseDatabase/Sources/third_party/FImmutableSortedDictionary/FImmutableSortedDictionary/FImmutableSortedDictionary-Prefix.pch
  FirebaseDatabase/Tests/Helpers/FTestBase.m
  FirebaseDatabase/Tests/Unit/FSyncPointTests.m
  FirebaseDatabase/Tests/en.lproj/InfoPlist.strings
  Package.swift
Labels: api: database, cla: yes

#6032 [GDTCORUploadCoordinator startTimer]: don't restart timer if already started
  GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m
  GoogleDataTransport/GDTCORLibrary/Private/GDTCORUploadCoordinator.h
  GoogleDataTransport/GDTCORTests/Common/Categories/GDTCORUploadCoordinator+Testing.m
Labels: GoogleDataTransport, cla: yes

#6023 Create Readme.md file for having release notes
  FirebaseDynamicLinks/CHANGELOG.md
  FirebaseDynamicLinks/README.md
Labels: api: dynamiclinks, cla: yes

#6035 Release 6.28.0 - GDT cherry pick of #6010 and #6032
  GoogleDataTransport/GDTCORLibrary/GDTCORFlatFileStorage.m
  GoogleDataTransport/GDTCORLibrary/GDTCORUploadCoordinator.m
  GoogleDataTransport/GDTCORLibrary/Private/GDTCORUploadCoordinator.h
  GoogleDataTransport/GDTCORTests/Common/Categories/GDTCORUploadCoordinator+Testing.m
  GoogleDataTransport/GDTCORTests/Unit/GDTCORFlatFileStorageTest.m
Labels: GoogleDataTransport, cla: yes

#6034 Enable cron job schedule for Firebase Performance tests on private repository
  .github/workflows/performance-integration-tests.yml
  .github/workflows/performance.yml
Labels: cla: yes

#6041 Add #include for config.h to get the value for HAVE_LIBDISPATCH.
  Firestore/CHANGELOG.md
  Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
  Firestore/Source/API/FIRFirestore.mm
Labels: api: firestore, cla: yes

#6042 Add #include for config.h to get the value for HAVE_LIBDISPATCH (#6041)
  Firestore/CHANGELOG.md
  Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
  Firestore/Source/API/FIRFirestore.mm
Labels: api: firestore, cla: yes

#6043 M75.1 version bumps
  Firebase.podspec
  FirebaseCore.podspec
  FirebaseFirestore.podspec
  Releases/Manifests/6.28.1.json
Labels: cla: yes

#5835 remove ios 7 logic as sdk minimum support is iOS 8 now
  Firebase/InstanceID/CHANGELOG.md
  Firebase/InstanceID/FIRInstanceIDConstants.h
  Firebase/InstanceID/FIRInstanceIDConstants.m
  Firebase/InstanceID/FIRInstanceIDTokenDeleteOperation.m
  Firebase/InstanceID/FIRInstanceIDTokenFetchOperation.m
  Firebase/InstanceID/FIRInstanceIDTokenOperation+Private.h
  Firebase/InstanceID/FIRInstanceIDTokenOperation.m
  Firebase/InstanceID/FIRInstanceIDURLQueryItem.h
  Firebase/InstanceID/FIRInstanceIDURLQueryItem.m
  FirebaseMessaging/CHANGELOG.md
  FirebaseMessaging/Sources/FIRMessagingContextManagerService.m
Labels: api: instanceid, api: messaging, cla: yes

#6033 Update zip
  .github/workflows/zip.yml
Labels: cla: yes

#6040 Merging the 6.28.0 release into master
  Firebase.podspec
  FirebaseAuth.podspec
  FirebaseCore.podspec
  FirebaseCoreDiagnostics.podspec
  FirebaseCrashlytics.podspec
  FirebaseDatabase.podspec
  FirebaseDynamicLinks.podspec
  FirebaseFirestore.podspec
  FirebaseFunctions.podspec
  FirebaseInAppMessaging.podspec
  FirebaseInstallations.podspec
  FirebaseInstanceID.podspec
  FirebaseMessaging.podspec
  FirebaseRemoteConfig.podspec
  FirebaseStorage.podspec
  Releases/Manifests/6.28.0.json
Labels: api: auth, cla: yes

#6049 Merging the 6.28.1 release into master
  Firebase.podspec
  FirebaseCore.podspec
  FirebaseFirestore.podspec
  Releases/Manifests/6.28.1.json
Labels: cla: yes

#6051 Cherry pick GoogleUtilities 6.7.1 fix to master
  GoogleUtilities.podspec
  GoogleUtilities/AppDelegateSwizzler/Private/GULAppDelegateSwizzler.h
  GoogleUtilities/CHANGELOG.md
Labels: cla: yes

#6044 License was never filled in it seems, figured it warrants a PR
  LICENSE
Labels: cla: yes

#6055 Add MLKit to SymbolCollision test
  SymbolCollisionTest/Podfile
Labels: cla: yes

#6009 Remote Config Console API for Testing
  .github/workflows/remoteconfig.yml
  FirebaseRemoteConfig.podspec
  FirebaseRemoteConfig/Tests/SwiftAPI/APITests.swift
  FirebaseRemoteConfig/Tests/SwiftAPI/AccessToken.json
  FirebaseRemoteConfig/Tests/SwiftAPI/RemoteConfigConsole.swift
  FirebaseRemoteConfig/Tests/SwiftAPI/Resources/README.md
  scripts/generate_access_token.sh
  scripts/gha-encrypted/RemoteConfigSwiftAPI/ServiceAccount.json.gpg
Labels: api: remoteconfig, cla: yes

#6054 Add an integration test for callbacks on the main thread.
  Firestore/Example/Tests/Integration/API/FIRDatabaseTests.mm
Labels: api: firestore, cla: yes

#6061 Remove deprecated ML pods from Zip and docs
  Carthage.md
  Rome.md
  ZipBuilder/Sources/ZipBuilder/FirebasePods.swift
  ZipBuilder/Sources/ZipBuilder/ZipBuilder.swift
Labels: cla: yes, zip-builder

#6060 Create app distribution api service to handle tester api calls.
  FirebaseAppDistribution.podspec
  FirebaseAppDistribution/Sources/FIRAppDistribution.m
  FirebaseAppDistribution/Sources/FIRAppDistributionAppDelegateInterceptor.m
  FirebaseAppDistribution/Sources/FIRFADApiService.m
  FirebaseAppDistribution/Sources/FIRFADLocalStorage.m
  FirebaseAppDistribution/Sources/FIRFADLogger.m
  FirebaseAppDistribution/Sources/Private/FIRAppDistributionAppDelegateInterceptor.h
  FirebaseAppDistribution/Sources/Private/FIRFADApiService+Private.h
  FirebaseAppDistribution/Sources/Private/FIRFADLocalStorage+Private.h
  FirebaseAppDistribution/Sources/Private/FIRFADLogger+Private.h
  FirebaseAppDistribution/Sources/Public/FIRAppDistribution.h
  FirebaseAppDistribution/Tests/Unit/FIRAppDistributionAuthPersistenceTests.m
  FirebaseAppDistribution/Tests/Unit/FIRAppDistributionMachOTests.m
  FirebaseAppDistribution/Tests/Unit/FIRFADApiServiceTests.m
Labels: cla: yes

#6045 Migrate zip test to zip workflow.
  .github/workflows/zip.yml
Labels: cla: yes

#6067 Update artifacts name
  .github/workflows/zip.yml
  scripts/remove_data.sh
Labels: cla: yes

#6063 App distribution signin persist
  FirebaseAppDistribution.podspec
  FirebaseAppDistribution/Sources/FIRAppDistribution.m
  FirebaseAppDistribution/Sources/FIRAppDistributionAppDelegateInterceptor.m
  FirebaseAppDistribution/Sources/FIRFADApiService.m
  FirebaseAppDistribution/Sources/FIRFADLocalStorage.m
  FirebaseAppDistribution/Sources/Private/FIRFADLocalStorage+Private.h
  FirebaseAppDistribution/Tests/Unit/FIRAppDistributionTests.m
  FirebaseAppDistribution/Tests/Unit/FIRFADApiServiceTests.m
Labels: cla: yes

#6068 Fix multithreaded _completion access
  FirebaseAuth/CHANGELOG.md
  FirebaseAuth/Sources/Utilities/FIRAuthURLPresenter.m
Labels: api: auth, cla: yes

#6070 Messaging: fix a warning in macOS build and sample podfile file path
  Example/watchOSSample/Podfile
  FirebaseMessaging/Tests/UnitTests/FIRMessagingContextManagerServiceTest.m
Labels: api: messaging, cla: yes

#6082 Update CHANGELOG for Firestore v1.16.3
  Firestore/CHANGELOG.md
Labels: api: firestore, cla: yes

#6086 update changelog for messaging and instanceID
  Firebase/InstanceID/CHANGELOG.md
  FirebaseMessaging/CHANGELOG.md
Labels: cla: yes

#6085 Remove zip testings from sdk workflows
  .github/workflows/abtesting.yml
  .github/workflows/auth.yml
  .github/workflows/crashlytics.yml
  .github/workflows/database.yml
  .github/workflows/dynamiclinks.yml
  .github/workflows/firestore.yml
  .github/workflows/inappmessaging.yml
  .github/workflows/installations.yml
  .github/workflows/messaging.yml
  .github/workflows/remoteconfig.yml
  .github/workflows/storage.yml
  .github/workflows/zip.yml
Labels: cla: yes

#6080 M76 changelog updates - ABT, Auth, FIAM, RC
  FirebaseABTesting/CHANGELOG.md
  FirebaseAuth/CHANGELOG.md
  FirebaseInAppMessaging/CHANGELOG.md
  FirebaseRemoteConfig/CHANGELOG.md
Labels: cla: yes

#6083 Fix potential strlen crash on NULL betaToken
  Crashlytics/CHANGELOG.md
  Crashlytics/Crashlytics/Components/FIRCLSContext.m
Labels: api: crashlytics, cla: yes

#6095 Create changelog and readme in preparation for release.
  FirebaseAppDistribution/CHANGELOG.md
  FirebaseAppDistribution/README.md
Labels: cla: yes

#6098 fix leakage in NSInvocation
  FirebaseMessaging/Tests/UnitTests/FIRMessagingTest.m
Labels: cla: yes

#6103 Remove instanceID dependency from Messaging
  FirebaseMessaging.podspec
  FirebaseMessaging/Apps/Sample/Sample/SceneDelegate.swift
  FirebaseMessaging/Apps/Sample/iOS/NotificationsController.swift
  FirebaseMessaging/Sources/FIRMessaging.m
  FirebaseMessaging/Sources/FIRMessagingClient.h
  FirebaseMessaging/Sources/FIRMessagingClient.m
  FirebaseMessaging/Sources/FIRMessagingCode.h
  FirebaseMessaging/Sources/FIRMessagingCodedInputStream.m
  FirebaseMessaging/Sources/FIRMessagingConstants.h
  FirebaseMessaging/Sources/FIRMessagingConstants.m
  FirebaseMessaging/Sources/FIRMessagingExtensionHelper.m
  FirebaseMessaging/Sources/FIRMessagingLogger.h
  FirebaseMessaging/Sources/FIRMessagingPubSub.m
  FirebaseMessaging/Sources/FIRMessagingPubSubRegistrar.h
  FirebaseMessaging/Sources/FIRMessagingPubSubRegistrar.m
  FirebaseMessaging/Sources/FIRMessagingTopicOperation.h
  FirebaseMessaging/Sources/FIRMessagingTopicOperation.m
  FirebaseMessaging/Sources/FIRMessagingUtilities.h
  FirebaseMessaging/Sources/FIRMessagingUtilities.m
  FirebaseMessaging/Sources/FIRMessaging_Private.h
  FirebaseMessaging/Sources/NSError+FIRMessaging.h
  FirebaseMessaging/Sources/Token/FIRMessagingAPNSInfo.h
  FirebaseMessaging/Sources/Token/FIRMessagingAPNSInfo.m
  FirebaseMessaging/Sources/Token/FIRMessagingAuthKeyChain.h
  FirebaseMessaging/Sources/Token/FIRMessagingAuthKeyChain.m
  FirebaseMessaging/Sources/Token/FIRMessagingAuthService.h
  FirebaseMessaging/Sources/Token/FIRMessagingAuthService.m
  FirebaseMessaging/Sources/Token/FIRMessagingBackupExcludedPlist.h
  FirebaseMessaging/Sources/Token/FIRMessagingBackupExcludedPlist.m
  FirebaseMessaging/Sources/Token/FIRMessagingCheckinPreferences.h
  FirebaseMessaging/Sources/Token/FIRMessagingCheckinPreferences.m
  FirebaseMessaging/Sources/Token/FIRMessagingCheckinService.h
  FirebaseMessaging/Sources/Token/FIRMessagingCheckinService.m
  FirebaseMessaging/Sources/Token/FIRMessagingCheckinStore.h
  FirebaseMessaging/Sources/Token/FIRMessagingCheckinStore.m
  FirebaseMessaging/Sources/Token/FIRMessagingKeychain.h
  FirebaseMessaging/Sources/Token/FIRMessagingKeychain.m
  FirebaseMessaging/Sources/Token/FIRMessagingTokenDeleteOperation.h
  FirebaseMessaging/Sources/Token/FIRMessagingTokenDeleteOperation.m
  FirebaseMessaging/Sources/Token/FIRMessagingTokenFetchOperation.h
  FirebaseMessaging/Sources/Token/FIRMessagingTokenFetchOperation.m
  FirebaseMessaging/Sources/Token/FIRMessagingTokenInfo.h
  FirebaseMessaging/Sources/Token/FIRMessagingTokenInfo.m
  FirebaseMessaging/Sources/Token/FIRMessagingTokenManager.h
  FirebaseMessaging/Sources/Token/FIRMessagingTokenManager.m
  FirebaseMessaging/Sources/Token/FIRMessagingTokenOperation.h
  FirebaseMessaging/Sources/Token/FIRMessagingTokenOperation.m
  FirebaseMessaging/Sources/Token/FIRMessagingTokenStore.h
  FirebaseMessaging/Sources/Token/FIRMessagingTokenStore.m
  FirebaseMessaging/Tests/IntegrationTests/FIRMessagingTokenRefreshTests.swift
  FirebaseMessaging/Tests/UnitTests/FIRInstanceIDWithFCMTest.m
  FirebaseMessaging/Tests/UnitTests/FIRMessagingClientTest.m
  FirebaseMessaging/Tests/UnitTests/FIRMessagingContextManagerServiceTest.m
  FirebaseMessaging/Tests/UnitTests/FIRMessagingHandlingTest.m
  FirebaseMessaging/Tests/UnitTests/FIRMessagingLinkHandlingTest.m
  FirebaseMessaging/Tests/UnitTests/FIRMessagingPubSubTest.m
  FirebaseMessaging/Tests/UnitTests/FIRMessagingServiceTest.m
  FirebaseMessaging/Tests/UnitTests/FIRMessagingTest.m
  FirebaseMessaging/Tests/UnitTests/FIRMessagingTestUtilities.h
  FirebaseMessaging/Tests/UnitTests/FIRMessagingTestUtilities.m
Labels: cla: yes

#6097 Change slices property from copy to strong
  FirebaseAppDistribution/Sources/FIRAppDistributionMachO.m
Labels: cla: yes

#6101 Change error handlers to return bool values instead of void
  FirebaseAppDistribution/Sources/FIRAppDistribution.m
  FirebaseAppDistribution/Sources/FIRFADApiService.m
  FirebaseAppDistribution/Tests/Unit/FIRAppDistributionTests.m
Labels: cla: yes

#6105 Publish SPM products for RC and DB
  Package.swift
Labels: cla: yes

#6102 GDT: fix time units for the request and events uptime
  GoogleDataTransport/CHANGELOG.md
  GoogleDataTransport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
  GoogleDataTransport/GDTCCTTests/Unit/GDTCCTNanopbHelpersTest.m
  GoogleDataTransport/GDTCCTTests/Unit/Helpers/GDTCCTEventGenerator.m
  GoogleDataTransport/GDTCORLibrary/GDTCORClock.m
  GoogleDataTransport/GDTCORLibrary/Public/GDTCORClock.h
  GoogleDataTransport/GDTCORTests/Unit/GDTCORClockTest.m
  GoogleDataTransport/GDTCORTests/Unit/GDTCOREventTest.m
Labels: GoogleDataTransport, cla: yes, public-api-change

#6099 Error code mapping and DelegateInterceptor refactoring
  FirebaseAppDistribution/Sources/FIRAppDistribution.m
  FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m
  FirebaseAppDistribution/Sources/Private/FIRAppDistribution+Private.h
  FirebaseAppDistribution/Sources/Private/FIRAppDistributionUIService.h
  FirebaseAppDistribution/Tests/Unit/FIRAppDistributionTests.m
Labels: cla: yes

#6108 Fix internal ABT imports
  FirebaseABTesting/Sources/Private/FirebaseABTestingInternal.h
  FirebaseInAppMessaging.podspec
  FirebaseRemoteConfig.podspec
  FirebaseRemoteConfig/Sources/FIRRemoteConfig.m
  FirebaseRemoteConfig/Sources/RCNConfigExperiment.m
  FirebaseRemoteConfig/Tests/Unit/RCNConfigExperimentTest.m
Labels: cla: yes

#6109 one more internal ABT import fix
  FirebaseInAppMessaging/Sources/Flows/FIRIAMDisplayExecutor.m
Labels: cla: yes

#6084 fix ordered code unit test for Release build
  Firestore/core/test/unit/util/ordered_code_test.cc
Labels: api: firestore, cla: yes

#6087 Rework config.h handling for Swift Package Manager compatibility
  .gitignore
  FirebaseFirestore.podspec
  Firestore/core/CMakeLists.txt
  Firestore/core/src/util/config.h
  Firestore/core/src/util/config_detected.h.in
Labels: api: firestore, cla: yes

#6110 Fix check breakage from when GHA was out
  scripts/check_no_module_imports.sh
Labels: cla: yes

#6094 Add github action for App Distribution
  .github/workflows/appdistribution.yml
  FirebaseAppDistribution/Tests/Unit/FIRAppDistributionTests.m
  README.md
Labels: cla: yes

#6111 Make the E2E test apps run once every 4 hours.
  .github/workflows/performance-integration-tests.yml
Labels: cla: yes

#6096 Move Core Publics so imports match between SPM and CocoaPods
  .github/workflows/firestore.yml
  FirebaseCore.podspec
  FirebaseCore/CMakeLists.txt
  FirebaseCore/Sources/FIRApp.m
  FirebaseCore/Sources/FIRConfigurationInternal.h
  FirebaseCore/Sources/FIRCoreDiagnosticsConnector.m
  FirebaseCore/Sources/FIRDiagnosticsData.m
  FirebaseCore/Sources/FIRLogger.m
  FirebaseCore/Sources/Private/FIRAppInternal.h
  FirebaseCore/Sources/Private/FIRLogger.h
  FirebaseCore/Sources/Private/FIROptionsInternal.h
  FirebaseCore/Sources/Private/FirebaseCoreInternal.h
  FirebaseCore/Sources/Public/FirebaseCore/FIRApp.h
  FirebaseCore/Sources/Public/FirebaseCore/FIRConfiguration.h
  FirebaseCore/Sources/Public/FirebaseCore/FIRLoggerLevel.h
  FirebaseCore/Sources/Public/FirebaseCore/FIROptions.h
  FirebaseCore/Sources/Public/FirebaseCore/FirebaseCore.h
Labels: api: core, cla: yes, public-api-change

#6113 Fix RemoteConfig sample
  .github/workflows/remoteconfig.yml
  FirebaseRemoteConfig.podspec
  FirebaseRemoteConfig/Sources/FIRConfigValue.m
  FirebaseRemoteConfig/Sources/FIRRemoteConfig.m
  FirebaseRemoteConfig/Sources/Private/FIRRemoteConfig_Private.h
  FirebaseRemoteConfig/Sources/Private/RCNConfigFetch.h
  FirebaseRemoteConfig/Sources/Private/RCNConfigSettings.h
  FirebaseRemoteConfig/Sources/Public/FirebaseRemoteConfig/FIRRemoteConfig.h
  FirebaseRemoteConfig/Sources/Public/FirebaseRemoteConfig/FirebaseRemoteConfig.h
  FirebaseRemoteConfig/Sources/RCNConfigContent.m
  FirebaseRemoteConfig/Sources/RCNConfigValue_Internal.h
  FirebaseRemoteConfig/Sources/RCNConstants3P.m
  FirebaseRemoteConfig/Sources/RCNUserDefaultsManager.m
  FirebaseRemoteConfig/Tests/Sample/Podfile
  FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp.xcodeproj/project.pbxproj
  FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/AppDelegate.m
  FirebaseRemoteConfig/Tests/Sample/RemoteConfigSampleApp/ViewController.m
  FirebaseRemoteConfig/Tests/Unit/RCNConfigContentTest.m
  FirebaseRemoteConfig/Tests/Unit/RCNConfigExperimentTest.m
  FirebaseRemoteConfig/Tests/Unit/RCNInstanceIDTest.m
  FirebaseRemoteConfig/Tests/Unit/RCNRemoteConfigTest.m
  scripts/build.sh
  scripts/check_imports.swift
  scripts/install_prereqs.sh
Labels: api: remoteconfig, cla: yes, public-api-change

#6118 Updating app distribution deployment target to iOS 9
  FirebaseAppDistribution.podspec
Labels: cla: yes

#6117 Feedback from PR#6099
  FirebaseAppDistribution/Sources/FIRAppDistribution.m
  FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m
  FirebaseAppDistribution/Sources/Private/FIRAppDistributionUIService.h
  FirebaseAppDistribution/Tests/Unit/FIRAppDistributionTests.m
Labels: cla: yes

#6119 Encoding app id colons with dashes
  FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m
Labels: cla: yes

#6120 Updates for bumping swiftformat to 0.44.17
  FirebaseABTesting/Tests/Integration/ABTQA/AppDelegate.swift
  FirebaseCore/Tests/SwiftUnit/FirebaseAppTests.swift
  FirebaseMessaging/Apps/Sample/Sample/SceneDelegate.swift
  FirebaseMessaging/Apps/Sample/iOS/NotificationsController.swift
  FirebaseRemoteConfig/Tests/FakeConsole/FakeConsoleTests.swift
  FirebaseRemoteConfig/Tests/SwiftAPI/APITests.swift
  FirebaseRemoteConfig/Tests/SwiftAPI/RemoteConfigConsole.swift
  FirebaseStorage/Tests/SwiftIntegration/StorageIntegration.swift
  FirebaseStorageSwift/Tests/Integration/StorageIntegration.swift
  scripts/style.sh
Labels: api: abtesting, api: core, api: messaging, api: remoteconfig, api: storage, cla: yes

#6106 Move Internal headers to Sources
  FirebaseAppDistribution/Sources/FIRAppDistribution.m
  FirebaseAppDistribution/Sources/FIRAppDistributionMachO.h
  FirebaseAppDistribution/Sources/FIRAppDistributionMachO.m
  FirebaseAppDistribution/Sources/FIRAppDistributionMachOSlice.h
  FirebaseAppDistribution/Sources/FIRAppDistributionMachOSlice.m
  FirebaseAppDistribution/Sources/FIRAppDistributionRelease.m
  FirebaseAppDistribution/Sources/FIRAppDistributionUIService.h
  FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m
  FirebaseAppDistribution/Sources/FIRFADApiService.h
  FirebaseAppDistribution/Sources/FIRFADApiService.m
  FirebaseAppDistribution/Sources/FIRFADLogger.h
  FirebaseAppDistribution/Sources/FIRFADLogger.m
  FirebaseAppDistribution/Sources/Private/FIRAppDistribution.h
  FirebaseAppDistribution/Sources/Private/FIRAppDistributionRelease.h
  FirebaseAppDistribution/Tests/Unit/FIRAppDistributionMachOTests.m
  FirebaseAppDistribution/Tests/Unit/FIRAppDistributionTests.m
  FirebaseAppDistribution/Tests/Unit/FIRFADApiServiceTests.m
Labels: cla: yes

#6114 Configure Python 3 in some GitHub workflows.
  .github/workflows/check.yml
  .github/workflows/firestore.yml
  scripts/check.sh
  scripts/setup_check.sh
Labels: cla: yes

#6088 Test release testing.
  .github/workflows/release.yml
  scripts/localize_podfile.swift
  scripts/setup_quickstart.sh
Labels: cla: yes

#6112 Update testing time.
  .github/workflows/abtesting.yml
  .github/workflows/auth.yml
  .github/workflows/crashlytics.yml
  .github/workflows/firestore.yml
  .github/workflows/inappmessaging.yml
  .github/workflows/installations.yml
  .github/workflows/messaging.yml
  .github/workflows/performance.yml
  .github/workflows/remoteconfig.yml
  .github/workflows/storage.yml
Labels: cla: yes

#6134 Added the actual error string that is intermittently encountered during manual install of Firebase SDK iOS
  ZipBuilder/Template/README.md
Labels: cla: yes

#6137 retry and xcpretty for spm ci
  .github/workflows/spm.yml
Labels: cla: yes

#6136 Update recommended public header location
  HeadersImports.md
Labels: cla: yes

#6138 Respond to code review feedback
  FirebaseAppDistribution.podspec
  FirebaseAppDistribution/Sources/FIRAppDistribution.m
  FirebaseAppDistribution/Tests/Unit/FIRAppDistributionTests.m
  FirebaseAppDistribution/Tests/Unit/FIRFADApiServiceTests.m
Labels: cla: yes

#6139 fix messaging breakage
  FirebaseMessaging/Tests/UnitTests/FIRMessagingRemoteNotificationsProxyTest.m
Labels: api: messaging, cla: yes

#6145 GULAppDelegateSwizzlerTest: use OCMClassMock for application to avoid mock conflicts with KVO
  GoogleUtilities/Tests/Unit/Swizzler/GULAppDelegateSwizzlerTest.m
Labels: GoogleUtilities, cla: yes

#6146 Update versions for Release 6.29.0
  Firebase.podspec
  FirebaseAuth.podspec
  FirebaseCore.podspec
  FirebaseCrashlytics.podspec
  FirebaseFirestore.podspec
  FirebaseInAppMessaging.podspec
  FirebaseInstanceID.podspec
  FirebaseMessaging.podspec
  FirebaseRemoteConfig.podspec
  GoogleDataTransport.podspec
  Releases/Manifests/6.29.0.json
Labels: api: auth, cla: yes

#6144 Initializing UIWindow using initWithWindowScene for ios 13 and removing UI code from main FIRAppDistribution.m
  FirebaseAppDistribution/Sources/FIRAppDistribution.m
  FirebaseAppDistribution/Sources/FIRAppDistributionUIService.h
  FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m
  FirebaseAppDistribution/Tests/Unit/FIRAppDistributionTests.m
Labels: cla: yes

#6126 Switch App Distribution SDK from AppAuth to FirebaseInstallations
  .github/workflows/appdistribution.yml
  FirebaseAppDistribution.podspec
  FirebaseAppDistribution/CHANGELOG.md
  FirebaseAppDistribution/README.md
  FirebaseAppDistribution/Sources/FIRAppDistribution.m
  FirebaseAppDistribution/Sources/FIRAppDistributionAppDelegateInterceptor.m
  FirebaseAppDistribution/Sources/FIRAppDistributionAuthPersistence.m
  FirebaseAppDistribution/Sources/FIRAppDistributionKeychainUtility.m
  FirebaseAppDistribution/Sources/FIRAppDistributionMachO.h
  FirebaseAppDistribution/Sources/FIRAppDistributionMachO.m
  FirebaseAppDistribution/Sources/FIRAppDistributionMachOSlice.h
  FirebaseAppDistribution/Sources/FIRAppDistributionMachOSlice.m
  FirebaseAppDistribution/Sources/FIRAppDistributionRelease.m
  FirebaseAppDistribution/Sources/FIRAppDistributionUIService.h
  FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m
  FirebaseAppDistribution/Sources/FIRFADApiService.h
  FirebaseAppDistribution/Sources/FIRFADApiService.m
  FirebaseAppDistribution/Sources/FIRFADLogger.h
  FirebaseAppDistribution/Sources/FIRFADLogger.m
  FirebaseAppDistribution/Sources/Private/FIRAppDistribution.h
  FirebaseAppDistribution/Sources/Private/FIRAppDistributionAppDelegateInterceptor.h
  FirebaseAppDistribution/Sources/Private/FIRAppDistributionAuthPersistence+Private.h
  FirebaseAppDistribution/Sources/Private/FIRAppDistributionKeychainUtility+Private.h
  FirebaseAppDistribution/Sources/Private/FIRAppDistributionRelease.h
  FirebaseAppDistribution/Sources/Public/FIRAppDistribution.h
  FirebaseAppDistribution/Tests/Unit/FIRAppDistributionAuthPersistenceTests.m
  FirebaseAppDistribution/Tests/Unit/FIRAppDistributionMachOTests.m
  FirebaseAppDistribution/Tests/Unit/FIRAppDistributionTests.m
  FirebaseAppDistribution/Tests/Unit/FIRFADApiServiceTests.m
  README.md
Labels: cla: yes, zip-builder

#6133 RCNConfigFetch: fix weakSelf/strongSelf usage
  FirebaseRemoteConfig/CHANGELOG.md
  FirebaseRemoteConfig/Sources/RCNConfigFetch.m
Labels: api: remoteconfig, cla: yes

#6162 Ignore SwiftPM gen'd files in style
  scripts/style.sh
Labels: cla: yes

#6163 Remove #if SWIFT_PACKAGE checks for nanopb
  Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.m
  Crashlytics/ProtoSupport/proto_generator.py
  Crashlytics/Protogen/nanopb/crashlytics.nanopb.h
  FirebaseInAppMessaging/Analytics/Protogen/nanopb/fiam.nanopb.h
  FirebaseInAppMessaging/ProtoSupport/nanopb_build_protos.py
  FirebaseInAppMessaging/Sources/Analytics/Protogen/nanopb/fiam.nanopb.h
  GoogleDataTransport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
  GoogleDataTransport/GDTCCTLibrary/GDTCCTUploader.m
  GoogleDataTransport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.h
  GoogleDataTransport/ProtoSupport/proto_generator.py
  Package.swift
  scripts/check_imports.swift
Labels: GoogleDataTransport, api: crashlytics, api: inappmessaging, cla: yes

#6157 Unset window.rootViewController when resetting UI
  FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m
Labels: cla: yes

#6164 Revert "Remove #if SWIFT_PACKAGE checks for nanopb (#6163)"
  Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.m
  Crashlytics/ProtoSupport/proto_generator.py
  Crashlytics/Protogen/nanopb/crashlytics.nanopb.h
  FirebaseInAppMessaging/Analytics/Protogen/nanopb/fiam.nanopb.h
  FirebaseInAppMessaging/ProtoSupport/nanopb_build_protos.py
  FirebaseInAppMessaging/Sources/Analytics/Protogen/nanopb/fiam.nanopb.h
  GoogleDataTransport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
  GoogleDataTransport/GDTCCTLibrary/GDTCCTUploader.m
  GoogleDataTransport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.h
  GoogleDataTransport/ProtoSupport/proto_generator.py
  Package.swift
  scripts/check_imports.swift
Labels: GoogleDataTransport, api: crashlytics, api: inappmessaging, cla: yes

#6165 Import nanopb without touching CocoaPods imports
  Crashlytics/Crashlytics/Models/Record/FIRCLSReportAdapter.m
  Crashlytics/Protogen/nanopb/crashlytics.nanopb.h
  GoogleDataTransport/GDTCCTLibrary/GDTCCTNanopbHelpers.m
  GoogleDataTransport/GDTCCTLibrary/GDTCCTUploader.m
  GoogleDataTransport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.h
  Package.swift
Labels: GoogleDataTransport, api: crashlytics, cla: yes

#5930 Fix bug where multiple keychain entries would result in user persistence failure
  FirebaseAuth/Sources/Storage/FIRAuthKeychainServices.m
  FirebaseAuth/Tests/Unit/FIRAuthKeychainServicesTests.m
Labels: api: auth, cla: yes

#6169 Add fallback for iOS 13 when not using scenes
  FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m
Labels: cla: yes

#6168 ABT - new public header structure
  FirebaseABTesting.podspec
  FirebaseABTesting/Sources/ABTConditionalUserPropertyController.m
  FirebaseABTesting/Sources/FIRExperimentController.m
  FirebaseABTesting/Sources/FIRLifecycleEvents.m
  FirebaseABTesting/Sources/Private/FirebaseABTestingInternal.h
  FirebaseABTesting/Sources/Public/FirebaseABTesting/FIRExperimentController.h
  FirebaseABTesting/Sources/Public/FirebaseABTesting/FIRLifecycleEvents.h
  FirebaseABTesting/Sources/Public/FirebaseABTesting/FirebaseABTesting.h
  FirebaseABTesting/Tests/Unit/ABTConditionalUserPropertyControllerTest.m
  FirebaseABTesting/Tests/Unit/FIRExperimentControllerTest.m
Labels: api: abtesting, cla: yes, public-api-change

#6170 Crashlytics - new public header structure
  Crashlytics/Crashlytics/Controllers/FIRCLSReportManager.h
  Crashlytics/Crashlytics/FIRExceptionModel.m
  Crashlytics/Crashlytics/Private/FIRExceptionModel_Private.h
  Crashlytics/Crashlytics/Private/FIRStackFrame_Private.h
  Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRCrashlytics.h
  Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRExceptionModel.h
  Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FIRStackFrame.h
  Crashlytics/Crashlytics/Public/FirebaseCrashlytics/FirebaseCrashlytics.h
  Crashlytics/UnitTests/FIRRecordExceptionModelTests.m
  FirebaseCrashlytics.podspec
Labels: api: crashlytics, cla: yes, public-api-change

#6171 RTDB - new public header structure
  Dangerfile
  FirebaseDatabase.podspec
  FirebaseDatabase/Sources/Api/FIRDataSnapshot.m
  FirebaseDatabase/Sources/Api/FIRDatabase.m
  FirebaseDatabase/Sources/Api/FIRDatabaseQuery.m
  FirebaseDatabase/Sources/Api/FIRMutableData.m
  FirebaseDatabase/Sources/Api/FIRServerValue.m
  FirebaseDatabase/Sources/Api/FIRTransactionResult.m
  FirebaseDatabase/Sources/Api/Private/FIRDataSnapshot_Private.h
  FirebaseDatabase/Sources/Api/Private/FIRDatabaseQuery_Private.h
  FirebaseDatabase/Sources/Api/Private/FIRDatabaseReference_Private.h
  FirebaseDatabase/Sources/Api/Private/FIRDatabase_Private.h
  FirebaseDatabase/Sources/Api/Private/FIRMutableData_Private.h
  FirebaseDatabase/Sources/Api/Private/FIRTransactionResult_Private.h
  FirebaseDatabase/Sources/Core/FListenProvider.m
  FirebaseDatabase/Sources/Core/FPersistentConnection.m
  FirebaseDatabase/Sources/Core/FRepo.h
  FirebaseDatabase/Sources/Core/FRepo.m
  FirebaseDatabase/Sources/Core/FSyncPoint.m
  FirebaseDatabase/Sources/Core/View/FChange.h
  FirebaseDatabase/Sources/Core/View/FDataEvent.h
  FirebaseDatabase/Sources/Core/View/FEvent.h
  FirebaseDatabase/Sources/Core/View/FEventRegistration.h
  FirebaseDatabase/Sources/Core/View/FView.m
  FirebaseDatabase/Sources/FIRDatabaseReference.m
  FirebaseDatabase/Sources/FViewProcessor.m
  FirebaseDatabase/Sources/Public/FirebaseDatabase/FIRDataEventType.h
  FirebaseDatabase/Sources/Public/FirebaseDatabase/FIRDataSnapshot.h
  FirebaseDatabase/Sources/Public/FirebaseDatabase/FIRDatabase.h
  FirebaseDatabase/Sources/Public/FirebaseDatabase/FIRDatabaseQuery.h
  FirebaseDatabase/Sources/Public/FirebaseDatabase/FIRDatabaseReference.h
  FirebaseDatabase/Sources/Public/FirebaseDatabase/FIRMutableData.h
  FirebaseDatabase/Sources/Public/FirebaseDatabase/FIRServerValue.h
  FirebaseDatabase/Sources/Public/FirebaseDatabase/FIRTransactionResult.h
  FirebaseDatabase/Sources/Public/FirebaseDatabase/FirebaseDatabase.h
  FirebaseDatabase/Sources/Realtime/FWebSocketConnection.m
  FirebaseDatabase/Sources/Utilities/FEventEmitter.h
  FirebaseDatabase/Sources/Utilities/FValidation.h
  FirebaseDatabase/Sources/Utilities/Tuples/FTupleFirebase.h
  FirebaseDatabase/Tests/Helpers/FDevice.m
  FirebaseDatabase/Tests/Helpers/FEventTester.m
  FirebaseDatabase/Tests/Helpers/FTestExpectations.h
  FirebaseDatabase/Tests/Helpers/FTestExpectations.m
  FirebaseDatabase/Tests/Helpers/FTupleEventTypeString.h
  FirebaseDatabase/Tests/Integration/FData.m
  FirebaseDatabase/Tests/Integration/FIRDatabaseTests.m
  FirebaseDatabase/Tests/Integration/FOrder.m
  FirebaseDatabase/Tests/Integration/FPersist.m
  FirebaseDatabase/Tests/Unit/FIRDataSnapshotTests.m
Labels: api: database, cla: yes, public-api-change

#6172 Storage - new public header structure
  FirebaseStorage.podspec
  FirebaseStorage/Sources/FIRStorage.m
  FirebaseStorage/Sources/FIRStorageComponent.m
  FirebaseStorage/Sources/FIRStorageConstants.m
  FirebaseStorage/Sources/FIRStorageDeleteTask.h
  FirebaseStorage/Sources/FIRStorageDownloadTask.m
  FirebaseStorage/Sources/FIRStorageDownloadTask_Private.h
  FirebaseStorage/Sources/FIRStorageErrors.h
  FirebaseStorage/Sources/FIRStorageErrors.m
  FirebaseStorage/Sources/FIRStorageGetDownloadURLTask.h
  FirebaseStorage/Sources/FIRStorageGetMetadataTask.h
  FirebaseStorage/Sources/FIRStorageGetMetadataTask.m
  FirebaseStorage/Sources/FIRStorageListResult.m
  FirebaseStorage/Sources/FIRStorageListResult_Private.h
  FirebaseStorage/Sources/FIRStorageListTask.h
  FirebaseStorage/Sources/FIRStorageMetadata.m
  FirebaseStorage/Sources/FIRStorageMetadata_Private.h
  FirebaseStorage/Sources/FIRStorageObservableTask.m
  FirebaseStorage/Sources/FIRStorageObservableTask_Private.h
  FirebaseStorage/Sources/FIRStorageReference.m
  FirebaseStorage/Sources/FIRStorageReference_Private.h
  FirebaseStorage/Sources/FIRStorageTask.m
  FirebaseStorage/Sources/FIRStorageTaskSnapshot.m
  FirebaseStorage/Sources/FIRStorageTaskSnapshot_Private.h
  FirebaseStorage/Sources/FIRStorageTask_Private.h
  FirebaseStorage/Sources/FIRStorageTokenAuthorizer.m
  FirebaseStorage/Sources/FIRStorageUpdateMetadataTask.h
  FirebaseStorage/Sources/FIRStorageUploadTask.m
  FirebaseStorage/Sources/Public/FirebaseStorage/FIRStorage.h
  FirebaseStorage/Sources/Public/FirebaseStorage/FIRStorageConstants.h
  FirebaseStorage/Sources/Public/FirebaseStorage/FIRStorageDownloadTask.h
  FirebaseStorage/Sources/Public/FirebaseStorage/FIRStorageListResult.h
  FirebaseStorage/Sources/Public/FirebaseStorage/FIRStorageMetadata.h
  FirebaseStorage/Sources/Public/FirebaseStorage/FIRStorageObservableTask.h
  FirebaseStorage/Sources/Public/FirebaseStorage/FIRStorageReference.h
  FirebaseStorage/Sources/Public/FirebaseStorage/FIRStorageTask.h
  FirebaseStorage/Sources/Public/FirebaseStorage/FIRStorageTaskSnapshot.h
  FirebaseStorage/Sources/Public/FirebaseStorage/FIRStorageUploadTask.h
  FirebaseStorage/Sources/Public/FirebaseStorage/FirebaseStorage.h
  FirebaseStorage/Tests/Integration/FIRStorageIntegrationTests.m
  FirebaseStorage/Tests/Unit/FIRStorageMetadataTests.m
  FirebaseStorage/Tests/Unit/FIRStorageReferenceTests.m
  FirebaseStorage/Tests/Unit/FIRStorageTestHelpers.h
  FirebaseStorage/Tests/Unit/FIRStorageTests.m
Labels: api: storage, cla: yes, public-api-change

#6174 Installations - new public header structure
  FirebaseInstallations.podspec
  FirebaseInstallations/Source/Library/Errors/FIRInstallationsErrorUtil.h
  FirebaseInstallations/Source/Library/FIRInstallations.m
  FirebaseInstallations/Source/Library/FIRInstallationsAuthTokenResultInternal.h
  FirebaseInstallations/Source/Library/FIRInstallationsVersion.m
  FirebaseInstallations/Source/Library/InstallationsAPI/FIRInstallationsAPIService.m
  FirebaseInstallations/Source/Library/Private/FirebaseInstallationsInternal.h
  FirebaseInstallations/Source/Library/Public/FirebaseInstallations/FIRInstallations.h
  FirebaseInstallations/Source/Library/Public/FirebaseInstallations/FIRInstallationsAuthTokenResult.h
  FirebaseInstallations/Source/Library/Public/FirebaseInstallations/FIRInstallationsErrors.h
  FirebaseInstallations/Source/Library/Public/FirebaseInstallations/FIRInstallationsVersion.h
  FirebaseInstallations/Source/Library/Public/FirebaseInstallations/FirebaseInstallations.h
  FirebaseInstallations/Source/Tests/Integration/FIRInstallationsIntegrationTests.m
  FirebaseInstallations/Source/Tests/Unit/FIRInstallationsAPIServiceTests.m
  FirebaseInstallations/Source/Tests/Unit/FIRInstallationsIDControllerTests.m
  FirebaseInstallations/Source/Tests/Unit/FIRInstallationsTests.m
  FirebaseInstallations/Source/Tests/Utils/FIRInstallations+Tests.h
  scripts/check_imports.swift
Labels: api: installations, cla: yes, public-api-change

#6176 Fix spm build warning
  Package.swift
Labels: cla: yes

#6178 GDT remove @import
  GoogleDataTransport/GDTCORLibrary/Internal/GoogleDataTransportInternal.h
  scripts/check_imports.swift
Labels: GoogleDataTransport, cla: yes

#6175 Remove non-existent Firestore/Protos/objc from podspec
  FirebaseFirestore.podspec
Labels: api: firestore, cla: yes

#6180 Fix CoreDiagnostics test regression
  Example/CoreDiagnostics/Tests/FIRCoreDiagnosticsTest.m
Labels: cla: yes

#6182 Update UIAlert copy.
  FirebaseAppDistribution/Sources/FIRAppDistributionUIService.m
Labels: cla: yes
